### ISSUE TITLE
火车头入库接口，内容介绍不能有&这个符号，好像其他标题等字段也不行

### ISSUE THREAD

**Issue by s7webroot** [magicblack/maccms10#10]
火车头入库接口，内容介绍不能有&这个符号，好像其他标题等字段也不行，
望老王测试修复

**Comment by magicblack** [comment]
有&符号的时候，建议自己转义一下 &amp; 。因为这个符号涉及到http请求参数。

**Comment by s7webroot** [comment]
> 有&符号的时候，建议自己转义一下 & 。因为这个符号涉及到http请求参数。

& 转义成这个&amp;还是有&，请问怎样转义的好？

**Comment by magicblack** [comment]
按正常来说post请求有&符号也是没有关系的呢。你配置一下改为post请求。

**Comment by s7webroot** [comment]
> 按正常来说post请求有&符号也是没有关系的呢。你配置一下改为post请求。

V10的火车头采集接口都是接收POST数据来的吧？不然我其他字段也没法入库，我就发现这个&字符有问题

**Comment by s7webroot** [comment]
> 按正常来说post请求有&符号也是没有关系的呢。你配置一下改为post请求。

老王大哥，您说的配置是配置哪里？还是没解决
