### ISSUE TITLE
year

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#100]
> <div class="box">
    <div class="title">
        <h2>2000年电视剧及以前</h2>
    </div>
    <div class="box_con">
        <ul class="img-list dis">
            {maccms:vod num="1000" year="2000,1998,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980,1979,1978,1977,1976,1975,1974,1973,1972,1971,1970" by="time"}
            <li><a href="{:mac_url_vod_detail($vo)}" title="{$vo.vod_name}"><h2>{$vo.vod_name}</h2></a></li>
            {/maccms:vod}
        </ul>
    </div>
</div>

只显示2000年的电视剧，不显示其他年代，是标签使用错了吗

**Comment by magicblack** [comment]
没错啊~~
