### ISSUE TITLE
希望增加webp格式上传支持

### ISSUE THREAD

**Issue by MechanicF** [magicblack/maccms10#1001]
**描述您的问题**  
现在上传webp格式图片提示不支持的格式，很多资源站封面才用webp格式图片将无法使用

**截图**  
![image](https://user-images.githubusercontent.com/52064115/209800638-050c6853-d2f2-47eb-a1da-58ecd51ae75e.png)

**版本信息:**  
 -  程序版本: [2022.1000.3032]
 - 操作系统: [Windows 10]
 - 浏览器: [chrome]

**Comment by magicblack** [comment]
感谢反馈，代码已提交，等待发布新版本支持。
