### ISSUE TITLE
现在版本的后台在线支付配置 支付宝已无法使用

### ISSUE THREAD

**Issue by tiqun** [magicblack/maccms10#1003]
**描述您的问题**  
现在后台的在线支付配置 支付宝配置好后已经无法使用

**如何重现**  
配置好后在会员中心在线充值

**预期结果**  
正常发起支付调用和回调
支付宝正常充值或者加一个易支付
**截图**  
![Screenshot_2022-12-30-13-47-28-42_8b7aa5be40a89c6](https://user-images.githubusercontent.com/58353527/210038823-385776fd-8898-471f-bc37-e8909c6fa1c7.jpg)
![Screenshot_2022-12-30-13-47-16-89_8b7aa5be40a89c6](https://user-images.githubusercontent.com/58353527/210038826-8471cfc9-2433-4a5e-a7a0-c34618d81e48.jpg)

**版本信息:**  
<html>
<body>

运行环境 | Linux (LiteSpeed)
-- | --
数据库版本 | 10.5.12-MariaDB-cll-lve
PHP版本 | 7.2.34
ThinkPHP版本 | 5.0.24
程序版本 | 2022.1000.3032

</body>
</html>

**其他备注信息**  
望修复或更新一下能增加一个易支付

**Comment by magicblack** [comment]
支付宝插件可能未更新。后面考虑增加易支付吧~

**Comment by tiqun** [comment]
> 支付宝插件可能还没有更新。后面考疑增加加易支付吧~

不考虑升级一下支付宝插件了吗？

**Comment by magicblack** [comment]
暂未收到其他人反馈，检查是否支付宝对接权限不足~
