### ISSUE TITLE
采集出问题，数据表字段不存在:[type_name]

### ISSUE THREAD

**Issue by goodreput** [magicblack/maccms10#1006]
如题，但是未更新版本(ver.3032) 是可以采集的，请问这个要咋解决，谢谢大家

**Comment by magicblack** [comment]
具体是哪张表，找找SQL日志贴出来看看~

**Comment by goodreput** [comment]
后来暂时先用别的办法先忽略，因为sql日志看不出哪个表有问题
暂时解决办法：

**Comment by magicblack** [comment]
不客气，有可能是旧版升级过来的过程中有字段没加上。先用吧，如果后面实在有问题可能需要备份好数据，重新安装一下最新版的~
