### ISSUE TITLE
The storage XSS is found in the website background.（网站后台发现存储型XSS）

### ISSUE THREAD

**Issue by pwolp** [magicblack/maccms10#1007]
**问题描述--Describe your problem**  
The storage XSS is found in the website background.
网站后台发现存储型XSS

**复现过程--How to reproduce**  
在后台的“服务器组件”、“播放器”和“视频”管理中的其他功能中，当添加内容时，一些输入（如“提示”）存储了XSS攻击。输入“<script>alert（xss）</script>”并保存后，当您再次访问页面时，将出现一个弹出窗口。
In the "Server Component", "Player" and other functions in the "Video" management in the background, when adding content, some inputs, such as "Prompt", have stored XSS attacks. After entering "<script>alert(document.cookie)</script>" and saving, a pop-up window will appear when you visit the page again.

![image](https://user-images.githubusercontent.com/46616498/210578516-f70997b1-76f4-43c5-89da-75f21f9c0787.png)
![image](https://user-images.githubusercontent.com/46616498/210579990-6229cde0-34cf-408e-a275-5575ea6d7680.png)
![image](https://user-images.githubusercontent.com/46616498/210580032-884a04c2-e051-4ac4-9fc3-a0eccd402f35.png)

**版本信息:**  
 -  程序版本: maccms-v10]

**Comment by magicblack** [comment]
感谢反馈，将在后续版本优化~
