### ISSUE TITLE
点击视频卡片去播放视频，新的网页页面提示以下错误

### ISSUE THREAD

**Issue by DEKVIW** [magicblack/maccms10#1008]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) ORDER BY `vod_hits_week` DESC LIMIT 0,8' at line 1

**Comment by magicblack** [comment]
需要提供完整的SQL语句来判断是哪里出错了~
