### ISSUE TITLE
关于视频列表排序问题，我希望查出来的视频就按照我给的ids的顺序摆放

### ISSUE THREAD

**Issue by wangya123456789** [magicblack/maccms10#1011]
{maccms:vod ids="30,40,10" by="ids"}
      {include file="block/rankbox"}
{/maccms:vod}

根据ids查出3个视频，我希望查出来的视频就按照我给的ids的顺序摆放，比如第一个视频就是id为30，第二个为40，第三个为10，我应该怎么做？

**Comment by magicblack** [comment]
`ids="30,40,10"` 在模板解析里是一个查询条件，没有排序功能。有2种办法支持你的需求：
1. 使用php语言编写，查出数据之后，通过php数组排序一次再输出；
2. 保持你现在的写法，然后加一段js，在前端操作dom重新排序。
