### ISSUE TITLE
一个静态页生成时很离奇的bug

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#1012]
有分页的页面（如分类页），如果设置成静态生成，有一个很离奇的bug。
就是调用的时候，第一个参数必须是num，不然就只能生成一页

`{maccms:vod num="24" half="3" paging="yes" by="time" order="desc"}
{/maccms:vod}
`
上面这样进行调用，就是可以正常生成分页

但如果num="24"不是第一个参数，如：
`{maccms:vod half="3" paging="yes" num="24" by="time" order="desc"}
{/maccms:vod}
`
这样的话就无法正常生成，只能生成第一页

麻烦作者大大修复一下这个bug

**Comment by magicblack** [comment]
暂时无法排除问题所在，可能是ThinkPHP底层模板标签库导致。先把num放到最前面用吧~
