### ISSUE TITLE
顶级api接口数据返回

### ISSUE THREAD

**Issue by oouuvs** [magicblack/maccms10#1013]
第一个问题：顶级分类1电影，2动漫。顶级分类1电影下有子分类5动作片，vod/?ac=detail&t=5可以返回子分类数据，如果想要获取顶级分类1电影下的全部数据vod/?ac=detail&t=1则返回为空，在有子分类的情况下获取不到数据。2动漫无子分类，vod/?ac=ldetail&t=2可以返回数据，请问怎么在有子分类的情况下api返回顶级数据。  

第二个问题：vod/?ac=detail&t=5&year=2010  那么地区参数是什么，筛选大陆地区的影视？

**Comment by aTenb** [comment]
好像没有地区筛选的参数 找了半天
