### ISSUE TITLE
静态生成时，分类页的bug

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#1014]
在分类页里，只要出现paging="yes"式的调用，无论是否有限制条件，在静态生成的时候就会自动生成多个分页
比如，我的模板里，是这样的逻辑
在有子分类的时候，如电影分类，列出各个子分类的视频，但不分页，paging="no"
在没有子分类的时候，如动漫分类，列出视频，并分页，paging="yes"
代码如下
`{if !empty($obj.childids)}
子分类1
子分类2
……
{else/}
视频
……
分页
{/if}
`
也就是在有子分类的情况下，分类页只有一页，没有分页
但是在静态生成的时候，这个没有子分类的顶级分类，还是生成了分页，并没有按照我的限制条件显示（动态模式下是正常的）

同样的问题，如果paging="yes"的部分是使用include file="xxxx"的形式引入的，静态生成的时候就完全不生成分页

麻烦作者大人修复一下，非常感谢

**Comment by magicblack** [comment]
不是很明白描述的问题所在，建议分条列出是哪些问题，以及尝试过的解决办法。这里已经很久没调整过了~
