### ISSUE TITLE
新增api需求

### ISSUE THREAD

**Issue by Hiram-Wong** [magicblack/maccms10#1016]
希望api增加maccms:vod模板by参数用于对接
比如by hits

**Comment by RipperTs** [comment]
> 希望api增加maccms:vod模板by参数用于对接 比如by hits

开发个插件就好了

**Comment by magicblack** [comment]
暂只支持vod_time的排序，如有需要可修改 ./application/api/controller/Provide.php 第124行部分自行定制参数~
