### ISSUE TITLE
分类管理，建议文章分为图文和纯文

### ISSUE THREAD

**Issue by nykk520** [magicblack/maccms10#1017]
分类管理，建议文章分为图文和纯文
因为图文的分类页我们可以做封面的列表
纯文的列表可以用标题来做列表

现在我们的解决方法是模板里面指定id 来做不同的渲染，但是不是通用模板，换了分类信息就需要去模板里面改

**Comment by magicblack** [comment]
这个你们可以自己用 推荐1~6 来实现~
<img width="536" alt="image" src="https://github.com/magicblack/maccms10/assets/20452515/eb82ba71-2418-4a15-a160-697a55fa03c8">
