### ISSUE TITLE
参数t=1 2 3 4这种大分类为什么什么都没返回？用哪个参数查这种大类别？

### ISSUE THREAD

**Issue by luddite1989** [magicblack/maccms10#1023]
**描述您的问题**  

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by magicblack** [comment]
如果是指的provide接口，这个不支持。建议寻找第三方的二次开发的独立接口~
