### ISSUE TITLE
redis只能本地使用

### ISSUE THREAD

**Issue by yyyou** [magicblack/maccms10#1026]
**描述您的问题**  
redis只能本地使用 如果第三方服务器ip就失效

**Comment by orangejx** [comment]
redis 默认是不能远程访问的, 远程访问的话需要开启密码和设置 bind 地址.
> PS: 使用 redis 本身就是为了高速缓存数据在内存中, 而使用第三方服务器会增加额外的通讯成本, 使用本地 redis 效果会更好一些. 

开启远程访问可以看 [https://www.jianshu.com/p/0ed7e88325dd](https://www.jianshu.com/p/0ed7e88325dd )

**Comment by magicblack** [comment]
同意楼上~
