### ISSUE TITLE
关于接口的搜索

### ISSUE THREAD

**Issue by 2674748933** [magicblack/maccms10#1031]
接口搜索功能只能搜索影视名称中包含的关键词，无法搜索演员和导演中的关键字

我把相关代码改动了一下
原代码：
if (!empty($this->_param['wd'])) {
    $where['vod_name'] = ['like', '%' . $this->_param['wd'] . '%'];
}
改动后：
if (!empty($this->_param['wd'])) {
    $where['vod_name'] = ['like', '%' . $this->_param['wd'] . '%'];
    $where['vod_actor'] = ['like', '%' . $this->_param['wd'] . '%'];
    $where['vod_director'] = ['like', '%' . $this->_param['wd'] . '%'];
}

如上，但这无法解决问题，反而连名字都搜不到了，搜索结果直接为0
请求告知解决方法或者新增该功能

**Comment by jxgzs** [comment]
后台不是可以直接设置打开 演员 导演.....

**Comment by 2674748933** [comment]
> 后台不是可以直接设置打开 演员 导演..... ![image](https://user-images.githubusercontent.com/52615372/222054089-17de3a44-4523-41f6-a56c-fa9dfddd1fcb.png)

这个确实可以，但他是管前台的。我说的是开放API接口里的搜索，这个确实是功能的不完善，参考以上代码
![image](https://user-images.githubusercontent.com/35019160/222054510-97ae7340-57a6-4b02-a76f-2bdf5ad9007c.png)

**Comment by magicblack** [comment]
> if (!empty($this->_param['wd'])) {
> $where['vod_name'] = ['like', '%' . $this->_param['wd'] . '%'];
> $where['vod_actor'] = ['like', '%' . $this->_param['wd'] . '%'];
> $where['vod_director'] = ['like', '%' . $this->_param['wd'] . '%'];
> }

你的改法查询语句变成AND了，可以参考这个写法（未测试过）：
```
if (!empty($this->_param['wd'])) {
    $where['vod_name|vod_actor|vod_director'] = ['like', '%' . $this->_param['wd'] . '%'];
}
```

另外这里暂不考虑在官方库里支持这样的筛选，采集暂时用不到，而且会给源站增加搜索压力~
