### ISSUE TITLE
新增加的分类默认都没有访问权限，建议把这个逻辑改掉

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#1032]
目前新增加的分类，任何用户组都没有访问权限，都需要手动调整
建议把这个逻辑改成新增分类拥有全部权限，需要限制的分类再自行调整
不然修改起来有些过于麻烦了

**Comment by jesusjsc** [comment]
> 

请问如何手动调整新增分类的权限？

**Comment by magicblack** [comment]
这里的逻辑是白名单，添加完默认是无权限~ 改权限麻烦可以用一些批量化工具~
