### ISSUE TITLE
采集接口一直在 502

### ISSUE THREAD

**Issue by Heqiaomu** [magicblack/maccms10#1034]
**添加采集502**
查看了配置项，没啥问题，但是有这个日志：
2023/03/02 22:09:45 [error] 11119#0: *408 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.2, server: video.heqiaomu123.cn, request: ＂POST /adminheqiaomu.php/admin/collect/test.html HTTP/1.1＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-74.sock:＂, host: ＂192.168.1.3:12345＂, referrer: ＂http://192.168.1.3:12345/adminheqiaomu.php/admin/collect/info/id/2.html＂

**Comment by pornlink** [comment]
> **添加采集502** 查看了配置项，没啥问题，但是有这个日志： 2023/03/02 22:09:45 [error] 11119#0: *408 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.2, server: video.heqiaomu123.cn, request: ＂POST /adminheqiaomu.php/admin/collect/test.html HTTP/1.1＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-74.sock:＂, host: ＂192.168.1.3:12345＂, referrer: ＂[http://192.168.1.3:12345/adminheqiaomu.php/admin/collect/info/id/2.html＂](http://192.168.1.3:12345/adminheqiaomu.php/admin/collect/info/id/2.html%EF%BC%82)

频率是不是太高了? 被cf锁了
