### ISSUE TITLE
为什么我同一个资源更新，后台会时不时有同一个视频

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms10#1035]
为什么我同一个资源更新，后台会时不时有同一个视频，我也只勾选了分类更新，其他更新都没有勾选，奇怪了

**Comment by aruoop** [comment]
我也是！就只勾选分类更新，一个资源
最多重复4个

**Comment by magicblack** [comment]
是否有多个采集源？

**Comment by Fewdays** [comment]
是不是这个版本有问题，我发现好多人都会重复，只采集一个源，也会重复3-4个同一个视频源

**Comment by magicblack** [comment]
入库判断这个地方的代码逻辑太多了，回头我再梳理检查一遍~

**Comment by magicblack** [comment]
> ![QQ截图20230427215757](https://user-images.githubusercontent.com/42017510/234885766-7a493564-6ee0-4092-8e2a-1224fa9e062e.jpg) ![QQ截图20230427215741](https://user-images.githubusercontent.com/42017510/234885801-411efb43-2061-4a06-aee8-7b44c15c493d.jpg)
> 
> 只勾选了名称和分类， 可是居然入库了6条，没有小分类

勾选表示**同时满足**才会判断为同一条数据。都不勾选，只保留**名称**试试呢？

**Comment by aruoop** [comment]
> > ![QQ截图20230427215757](https://user-images.githubusercontent.com/42017510/234885766-7a493564-6ee0-4092-8e2a-1224fa9e062e.jpg) ![QQ截图20230427215741](https://user-images.githubusercontent.com/42017510/234885801-411efb43-2061-4a06-aee8-7b44c15c493d.jpg)
> > 只勾选了名称和分类， 可是居然入库了6条，没有小分类
> 
> 勾选表示**同时满足**才会判断为同一条数据。都不勾选，只保留**名称**试试呢？

只勾选名称的话，很多同名电视剧和电影会合并的
