### ISSUE TITLE
重命名admin.php后访问显示当前无法使用此页面

### ISSUE THREAD

**Issue by jinghuashang** [magicblack/maccms10#1048]
https://5.jinghuashang.cn/xiao.php/admin/index/index.html)/xiao.php/admin/index/index.html

当前无法使用此页面5.jinghuashang.cn 重定向次数过多。
若要解决此问题，请尝试[清除 Cookie](https://go.microsoft.com/fwlink/?linkid=2112473).
ERR_TOO_MANY_REDIRECTS当前无法使用此页面5.jinghuashang.cn 重定向次数过多。
若要解决此问题，请尝试[清除 Cookie](https://go.microsoft.com/fwlink/?linkid=2112473).
ERR_TOO_MANY_REDIRECTS当前无法使用此页面5.jinghuashang.cn 重定向次数过多。
若要解决此问题，请尝试[清除 Cookie](https://go.microsoft.com/fwlink/?linkid=2112473).
ERR_TOO_MANY_REDIRECTS

**Comment by magicblack** [comment]
检查nginx配置和伪静态相关配置~
