### ISSUE TITLE
访问网站报500错误

### ISSUE THREAD

**Issue by ErDongChen1973** [magicblack/maccms10#1049]
**描述您的问题**  
之前升级了2023.1000.3051，访问网站首页的时候经常出现500错误，但后台可以正常登录。升级之前稳定运行了一周，没有出现过类似问题。
现在经常过十几个小时，网站访问就报错，但从服务器上的浏览器可以正常访问，然后总其他电脑也可以正常访问，感觉像是重新被激活。（可能描述的不清楚）

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]
Win10  小皮面板

**其他备注信息**

**Comment by magicblack** [comment]
请提供nginx或php关于500请求的日志~
