### ISSUE TITLE
能否增加一个Google的url推送功能，感谢

### ISSUE THREAD

**Issue by longgege666** [magicblack/maccms10#1052]
目前最新版只有百度推送，希望能增加一个Google的推送功能，非常感谢
![K`NTTPU$ZD44MXQ E{5S9LX](https://github.com/magicblack/maccms10/assets/105694435/5a40a1de-c992-4072-a04f-f455bc12bbb2)

**Comment by magicblack** [comment]
暂时没有规划，后期可能会考虑吧~
