### ISSUE TITLE
查询重名视频数据时报错

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#1056]
**描述您的问题**  
查询重名视频数据时报错

**截图**  
![QQ截图20230623132759](https://github.com/magicblack/maccms10/assets/52378245/c67ade69-f51c-431c-8780-d7d9d6f71ea6)

**版本信息:**  
 -  程序版本: [2023.1000.3051]
 - 操作系统: [如 Windows 11]
 - 浏览器: [chrome,]

**其他备注信息**  
数据库版本：5.7

**Comment by magicblack** [comment]
是否数据库里视频名称做了字符集变更？试试数据库执行这句后，再查询重名：
```
ALTER TABLE `mac_tmpvod` CHANGE `name1` `name1` varchar(1024) COLLATE 'utf8mb4_general_ci' NOT NULL DEFAULT '' AFTER `id1`;
```

**Comment by dd0072** [comment]
把所有表排序规则改为：utf8_general_cl后，可以正常查询重名视频数据了
