### ISSUE TITLE
能不能设置采集什么年份的视频

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms10#1057]
能不能设置采集什么年份的视频，比如我只想采集2021,2022,2023年的视频这样的能设置嘛

**Comment by magicblack** [comment]
已开发支持，下个版本一起发布~

<img width="891" alt="image" src="https://github.com/magicblack/maccms10/assets/20452515/4bfac35f-dcf7-41e6-a5dc-793d1b9f49e4">

<img width="283" alt="image" src="https://github.com/magicblack/maccms10/assets/20452515/6590814f-a784-493b-9e19-c711d46109e2">
