### ISSUE TITLE
Class "think\captcha\Captcha" not found

### ISSUE THREAD

**Issue by googidaddy** [magicblack/maccms10#1059]
刚安装完，也重命名admin.php为其他，登入后台无法加载验证码，在浏览器console network中发现此问题，如何解决？

**Comment by 1579704169** [comment]
没有gd.php文件，gp库依赖没有装，如果是在本地则找到php的安装目录打开php.ini，搜索gd，找到  ;extension=gd，删除前面的分号;，保存文件重新运行项目，或者直接把gd库安上

**Comment by googidaddy** [comment]
> 没有gd.php文件，gp库依赖没有装，如果是在本地则找到php的安装目录打开php.ini，搜索gd，找到 ;extension=gd，删除前面的分号;，保存文件重新运行项目，或者直接把gd库安上

谢谢，但我发现我其实是Cloudflare ssl检查没开完全mode，不过你这个建议确实是抛砖引玉
