### ISSUE TITLE
采集时能否对视频名称的开头结尾默认自动去掉空格？

### ISSUE THREAD

**Issue by jesusjsc** [magicblack/maccms10#106]
采集时能否对视频名称的开头结尾自动去掉空格或者tab等？
例如下图，采集的视频中有的视频名称以空格开头，有的以tab开头，等等。

![image](https://user-images.githubusercontent.com/4392829/68522552-5aa9cd80-02e7-11ea-9ea4-d91b1af980c2.png)

**Comment by magicblack** [comment]
嗯，这个可以考虑
