### ISSUE TITLE
支付哪个靠谱正常使用

### ISSUE THREAD

**Issue by XiaomiYe** [magicblack/maccms10#1060]
**描述您的问题**  

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by XiaomiYe** [comment]
里面的其他支付都没法用了，。支付哪个靠谱正常使用

**Comment by magicblack** [comment]
正在开发的版本增加了易支付接口，到时候发布了可以自己找易支付提供商~
