### ISSUE TITLE
{:mac_url_type($obj)} 在文章详情页 生成链接不符

### ISSUE THREAD

**Issue by cdnov** [magicblack/maccms10#1061]
**描述您的问题**  
`<a href="/vodtype/28.html">`

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by magicblack** [comment]
文章类型的`type_mid`需要为2~
