### ISSUE TITLE
致命错误: curl_setopt(): Argument #2 ($option) is not a valid cURL option

### ISSUE THREAD

**Issue by xixihaha806** [magicblack/maccms10#1066]
老王  百度推送比如每页推送设置50条数据  点击推送全部视频后 推送完50条后就显示 致命错误: curl_setopt(): Argument #2 ($option) is not a valid cURL option 这个错误   php版本是8.1  请问这个是怎么回事?

**Comment by magicblack** [comment]
感谢反馈，这边测试下。你切换到PHP 7.4试试~
