### ISSUE TITLE
json接口采集问题

### ISSUE THREAD

**Issue by 2100690024** [magicblack/maccms10#1068]
json接口采集，采集参数设置不好使，他会采集资源站的人气和评分，设置无效

**Comment by 2100690024** [comment]
xml接口无法采集拓展分类

**Comment by magicblack** [comment]
> json接口采集，采集参数设置不好使，他会采集资源站的人气和评分，设置无效

后台 - 采集设置 - 随机评分数 设置为开启，就会以随机的为准。

xml和json都经过统一的数据处理，因此也不会有拓展分类有/无的情况~
