### ISSUE TITLE
捉到一个BUG，这个写法会导致不兼容以前的写法

### ISSUE THREAD

**Issue by smithyj** [magicblack/maccms10#1072]
https://github.com/magicblack/maccms10/blob/b1c143be0e90599520ff4097290b97949b7a825e/application/common/model/Collect.php#L716C25-L716C78

## 解决方法如下，改成下面的就可以兼容了

```
if (($param['filter'] == 1 || $param['filter'] == 2) && $collect_filter['play'][$param['filter']]['cj_play_url_arr']) {
```

**Comment by magicblack** [comment]
我看了判断条件是不一样的，主要是兼容哪种场景？

**Comment by smithyj** [comment]
> 我看了判断条件是不一样的，主要是兼容哪种场景？

主要是为了兼容之前的规则，你现在的这个变动会导致以前的采集规则被破坏掉，无法正常采集视频链接

**Comment by magicblack** [comment]
好的，感谢反馈~

**Comment by magicblack** [comment]
检查了一下历史提交，这里如果用你写的逻辑，判断条件会发生变化。
目前不太理解如果用现在的版本，而不是你改动的，会有什么样的问题出现？

**Comment by smithyj** [comment]
因为以前规则不是走的 cj_play_url_arr

**Comment by magicblack** [comment]
这里暂时不做改动，你那边可以保持兼容一下~
