### ISSUE TITLE
php8.0.28环境下

### ISSUE THREAD

**Issue by JasonMetal** [magicblack/maccms10#1073]
**描述您的问题**  

[Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` 

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: 最新版本
 - 操作系统: centos7
 - 浏览器:  chrome

**其他备注信息**

**Comment by magicblack** [comment]
查看一下PHP日志是哪个文件、多少行报的这个错，我们收到后修改。生产环境先使用PHP7.4~
