### ISSUE TITLE
采集站API设置了指定多个播放组，JSON接口采集入库播放组和地址都是空的

### ISSUE THREAD

**Issue by Jisucloud** [magicblack/maccms10#1074]
**描述您的问题**  
采集站API设置了指定播放组，如果指定多个播放组，JSON接口采集入库播放组和地址都是空的，单个播放组的正常入库
备注：打开API是显示所有指定的播放组的，只是采集入库有多个播放组的视频，播放组和地址都是空的！

**如何重现**  
A站所有视频都有m3u8,mp4两个播放组
A站开放API配置---指定播放组---m3u8,mp4
B站使用JSON接口采集
B站JSON接口采集入库后播放组为空

**预期结果**  
JSON接口B站采集A站指定的多个播放组正常入库

**截图**  
![image](https://github.com/magicblack/maccms10/assets/85449174/dd89691f-2618-4c88-8e21-25605364c530)

![image](https://github.com/magicblack/maccms10/assets/85449174/8803fc07-cd00-4ecf-9f86-5a18a1969e6c)

**版本信息:**  
 -  程序版本: 2023.1000.3051
 - 操作系统: Linux (nginx/1.22.1)
 - PHP版本：7.3.31
 - 浏览器: [如 chrome, safari]

**其他备注信息**  
采集站视频有多个播放组的才会出现入库播放组为空

**Comment by magicblack** [comment]
类似issue:
https://github.com/magicblack/maccms10/issues/888

可能是json采集时过滤播放器逻辑问题。试一下用xml格式采集~

**Comment by hmgdxfoss** [comment]
> 类似issue: #888
> 
> 可能是json采集时过滤播放器逻辑问题。试一下用xml格式采集~
不行，老板。这是个BUG，很多年了，求修复。

**Comment by hmgdxfoss** [comment]
指定多个播放组采集，采集的时候，只有单个播放组的数据正常入库，包含多个播放组的数据采集为空播放器
