### ISSUE TITLE
为什么runtime/tem目录大量缓存东西

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms10#1081]
为什么runtime/tem目录大量缓存东西

![IMG_20231107_215806](https://github.com/magicblack/maccms10/assets/20038296/035807a7-688f-4eb0-9f96-1adadda36ece)

流量大量上行和下行，把tem目录改成只读权限就没事了

**Comment by magicblack** [comment]
可能是有爬虫，页面有缓存的话就会写到temp目录下。自己看nginx日志~
