### ISSUE TITLE
什么时候苹果搜索加一个滑动验证码

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms10#1082]
什么时候苹果搜索加一个滑动验证码
![IMG_20231108_124621](https://github.com/magicblack/maccms10/assets/20038296/eb1ffbce-42c0-44f8-8483-03a75256cc1a)
或者这样的
![Image_1699419889590](https://github.com/magicblack/maccms10/assets/20038296/ecf53c19-7e35-4cc3-b75f-e53e3dce3eca)

**Comment by magicblack** [comment]
https://github.com/magicblack/maccms_down/blob/master/%E4%B8%93%E7%94%A8v10%E6%90%9C%E7%B4%A2%E7%AD%9B%E9%80%89%E9%AA%8C%E8%AF%81%E7%A0%81%E6%A8%A1%E6%9D%BF.zip

参考这个~
