### ISSUE TITLE
重复内容筛选功能

### ISSUE THREAD

**Issue by iermei** [magicblack/maccms10#1086]
以前的版本在重复视频等有重复多少字的筛选，现在版本没有。
那个功能非常的实用。比如名称比较长的，或者名里面有一个字错了或者加了一个字，其实是重复的两个内容，无法被筛选到。
其实内容里面有超多这样重复的。
希望这个功能加回来。

**Comment by magicblack** [comment]
重名问题筛选效率不高，暂无开发计划~ 类似的可参考：https://github.com/magicblack/maccms10/issues/1043
