### ISSUE TITLE
数据更新不成功！

### ISSUE THREAD

**Issue by manongwuma** [magicblack/maccms10#109]
修改网站配置或者绑定分类，一切操作数据库的行为，都不能第一次成功！
清除缓存也不行，明明是提醒成功了，但是刷新后，还是没有改变，清缓存也不成功！
之前的版本好好的，换了最新版就不行了！

**Comment by magicblack** [comment]
这个一般是web服务配置了缓存导致的~~
访问phpinfo(),看看是不是你开启了ZendOpcache之类的opcode缓存.ZendOpcache里面有个过期时间配置,如opcache.revalidate_freq=60 ,表示60秒后脚本再次被访问时会检测PHP文件的时间戳,有改变则更新opcode缓存,你可以设为0,这样每次访问都会检测文件时间戳,你的修改就能生效了.

在php.ini文件中找到
opcache.enable=1
或
opcache.enable_cli=1
改为0，重启php-fpm，done
