### ISSUE TITLE
筛选页最多只能显示前20条子分类信息

### ISSUE THREAD

**Issue by ninglala789** [magicblack/maccms10#1092]
**描述您的问题**  
maccms10开通筛选功能，视频子分类有40 个
**如何重现**  
maccms10开通筛选功能，视频子分类有40 个，但是在筛选页最多只能显示前20条子分类信息，后面的分类信息无法显示，但是打开筛选页的全部视频，是可以看到后面子分类中的视频，怎么更改显示的子分类数目，望解答，谢谢大大。
**预期结果**  

**截图**  
![image](https://github.com/magicblack/maccms10/assets/121956719/85b13993-4200-4c71-9546-05b7b6b6c297)

**版本信息:**  
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by kay1003** [comment]
+1 我也是这个情况，这都大半年了 作者不维护了吗

**Comment by kay1003** [comment]
看源码暂时找到一个方法
#### 文件路径
```php
 /application/common/model/Type.php:112 
```
 将20更改为40或更多
