### ISSUE TITLE
为什么筛选不出任何内容？

### ISSUE THREAD

**Issue by cyberxsboy** [magicblack/maccms10#1093]
**描述您的问题**  
都添加好了各种筛选选项，可就是筛选不出数据来（都是有内容的，如果手动搜索一些标签是有效，可自动调用的标签也不行）。

**具体问题**  

1. 分类页上面的筛选标签无用，点击任何一个都会跳转到当前分类页。（手动给视频资源添加标签之后去测试筛选标签也是不行的）
2. 网站顶部搜索的视频推荐，直接点击弹出来的视频名称，也是不能搜索出结果，只能手动输入视频名称去回车才行。

**其它问题**  
如何将采集数据当中的TAG标签自动添加到采集选项当中的扩展分类当中？

**截图**  
![2023-12-19_125653](https://github.com/magicblack/maccms10/assets/14195003/d2a43b1a-497f-4a78-af23-0ce706a8b046)

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**  
网站域名：animateds.xyz

**Comment by magicblack** [comment]
模板问题，检查模板标签
