### ISSUE TITLE
player.js 里面播放代码加密了？

### ISSUE THREAD

**Issue by dysibai** [magicblack/maccms10#1097]
player.js 里面播放代码加密了？

**Comment by magicblack** [comment]
这里有未加密的~
https://github.com/magicblack/maccms_down/blob/master/%E4%B8%93%E7%94%A8player.js%E5%AE%8C%E5%85%A8%E5%BC%80%E6%BA%90%E6%97%A0%E5%8A%A0%E5%AF%86%E6%97%A0%E8%BF%9C%E7%A8%8B%E8%B0%83%E7%94%A8%E7%89%88%E6%9C%AC.zip
