### ISSUE TITLE
网盘资源

### ISSUE THREAD

**Issue by wanghaisheng** [magicblack/maccms10#1098]
请教一下，我有一些自有资源，目前存在好几个主流网盘那里，大概100G的样子，除了直接下载后台上传以外，有其他方式能直接挂载 的吗，随着内容整理工作的继续，当自由视频容量超过1T时，如果使用这个工具搭建网站，网站流量的费用会不会直接把我干倒了，怎么应对@magicblack

**Comment by magicblack** [comment]
要看主流网盘有没有给接口直接外链播放~通常是不会给的，服务器带宽资源很贵的~
