### ISSUE TITLE
使用苹果cms10最新版怎么筛选出扩展分类下的（所有分类）内容吗？

### ISSUE THREAD

**Issue by 9miaopw** [magicblack/maccms10#1101]
扩展分类只能筛选出某个分类下的数据，我想筛选出所有分类下的数据怎么搞？提示没有权限！

路径：http://dome/index.php/vod/show/class/爱情/id/1.html
以上url只能筛选出 id 为 1下面的数据，我想筛选出所有扩展分类 为 爱情 的数据 （它可能是电视剧又或者是电影动漫等）

使用下面url :http://dome/index.php/vod/show/class/爱情.html  就提示无权限访问了，我应该怎么解决？？？
👍 👍 👍 👍 
帮我！！！

**Comment by 9miaopw** [comment]
Uploading NzQyNjg3MDAxODU_zh_4.mp4…

**Comment by 9miaopw** [comment]
@magicblack   帮我！！

**Comment by ww601063514** [comment]
你这个问题，plus里面有代码，你可以看看

**Comment by magicblack** [comment]
建议查看视频是否存在分类。
