### ISSUE TITLE
登录IP等不支持IPv6 会被显示为0.0.0.0

### ISSUE THREAD

**Issue by esme518** [magicblack/maccms10#1104]
**描述您的问题**  
登录IP等不支持IPv6 会被显示为0.0.0.0

**如何重现**  
用IPv6登陆maccms10

**预期结果**  
显示和Apache中一样的正确IPv6

**版本信息:**  
 -  程序版本: [2023.1000.3052]

**其他备注信息**  
看了下application/common.php，会把IPv6当作非正常IP排除并付值0.0.0.0

**Comment by wellos99** [comment]
请老王重视IPv6问题，强制赋值0.0.0.0影响用户注册，ipv6问题总不能一直回避不解决。

**Comment by Yikang666** [comment]
@magicblack 此问题我也遇到了，老王从2020年就说要改进ip存储方式，到现在依然没有修复。麻烦重视一下，谢谢！
