### ISSUE TITLE
关于maccms V10 2021.1000.2000 的统计代码设置问题

### ISSUE THREAD

**Issue by 602700527** [magicblack/maccms10#1107]
最近搭建好了自己的网站，兴致勃勃的想打开统计功能，就去做推广，发现无论是百度统计还是谷歌统计的代码，设置进去了压根不起作用，无论是设置在cms后台，还是模板的后台，都不起作用。

![0c3ede14f66739ecca93039ca38e9e0](https://github.com/magicblack/maccms10/assets/34017481/368a59dd-2443-4f97-8b1d-9947177cbaad)
![11cb41b2c0122174f08d953c2e6cf98](https://github.com/magicblack/maccms10/assets/34017481/cdc6fb96-7d79-461a-b3cb-35037fa6d070)
![d70dd59fa5137125243e94707b68464](https://github.com/magicblack/maccms10/assets/34017481/1540d875-5770-4a69-9a13-ec132288a5ce)

 -  程序版本: [ 2021.1000.2000]
 - 操作系统: [ Windows 11]
 - 浏览器: [ chrome, safari]

不知道是bug还是我下载的假cms？望大佬指点，相信应该还有其他和我遇到一样的问题的朋友，谢谢！

**Comment by 602700527** [comment]
补充一点:系统部署在宝塔面板，不知道是不是宝塔的问题。

**Comment by magicblack** [comment]
检查模板问题
