### ISSUE TITLE
会员中用户ip显示有的是0.0.0.0，这是为啥？

### ISSUE THREAD

**Issue by jesusjsc** [magicblack/maccms10#111]
后台，“用户”=》“会员”中用户ip显示有的是0.0.0.0，这是为啥？

![image](https://user-images.githubusercontent.com/4392829/68834599-1fe1d400-06f1-11ea-8f9d-7a296eb64fdf.png)

**Comment by magicblack** [comment]
部分移动用户或者ipv6用户可能显示这个。后续会改进。
