### ISSUE TITLE
經 NginxReverseProxyManager 登錄IP 是Docker Gateway IP

### ISSUE THREAD

**Issue by yauyauwind** [magicblack/maccms10#1112]
你好,

我使用 Nginx Reverse Proxy Manager "NPM" "Docker" 來做反向
Maccms 的登錄IP是Docker 那網路段的Gateway
已有在 加入Xforwarded 等設定
location / {
    proxy_set_header Host $host;
    proxy_pass $forward_scheme://$server:$port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 }
我其它Docker 也能透過NPM 後獲得真實IP
其中有些需要設 Trusted Proxy
請問這個 Maccms 是否有相關地方需要設定, 找過一遍沒有找到

煩請指教
謝謝~

**Comment by magicblack** [comment]
location /{
   proxy_set_header HTTP_X_REAL_IP $remote_addr;
}
