### ISSUE TITLE
如何隐藏timming外链

### ISSUE THREAD

**Issue by xiaokuqwq** [magicblack/maccms10#1113]
**描述您的问题**  
在访问网站时发现了一条网络日志

website/api.php/timming/index?t=0.2645876320557372

**如何重现**  
直接打开网站并查看网络日志

**版本信息:**  
 -  程序版本: 官方2023.1000.3052
 - PHP版本	7.4.33
ThinkPHP版本	5.0.24
 - 操作系统: debian11
 - 浏览器: via

**Comment by magicblack** [comment]
可以具体说明，截图示例。

**Comment by xiaokuqwq** [comment]
![Screenshot_2024-02-26-18-55-03-78_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/magicblack/maccms10/assets/108404837/57f2a63c-c7f2-4202-832f-ab52ce35435b)
![Screenshot_2024-02-26-18-54-53-29_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/magicblack/maccms10/assets/108404837/e4b17483-33b4-4aa9-85bf-e827b9a51dac)

**Comment by xiaokuqwq** [comment]
> 可以具体说明，截图示例。

![Screenshot_2024-02-26-18-55-03-78_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/magicblack/maccms10/assets/108404837/5b0d3827-fee1-40b7-a64f-050824471870)
![Screenshot_2024-02-26-18-54-50-55_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/magicblack/maccms10/assets/108404837/02ba6c53-f8c4-4f18-b1ab-1491680e4588)

**Comment by magicblack** [comment]
这个问题你可以根据自己的需要，在nginx做屏蔽，或者修改源码。
