### ISSUE TITLE
使用timehits条件筛选数据会导致整个页面返回空白

### ISSUE THREAD

**Issue by 502315278** [magicblack/maccms10#1116]
使用timehits条件筛选数据会导致整个页面返回空白
{maccms:vod num="10" type="all" timehits="-3 month" order="desc" by="hits"}{$vo.vod_name}{/maccms:vod}
比如这种，不返回任何数据

**Comment by magicblack** [comment]
功能自测了是正常的，检查一下vod_time_hits、点击时间相关数值~
