### ISSUE TITLE
多站共用一个服务器上redis时需区分开,是如何设置，请告知。

### ISSUE THREAD

**Issue by 1709926360** [magicblack/maccms10#112]
多站共用一个服务器上redis时需区分开,是如何设置，请告知。

**Comment by magicblack** [comment]
后台配置修改一下 缓存标识 就可以了

**Comment by 1709926360** [comment]
是每个站都需要修改吗，我修改了设置后台其他站也变成了相同的设置，关键词也也变成相同的了

**Comment by magicblack** [comment]
每个不同的站点肯定需要修改的。   缓存只缓存数据~~~

**Comment by 1709926360** [comment]
每个站点我都设置过了，但是一但保持数据就相同了，我使用站群模式，所以站都在同一目录下
