### ISSUE TITLE
反馈几个bug

### ISSUE THREAD

**Issue by zs126331** [magicblack/maccms10#1121]
1.重名视频数据功能只用有上千个资源就无法打开直到卡死，老版本没有这个问题
2.重名视频不是一个分类的也被检测出来是重名，比如电影叫花千骨动漫也叫花千骨就会被认定为重名资源

**Comment by magicblack** [comment]
问题1已优化： [优化重名检测](https://github.com/magicblack/maccms10/commit/2a521dc7fd27eaed474bc6813d46ef7a57a54b74)

问题2，暂时不会判断分类~
