### ISSUE TITLE
反馈bug

### ISSUE THREAD

**Issue by zs126331** [magicblack/maccms10#1122]
自定义采集的时候手机滑动不了编辑窗口无法编辑和变成手机切换浏览器也无法滑动能底部保存
![Screenshot_20240315_011457](https://github.com/magicblack/maccms10/assets/163433215/67af8f61-e788-4330-abd6-a456167bdff7)
![Screenshot_20240315_011526](https://github.com/magicblack/maccms10/assets/163433215/54995a63-39b4-42f1-b18c-fab1182e96fa)

**Comment by magicblack** [comment]
后台建议使用电脑版本

**Comment by magicblack** [comment]
后面会重新优化后台移动端效果~
