### ISSUE TITLE
无法添加采集，报错！！

### ISSUE THREAD

**Issue by woaijorden** [magicblack/maccms10#1126]
**描述您的问题**  
如图所示，在家里的小主机搭建，添加采集接口后报错！！

**如何重现**  

**预期结果**  

**截图**  

![QQ图片20240322115349](https://github.com/magicblack/maccms10/assets/14155266/54446d70-d969-4089-a612-9378b42c3fdd)

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [Windows 11]
 - 浏览器: [edge]

**其他备注信息**

**Comment by magicblack** [comment]
检查本地与接口的连接~
