### ISSUE TITLE
2024.1000.3000版本后台批量设置了推荐，再改取消推荐出现参数错误。

### ISSUE THREAD

**Issue by China-huc-hk** [magicblack/maccms10#1128]
2024.1000.3000版本后台批量设置了推荐，再改取消推荐出现参数错误。

**Comment by magicblack** [comment]
截图说明

**Comment by China-huc-hk** [comment]
@magicblack  
![微信截图_20240412090302](https://github.com/magicblack/maccms10/assets/63083490/2129a466-a4dd-4e21-9d8e-530282d34a70)

**Comment by sjhupp** [comment]
一样的问题  提示

> 参数错误

**Comment by sjhupp** [comment]
老哥有定位到问题吗
