### ISSUE TITLE
老王  关于自定义404错误页面有个小bug

### ISSUE THREAD

**Issue by xixihaha806** [magicblack/maccms10#1129]
关于苹果cms本身不存在的url 比如https://maccms.test/abc/defg.html   这种404错误 默认是使用think_exception.tpl这个默认模板  我在config.php添加了以下异常处理 'http_exception_template' => [404 => '404.html'], 后  以上的url倒是可以调用根目录的404了  但是也出了个小问题 如下图

![屏幕截图 2024-03-29 183245](https://github.com/magicblack/maccms10/assets/68390320/b26a6948-1995-4d46-a38a-52ccb7424033)

我就新建了个404随便写了几个字 问题是前面的js不知道是哪里来的  还是自动添加的 想删都找不到地方删 老王能处理下吗?

**Comment by deinfo** [comment]
程序系统设置--性能优化提供了一个404页面的方法  你可以试试 不知道行不

**Comment by xixihaha806** [comment]
> 程序系统设置--性能优化提供了一个404页面的方法 你可以试试 不知道行不

你说的方法是管内部url的 比如/index.php/vod/play/id/1135/sid/1/nid/1.html   这样的 你把/id/1355/改成/id/135500000/就显示404页了

**Comment by magicblack** [comment]
全局搜索一下试试，应该是404后自动返回到首页功能~
