### ISSUE TITLE
php8.x 环境下mac_data_count函数mac_data_count=today报错

### ISSUE THREAD

**Issue by deinfo** [magicblack/maccms10#1131]
php8.x 环境下mac_data_count函数mac_data_count=today和mac_data_count=all都报错
致命错误: Undefined constant "all"
致命错误: Undefined constant "today"

**Comment by deinfo** [comment]
mac_day=color 也报错了  我用的最新版2024.1000.3000  php8.3 测试的

**Comment by deinfo** [comment]
今天无聊去问了下百度的文心一言 解决了。。。
mac_data_count="today"加上引号就OK了

**Comment by deinfo** [comment]
{$vo.vod_time|mac_day="color"|mac_substring=10}当更新时间为今天的时候 标签解析出了问题只解析出<符号

**Comment by magicblack** [comment]
感谢反馈~
