### ISSUE TITLE
implode(): Argument #2 ($array) must be of type ?array, string given

### ISSUE THREAD

**Issue by zlmnlskk** [magicblack/maccms10#1135]
最后一步提交安装的时候，提示implode(): Argument #2 ($array) must be of type ?array, string given 安装失败

环境是debian12 php8.2

**Comment by magicblack** [comment]
感谢反馈，可先使用PHP7安装好，再切换PHP8试试。目前全局搜索了一下implode，未找到可疑点。如果有具体是哪一行报错的，更有利于问题修复~
