### ISSUE TITLE
后台视频去重页面打不开，数据库mysql报错

### ISSUE THREAD

**Issue by AD696** [magicblack/maccms10#1136]
**描述您的问题**  
后台视频去重页面打不开，数据库mysql报错SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE8\xAE\xA1\xE5\x88\x92' for column 'name1' at row 70439，查询更改编码也不行，只能清空重新做
**如何重现**  
采集资源之后使用视频去重就会报错

**预期结果**  
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE8\xAE\xA1\xE5\x88\x92' for column 'name1' at row 70439
理论相同，都是这个SQLSTATE[HY000]: 
**截图**  
![c85dba8afb863dd31aad9ebe83599b5](https://github.com/magicblack/maccms10/assets/127026717/748681db-fb8b-4ddb-8b95-f39183f5d0ae)

**版本信息:**  
 -  程序版本: [ 2024.1000.3000]
 - 操作系统: [Centos]
 - 浏览器: [chrome ]

**Comment by zs126331** [comment]
跟你一样的，重复视频哪里打不开，因为数据超过1000左右就打不开，我切换2020年的版本就可以打开

**Comment by zs126331** [comment]
跟服务器性能没关系，我用杜甫测试了，还是一样的

**Comment by magicblack** [comment]
新版优化了。类似issue：https://github.com/magicblack/maccms10/issues/1043
