### ISSUE TITLE
分级剧情没办法和角色一样搜索视频名称获取视频ID添加剧情吗？？？

### ISSUE THREAD

**Issue by 56025192** [magicblack/maccms10#114]
分级剧情没办法和角色一样搜索视频名称获取视频ID添加剧情吗？？？

**Comment by magicblack** [comment]
目前分集剧情是集成在 vod模块的~~  和 角色处理方式不一样。

**Comment by 56025192** [comment]
> 目前分集剧情是集成在 vod模块的~~ 和 角色处理方式不一样。

好吧，我试试会不会重复
