### ISSUE TITLE
关于rss以及sitemap报错

### ISSUE THREAD

**Issue by shidao144** [magicblack/maccms10#1142]
**描述您的问题**  
站点rss以及其他sitemap打开报错

**截图**  
![image](https://github.com/magicblack/maccms10/assets/94615613/998ac861-bb91-4beb-b45c-c31ece7ff185)

**版本信息:**  
 -  程序版本:2024.1000.4010
 - 操作系统:linux
 - 浏览器: chrome

**Comment by heli888** [comment]
你这个是开启了动态，然后生成了静态页面

**Comment by moonmusicstone** [comment]
这个是新版本更新后`application/common/controller/All.php`文件中的一个错误使得生成的RSS文件末尾被附加了一段`script`，使得XML文件语法错误所以报错
```
<script>
        // 兼容低版本浏览器插件
        var um = document.createElement("script");
        um.src = "https://cdn.polyfill.io/v3/polyfill.min.js?features=default";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(um, s);
</script>
```
2天前的更新里已经修复[commit](https://github.com/magicblack/maccms10/commit/2805a4ff7bf08d2b81648f8a7846fff1de690540)，替换该文件内容后显示正常
