### ISSUE TITLE
Ajax模板是否不支持多语言？

### ISSUE THREAD

**Issue by secretwebmaster** [magicblack/maccms10#1147]
**描述您的问题**  
在ajax加载的模块中使用{:lang('key')}时，只返回key，key是确定存在的，在非ajax模板中可以成功输出

**如何重现**  
1. 使用任意lang中的key，或新增自定key (例如 'key' => 'value')
2. 在ajax_login.html中调用 {:lang('key')}，发现只输出了key
3. 在任意模板中调用 {:lang('key')}，成功输出 value

**Comment by magicblack** [comment]
目前管理后台支持了多语言，前端需要模板开发者来支持~
