### ISSUE TITLE
当数据库中视频条数大于7-8万条以后，mysql查询数据非常慢

### ISSUE THREAD

**Issue by BenNewYear** [magicblack/maccms10#1149]
**描述您的问题**  
当数据库中视频条数大于7-8万条以后，mysql查询数据非常慢
后台重名视频数据也无法运行，返回404

**如何重现**  
当数据库中视频条数大于7-8万条以后，
后台-视频-重名视频数据，返回404

**Comment by BenNewYear** [comment]
当视频条数大于12万条以后，前台反应时间非常慢，前台输入一个电影名称点击查询基本要1分钟才会有响应

**Comment by magicblack** [comment]
目前对大量数据的处理性能可能不太好。可以在后台开启搜索缓存，并把缓存时间设置久一些，看看能不能改善~
