### ISSUE TITLE
关于点击量的逻辑问题

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#1150]
对于hits_day、hits_week和hits_month这几个点击量的值，我觉得计算的逻辑有点问题。
比如周点击量hits_week，如果上周某个视频累积了900个点击，但是到了下一周，还没有人点击此视频，这900个点击量并不会自动清零，而是会保持900这个值。这样按周点击调用的热门影片，就并不是实际的热门影片。
不知这方面的问题能否优化呢

**Comment by magicblack** [comment]
这部分暂时无计划改动。但对于你的需求，可以通过定期执行外部脚本，更新数据库字段的值，即可实现~
