### ISSUE TITLE
大佬，求问题排查

### ISSUE THREAD

**Issue by heli8888** [magicblack/maccms10#1153]
**描述您的问题**  
采集出现此问题

**如何重现**  
采集会出现此问题

[2] ErrorException in Request.php line 147
file_get_contents(): open_basedir restriction in effect. File(/opt/rasp74/logs/plugin/plugin.log.2024-05-21) is not within the allowed path(s): (/www/wwwroot/he****/:/tmp/:/www/php_session/heli****/)
            if (property_exists($this, $name)) {
                $this->$name = $item;
            }
        }
        if (is_null($this->filter)) {
            $this->filter = Config::get('default_filter');
        }

        // 保存 php://input
        $this->input = file_get_contents('php://input');
    }

    public function __call($method, $args)
    {
        if (array_key_exists($method, self::$hook)) {
            array_unshift($args, $this);
            return call_user_func_array(self::$hook[$method], $args);
        } else {
            throw new Exception('method not exists:' . __CLASS__ . '->' . $method);
Call Stack
in Request.php line 147
at Error::appError()
at file_get_contents() in Request.php line 147
at Request->__construct() in Request.php line 185
at Request::instance() in App.php line 79
at App::run() in start.php line 19
at require('/www/wwwroot/he****...') in admin****.php line 39

**版本信息:**  
 -  程序版本: 2024.1000.4030
 - 操作系统: Linux (nginx/1.25.5)
 - 浏览器: 搜狗+360浏览器

**其他备注信息**  
也不知道是不是问题，但是经常出现这个问题

**Comment by magicblack** [comment]
可能是站点配置问题，谷歌搜索 open_basedir restriction in effect~
