### ISSUE TITLE
多个定时任务无法生效

### ISSUE THREAD

**Issue by muyiacc** [magicblack/maccms10#1155]
**描述您的问题**  
有多个定时任务采集，结果只生效第一个

**如何重现**  
1.编辑多个定时任务
2.定时执行
3.出错

**预期结果**  
只生效第一个

**截图**  
![e0cdb5fb954e0ec6469061c1fbc0e931](https://github.com/magicblack/maccms10/assets/115904774/22a872df-de45-4eab-b4cd-f204cc851902)
![684de75ca80de6217306664cd7eb2d0b](https://github.com/magicblack/maccms10/assets/115904774/3b5172b3-6110-4457-9939-70808e0e614c)
![7cb72d721a28ed1baadbf3a451436786](https://github.com/magicblack/maccms10/assets/115904774/e964e808-3dc5-4f80-8152-96ba4c9dda29)
![ea8533ad2ed680a0315236dd77319acc](https://github.com/magicblack/maccms10/assets/115904774/7b549ed9-0be4-4641-9eb4-598ad95115d8)

**版本信息:**  
 -  程序版本: 2022.1000.4030
 - 操作系统: Linux (Apache/2.4.54 (Debian))
 - 浏览器: firefox

**其他备注信息**  
查看定时任务的执行，看到实际上执行了，但是maccms后台定时查看只生效了第一条

**Comment by jisoypub** [comment]
同样的问题，debug发现原因参数被只吃掉了。
不改代码的情况可以这么修改：

原url后面的enforce=1&去掉，只保留name这个参数。
curl https://xxx.com。。。/timming/index.html?enforce=1&name=aaa
修改为：
curl https://xxx.com。。。/timming/index.html?name=aaa

**Comment by magicblack** [comment]
如楼上，改一下试试，或者 curl 'https://xxxxx/'
