### ISSUE TITLE
请求修改验证码页面路径

### ISSUE THREAD

**Issue by wooozy64** [magicblack/maccms10#1156]
**描述您的问题**  
后台开启搜索验证码和筛选页验证码后，如果使用了CDN缓存后，访问这些页面会一直在验证码界面循环，不能访问到真正的页面。

**其他备注信息**  
网上查询可以使用Cache-Contral来告诉CDN不要缓存，但是这个需要CDN遵守，另外我的这些页面也需要缓存，只是不想缓存验证码页面。

目前我能想到的方法是：
假设默认搜索页面路径是：`xx.com/search.html?wd=xxxooo`  验证码页面的路径也是这个。这样就导致CDN会缓存这个页面，如果验证码页面变成 `xx.com/search.html?wd=xxxooo？t=13534e53535` 这种增加了时间戳的路径， 或者其它独有的路径，这样就不会被CDN缓存了。

上面都是我能想到的解决方法，作者可能有其它不同的解决方法能解决这个问题也是一样的。

**Comment by magicblack** [comment]
优先在cdn侧配置规则验证码路径不缓存，或者加个时间戳~
