### ISSUE TITLE
最新版网站源代码里面有这个是怎么回事？

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms10#1157]
**描述您的问题**  
最新版网站源代码里面有这个是怎么回事？

![1922662082](https://github.com/magicblack/maccms10/assets/20038296/70868707-8899-4604-b7d3-8195c50f6f5e)

**Comment by hunt678** [comment]
polyfill.js解决浏览器兼容性问题

**Comment by Fewdays** [comment]
> polyfill.js解决浏览器兼容性问题

可以删除吗？在哪里删除？

**Comment by magicblack** [comment]
已经提供配置开关，现代浏览器用户居多的话，关掉即可~
