### ISSUE TITLE
请问接口application/api/controller/Provide.php 里的 搜索能否使用上vod_search的缓存？

### ISSUE THREAD

**Issue by huanzhiyi** [magicblack/maccms10#1161]
在接口搜索的 没在vod_search 数据表添加  应该是没有用上缓存？能否添加上？

**Comment by youxinge** [comment]
苹果CMS 站群  添加超过143个网站后  就不能添加了  在哪里修改限制

**Comment by witchsman** [comment]
> 苹果CMS 站群 添加超过143个网站后 就不能添加了 在哪里修改限制

你这种人吧蛮可怕的，而且脑子是有问的，
