### ISSUE TITLE
苹果CMS10 首页显示异常,游客身份无该分类权限,但是显示了

### ISSUE THREAD

**Issue by tangzhi1996** [magicblack/maccms10#1162]
**描述您的问题**  

首页出现了不应该出现的分类

**如何重现**  
创建了一个新分类,并且游客无该访问权限,
网站参数设置>性能优化 >数据权限过滤： 开启
定时任务,生成首页
使用游客身份,打开首页发现出现了不应该出现的分类,

**预期结果**  
游客身份无相对于分类权限,不应该出现

**截图**  

**版本信息:**  
 -  程序版本: 2024.1000.4030
 - 操作系统: Windows 10
 - 浏览器: edge

**其他备注信息**

**Comment by tangzhi1996** [comment]
好了,我知道原因了,是模板导致的问题,

**Comment by tangzhi1996** [comment]
模板issue

**Comment by zs126331** [comment]
应该是模板的问题，换个模板试试
