### ISSUE TITLE
最新版网站参数设置保存一直卡在数据提交中

### ISSUE THREAD

**Issue by zs126331** [magicblack/maccms10#1166]
**描述您的问题**  
最新版网站参数设置保存一直卡在数据提交中

**如何重现**  
仅在网站参数设置保存出现以上问题，其他地方保存没问题，切换手机测试也不行
**版本信息:**  
 -  程序版本: [如 2024.1000.4043]
 - 操作系统: [如 Windows 11，安卓手机]
 - 浏览器: [如 chrome, ]

**Comment by magicblack** [comment]
给data目录写入权限试试~ 如果还不行，查看一下网站日志，找到具体报错位置贴一下。
