### ISSUE TITLE
入库重复规则能否单独对比 douban id 

### ISSUE THREAD

**Issue by wietrade** [magicblack/maccms10#1167]
**描述您的问题**  
资源站大量使用自己组合的电影名称，有些自己添加年份，空格，符号，或者高清类自己的标签，造成大量重复的电影资料入库，而douban_id是唯一，能否在入库重复规则哪里添加douban_id选项，而不是仅有电影名称，年份，导演，
而且希望这个电影名称没必要必选项，
![屏幕截图 2024-07-07 223447](https://github.com/magicblack/maccms10/assets/18505826/8b95102a-c992-4b5e-b1b6-ddf77dd3a428)

**预期结果**  
目前依靠豆瓣的电影数据生成电影资料已经很成熟，
希望能够依靠豆瓣ID来区分电影是否重复，而不是各种组合的电影名称，

**其他备注信息**  
可以付费开发

**Comment by wietrade** [comment]
这样也可以倒促资源站，提供豆瓣ID，不需要在提供电影资料，从而节省各方资源，和用户浏览的方便性

**Comment by zs126331** [comment]
这个反馈不错哦

**Comment by magicblack** [comment]
好的，感谢反馈，最近开发一下~

**Comment by magicblack** [comment]
[feat入库重复规移除名称必选和新增豆瓣id](https://github.com/magicblack/maccms10/commit/130b2bf123ecf576fd3f3dad4739cb27de44244b)

**Comment by ihwf** [comment]
这个其实最好做成或的关系, 豆瓣 id 相等的时候直接判断为重复,没有豆瓣 id 的时候还是走原有的逻辑, 不然碰上一些豆瓣 id 相同, 名字不同的还是分成了两个,但其实只是名字不完全一致
