### ISSUE TITLE
播放器同义词替换这个怎么用的

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms10#1168]
lzm3u8=wjm3u8  量子的资源会入库成无尽？

![Image_1720411158365](https://github.com/magicblack/maccms10/assets/20038296/9e80bcfd-312c-47b4-a388-2ebd8a075c6f)

**Comment by zs126331** [comment]
这种问题就不要来这里问了，去交流群问，这里是反馈bug的

**Comment by magicblack** [comment]
不是bug
