### ISSUE TITLE
新版本采集视频重复入库

### ISSUE THREAD

**Issue by zs126331** [magicblack/maccms10#1171]
**描述您的问题**  
自动采集会同视频重复入库，采集参数规则仅有名称,分类,年代可以重复入库,已经检查视频为同资源站同播放器同名字无空格特殊符号同年代并且已检查非资源站问题资源站仅单视频

**如何重现**  
1.设置的定时自动采集每10分钟执行一次
2.重复入库视频为同一资源站
3.重复入库的视频更新视频间隔1秒或无间隔
4.发生在最新版本之前版本暂无该问题，站点已经运行2年之前无类似问题

**截图**  
![Screenshot_2024_0713_044223](https://github.com/user-attachments/assets/e7e037ca-3bac-407d-a53c-01c36a6ec529)
![Screenshot_2024_0713_043943](https://github.com/user-attachments/assets/320c5d3f-045d-4be9-83a9-d41fadd1a0b7)
![Screenshot_2024_0713_044425](https://github.com/user-attachments/assets/8569e239-91a3-411a-97e7-53050c98990a)
![Screenshot_2024_0713_044129](https://github.com/user-attachments/assets/a3db9aa0-c6d7-4af8-93b7-f21a08870f75)

**版本信息:**  
 -  程序版本: [如 2024.1000.4043]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by dreampjk** [comment]
这是哪个采集源的
