### ISSUE TITLE
首页logo，通过Dyxs2/dyxs2set更换完后不显示

### ISSUE THREAD

**Issue by jackymrx** [magicblack/maccms10#1175]
**描述您的问题**  

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by sanxianla** [comment]
这个模板有后门 早点弃坑
