### ISSUE TITLE
采集BUG求修复或者指点

### ISSUE THREAD

**Issue by heli8888** [magicblack/maccms10#1179]
部分YS采集，出现如    XXX 无需更新。

名字完全一样：如 唐朝诡事录之西行  

但是视频数据里  查询数据后编辑，无法看到该 视频源

大部分都正常，有小部分出现这种情况

**版本信息:**  
 -  程序版本: 2024.1000.4043
 - 操作系统: Linux (nginx/1.24.0)

**Comment by magicblack** [comment]
不太理解。尝试删除重新采集~
