### ISSUE TITLE
有没有扒出来影视站采集资源来源的技巧

### ISSUE THREAD

**Issue by sanxianla** [magicblack/maccms10#1180]
**描述您的问题**  
看到其他影视站用的苹果cms但是修改了播放器备注，有没有什么思路找到采集的哪家影视资源站的数据

**如何重现**  
例如这家https://www.ncat1.app  的超清资源眼馋很久了只能抓包到一个ip地址的播放数据找不到采集的哪家资源
视频里有广告应该不是付费采集那种

看模板应该是mxone

**Comment by 1060404996** [comment]
我试了一下确实没弄下来

**Comment by 1060404996** [comment]
[Fiddler] 连接到 'www.ncat1.app' 失败.
System.Security.SecurityException 无法与服务器协商HTTPS连接.fiddler.网络.https> HTTPS握手 www.ncat1.app (for #1179) 失败. System.IO.IOException 由于远程方已关闭传输流，身份验证失败。
