### ISSUE TITLE
能不能解决解决重复名问题，重复名多了的情况批量处理直接卡死

### ISSUE THREAD

**Issue by A3tery** [magicblack/maccms10#1182]
能不能解决解决重复名问题，重复名多了的情况批量处理直接卡死，并且网站前台播放会黑屏，只要点击重名批量处理直接卡蹦

**Comment by sanxianla** [comment]
一样 我的站也是 点那个直接卡死 有没有数据库命令可以进数据库改

**Comment by sanxianla** [comment]
什么19版？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月12日(周四) 晚上11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [magicblack/maccms10] 能不能解决解决重复名问题，重复名多了的情况批量处理直接卡死 (Issue #1182)




  
一样 我的站也是 点那个直接卡死 有没有数据库命令可以进数据库改
  
19版的，你可以先用19版的删

**Comment by magicblack** [comment]
Duplicate: https://github.com/magicblack/maccms10/issues/1043
在那边统一解决~

**Comment by sanxianla** [comment]
好嘞



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月11日(周一) 上午10:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [magicblack/maccms10] 能不能解决解决重复名问题，重复名多了的情况批量处理直接卡死 (Issue #1182)




 
Duplicate: #1043
 在那边统一解决~
