### ISSUE TITLE
MySQL 慢日志过多，SELECT *  FROM mac_vod WHERE vod_name LIKE '%xxx%'，服务器负载超标

### ISSUE THREAD

**Issue by 52linglong** [magicblack/maccms10#1184]
**描述您的问题**  
MySQL 慢日志过多，如 `SELECT *  FROM mac_vod WHERE vod_name LIKE '%xxx%'`。服务器负载/CPU超载，服务器/全站卡顿，影响其他站点。

**如何重现**  
十万级数据。

**预期结果**  
优化数据，减低负载。

**截图**  
![load average 1](https://github.com/user-attachments/assets/94faff75-ab0f-4b65-80ad-ef47b223b7e3)
![load average 2](https://github.com/user-attachments/assets/73e1596d-22d5-426d-90b2-bc83271368b6)

**版本信息:**  
 -  程序版本: [如 2024.1000.4040]
 - 操作系统: [如 Debian 11]
 - 浏览器: [如 Chrome]

**其他备注信息**  
十分感谢 Maccms，希望越来越好 ，但是，当前影响服务器整体负载，影视站还是放弃了（闭站），山水有相逢，来日皆可期。
![Close website](https://github.com/user-attachments/assets/05be8fb5-d3db-4859-958a-d0a308a7dab6)

**Comment by magicblack** [comment]
感谢反馈，可尝试开启搜索缓存优化来逐步生成搜索缓存，以降低服务器负载~
