### ISSUE TITLE
一键去重功能异常逻辑

### ISSUE THREAD

**Issue by trainliang** [magicblack/maccms10#1187]
**描述您的问题**  
使用视频分类的一键去重功能没有合并重复分组里不同播放器的数据，造成采集数据丢失

**如何重现**  
任意版本使用重复视频数据合并功能时

**预期结果**  
根据选择的保留大id或小id，删除时判断是否保留的数据内存在被删除的数据，如果有的话就直接删除，没有的话合并删除。

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by magicblack** [comment]
类似：https://github.com/magicblack/maccms10/issues/1043
已经提交代码优化~
