### ISSUE TITLE
恶意拉人头代码

### ISSUE THREAD

**Issue by Rockney99** [magicblack/maccms10#1191]
今天发现有的资源站播放接口在移动端站点播放视频切到抖音会弹出邀请口令识别，这种情况该怎么办
![微信图片_20240924113839](https://github.com/user-attachments/assets/b24583b0-ba5a-41af-8151-67179124312e)
![微信图片_20240924113836](https://github.com/user-attachments/assets/4c194b8a-531d-4370-8b23-9208558ab054)
ba75)
![微信图片_20240924113840](https://github.com/user-attachments/assets/ba37785d-f3b1-4b52-9df8-4aa0fa4ec5e4)

**Comment by teaka-xss** [comment]
这个是APP代码问题吧，可以详细说一下，挺感兴趣的

**Comment by magicblack** [comment]
检查模板前端代码~
