### ISSUE TITLE
后台登陆页面不显示验证码

### ISSUE THREAD

**Issue by zzh4141** [magicblack/maccms10#1193]
**描述您的问题**  
安装完毕并更改了后台访问地址,想要登录的时候发现验证码没有显示,网站是套cf cdn
**如何重现**  
1. 安装cms
2. 修改后台地址
3. 但登录的时候需要验证码验证码是损坏的

**截图**  

![图片](https://github.com/user-attachments/assets/3f9bb887-6508-4423-930c-b05bf8c45af5)

**版本信息:**  
 - 操作系统:  Windows 10
 - 浏览器: 火狐

**其他备注信息**  
搭建面板使用的是1p
运行环境是使用运行在docker php:8.3.8

**Comment by magicblack** [comment]
检查请求500报错具体原因~ 缺失扩展还是？php版本尝试降到7.4~
