### ISSUE TITLE
有个很严重的问题

### ISSUE THREAD

**Issue by hengmeiliLLC** [magicblack/maccms10#1194]
支付对接里面，易支付，添加了以后，其他支付方式全部留空，前面还是无法显示易支付，后来网上查找教程怎么填加易支付，全部教程都是说application/SDK在这个文件夹，可是找来找去都没有看见这个文件夹，麻烦给个解决办法，易支付明明添加了，前台还是无法显示提示支付未启用

**Comment by magicblack** [comment]
检查模板是否支持易支付选项~ 
参考：https://github.com/magicblack/maccms10/commit/9a4aced7e5158a89a0d6bface6e7ba61e93abc06
