### ISSUE TITLE
希望增加海外图片存储支持

### ISSUE THREAD

**Issue by liuchengts** [magicblack/maccms10#1196]
**描述您的问题**  
首先非常感谢作者提供这个开源项目，对我帮助很大。
出于这一个多月的使用感受，我提了这个issue，同时也希望这个项目能够帮助到更多人，再次感谢作者。

我的问题：希望在“附件参数配置”中增加比较出名的海外oss存储服务支持，比如 cloudflare

**如何重现**  
我用maccms10部署网站在国外，纯正的英文网站，图片加载cdn却是用的国内，导致有些地区访问图片加载会很慢。而且看着不那么具有英文网站的纯了

**预期结果**  
希望图片也能走国外oss存储，能让网站成为一个纯正的国外网站

**Comment by magicblack** [comment]
可以先通过ftp功能实现，或保存到本地，使用Cloudflare的域名加速访问~
