### ISSUE TITLE
采集时偶发性报下面错误

### ISSUE THREAD

**Issue by 30873732** [magicblack/maccms10#1202]
SQLSTATE[42S02]: Base table or view not found: 1146 Table ＇数据库名.mac_vod_repeat＇ doesn＇t exist
![image](https://github.com/user-attachments/assets/68769b82-c9d3-4a79-af81-e62203b8dc33)
数据库中我看也有这个表名

**Comment by 30873732** [comment]
程序版本2024.1000.4044，环境PHP 7.4.33  MySQL 5.7.44  Nginx 1.24.0

**Comment by woodchen-ink** [comment]
+1

**Comment by zhengyongtao** [comment]
+1，啥时候能有新版本啊？最近爬取全部老费劲了，时不时就要上去刷一下页面，不然就卡在这儿

**Comment by a521450** [comment]
我现在是程序会自动删除这个表，SQLSTATE[HY000]: General error: 1813 Tablespace '`cssailai`.`mac_vod_repeat`' exists.
我把mac_vod_repeat加进去，一采集就删除了，不知道咋搞了

**Comment by magicblack** [comment]
先在后台 视频 - 重名视频数据 - 点击一下更新缓存按钮~ 下个版本优化修复~
