### ISSUE TITLE
王哥开启页面缓存所以网站的标题和关键词都相同了，需要在哪里设置。

### ISSUE THREAD

**Issue by 1709926360** [magicblack/maccms10#122]
同标题

**Comment by magicblack** [comment]
pc  和 wap吗，暂时可以单独在模板里设置。

**Comment by 1709926360** [comment]
主要我有几百个站不可能每个来单独创建这么多模板，可以通过修改便签或函数来实现吗

**Comment by 1709926360** [comment]
还有我现在调用time标签设置一周，一月等标签无法实现，如：timeadd_week标签，{maccms:type num="10" order="asc" by="timeadd_week" ids="all"}还是我用法错误，望告知

**Comment by magicblack** [comment]
目前v10没有提供站群功能。不支持一个站点绑定N个域名访问。 建议关闭页面缓存只开启数据缓存。

**Comment by 1709926360** [comment]
可以告诉我在什么修改吗，我可以自己二开不，修改页面缓存功能
