### ISSUE TITLE
你好，请问如果不小心删除了服务器本地（upload）的图片，有没有办法再次同步？

### ISSUE THREAD

**Issue by X-Empire** [magicblack/maccms10#123]
①如题，昨天手残了，在宝塔面板删除多余图片时，删除了upload/vod的文件，宝塔没有开启回收站，所以图片找不回来了，所以请问一下有没有办法再次同步资源站图片，谢谢
②采集视频时有没有办法自动同步豆瓣ID，进而同步豆瓣评分

**Comment by magicblack** [comment]
没有直接办法。只能是 重新更新下图片地址 ，从新同步。
