### ISSUE TITLE
请问 开放API配置 开启后 使用接口发现 顶级分类的取不到数据

### ISSUE THREAD

**Issue by a568640533** [magicblack/maccms10#130]
请问 开放API配置开启后。使用“/api.php/provide/vod/?ac=detail&t=”参数去取数据。顶级分类的取不到任何数据，反而子分类下的都一切正常可以取到数据。。。
把站点删除重新安装部分顶级分类却又可以取到但依旧是不正常！！

比如：分类1、跟后台分类ID一致//  取到的数据却是。。。{"code":1,"msg":"\u6570\u636e\u5217\u8868","page":1,"pagecount":0,"limit":"20","total":0,"list":[]}
取子分类的数据却正常：
{"code":1,"msg":"\u6570\u636e\u5217\u8868","page":1,"pagecount":3,"limit":"20","total":41,"list":[{"vod_id":210,"type_id":22,"type_id_1":3,"group_id":0,"vod_name":"\u7231\u73a9\u5ba22019","vod_sub":"","vod_en":"aiwanke2019","vod_status":1,"vod_letter":"A","vod_color":"","vod_tag":"\u7231\u73a9,\u7231\u73a9\u5ba2,\u73a9\u5ba2,2019,\u4e09\u7acb,\u4e09\u7acb\u90fd\u4f1a,\u4e09\u7acb\u90fd\u4f1a\u53f0,\u90fd\u4f1a,\u90fd\u4f1a\u53f0,\u4f1a\u53f0,\u6bcf\u5468,\u5468\u4e00,\u4e00\u5230,\u5468\u4e94,21:00,\u5de5\u4f5c,\u7231\u5728,\u5728\u751f,\u5728\u751f\u6d3b,\u751f\u6d3b,\u7231\u73a9,\u7231\u73a9\u5ba2,\u73a9\u5ba2,\u5168\u65b0,\u65b0\u7684,\u65c5\u884c,\u5403\u73a9,\u5168\u4e16\u754c,\u4e16","vod_class":"\u6e2f\u53f0\u7efc\u827a","vod_pic":"https:\/\/images.cnblogsc.com\/pic\/upload\/vod\/2017-09-05\/15045936686.jpg","vod_pic_thumb":"","vod_pic_slide":"","vod_actor":"\u8a79\u59c6\u58eb","vod_director":"","vod_writer":"","vod_behind":"","vod_blurb":"\u4e09\u7acb\u90fd\u4f1a\u53f0\u6bcf\u5468\u4e00\u5230\u5468\u4e9421:00\uff0c\u73a9\u5728\u5de5\u4f5c\uff0c\u7231\u5728\u751f\u6d3b\uff0c\u300a\u7231\u73a9\u5ba2\u300b\u5168\u65b0\u7684\u65c5\u884c\u5e26\u4f60\u5403\u73a9\u5168\u4e16\

**Comment by magicblack** [comment]
嗯，这里的确是不让显示点

**Comment by a568640533** [comment]
> 
> 
> 嗯，这里的确是不让显示点

那该如何解决呢？现在因为这个问题删除重装在删除重装。。。折腾好久了！！
