### ISSUE TITLE
伪静态如何实现和虎牙主播一样的根目录路径？

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#133]
比如：https://www.huya.com/longdd
           https://www.huya.com/831392

我现在使用苹果cms能实现的如下：

          https://www.xxx123.com/mulu/longdd
          https://www.xxx123.com/mulu-831392

和虎牙直播的伪静态路径相比，明显比我强啊
那么，请问如何让苹果CMSv10实现和虎牙直播一样的根目录路径呢？

**Comment by magicblack** [comment]
目前不支持根目录下的伪静态，必须有二级目录或字符来区分。

**Comment by ycgz2008** [comment]
可惜了~希望下一版本加强此功能，跟上时代潮流
