### ISSUE TITLE
飞飞CMS转换苹果CMSv10 别名全是0

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#134]
最近刚从飞飞CMS转换到苹果CMSv10，视频数据别名全是 0 

打开其中一个视频数据，不编辑，点击保存，这个视频数据别名自动从 0 变回正常别名（也就是视频拼音）,或者打开一个视频数据，删除别名 0 ，点保存也可以

全部数据难道要一个一个点击编辑，然后点击保存？

尝试进入MYSQL删除vod_en中的 0 删除测试失败

因为使用的拼音伪静态，ID伪静态不存在此问题

**Comment by magicblack** [comment]
查阅相关代码没有发现问题~

**Comment by ycgz2008** [comment]
> 查阅相关代码没有发现问题~

好吧，我手动一个一个修改吧2000多数据，说多也不多
