### ISSUE TITLE
后台 视频数据 无 视频年代 选项

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#135]
![360截图20191203170728011](https://s2.ax1x.com/2019/12/03/QMay2d.jpg)

如上图没有 视频年代 选项？故意为之吗，还是有什么原因，想使用，发现没有

**Comment by magicblack** [comment]
使用频率比较少，位置有限

**Comment by ycgz2008** [comment]
> 使用频率比较少，位置有限

因为有用到，能告诉应该修改那个文件吗？感觉很简单，依照其他选项添加下应该就可以了
