### ISSUE TITLE
mac_tmpart 表发现很多沉余数据 有 1011712 kb 怎么处理

### ISSUE THREAD

**Issue by wmxsd123456** [magicblack/maccms10#136]
mac_tmpart 表发现很多沉余数据 有 1011712 kb 怎么处理
表里面没有任何数据

**Comment by anglesgirl** [comment]
优化

**Comment by wmxsd123456** [comment]
优化不管用

在 2019-12-03 20:55:46，"雅丶涵" <notifications@github.com> 写道：


优化

**Comment by magicblack** [comment]
灭有关系可以删除，是重名数据查询自动创建的表。
