### ISSUE TITLE
火车头api发布视频 地址写不进去

### ISSUE THREAD

**Issue by websecer** [magicblack/maccms10#138]
我用的火车头9 api发布，我的操作步骤是，在后台正常不发，然后抓包，把参数写进去发布模块，post的地址就是api的地址，最后加上密码参数 ，其他都有写入，就是播放地址发布失败

**Comment by magicblack** [comment]
建议从数据库中查看一下 地址是否正确写入。 然后再查看是否自行整合了对应的播放器
