### ISSUE TITLE
希望联系到王哥，期待你的邮件

### ISSUE THREAD

**Issue by natural-ts** [magicblack/maccms10#14]
我的邮箱pengxp1996@hotmail.com
希望联系上王哥，获取到版本更新的具体内容
期待你的邮件

**Comment by magicblack** [comment]
点击wiki菜单里边有更新日志。

**Comment by natural-ts** [comment]
> 点击wiki菜单里边有更新日志。

好的，我会转发最新版本至博客

**Comment by natural-ts** [comment]
> 点击维基菜单里边有更新日志。

苹果CMS V10 入库接口说明 https://www.wanvi.net/10489.html
苹果CMS V10 定时任务说明https://www.wanvi.net/10490.html
苹果CMS V10 标签文档https://www.wanvi.net/10491.html

如果有什么问题，请及时回复我
