### ISSUE TITLE
不知道算不算BUG

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#140]
投放代码
< meta name="description" content="{$obj.vod_content|mac_substring=100|mac_filter_html}" />

显示效果
< meta name="description" content="&nbsp.;  &nbsp.; &nbsp.;&nbsp.;电视剧《青春时代》由曾执导《亲爱的恩东啊》等作品的李太坤导演执导，讲述了住在同一屋檐下的外貌、性格、专业、喜欢的男生类型、恋爱方式各不相同的五名女大" />

“&nbsp.;  &nbsp.; &nbsp.;&nbsp.;”剧情简介里面的空格符，剧情简介里没有空 格正常，如何不显示这些，这算不算是BUG？

**Comment by magicblack** [comment]
可以尝试把 mac_filter_html 换成 strip_tags函数试试

**Comment by ycgz2008** [comment]
> 可以尝试把 mac_filter_html 换成 strip_tags函数试试

尝试下面三种方式，并后台清除缓存，前台浏览，测试失败

{$obj.vod_content|mac_substring=100|strip_tags}
{$obj.vod_content|mac_substring=100|mac_filter_html|strip_tags}
{$obj.vod_content|strip_tags}
