### ISSUE TITLE
关于文章编辑

### ISSUE THREAD

**Issue by ayanyi** [magicblack/maccms10#141]
文章编辑超级链接将https改成http发布文章后http会变成mac://www.baidu.com，这个有什么解决方案吗

**Comment by magicblack** [comment]
暂时可以用 mac_url_content_img 函数处理详情内容。 

{$obj.vod_content|mac_url_content_img} 如果使用了第三方附件存储，附件和图片默认url是mac:开头的，此方法将替换为http
