### ISSUE TITLE
角色采集会出现同演员名称和角色名称一样，视频名称不一样会导致采集重复无法入库

### ISSUE THREAD

**Issue by 56025192** [magicblack/maccms10#142]
![image](https://user-images.githubusercontent.com/39239064/70589260-43be0a00-1c0a-11ea-9fc4-2c22493e3c4a.png)
![image](https://user-images.githubusercontent.com/39239064/70589269-49b3eb00-1c0a-11ea-87da-f0d04739fb05.png)

**Comment by magicblack** [comment]
已经确认修复

**Comment by 56025192** [comment]
无法在线更新？？？
