### ISSUE TITLE
苹果cms V10 文章内容页如何获取上一篇下一篇

### ISSUE THREAD

**Issue by X-Empire** [magicblack/maccms10#144]
href 文章上一篇下一篇代码

例如：<a class="text-overflow" href="/artdetail/639543.html" target="_self">上一篇：《幸福在一起》开播王培栋合作《回家》班底</a>
<a class="text-overflow" href="/artdetail/639545.html" target="_self">下一篇：电视剧《权与利》待播，杜安琪化身主持人</a>

**Comment by X-Empire** [comment]
<li class="col-md-6"><a class="text-overflow" href="/artdetail/14499.html" target="_self">上一篇：《幸福在一起》开播王培栋合作《回家》班底</a></li>
<li class="col-md-6"><a class="text-overflow" href="/artdetail/14501.html" target="_self">下一篇：电视剧《权与利》待播，杜安琪化身主持人</a></li>

**Comment by X-Empire** [comment]
<---li class="col-md-6"><a class="text-overflow" href="/artdetail/14499.html" target="_self">上一篇：《幸福在一起》开播王培栋合作《回家》班底</a></li>
<li class="col-md-6"><a class="text-overflow" href="/artdetail/14501.html" target="_self">下一篇：电视剧《权与利》待播，杜安琪化身主持人</a></li>
</ul>
  <-----/div>

**Comment by magicblack** [comment]
可以参考默认文章详情页模板

**Comment by martenorton** [comment]
没有呢
