### ISSUE TITLE
这个文件xmlutf_2014.js链接不到

### ISSUE THREAD

**Issue by jctml** [magicblack/maccms10#15]
maccms后台=>采集=>联盟资源库，页面中什么都没有，GOOGLE=>NETWORK报了个错

> Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
> GET http://www.maccms.com/union/xmlutf_2014.js net::ERR_CONNECTION_TIMED_OUT

具体文件是
 **application/admin/view/collect/union.html**
```
 <script src="//www.maccms.com/union/xmlutf_2014.js" charset="utf-8"></script>
```

这个资源下载不下来，不知道是做什么用的，能不能将这个文件也放在GITHUB上，谢谢

**Comment by magicblack** [comment]
不提供采集插件，请自己整合。
