### ISSUE TITLE
年份筛选能否增加一个“更早”选项呢

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#153]
如题，毕竟能写在分类设置里的年份是有限的，更早的电影就无法筛选出来了，所以能否增加一个“更早”的筛选项呢，比如可以筛选出2000年之前的视频，而且这个2000如果可以自己设置就更完美了^_^

**Comment by magicblack** [comment]
是支持的参数可以写年代区间例如2000-1900

**Comment by lixuehan1234** [comment]
好的，多谢作者大人
