### ISSUE TITLE
无法采集

### ISSUE THREAD

**Issue by zuoan0** [magicblack/maccms10#154]
服务器和资源站没有问题
我系统重新安装了，服务器也换了，最多正常采集两天，后面就提示"连接API资源库失败，通常为服务器网络不稳定或禁用了采集" 请问这是什么问题呀 ，这种情况下我重新安装系统8次了 换过一次服务器

**Comment by magicblack** [comment]
目标站点或者你的站点网络不稳定，或者被封。
