### ISSUE TITLE
希望改进一下PC和移动的播放方式

### ISSUE THREAD

**Issue by akaqing** [magicblack/maccms10#157]
PC下打开播放地址提示，需要移动端才可以播放

**Comment by akaqing** [comment]
<div class="vod">
<div id="playpage_player" style=" height: 100%; width: 100%;">
                               {$player_data}{$player_js}	
                         </div> 
     <script>     
                                var arr = ["1","2",'3',"4"]; //限制多个分类必须在移动端播放                                 
                                if(IsPC() &&arr.indexOf("{$XXXXXXXXXX当前分类怎么设置判断}")>-1)
                                {
                                 document.getElementById("playpage_player").innerHTML="<br><br><div style='text-align:center;color:red;'>当前视频只支持移动端播放<br><br><p><img src='{seacms:siteurl}/qrcode/?text={seacms:siteurl}{playpage:link}'/></p>扫一扫用手机观看 </div>";
                                }    
    </script>									
</div>

**Comment by magicblack** [comment]
建议自行在模板里判断。

**Comment by akaqing** [comment]
{$player_data}{$player_js}  能写一个示例吗？

**Comment by akaqing** [comment]
> 建议自行在模板里判断。

{$player_data}{$player_js} 能写一个示例吗？
