### ISSUE TITLE
蓝奏网盘下载地址

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#158]
老大给个蓝奏网盘的下载地址呗

**Comment by magicblack** [comment]
用什么蓝凑啊，直接git直连下载 

v10
https://github.com/magicblack/maccms10/archive/master.zip

v8
https://github.com/magicblack/maccms8/archive/master.zip

**Comment by moyan73807** [comment]
这直连 直接是全部的啊  没更新的

**Comment by dd0072** [comment]
> 用什么蓝凑啊，直接git直连下载
> 
> v10
> https://github.com/magicblack/maccms10/archive/master.zip
> 
> v8
> https://github.com/magicblack/maccms8/archive/master.zip

这要全部上传覆盖，我想着还是升级包方便一点。
