### ISSUE TITLE
怎么把hits,hits_day,hits_week,hits_month 1000显示成1K 10000显示成1W

### ISSUE THREAD

**Issue by akaqing** [magicblack/maccms10#162]

**Comment by magicblack** [comment]
建议你使用模板自定义函数来处理 ，送你一个php函数

public function friendNum($num){  
  if(empty($num) || !is_numeric($num)){  
    return 0;  
 }  
 if($num >=1000 && $num < 10000){  
    return round($num/1000,1).'K';  
 }  
 if ($num >= 10000) {  
    return round($num/10000,2).'W';  
 }  
    return $num;  
}
