### ISSUE TITLE
检测反链也有问题

### ISSUE THREAD

**Issue by 2445990463** [magicblack/maccms10#164]
检测反链也有问题

**Comment by magicblack** [comment]
神马问题？

**Comment by 2445990463** [comment]
不管正常不正常都反链异常

**Comment by 2445990463** [comment]
去了他就正常了
![QQ图片20191229125145](https://user-images.githubusercontent.com/45478919/71552548-34c4bd80-2a3a-11ea-9d99-964f5b5593e1.png)

**Comment by magicblack** [comment]
稍后更新
