### ISSUE TITLE
页码分布有一个不合理之处

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#165]
分页使用默认的half值，只显示5个页码，测试分类总共56页。
从前面数，在第4页的时候，页码整体向前移动，这部分是正常的。
![1](https://user-images.githubusercontent.com/55046423/71543606-dfdc6500-29af-11ea-9423-456935e46564.png)

而从后面数，正常的情况应该倒数第4页时，页码就已经向后移动，可是并没有，在倒数第5页的时候页码仍没有移动，如图：
![3](https://user-images.githubusercontent.com/55046423/71543607-e539af80-29af-11ea-86d7-f9c8381ad04d.png)

这就造成了一个问题，就是页面上必须要加 上一页 和 下一页 链接，不然用户从后往前翻的时候，到了倒数第5页就无法再继续向前翻页了，这在手机版有限的空间里多加两个链接不太容易办。

看了一下代码，发现向左移动的数值是 floor($page_half / 2)，而向右移动的数值是 $page_total - $page_half ，能否把向右移动的数值也改为用  总页数 - half/2  值进行判断，或者至少把数值扩大1，以杜绝上面这个很恼人的问题呢？

多谢~

**Comment by magicblack** [comment]
稍后测试一下
