### ISSUE TITLE
可以增加入库api设置的播放地址 倒序 正序 设置吗？

### ISSUE THREAD

**Issue by moyan73807** [magicblack/maccms10#166]
可以增加入库api设置的播放地址 倒序 正序 设置吗？
就腾讯视频火车头采集动漫视频的时候  是从最新更新的集数开始的（倒序）
这类型  https://cdn.u1.huluxia.com/g3/M01/B5/D2/wKgBOV4HZY6APY2XAABv8XHRMNA716.png

**Comment by moyan73807** [comment]
火车头设置没法改变  就只有 老王 你这边 麻烦麻烦了

**Comment by magicblack** [comment]
这个建议统一入库的时候做好处理。不然有的正序有的倒序  不好处理。
