### ISSUE TITLE
这个建议统一入库的时候做好处理。不然有的正序有的倒序  不好处理。

### ISSUE THREAD

**Issue by moyan73807** [magicblack/maccms10#167]
这个建议统一入库的时候做好处理。不然有的正序有的倒序  不好处理。

_Originally posted by @magicblack in https://github.com/magicblack/maccms10/issues/166#issuecomment-569468806_
  火车头好像暂时没有这类插件。。。

**Comment by magicblack** [comment]
这个自己写规则的时候就可以处理啊。

**Comment by moyan73807** [comment]
火车头 好像暂时没有 正序 倒序的设置 在里面
