### ISSUE TITLE
请问下，网址导航栏目列表有翻页相关标签么

### ISSUE THREAD

**Issue by sd231902** [magicblack/maccms10#168]
请问下，网址导航栏目列表有翻页相关标签么
还有辛苦问下，后面会加用户投稿么。。

**Comment by magicblack** [comment]
和文章分类等等  页面是一样的~~~  用户投稿会加入

**Comment by sd231902** [comment]
`websitetype/<id>-<page?>   => website/type
websitetype/<id>   => website/type
website-<page?>   => website/index
website$ => website/index
websitedetail-<id>   => website/detail
websiteshow/<id>-<area?>-<by?>-<class?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<tag?>   => website/show
websitesearch/<wd?>-<area?>-<by?>-<class?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<tag?>   => website/search`

路由规则里已经加了这一段
翻页处，也是用的默认的翻页标签，视频，文章列表翻页都正常
`   <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=1}" title="首页">首页</a>
        <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_prev}" title="上一页">上一页</a>
        {maccms:foreach name="$__PAGING__.page_num" id="num"}
        {if condition="$__PAGING__['page_current'] eq $num"}
        <a class="page_link page_current" href="javascript:;" title="第{$num}页">{$num}</a>
        {else}
        <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$num}" title="第{$num}页" >{$num}</a>
        {/if}
        {/maccms:foreach}
        <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_next}" title="下一页">下一页</a>
        <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_total}" title="尾页">尾页</a>`

就是到网址列表翻页这里，每次都是
abc.com/website-1.html
abc.com/website-2.html
abc.com/website-3.html

是我添加错了么还是？
