### ISSUE TITLE
还是网址列表翻页问题

### ISSUE THREAD

**Issue by sd231902** [magicblack/maccms10#170]
websitetype/<id>-<page?> => website/type websitetype/<id> => website/type website-<page?> => website/index website$ => website/index websitedetail-<id> => website/detail websiteshow/<id>-<area?>-<by?>-<class?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<tag?> => website/show websitesearch/<wd?>-<area?>-<by?>-<class?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<tag?> => website/search

路由规则里已经加了这一段
翻页处，也是用的默认的翻页标签，视频，文章列表翻页都正常
<a class="page_link" href="{$__PAGING__.page_url|mac_url_page=1}" title="首页">首页</a> <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_prev}" title="上一页">上一页</a> {maccms:foreach name="$__PAGING__.page_num" id="num"} {if condition="$__PAGING__['page_current'] eq $num"} <a class="page_link page_current" href="javascript:;" title="第{$num}页">{$num}</a> {else} <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$num}" title="第{$num}页" >{$num}</a> {/if} {/maccms:foreach} <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_next}" title="下一页">下一页</a> <a class="page_link" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_total}" title="尾页">尾页</a>

就是到网址列表翻页这里，每次都是
abc.com/website-1.html
abc.com/website-2.html
abc.com/website-3.html

是我添加错了么还是？

**Comment by magicblack** [comment]
分类列表  具体是哪个分页。

**Comment by sd231902** [comment]
分类页模版type.html            abc.com/websitetype/5.html
abc.com/websitetype/5-2.html

**Comment by sd231902** [comment]
模板website下有index.html，type.html，show.html，detail.html，search.html
重新做的模板

以分类ID5举例    
类型，网址
分类页模版 type.html        
 abc.com/websitetype/5.html

筛选页模版show.html
abc.com/websitetype/5-2.html
abc.com/websitetype/5-3.html
abc.com/websitetype/5-4.html
 
正常地址应该是上面所示
现在是所有网址分类ID，包括分类ID2,分类ID3,分类ID4，（以上分类，类型都是网址）下的列表翻页的第一页，第二页，第三页，第四页等
都是
abc.com/website-2.html
abc.com/website-3.html
abc.com/website-4.html
 

还有，后台-基础-分类管理，类型是网址的分类下统计数量都是0，
后台-网址-网址数据-这里面是正常有数据的，且显示统计数量

不知道表达清楚没有，你可以测试一下~

**Comment by sd231902** [comment]
还有辛苦问下，系统-网站参数设置-性能优化，是否有网址搜索规则

**Comment by magicblack** [comment]
修复了，稍后更新。
