### ISSUE TITLE
演员show页面还是没有权限

### ISSUE THREAD

**Issue by 2445990463** [magicblack/maccms10#173]
演员show页面还是没有权限

**Comment by magicblack** [comment]
新加的分类，  会员组是否 分配了权限呢。

**Comment by 2445990463** [comment]
好像是必须加上分类id像下面这样
{:mac_url('actor/show',['area'=>'大陆,内地','id'=>22])}

**Comment by magicblack** [comment]
当然里，，，没分类id  谁知道哪个份额里。
