### ISSUE TITLE
同步图片反馈建议

### ISSUE THREAD

**Issue by vcanlin** [magicblack/maccms10#175]
视频管理，文章管理等，同步图片功能有个提议。
如果我之前同步过图片，并且导出到个人网盘（或其他图床），通过数据替换upload/vod/0a3eab9b897d192cfde5e0eaf779a224.jpg
替换为图床的url:
http(s)://img.mydomain.com/vod/0a3eab9b897d192cfde5e0eaf779a224.jpg。
主要是这样做主要原因是分开储存图片，分流和搬站也方便。（图片不用再搬）。
但是问题就存在：
采集到新资源（或资源更新）时，再同步图片时，那么图床图片（http开头的）也会重新再被同步到站点的目录下。（按日期同步只能选一天，也是不方便操作）
建议同步图片时，可以有个选择，能够避免这种情况发生。
希望老大能看到这个问题,谢谢

**Comment by magicblack** [comment]
你可以把图片开头地址改为 mac:// 这样不会再次同步。
