### ISSUE TITLE
采集的时候出错

### ISSUE THREAD

**Issue by lukemin** [magicblack/maccms10#178]
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'vod_en' at row 1
怎么设置才能跳过错误的页面？
RE:############################################
该错误就插入字段长度超过设定的长度，一般程序会在数据库字段设置字符长度在插入之前程序很少会先判断数据长度和截取数据 这样会影响性能，所以你就需要修改你数据库的配置文件一般在MYSQL 安装目录中的my.ini中 搜索sql-mode
sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
把其中的STRICT_TRANS_TABLES,去掉 建议使用该方法
sql-mode=“NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
或者把
sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION” 直接删除
已经修改过了。

**Comment by magicblack** [comment]
修改后重启下mysql就行里呢。

**Comment by lukemin** [comment]
谢谢，回复。
采集的时候有些页面报错，就会反复重试，怎么才能跳过报错的页面？能否加上一个采集的时候忽略错误的选项？
