### ISSUE TITLE
memcached发生错误，请检查是否开启扩展库和配置项!

### ISSUE THREAD

**Issue by aoerboquartz** [magicblack/maccms10#179]
你好，
宝塔安装php7.3
php扩展安装的memcached
但是苹果10后台，不管选择memcache还是memcached 都提示：
发生错误，请检查是否开启扩展库和配置项!
端口号没有问题，核对过了。

**Comment by aoerboquartz** [comment]
宝塔安装的Memcached 1.5.17 版本

**Comment by magicblack** [comment]
测试的时候F12看看返回内容是什么。

**Comment by aoerboquartz** [comment]
![image](https://user-images.githubusercontent.com/17606183/72029665-9c43fe00-32c1-11ea-8947-2007805b2f5a.png)

**Comment by aoerboquartz** [comment]
不管是进行memcache还是memcached，点击测试按钮，都提示这个。

**Comment by toooooop** [comment]
你没安装memache吧

**Comment by aoerboquartz** [comment]
服务端 安装的 Memcached 1.5.17
php 扩展 安装的 memcached
