### ISSUE TITLE
后台管理-用户  会员组、充值卡、会员订单排序异常

### ISSUE THREAD

**Issue by Jackzyy** [magicblack/maccms10#18]
**问题**：生成项后删除，再重新生成，长度并没有清空，接着上一个长度开始生成，清空缓存无作用。

**预期**：生成项删除后，长度按删除项减少，并从删除后的长度开始递增新项。

**版本**：2019.1000.1008
![image](https://user-images.githubusercontent.com/39424122/63498807-3664fe80-c4f9-11e9-9eb9-77a868620dd2.png)

**复现截图**：

![image](https://user-images.githubusercontent.com/39424122/63498169-e6396c80-c4f7-11e9-9886-632882ff49a8.png)
![image](https://user-images.githubusercontent.com/39424122/63498208-fa7d6980-c4f7-11e9-8f39-8a31e2e7041c.png)
![image](https://user-images.githubusercontent.com/39424122/63498228-08cb8580-c4f8-11e9-923d-30030d9a2bca.png)

**Comment by magicblack** [comment]
后台所有的数据删除之后都会继续按照之前最大值ID+1 ， 自增字段都是这样的。 没有问题。

**Comment by Jackzyy** [comment]
> 后台所有的数据删除之后，新增数据的ID都会继续按照之前最大值ID+1 ， 自增字段都是这样的。 没有问题。

可是前端这样显示总觉得怪怪的，后端逻辑如果是这样的话，也行。前端来显示，还是建议是从 0 开始，一直到到数组的长度。
