### ISSUE TITLE
自定義採集，提示沒有默認值

### ISSUE THREAD

**Issue by natural-ts** [magicblack/maccms10#19]
保存報錯：SQLSTATE[HY000]: General error: 1364 Field 'page_base' doesn't have a default value

**Comment by magicblack** [comment]
可以修改下mysql的配置，来解决这类问题。
MYSQL 安装目录中的my.ini中 搜索sql-mode
sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
把其中的STRICT_TRANS_TABLES,去掉 建议使用该方法
sql-mode=“NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
或者把
sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION” 直接删除
############################################

**Comment by natural-ts** [comment]
> 可以修改下mysql的配置，来解决这类问题。
> MYSQL 安装目录中的my.ini中 搜索sql-mode
> sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
> 把其中的STRICT_TRANS_TABLES,去掉 建议使用该方法
> sql-mode=“NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
> 或者把
> sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION” 直接删除
> ############################################

原來如此，感謝解答
