### ISSUE TITLE
路由伪静态不稳定

### ISSUE THREAD

**Issue by 2389957681** [magicblack/maccms10#190]
开启伪静态后，网站路径url 有时候还是会变成index.php

**Comment by 2389957681** [comment]
导致多次收录重复页面。

**Comment by 2389957681** [comment]
还有一个问题，最近更新的苹果，有些人反映明星翻页没有权限，或者翻页直接跳转到电影筛选页。

**Comment by 2389957681** [comment]
是不是默认规则错了，导致有些模板不适应，不能翻页

**Comment by magicblack** [comment]
原来明星模块灭有分类。现在是有分类的，所以模板里必须从分类进入明星列表。 或者直接进入明星首页 。  没有分类id的会提示权限错误。
