### ISSUE TITLE
后台分类管理报错！！

### ISSUE THREAD

**Issue by songguowei** [magicblack/maccms10#191]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type_id_1' in 'field list'

怎么解决

**Comment by magicblack** [comment]
数据库结构没有正确升级。 可以下载离线升级包覆盖升级，然后后台首页刷新 按提示 进入数据库升级

**Comment by songguowei** [comment]
离线升级包怎么下载呢 我只会在github下载整包
