### ISSUE TITLE
动静分离

### ISSUE THREAD

**Issue by bdsdyj** [magicblack/maccms10#193]
苹果cms10下一步有没有想法 支持一下云存储 | 支持镜像存储加速功能

**Comment by magicblack** [comment]
第三方存储一直都是支持的。后续会增加更多支持库

**Comment by bdsdyj** [comment]
可不可以后续加上动静态分离的功能，如果我们服务器放在美国或者其他线路不好的机房，动静态分离的话可以使静态资源加载的更快

**Comment by magicblack** [comment]
建议使用cdn加速~~页面没必要分离吧， 图片和附件分离就可以里。
