### ISSUE TITLE
能不能添加阿里云图床，免费的那个公共图床

### ISSUE THREAD

**Issue by anglesgirl** [magicblack/maccms10#197]
这是别人的代码
用来上传jpg格式的视频文件
https://blog.kieng.cn/1844.html

用他的代码改造一下，应该就可以
，
这是别人的api，不知道如何利用
http://api.uomg.com/doc-image.ali.html
新浪不能外链后，也就这个还能用了，已经稳定几年了

**Comment by 2445990463** [comment]
自己写一个

**Comment by magicblack** [comment]
1023已经增加
