### ISSUE TITLE
共用redis服务器，缓存标识如何填写

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#198]
我用两台服务器做了upstream，数据库和redis服务器共享。在redis缓存标识那应该写一样的还是不一样？

**Comment by dd0072** [comment]
我在后台开启redis，填入远端IP地址和端口，密码，测试连接不成功。像我这种情况我应该是在后端的两台服务器分别配置redis还是怎么办？

**Comment by magicblack** [comment]
后台可以配置 缓存标识~~~可以修改为不一样的
