### ISSUE TITLE
发现几个问题 !!

### ISSUE THREAD

**Issue by inboxs** [magicblack/maccms10#2]
一. /application/data/  没有 backup文件夹  
    /application/data/   没有 install文件夹  无法创建install.lock文件  导致一直循环安装界面

二.后台验证码 无法加载  不知道是不是个例!

之前版本 会员权限有问题 不知道现在是否存在  还没有测试!!

**Comment by inboxs** [comment]
已解决!!!

**Comment by vimcwal** [comment]
大佬怎么解决直循环安装界面的问题啊
