### ISSUE TITLE
定时任务能不能做成输入某个时间就自动执行，而不是现在的还要监控定时任务链接才执行？

### ISSUE THREAD

**Issue by s7webroot** [magicblack/maccms10#20]
比如说输入1小时的N分钟，就自动执行
例如：2,18,39,59
当然也可以选择周，月，日

这样可以生成网页的时候更灵活

或者弄成现在的不是每个小时，可以输入时间，一旦访问定时任务链接就马上执行。
现在的限制在每小时感觉不够灵活。

仅此建议，谢谢老王不辞劳苦的付出，我几个站用海洋CMS的都转到V10了，谢谢

**Comment by magicblack** [comment]
本身就可以使用第三方的触发器。也可以使用网站本身访客触发。 参考标签文档

**Comment by s7webroot** [comment]
> 本身就可以使用第三方的触发器。也可以使用网站本身访客触发。 参考标签文档

你说的方法我都知道，就算是触发了，也是每小时运行一次的吧？
海洋CMS的定时功能挺灵活的，就是后台设置好一小时内分钟数，月周日可选这样的，比较到位，也不用等到一小时集中执行
