### ISSUE TITLE
上传jpge格式图片

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#203]
我的图片是保存到第三方图床。当图片格式是jpeg格式时提示系统禁止上传。我修改/application/admin/controller/Upload.php $upload_image_ext = 'jpg,png,gif' 后又提示请求上传接口出现异常，请问我应该如何修改呢？

**Comment by anglesgirl** [comment]
你会改php吗，我这里有别人的第三方扩展，你能改一下吗

**Comment by dd0072** [comment]
> 你会改php吗，我这里有别人的第三方扩展，你能改一下吗

我也是小白，简单的还可以，复杂一点就不行。

**Comment by magicblack** [comment]
建议把jpeg改为jpg。。。

**Comment by dd0072** [comment]
> 建议把jpeg改为jpg。。。

当jpeg格式图片太多的时候，一个一个改很麻烦。所以我还是想修改maccms，可以上传jpeg格式。

**Comment by magicblack** [comment]
会添加jpeg支持的，稍后更新。
