### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by anglesgirl** [magicblack/maccms10#204]
在启用缓存的模式下
页面的链接有时候会自动加上index.php 也就是伪静态丢失，清除缓存后恢复。这个希望能解决

并且 批量操作，删除播放组，删除到100-200页以后，出现只跳页面，内容为空，只能关掉批量删除页，重新操作一次，然后到50-60页的时候重复出现问题，操作4-5次后，才能搞完毕

**Comment by lukemin** [comment]
我也一样，我是同步图片的时候，出现这样的情况。

**Comment by songguowei** [comment]
这是个老问题了

**Comment by xqd360** [comment]
不启用缓存的情况发现也会丢失伪静态，我看统计中很多带index.php的链接进入
