### ISSUE TITLE
网址导航模块的来路一直显示0

### ISSUE THREAD

**Issue by dwwl886** [magicblack/maccms10#206]
网址导航模块的来路一直显示0

如何才能启动来路次数显示
{:mac_data_count(0,'all')}  这个标签显示 vod使用的数量正常 

显示website 网址分类的数量就不正常

例如 网址分类ID是100  {:mac_data_count(100,'all')}  前台会显示0

**Comment by magicblack** [comment]
参数缺少造成的。~~默认获取的是 vod模块的数据量。
{:mac_data_count(0,'all','vod')} 获取视频总数量
{:mac_data_count(0,'today','vod')} 获取今日更新视频总数量

{:mac_data_count(0,'all','art')} 获取文章总数量
{:mac_data_count(0,'today','art')} 获取今日更新文章总数量

{:mac_data_count(1,'all')} 获取某个分类下的数据总量，支持视频和文章,传入分类ID
{:mac_data_count(1,'today')} 获取某个分类下的今日更新数据总量，支持视频和文章,传入分类ID

另外还支持topic,website,actor,role模块的获取数据数量
