### ISSUE TITLE
采集以及搜索相关问题

### ISSUE THREAD

**Issue by fqylw** [magicblack/maccms10#207]
采集入库的时候能不能把别名数据也采集进去，很多影片都有别名的，现在很多资源站都有别名数据，没采集到别名的话会导致搜索别名的时候搜索不到相关的影片。
还有就是搜索的话能不能新增个模糊搜索,这样用户体验也会大大增加，减少搜不到影片的记录。

**Comment by magicblack** [comment]
后续会增加此字段
