### ISSUE TITLE
如何直接进入视频界面，而不是功能界面

### ISSUE THREAD

**Issue by qwertyuiop2018** [magicblack/maccms10#209]
如何直接进入视频界面，而不是功能界面

**Comment by magicblack** [comment]
模板里的站内链接也是标签来实现的呢，改一下标签即可啊。
{:mac_url_vod_play($obj,['sid'=>1,'nid'=>1])}   视频播放页链接
{:mac_url_vod_play($obj,'first')}   视频播放页第一条链接
