### ISSUE TITLE
能不能强化和增加移动端api接口

### ISSUE THREAD

**Issue by 748297973** [magicblack/maccms10#21]
像飞飞cms那种用户注册登录,评论收藏,影片信息,积分兑换等弄个api接口

**Comment by magicblack** [comment]
本身支持一些接口就是json交互的，都可以利用。稍后罗列一下api和参数。

**Comment by s7webroot** [comment]
> 本身支持一些接口就是json交互的，都可以利用。稍后罗列一下api和参数。

方便用uni-app等做APP
