### ISSUE TITLE
cms10 更新的集数对不上 如何解决

### ISSUE THREAD

**Issue by qijiannet** [magicblack/maccms10#214]
用的宝塔面板

资源是设置自动采集的

采集什么的都没有问题；

但是前台更新集数始终对不上，内页里面更新到了18集，分类页上面显示更新至2集；

电视剧很多资源都是这样；

按照网上的设置了 二次采集-备注 更新，还是没用；

求大佬指导～ 谢谢～！

**Comment by magicblack** [comment]
修改模板调用备注字段。
