### ISSUE TITLE
优化一下RSS，提高搜索引擎提交和爬取

### ISSUE THREAD

**Issue by akaqing** [magicblack/maccms10#215]
现在的只能生成固定数据量，如果数据很多生成就会耗资源，而且文件体积也大，能不能优化一下：比如百度sitemap 全站生成就是

baidusitemap_index.xml  XML引导页

视频类：baidusitemap_vod_1.xml、baidusitemap_vod_2.xml.......
文章类：baidusitemap_art_1.xml、baidusitemap_art_2.xml......

以此类推！这样单个文件不会很大生成也快可包含全部资源，提高搜索引擎爬取和提交！

**Comment by magicblack** [comment]
后续会优化

**Comment by magicblack** [comment]
sitemap生成完毕后，建议创建自定义页面来生成 sitemap_index文件。
