### ISSUE TITLE
播放器文件加一段什么代码能让它跳转到官方页面播放

### ISSUE THREAD

**Issue by happyagirl** [magicblack/maccms10#216]
我没有填解析接口它也不跳转

**Comment by magicblack** [comment]
可以在内容页面显示集数链接的地方，直接跳转官方地址，
{$obj['vod_play_list'][$param['sid']]['urls'][$param['nid']]['url']} 

也可以在  播放器文件里加控制，弹出 或 跳转到 官方地址， 
比如  top.location.href=MacPlayer.PlayUrl;。

**Comment by happyagirl** [comment]
不跳转直接在播放器的那个播放框内播放官方的呢？应该怎么加代码

**Comment by happyagirl** [comment]
> 可以在内容页面显示集数链接的地方，直接重定向官方地址，
> {$ obj ['vod_play_list'] [$ param ['sid']] ['urls'] [$ param ['nid']] [' url']}
> 
> 也可以在播放器文件里加控制，展开或扩展到官方地址，
> 上方top.location.href = MacPlayer.PlayUrl;。

不跳转直接在播放器的那个播放框内播放官方的呢？应该怎么加代码

**Comment by magicblack** [comment]
参考程序包内的 iframe.js

**Comment by happyagirl** [comment]
> 参考程序包内的iframe.js

MacPlayer.Html = '<iframe width="100%" height="100%" src="'+MacPlayer.PlayUrl+'" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen"></iframe>';
MacPlayer.Show();
这个应该怎么改
