### ISSUE TITLE
反馈问题和需求

### ISSUE THREAD

**Issue by wanmeikk** [magicblack/maccms10#217]
1.想实现一个登录后才能观看的功能，未登录的普通游客在浏览视频详情页时，页面播放信息哪里显示一行文字“请登录后观看”，不知道有没有办法实现，现在是跳转页显示信息；
2.用户注册的时候，前台显示注册成功，后台却无用户数据，不知道是不是我开了数据缓存的原因，还是程序的bug；测试了一天的注册功能，包括短信验证，经常前台显示成功后台无用户数据，短信验证码也发送成功；另外，这个短信发送请不要太频繁的时间怎么改，太短了。总结：用户注册问题很大，无法投入使用。

**Comment by magicblack** [comment]
完全没有问题呢，可以自己在模板里判断  当前登录用户标签数据 来检测是否登录 。
邮件这个应该没问题，请检查配置。

**Comment by wanmeikk** [comment]
现在的问题是 用户前台注册成功，后台实际上没有数据。导致无效注册行为，建议自己测试下。
