### ISSUE TITLE
分类列表设置静态，生成静态的时候只能生成第一页，紧急求更新

### ISSUE THREAD

**Issue by s7webroot** [magicblack/maccms10#22]
分类列表设置静态，生成静态的时候只能生成第一页，紧急求更新

**Comment by magicblack** [comment]
是否测试过默认模板，如果没问题，请检查你的模板。 标签使用是否正确，应检查一下：标签的 分页参数

**Comment by s7webroot** [comment]
> 是否测试过默认模板，如果没问题，请检查你的模板。 标签使用是否正确，应检查一下：标签的 分页参数

好奇怪~默认模板真的是正常的
请教要传那个参数进去？下面是我的分页代码
`{if condition="$__PAGING__.page_total gt 1"}
<ul class="shot-page text-center clearfix">
	<li><a href="{$__PAGING__.page_url|mac_url_page=1}">首页</a></li>
	<li><a href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_prev}">上一页</a></li>							
	{maccms:foreach name="$__PAGING__.page_num" id="num"}
	<li class="hidden-xs {if condition="$__PAGING__['page_current'] eq $num"}active{/if}"><a href="{$__PAGING__.page_url|mac_url_page=$num}">{$num}</a></li>
	{/maccms:foreach}
	<li class="active visible-xs"><span class="num">{$__PAGING__.page_current}/{$__PAGING__.page_total}</span></li>
	<li><a href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_next}">下一页</a></li>
	<li><a href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_total}">尾页</a></li>							
</ul>
{/if}`

**Comment by s7webroot** [comment]
> 是否测试过默认模板，如果没问题，请检查你的模板。 标签使用是否正确，应检查一下：标签的 分页参数

终于找到原因了，模板啥的都没问题，我是把
{maccms:vod num="36" paging="yes" type="current" order="desc" by="sort"}
这个循环和{include file="block/page"}这两个再放到了一个页面文件去，而没有放到type.html这个文件。

所以现在把循环和{include file="block/page"}都放到type.html文件就正常了。。。折腾半天，希望后来的人可以看见省事
