### ISSUE TITLE
本地图片不小心删除了  但采集参数那里点了二次更新图片但不更新

### ISSUE THREAD

**Issue by moyan73807** [magicblack/maccms10#223]
本地图片的 upload\vod   和mac://的不在更新图片了

**Comment by anglesgirl** [comment]
这两个本来就是不更新的，你如果想重新更新，直接去数据那里吧图片地址替换，添加http开头就可以更新图片了

**Comment by magicblack** [comment]
本地图片是不会再次更新的，你可以把所有图片地址设置为空，重新即可
