### ISSUE TITLE
关于宝塔定时百度推送问题

### ISSUE THREAD

**Issue by ymh1147** [magicblack/maccms10#230]
我的站用宝塔对视频进行百度定时推送，日志返回：

> 任务：z1，状态：开启，上次执行时间：2020-03-03 23:01:02---执行<br><style type="text/css">body{font-size:12px;color: #333333;line-height:21px;}span{font-weight:bold;color:#FF0000}</style><br>没有获取到数据<br>数据推送完毕<br><script>setTimeout(function (){location.href="/api.php/urlsend/index.html";},3000);</script><span>暂停3秒后继续  >>>  </span><a href="/api.php/urlsend/index.html" >如果您的浏览器没有自动跳转，请点击这里</a><br>----------------------------------------------------------------------------
★[2020-03-04 23:01:02] Successful

文章推送也是类似，获取不到数据，熊掌推送又都是正常的，手动推送百度也是正常的，请问这是什么原因？

**Comment by magicblack** [comment]
提示这个说明没有待同步的数据呢。。检查一下参数吧。

**Comment by ymh1147** [comment]
我重新增加了两组定时推送，三组不同时段，现在可以正常推送😂
