### ISSUE TITLE
关于开启数据缓存 静态生成的问题

### ISSUE THREAD

**Issue by jiusuiwang** [magicblack/maccms10#235]
现在是这样的一个问题 我后台开启了数据缓存 我每天采集的之后需要生成静态 ，可是静态页面显示的资源并没有更新，每次我都要清除缓存 然后再生成，这样前台的静态页才可以显示到最新更新的资源！这个有些不合理啊！太麻烦了，请问下老大怎么解决啊！

**Comment by magicblack** [comment]
可能是缓存时长引起的，稍后更新试试。
