### ISSUE TITLE
nginx 规则修改

### ISSUE THREAD

**Issue by guoyangd** [magicblack/maccms10#237]
按照目前wiki中nginx规则，会导致页面找不到，建议修改nginx规则；

if (!-e $request_filename) {
rewrite ^/index.php(.*)$ /index.php?s=$1 last;
rewrite ^/修改后的文件名.php(.*)$ /修改后的文件名.php?s=$1 last;
rewrite ^/api.php(.*)$ /api.php?s=$1 last;
rewrite ^(.*)$ /index.php?s=$1 last;
break;
}

**Comment by magicblack** [comment]
不错。。。ikeyi借鉴
