### ISSUE TITLE
大佬，未来会更新把文章内的图片一键同步到本地的功能吗？

### ISSUE THREAD

**Issue by X-Empire** [magicblack/maccms10#239]
之前有人提过建议，把文章内的图片同步到本地，如果能保存到阿里巴巴云存储/优启梦云存储就更好了。要做一个漫画站或资源站，需要大量的存储空间，如果能同步到云存储，利用图床cdn加速图片，这个功能什么时候能实现啊？谢谢

**Comment by hercolor** [comment]
自己其实可以改，难度不是很大，外加个判断文章是否有远程图，下载上传云，删除本地替换图片地址就可以了。

**Comment by linkala** [comment]
@hercolor 大佬，请问怎么实现，付费求指导。

**Comment by hercolor** [comment]
文章里面找出图片地址，老王有阿里巴巴图床的api，把他调用一下，替换返回的阿里巴巴地址就可以了。
