### ISSUE TITLE
寻求大佬解释优启梦云存储

### ISSUE THREAD

**Issue by jiusuiwang** [magicblack/maccms10#240]
优启梦云存储 OPENID和操作员名怎么填写啊！还是从哪里注册的来的呢？求大佬解释

**Comment by hercolor** [comment]
不需要填写的。免费使用

**Comment by jiusuiwang** [comment]
> 不需要填写的。免费使用
不填写的话 图片就是在本地啊！没有上传啊

**Comment by hercolor** [comment]
你的配置发给我看下呢

**Comment by hercolor** [comment]
远程图片他才会上传，如果已经下载到本地是不会上传的。不过有方法可以解决。

**Comment by jiusuiwang** [comment]
我类型选择阿里巴巴和百度识图 新浪微博 搜狗图片京东商城都不行  能用的只有360和掘金可以上传  你的是这样吗

**Comment by jiusuiwang** [comment]
我想用这个百度识图的 阿里巴巴的我看网上说有些会被封！

**Comment by xqd360** [comment]
这些图片以后还拿得出来吗？会不会被封闭了？图片是不是就没了

**Comment by jiusuiwang** [comment]
我也不知道啊！有大佬出来解释一下吗

**Comment by hercolor** [comment]
阿里巴巴不上违规的图都不会封，封了以后肯定图片就无法访问了。解决办法有一个就是在数据库增加一个字段用来放远程图片，前端做个判断有远程显示远程，没有远程显示本地。

**Comment by jiusuiwang** [comment]
请问是什么字段呢 大佬

**Comment by hercolor** [comment]
你自己手动添加一个字段，修改同步图片的代码，同步成功后地址写入新增加的字段，前端做判断就可以
