### ISSUE TITLE
更换服务器后，数据库报错，后台数据无法保存

### ISSUE THREAD

**Issue by 52cn10086** [magicblack/maccms10#242]
'Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
Warning in ./libraries/config/FormDisplay.php#661
 "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

Backtrace

./vendor/composer/ClassLoader.php#444: include()
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/www/server/phpmyadmin/phpmyadmin_44959002d169c3a4/vendor/composer/../..//libraries/config/FormDisplay.php')
Composer\Autoload\ClassLoader->loadClass(string 'PMA\\libraries\\config\\FormDisplay')
./libraries/config/PageSettings.php#76: spl_autoload_call(string 'PMA\\libraries\\config\\FormDisplay')
./libraries/config/PageSettings.php#215: PMA\libraries\config\PageSettings->__construct(string 'DbStructure')
./libraries/controllers/database/DatabaseStructureController.php#163: PMA\libraries\config\PageSettings::showGroup(string 'DbStructure')
./db_structure.php#40: PMA\libraries\controllers\database\DatabaseStructureController->indexAction()
./index.php#80: include(./db_structure.php)

**Comment by magicblack** [comment]
看看是不是这个引起的

PHP 7.3: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? · Issue #4037 · aces/Loris
https://github.com/aces/Loris/issues/4037
这个错误是7.3的bug，新版本的已经修复了
3.38.0 · braintree/braintree_php@0affc87
https://github.com/braintree/braintree_php/commit/0affc87b538b048514901c9865765235e5cdd9b6

PHP For Windows: Binaries and sources Releases
https://windows.php.net/download#php-7.0

下载最新版xammp安装应该可以解决问题，不行就降级到7.2版本了
Download XAMPP
https://www.apachefriends.org/download.html

redis dll 下载

PECL :: Package :: redis 4.2.0 for Windows
https://pecl.php.net/package/redis/4.2.0/windows
