### ISSUE TITLE
明星无法翻页，page的问题还是SHOW的问题？

### ISSUE THREAD

**Issue by akaqing** [magicblack/maccms10#243]
{maccms:actor num="60" paging="yes" pageurl="show" order="desc" by="time"}
.......
{/maccms:actor}

pageurl="show" 这个选择show显示地址为actor/show/area/香港/page/2.html打开是首页，正确的网址是actorshow/area/香港/page/2.html

pageurl="actor/show" 这个选择show显示地址为vod/show/area/香港/page/2.html开始是错误

{if condition="$__PAGING__.page_total gt 1"}
<ul class="myui-page text-center clearfix">
	<li><a class="btn btn-default" href="{$__PAGING__.page_url|mac_url_page=1}">首页</a></li>
	<li><a class="btn btn-default" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_prev}">上一页</a></li>							
	{maccms:foreach name="$__PAGING__.page_num" id="num"}
	<li class="hidden-xs"><a class="btn {if condition="$__PAGING__['page_current'] eq $num"} btn-warm{else} btn-default{/if}" href="{$__PAGING__.page_url|mac_url_page=$num}">{$num}</a></li>
	{/maccms:foreach}
	<li class="visible-xs"><a class="btn btn-warm">{$__PAGING__.page_current}/{$__PAGING__.page_total}</a></li>
	<li><a class="btn btn-default" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_next}">下一页</a></li>
	<li><a class="btn btn-default" href="{$__PAGING__.page_url|mac_url_page=$__PAGING__.page_total}">尾页</a></li>							
</ul>
{/if}

page这里是不是要修改一下？

**Comment by magicblack** [comment]
pageurl=“actor/show” 应该是这样吧。

**Comment by akaqing** [comment]
> pageurl=“actor/show” 应该是这样吧。

pageurl="actor/show" 这个选择show显示地址为vod/show/area/香港/page/2.html开始是错误
