### ISSUE TITLE
能否每次升级后台可以自动升级或者提供下升级包？

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#245]
请问大佬能否每次升级后台可以自动升级或者提供手动下升级包？对于技术能力不强的人来说说还是比较麻烦的，不太清楚更新了什么文件，系统全部得替换，会导致暂时关闭网站

**Comment by magicblack** [comment]
请在  https://github.com/magicblack/maccms_down  下载打包好的文件
