### ISSUE TITLE
数据权限过滤问题,麻烦再看下!

### ISSUE THREAD

**Issue by bbmimi** [magicblack/maccms10#246]
当会员帐号在另一终端登录后,会导致挤掉退出的这个终端页面分类全部隐藏!没设置隐藏的也会隐藏,只剩个首页,而且没有任何内容.
![2020-3-28 15-3-17](https://user-images.githubusercontent.com/47265748/77819872-370de500-7119-11ea-93ae-ab4cb752939b.png)
![2020-3-28 16-42-3](https://user-images.githubusercontent.com/47265748/77819873-3c6b2f80-7119-11ea-8d48-6329950ccf8e.png)

**Comment by magicblack** [comment]
是最新版本上测试的吗

**Comment by bbmimi** [comment]
是的,最新版(1024-C)也是这样!
