### ISSUE TITLE
访问报“页面不存在”

### ISSUE THREAD

**Issue by otary** [magicblack/maccms10#250]
将admin.php修改为admin2.php，然后访问 http://IP:port/admin2.php 跳转到了http://IP:port/admin2.php/admin/index/index.html ，并且报 “页面不存在”，这是怎么回事呢？

**Comment by wenzhifeifeidetutu** [comment]
贴一下包含你改的文件，宝塔后台的文件路径截图

**Comment by toooooop** [comment]
不支持这样子修改



郑州618信息网，老百姓身边的生活信息网站


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chenzw"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 凌晨0:46
收件人:&nbsp;"magicblack/maccms10"<maccms10@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[magicblack/maccms10] 访问报“页面不存在” (#250)





 
将admin.php修改为admin2.php，然后访问 http://IP:port/admin2.php 跳转到了http://IP:port/admin2.php/admin/index/index.html ，并且报 “页面不存在”，这是怎么回事呢？

**Comment by otary** [comment]
server {
    listen 80;
    server_name localhost;
    root   /data/wwwroot;
    index  index.php index.html index.htm;

    location / {
        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.php?s=$1 last;
            break;
        }
    }

   location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
        expires 30d;
        access_log off;
    }

    location ~ .*\.(js|css)?$ {
        expires 7d;
        access_log off;
    }

    location ~ /\.(ht|git|vscode|idea) {
        deny all;
    }
}


使用nginx代理，项目放在 /data/wwwroot目录下，最后经过测试，发现原来访问http://IP:port/index.php/topic/index.html的地址换成http://IP:port/topic/index.html可以访问到，但是后台就不知道怎么访问了，我代码看了下，很可能是controller名错了，又或者是dispatcher数组不对，还没看明白

**Comment by otary** [comment]
解决了，原来是nginx rewrite搞错了
