### ISSUE TITLE
如何将后台的分类,  替换成前台的类型?

### ISSUE THREAD

**Issue by fangjunai** [magicblack/maccms10#251]
如何将后台的分类,   替换成前台的类型? 

比如: 
前台类型:   古装战争青春偶像喜剧家庭犯罪动作奇幻剧情历史经典乡村情景商战网剧其他
而后台:  国产剧,港台剧,日韩剧,欧美剧,其他

这样在前台筛选的时候根本筛选不到数据.

**Comment by magicblack** [comment]
自行对应 后台站点配置里的预留信息，和分类里的扩展配置。  对应模板里的内容。
