### ISSUE TITLE
同步图片问题

### ISSUE THREAD

**Issue by linglongx** [magicblack/maccms10#254]
同步图片已设置阿里云存储，但是会出本地存储，不上传阿里？这是BUG，还是其他的什么原因？

![同步图片反馈](https://user-images.githubusercontent.com/51982959/79052874-ee534180-7c6b-11ea-894a-203298a12e9e.png)

**Comment by xx599** [comment]
没看设置上面的说明吗？
无论本地还是第三方，都会下载图片到服务器

**Comment by magicblack** [comment]
有些可能是请求远程存储出错了，请求过于频繁。
