### ISSUE TITLE
试看功能BUG反馈

### ISSUE THREAD

**Issue by xx599** [magicblack/maccms10#255]
试看功能在实际运行时，比如设置2分钟试看，时间到了，出现提示注册会员，但是，刷新浏览器后又可以重新获取2分钟试看，而且可以拉动视频进度条，这样的BUG导致可以无限试看完这整部影片。
你看能不能写成像优酷腾讯他们那样，试看只能看允许的时间

**Comment by magicblack** [comment]
这个属于播放器内置的功能， dplayer和ck都支持 在内部做判断。 建议你看看相关文档。 cms程序只提供相关字段数据。
