### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by GXSZone** [magicblack/maccms10#256]
从资源库采集图片地址都是完整的网络连接，但是自己上传图片都是绝对路径，能不能直接在上传的时候加入域名或者当前ip形成完整的网络链接存入数据库，返回json也不至于是绝对路径了

**Comment by anglesgirl** [comment]
你是否想过为什么会这样，原始http:// https://开头的地址，表示远程地址，采集二次更新的时候可以更新，相对路径表示本地路径，模板会自动补全地址，也可以在附件设置里修改补全域名，叫远程访问，mac:开头的就是第三方插件，骑牛之类的
模板会自动处理数据，你就不能参考模板？

**Comment by GXSZone** [comment]
@anglesgirl 感谢回答，我知道，解释的多了越描越黑，与我这边业务逻辑冲突，不过我这边app用了两个域名最终多加了个域名解决
