### ISSUE TITLE
QQ一键登录不了

### ISSUE THREAD

**Issue by 1115965515** [magicblack/maccms10#258]
配置好QQ互联后，用QQ登录提示同步信息注册失败

**Comment by elim12joel** [comment]
我也是这个问题，希望尽快修复吧

**Comment by elim12joel** [comment]
@magicblack 老大，bug提交，qq一键登录同步信息失败，升级到1028版也是一样呢，请及时修复一下吧，谢谢！

**Comment by 1115965515** [comment]
我还以为就我一个人这样，百度也搜不到相关的解决办法

**Comment by 1115965515** [comment]
@elim12joel 我还以为就我一个人这样，百度也搜不到相关的解决办法

**Comment by baiyanghk** [comment]
顺便把后台那个新版更新检查去掉吧，没作用不说还误导以为真是最新版 囧
