### ISSUE TITLE
视频详情页使用静态模式时获取不到剧情列表

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#260]
视频详情页在静态模式下获取不到 $obj.vod_plot_list，只能得到一个数字 1
而在动态模式下可以正常获取到

麻烦作者大人处理一下吧，多谢~

**Comment by magicblack** [comment]
这里没有做特殊的判断，应该是没有问题的。

**Comment by magicblack** [comment]
问题已经修复，稍后更新。
