### ISSUE TITLE
文章 上一篇 下一篇 标签没有了吗 ？

### ISSUE THREAD

**Issue by dadage888** [magicblack/maccms10#263]
文章 上一篇 下一篇 标签没有了吗 ？

**Comment by magicblack** [comment]
目前没有内置这个标签，可以使用其他方式实现这个功能。

**Comment by dadage888** [comment]
用  什么方式 实现呢

magicblack <notifications@github.com> 于2020年4月21日周二 下午9:15写道：

**Comment by magicblack** [comment]
详情页面可以使用以下标签实现。

{php}
            $where=[];
            $where['art_status'] = ['eq',1];
            //上一篇数据
            $where['art_id'] = ['lt',$obj['art_id']];
            $pre_info = model('art')->infoData($where,'*',1);
            //下一篇数据
            $where['art_id'] = ['gt',$obj['art_id']];
            $next_info = model('art')->infoData($where,'*',1);
            {/php}

            {if condition="$pre_info['code'] eq 1"}
                <a href="{:mac_url_art_detail($pre_info['info'])}" >上一篇：{$pre_info['info']['art_name']}</a>
            {/if}
            {if condition="$next_info['code'] eq 1"}
            <a href="{:mac_url_art_detail($next_info['info'])}" >下一篇：{$next_info['info']['art_name']}</a>
            {/if}
