### ISSUE TITLE
缓存无法清理，缺少文件 admin/index/clear.html

### ISSUE THREAD

**Issue by leoisummer** [magicblack/maccms10#266]
缓存清理不了，几百万个缓存文件。。。头疼

**Comment by magicblack** [comment]
文件太多建议直接 在宝塔面板里执行定时删除任务。  这个提示是缺少模板文件，下载离线包覆盖一下即可。

**Comment by leoisummer** [comment]
好的，谢谢

magicblack <notifications@github.com> 于2020年4月21日周二 下午2:51写道：

**Comment by leoisummer** [comment]
另外我想问下，新增的板块
【网址】这个分类在哪里添加我没找到。还有关于【来路统计】得自己添加到，自定义菜单里，具体怎么调用也是不明白。请问关于新增的功能有说明文件吗？

magicblack <notifications@github.com> 于2020年4月21日周二 下午2:51写道：
