### ISSUE TITLE
兼容php7.4的方法

### ISSUE THREAD

**Issue by anglesgirl** [magicblack/maccms10#267]
有些同学可能已经想使用php7.4了，但是不知道怎么办
这里我来给大家说一下，只需要修改两个地方
第一个地方就是
thinkphp\library\think\db\Query.php的399行
参考答案在这里 http://www.thinkphp.cn/topic/67036.html
第二地方就是application\common.php的299行 把那个{} 改为[]即可

**Comment by magicblack** [comment]
已经修复。稍后提交。
