### ISSUE TITLE
啥标签弄出名字相似的电影，如霹雳娇娃第二季，调出霹雳娇娃第一季

### ISSUE THREAD

**Issue by s7webroot** [magicblack/maccms10#27]
用rel=$vo.vod_name这样显然是弄不出来的，请教老王大佬

**Comment by magicblack** [comment]
这样的情况【霹雳娇娃第二季，霹雳娇娃第一季】由于整体名字有区别 ， 建议单独使用tag来做关联。
rel是用来调用相关数据的,但是视频的信息关联项目里必须也要填写这些关键字.
  比如 rel="火影忍者,海贼王"
使用名称来匹配传入的参数是wd=“霹雳娇娃”

**Comment by s7webroot** [comment]
> 这样的情况【霹雳娇娃第二季，霹雳娇娃第一季】由于整体名字有区别 ， 建议单独使用tag来做关联。
> rel是用来调用相关数据的,但是视频的信息关联项目里必须也要填写这些关键字.
> 比如 rel="火影忍者,海贼王"
> 使用名称来匹配传入的参数是wd=“霹雳娇娃”

wd=“霹雳娇娃第二季” 这个参数能匹配出霹雳娇娃第四季，霹雳娇娃第一季等视频吗？

**Comment by magicblack** [comment]
回答很明确了，有关联性的数据， 要么都填写关键字到tag里，要么都填写到  关联里。 2个方案。
