### ISSUE TITLE
关于清除缓存导致前台权限异常问题

### ISSUE THREAD

**Issue by anglesgirl** [magicblack/maccms10#270]
启用了redis，在进行清除缓存的时候，有一定概率导致前台所有用户，包括游客出现无法获取任何数据，点击任何影片都是没有权限，让升级或者登录
虽然一般再一次清除缓存就好了，不过系统设置的是一个小时清除一次缓存
这会导致一个小时里出现异常

不知道这是redis的问题还是什么
改用memcached能解决吗？

**Comment by jesusjsc** [comment]
我这为啥开启不了缓存呢？显示“发生错误，请检查是否开启扩展库和配置项”。
但我确实已经开了扩展库呀 

![image](https://user-images.githubusercontent.com/4392829/80269893-4bc4a500-86e6-11ea-873a-fd93b5beb983.png)

**Comment by anglesgirl** [comment]
> 我这为啥开启不了缓存呢？显示“发生错误，请检查是否开启扩展库和配置项”。
> 但我确实已经开了扩展库呀
> 
> ![image](https://user-images.githubusercontent.com/4392829/80269893-4bc4a500-86e6-11ea-873a-fd93b5beb983.png)

你需要安装缓存的软件，并且安装php扩展
