### ISSUE TITLE
地址二更规则：合并

### ISSUE THREAD

**Issue by 52linglong** [magicblack/maccms10#271]
地址二更规则：合并，即整合原有地址和新地址去重。

如下：
第46集$http://www.iqiyi.com/v_19rwg6q0yg.html
46$http://www.iqiyi.com/v_19rwg6q0yg.html

这两个地址是相同的，合并去重不是单纯的地址去重，而是带着$前面的集数去重，这个就造成了有两个46。

建议是纯地址合并去重。

**Comment by linglongx** [comment]
感觉是716行-717行的问题吧？

![Snipaste_2020-04-26_15-36-46](https://user-images.githubusercontent.com/51982959/80301010-d3d4a880-87d3-11ea-806a-3d1cc7009dae.png)

**Comment by magicblack** [comment]
后续会考虑改机这块
