### ISSUE TITLE
伪静态重名数据

### ISSUE THREAD

**Issue by xingyux** [magicblack/maccms10#277]
开启伪静态，在视频ID为拼音的情况下，重名数据只显示小ID的，想要各自显示怎么解决？
![2020-05-03_22-40-24](https://user-images.githubusercontent.com/37532813/80917166-cc8f3b00-8d8f-11ea-9adc-221bd228d75e.png)
如：《神话》，一个是成龙版的电影，一个是胡歌版的电视剧，网址都是 /shenhua.html，这样只能显示一个。

**Comment by magicblack** [comment]
在后台数据中， 自行修改一下 数据的拼音就可以了~

**Comment by xingyux** [comment]
数据量一多，不能全部人工来改吧？
伪静态能否像静态一样，支持自定义？
比如：拼音+ID 或者 分类/拼音

**Comment by Mydong** [comment]
是的  我也发现这个问题了，因为存在这个问题，所以还是用ID来代替了

**Comment by klmahua** [comment]
其实就是一个判断的问题，如果发现拼音名称重复，自动在后面加个1就可以了
