### ISSUE TITLE
火车头分集剧情入库bug

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#278]
火车头入库成功，后台看视频无剧情显示，点击编辑查看入库成功，前台使用了判断标签无显示，
需要后台保存下才会正常

**Comment by aruoop** [comment]
升级26也是一样
![1](https://user-images.githubusercontent.com/42017510/81147974-f32abd00-8fad-11ea-8bb2-1695fefa6a61.png)
后台入库，无剧情显示
![2](https://user-images.githubusercontent.com/42017510/81147993-ffaf1580-8fad-11ea-8cbc-b065212b1ebc.png)
点击编辑后台剧情是存在的

![3](https://user-images.githubusercontent.com/42017510/81148155-54529080-8fae-11ea-8f9b-4bae32620605.png)
前台未加判断的情况下是可以显示，但是这样会导致一个问题是所有的电影，综艺和未有分集剧情的内容都会多一个分集剧情，无法隐藏
![4](https://user-images.githubusercontent.com/42017510/81148282-92e84b00-8fae-11ea-83c0-cfcac85dac3f.png)
这个是加了判断的情况下，前台无分集剧情显示

后台需要单独保存下入库的剧情，前台的判断才会生效

**Comment by magicblack** [comment]
到mysql数据库里，看看字段的内容。 才能分析

**Comment by aruoop** [comment]
不懂看....

**Comment by magicblack** [comment]
修复此问题了，稍后更新。
