### ISSUE TITLE
升级的1026出现错误，网站打不开了。

### ISSUE THREAD

**Issue by lukemin** [magicblack/maccms10#279]
Fatal error: Call to undefined method think\Cache::reset_init()

**Comment by moyan73807** [comment]
我也是。。   我看mac更新git页面  添加了think1026的专版  你试试

**Comment by lukemin** [comment]
我直接下载完整版覆盖了，能打开，都是后台进不去了

**Comment by moyan73807** [comment]
我上传了think1026的专版后就正常了

**Comment by magicblack** [comment]
重新下载升级包覆盖即可。。。
