### ISSUE TITLE
sql替换图片死活不成功！

### ISSUE THREAD

**Issue by songguowei** [magicblack/maccms10#28]
UPDATE {pre}vod SET vod_pic=REPLACE(vod_pic, '/upload/vod/', 'https://www.baidu.com/upload/vod/')
这样的就死活替换不了，我想替换成绝对地址然后同步到云存储！

**Comment by magicblack** [comment]
数据库里默认是 upload/ 开头的，不是 /upload/vod/   你当然替换失败了。。。
