### ISSUE TITLE
1026 mem缓存导致分类权限全丢失

### ISSUE THREAD

**Issue by anglesgirl** [magicblack/maccms10#281]
上次放弃redis改用mem，一直挺正常，更新1026后，所有分类全部没有权限
然后把缓存改为文件，发现权限恢复了，卸载mem，安装redis后，也正常

php为7.4.5

**Comment by magicblack** [comment]
是不是mem连接失败造成的。 后台点击测试 试试。

**Comment by anglesgirl** [comment]
> 是不是mem连接失败造成的。 后台点击测试 试试。

测试过，连接正常，现在已经改redis了
