### ISSUE TITLE
1027缓存设置成redis 不生效

### ISSUE THREAD

**Issue by jiusuiwang** [magicblack/maccms10#283]
1027缓存设置成redis 不生效

**Comment by jiusuiwang** [comment]
只有file可以 其他的都不可以

**Comment by jiusuiwang** [comment]
之前是1024  redis是可以的！然后下载的maccms10_update.zip升级包。 redis就不可以了，cache只有一个4e文件夹819c837d54a6ed09abc77a8560a66f.php文件名称<?php
//000000000000
 exit();?>
a:0:{}文件内容，所有的站都是这样

**Comment by jiusuiwang** [comment]
重新下载最新版的v10也是这样呢！麻烦老王给看看啊！愁

**Comment by magicblack** [comment]
之前的缓存除了file其他都不能正常使用 ， 1027修复了这个问题。  缓存目录下只剩下1个文件很正常。

**Comment by jiusuiwang** [comment]
1024和1027的缓存不一样了吗？我用1024的话cache里面有很多文件，用这1027就一个4e，这不正常吧

**Comment by jiusuiwang** [comment]
> 之前的缓存除了file其他都不能正常使用 ， 1027修复了这个问题。 缓存目录下只剩下1个文件很正常，其他类型的换粗不会生成缓存文件。

**Comment by jiusuiwang** [comment]
> 之前的缓存除了file其他都不能正常使用 ， 1027修复了这个问题。 缓存目录下只剩下1个文件很正常，其他类型的换粗不会生成缓存文件。

1024和1027缓存不一样了吗？我用1024的话cache里面有很多文件的，用1027就一个4e文件！这不正常吧

**Comment by magicblack** [comment]
使用file文件缓存， cache下边会产生文件。你试试

**Comment by jiusuiwang** [comment]
file文件缓存是可以的，其他的都不行

**Comment by jiusuiwang** [comment]
> 在后台切换为使用file文件缓存， cache下边会产生文件。你试试

file文件缓存是可以的，其他的都不行

**Comment by a419377389** [comment]
升级到1027后点采集要等好久好久才可以，而且很慢很卡的
