### ISSUE TITLE
如何调用api接口，传入需要显示的typeid，不止一个typeid，多个行吗

### ISSUE THREAD

**Issue by dary123** [magicblack/maccms10#284]
目前我发现只能传&t=1这样，如果传&t=1,26这样多个就不行，或者能不能过滤某个类型啊，想要动态过滤，并不是后台直接屏蔽掉，而是例如传&t!=1，就是不返回type_id=1的数据

**Comment by dary123** [comment]
我用的ac=videolist这个接口

**Comment by elim12joel** [comment]
建议自定义接口，这样想调什么调什么

**Comment by dary123** [comment]
> 建议自定义接口，这样想调什么调什么

不会啊

**Comment by magicblack** [comment]
建议在前台模板中 自定义页面来实现 数据的交互。
