### ISSUE TITLE
缓存器不生效，出现错误

### ISSUE THREAD

**Issue by cainiao8899** [magicblack/maccms10#285]
缓存器 memcache，memcached，redis  保存的时候整站出现错误，包括前台和后台
都不能用

Fatal error: Call to undefined method think\Cache::reset_init()

**Comment by magicblack** [comment]
重新下载升级包 覆盖即可。 或者下载 专用thinkphp框架覆盖

**Comment by cainiao8899** [comment]
非常感谢，现在可以用了
