### ISSUE TITLE
请问下如何实现角色模块，在有角色的情况下显示！

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#286]
请问下如何实现角色模块，在有角色的情况下显示！？
我用{if$obj.role}判断，有角色无角色的情况下都会隐藏，无法生效！

去掉if判断后，有无角色的情况下都显示一个相关角色出来
![22](https://user-images.githubusercontent.com/42017510/81507214-675abd00-932e-11ea-8854-cdd389e7d639.png)

**Comment by magicblack** [comment]
参考标签文档。。。使用role标签来获取视频数据里的角色。
{maccms:role num="10" paging="no" rid="'.$obj['vod_id'].'" order="asc" by="sort"}
   内部同下方，{$obj.改为{$vo.开头即可
{/maccms:role}

**Comment by aruoop** [comment]
> 参考标签文档。。。使用role标签来获取视频数据里的角色。
> {maccms:role num="10" paging="no" rid="'.$obj['vod_id'].'" order="asc" by="sort"}
> 内部同下方，{$obj.改为{$vo.开头即可
> {/maccms:role}
这个已经写好了，但是出现了不管有没有角色数据
他都会显示一个相关角色出来，
用什么判断可以让他有角色数据显示，没有角色数据就隐藏？
{if$obj.vod_plot}像这个分集剧情现在就可以达到有就显示，无就隐藏效果
![QQ截图20200511142902](https://user-images.githubusercontent.com/42017510/81530885-53e23d00-9394-11ea-94af-93dc0c41f267.png)
![2](https://user-images.githubusercontent.com/42017510/81530894-5775c400-9394-11ea-8d3e-2cf5c19cc38e.png)

**Comment by aruoop** [comment]
三克油！
