### ISSUE TITLE
v10采集v8提示xml错误都是最新版检查过数据库内容 都是一样

### ISSUE THREAD

**Issue by skin007** [magicblack/maccms10#29]
v10采集v8提示xml错误都是最新版检查过数据库内容 都是一样

**Comment by skin007** [comment]
手动修改页参数跳过那页正常采集

**Comment by magicblack** [comment]
可能api那一页数据有特殊字符导致的解析失败，请联系资源站调试解决。

**Comment by skin007** [comment]
据说所有的资料都是通过API去获取的

**Comment by skin007** [comment]
”、“

**Comment by magicblack** [comment]
建议发个 遇到采集空白的api地址出来 包含页码参数的，好查看原因

**Comment by skin007** [comment]
https://www.398zy.com/inc/mac_api.php?ac=videolist&t=&pg=781&h=&ids=&wd=
https://www.398zy.com/inc/mac_api.php?ac=videolist&t=&pg=782&h=&ids=&wd=

**Comment by bwcxy** [comment]
采集明星之只能采集一页，老版本没问题

**Comment by magicblack** [comment]
> 采集明星之只能采集一页，老版本没问题

采集什么明星？接口地址？

**Comment by magicblack** [comment]
测试了350页 - 410页没有出现xml错误 和 空白的现象。整站请求速度较慢，可以使用http请求试试。

**Comment by skin007** [comment]
你得重第一页采集开始 到后面就出现了  还有这个采集明星不跳转也有这个问题
