### ISSUE TITLE
1026版采集资源站偶尔会重复入库

### ISSUE THREAD

**Issue by jackrebel** [magicblack/maccms10#290]
问题：  采集同一个资源站，  偶尔会连续插入两条一模一样的视频数据。 入库时间只相差两秒左右。 
之前的版本没有出现过这个问题， 

后台设置： 入库重复规则已经勾选了：标题、分类；

缓存：开启了Redis、opcache扩展。

**Comment by jackrebel** [comment]
1029版也是一样会重复。

**Comment by leoisummer** [comment]
确实有这个问题，片名一模一样的资源会有N条，不管资源名称长短都一样。每天都要删。。

**Comment by jackrebel** [comment]
> 确实有这个问题，片名一模一样的资源会有N条，不管资源名称长短都一样。每天都要删。。

是不是开了opcache扩展, 我把php这个扩展关了就没问题了。

**Comment by leoisummer** [comment]
没开opcache扩展，仅仅开了redis

**Comment by jackrebel** [comment]
> 没开opcache扩展，仅仅开了redis

我之前opache和redis全开了。 我升到1029后，把opache关了， 现在一天下来， 没有重复的了。

**Comment by SAMSUNGO** [comment]
LZ，1029你那里采集完成还会出现进入断点采集的按钮吗？

**Comment by leoisummer** [comment]
我是火车头入库的。你呢？

**Comment by magicblack** [comment]
opache 可能会引起这个问题，建议关闭。 或者定期删除

**Comment by jackrebel** [comment]
> LZ，1029你那里采集完成还会出现进入断点采集的按钮吗？

会， 会出现断点采集……

**Comment by jackrebel** [comment]
> 我是火车头入库的。你呢？

后台。。。
