### ISSUE TITLE
重名判定问题

### ISSUE THREAD

**Issue by lqhi** [magicblack/maccms10#291]
例如“一人之下第三季”和"一人之下 第三季"，区别只有多了一个空格
但在采集时，系统会当作两部片子，并且视频管理里，重名列表也不会出现这两部片子。

**Comment by lqhi** [comment]
补充，同样的符号，英文输入下和中文输入下，全角半角的分别，系统也会判定成2个片子

**Comment by magicblack** [comment]
是的，建议在采集相关配置中  做一下 名称同义转换。
