### ISSUE TITLE
老王，文章详情关联视频和关联文章，能否改为关联名称，现在标签只有关联ID

### ISSUE THREAD

**Issue by linkala** [magicblack/maccms10#296]
如文章标题为《变形金刚***》,关联视频后台为变形金刚，模版标签不知道怎么调用，现在只有ID的调用标签。谢谢。

**Comment by magicblack** [comment]
文章关联视频、文章 。  或者 视频关联文章、视频 。
只需要把  关联视频 或  关联文章字段填写   ids  或者统一的 字符串 即可。
然后标签使用rel参数来调用关联数据。

**Comment by linkala** [comment]
@magicblack 好的，我自己尝试一下
