### ISSUE TITLE
同一个播放源多次入库会直接替换，这样就无法同一个播放源入库多个地址了，麻烦老王指点

### ISSUE THREAD

**Issue by s7webroot** [magicblack/maccms10#3]
同一播放源应该是要直接覆盖才行，不过如果是磁力链的，同一播放源不断增加磁力链地址的，我就不知道怎样采集更新了。。。
请老王大神指点一下

我猜想，如果能在后台设置每个播放器的更新方法来接收采集数据，那应该就能解决了。
 在播放器里面设置是每次不断递增播放地址，还是每次自己覆盖。

**Comment by magicblack** [comment]
后续会增加配置功能，自由选择  整个替换 还是 取交集。

**Comment by s7webroot** [comment]
取交集就能满足，不然同一个播放源

> 后续会增加配置功能，自由选择 整个替换 还是 取交集。

老王大佬，近期有计划弄吗？卡在这了，每次都自己替换好郁闷呀。上次那个MD5静态的也是我反馈的，喜欢苹果CMS，哈哈
