### ISSUE TITLE
建议增加功能：按照播放器（资源站）设置是否新增视频，一个站一个主播放器就够了

### ISSUE THREAD

**Issue by s7webroot** [magicblack/maccms10#30]
例如全部采集  aaa资源站的视频，也想把bbb资源站的视频地址也作为一条播放线路。但是不想把aaa资源站没有的，而只在bbb资源站有的采集作为新增视频。

**Comment by magicblack** [comment]
会考虑这个功能的~~感谢提议

**Comment by s7webroot** [comment]
> 会考虑这个功能的~~感谢提议

希望老王大神早日添加，现在资源站一大堆，全采集了也不好

**Comment by s7webroot** [comment]
> 会考虑这个功能的~~感谢提议

实现方式应该可以这样：在后台加个配置项，里面让填写新增影片的“播放器代码”，不填写的就不新增，只判断存在的影片并更新播放地址
