### ISSUE TITLE
建议增设后台手动更新会员组状态按钮。

### ISSUE THREAD

**Issue by leoisummer** [magicblack/maccms10#300]
现有情况，根据用户登陆后更新会员状态太被动了。如用户VIP状态已过期，但是过期后他没有登陆，查询的时候，他任然显示在vip用户组。这样管理起来很麻烦，还得挨个区分，建议增设后台手动更新会员组状态按钮。

**Comment by magicblack** [comment]
这块后续会进行优化的感谢提议。
