### ISSUE TITLE
能过滤掉标题中的空格吗？

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#302]
能过滤掉标题中的空格吗？
比如多个资源站资源出现的
xxx第一季
xxx 第一季这种！

**Comment by anglesgirl** [comment]
采集替换功能里，添加 空格第一季 替换第一季
这样来避免出现

**Comment by aruoop** [comment]
> 采集替换功能里，添加 空格第一季 替换第一季
> 这样来避免出现

好的 我试试
可以直接 空格=
去替换掉所有空格吗？

**Comment by linkala** [comment]
@aruoop 。。。

**Comment by magicblack** [comment]
完美的实现
