### ISSUE TITLE
1026版本怎么升级到最新？

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#308]
1026版本怎么升级到最新？看到管理把代码仓库的旧版更新全部都删除了，更新的历史文件都没有了，，，也不知道管理都更新了哪些文件，大佬版本是大的改动啊。。。给个升级的教程吧！

**Comment by lqhi** [comment]
https://github.com/magicblack/maccms_down
另一个项目里有更新到1029改动文件的打包，覆盖下就行

**Comment by magicblack** [comment]
2楼正确解释。
