### ISSUE TITLE
站群配置，模板标签调取站点名称有相关说明吗？

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#311]
站群配置，模板标签调取站点名称有相关说明吗？选择了不同模板。。结果站名和关键词都一样。。。求使用说明

**Comment by klmahua** [comment]
另外，站群模式下，百度xml地图能分站点生成不同的xml吗？

**Comment by magicblack** [comment]
站群后  标签和功能没有任何变化，只需要准备多套不同的模板即可。
