### ISSUE TITLE
更新后火车头发布重名的过滤部分失效

### ISSUE THREAD

**Issue by leoisummer** [magicblack/maccms10#313]
更新版本后，设置都没变现在火车头采集发布重名的影片越来越多。且没找到规律，但确定和片名长短没关系，因为有些片名只有2个字一样重复发布。过滤丢失率差不多7-8%，也就是说90%正常发布没有任何问题且不重复。但是那7-8%找不到原因。

**Comment by magicblack** [comment]
检查是否开启了 opcache等缓存组件。 入库的时候建议关闭试试。

**Comment by leoisummer** [comment]
> 检查是否开启了 opcache等缓存组件。 入库的时候建议关闭试试。
除了redis,其他缓存组件都没启用.
