### ISSUE TITLE
角色api开启无效

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#314]
角色api开启无效，已经在有角色数据的网站开启了角色api，
其他网站通过api采集 提示连接API资源库失败，通常为服务器网络不稳定或禁用了采集
视频，明星正常

**Comment by magicblack** [comment]
测试没有问题啊，什么运行环境

**Comment by aruoop** [comment]
> 测试没有问题啊，什么运行环境
好了，用下面这个地址就无法采集
/api.php/provide/role/?ac=list

用/api.php/provide/role/就正常了....
