### ISSUE TITLE
负载均衡节点服中redis缓存标识问题

### ISSUE THREAD

**Issue by wellos99** [magicblack/maccms10#315]
网站使用了多台负载均衡服务器，均衡服务器访问的内网数据服务器，请问均衡服务器的redis缓存标识是否需要一致？

**Comment by magicblack** [comment]
必须改为不一样的标识才行，否则缓存可能调用错乱。

**Comment by linkala** [comment]
@wellos99 大佬百万IP吗 膜拜一下🌝
