### ISSUE TITLE
如何获取全站播放页播放列表，以便提交到百度？是播放地址不是详情页地址！

### ISSUE THREAD

**Issue by heimi8** [magicblack/maccms10#325]

**Comment by magicblack** [comment]
可以修改sitemap模板，输出播放地址。再把sitemap提交到百度啊。

**Comment by heimi8** [comment]
具体的代码呢？这是详情页的代码{:mac_url_vod_detail($vo)}，那播放页代码呢？

**Comment by aruoop** [comment]
{:mac_url_vod_detail($vo)}

> 具体的代码呢？这是详情页的代码{:mac_url_vod_detail($vo)}，那播放页代码呢？

detail 改为play

**Comment by heimi8** [comment]
@aruoop 
detail 改为play 只会获取视频的第一个播放地址，如：34400-1-1.html。
不能获取此视频的其他地址，比如34400-1-2.html、34400-1-3.html、34400-1-4.html。

**Comment by magicblack** [comment]
参考下标签文档和内容页面显示播放列表的部分 都可以用~~
