### ISSUE TITLE
能修复下由于单引号引起的前台无法显示问题吗？

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#329]
由于部分资源站明星和导演采用‘单引号区分
比如：阿米尔'汉
导致前台无法显示
报错
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' ) LIMIT 0,6' at line 1` 
后台正常，想用数据替换功能，但是后台无法批量替换，只能一个个的去修改，
这个有办法让他在采集的时候就替换掉 或者是不入库吗

**Comment by magicblack** [comment]
前台标签如何写的？ 这是哪个页报错的

**Comment by aruoop** [comment]
视频详情页面！使用的{$obj.vod_actor|mac_substring=30|mac_url_create='actor'}   {$obj.vod_actor|mac_url_create='actor'}  这两种表达方式都会出现上面的报错

**Comment by magicblack** [comment]
使用  aa'bb,cc'dd,ee'ff    作为主演内容测试了，没有报错啊。 具体产生错误的原因有待验证。
