### ISSUE TITLE
视频介绍同义词没法替换空格

### ISSUE THREAD

**Issue by moyan73807** [magicblack/maccms10#33]
视频介绍同义词没法替换空格，详细介绍那里有些采集有空格，我用 视频介绍同义词 把空格替换为无，但真实采集的时候还是有空格在

**Comment by moyan73807** [comment]
http://chuantu.xyz/t6/702/1568026797x992245926.png

**Comment by magicblack** [comment]
经测试没有问题呢，配置里是否开启了  同义词替换。
![image](https://user-images.githubusercontent.com/20452515/64659761-fa75e700-d46f-11e9-902a-8fa4436b9bbf.png)

![image](https://user-images.githubusercontent.com/20452515/64659744-e631ea00-d46f-11e9-8656-605d76da05fa.png)

![image](https://user-images.githubusercontent.com/20452515/64659720-cef2fc80-d46f-11e9-84db-521a5fe46b92.png)

**Comment by moyan73807** [comment]
开启了的，麻烦测试下   我是采集卧龙采集资源网的
