### ISSUE TITLE
1031的url推送直接是这样的 是我更新错了吗？

### ISSUE THREAD

**Issue by lichen780** [magicblack/maccms10#333]
https://ae01.alicdn.com/kf/Hf2a45dd8661746b1992a262b92b434c41.jpg

**Comment by lichen780** [comment]
没有推送token填写位置 推送类型也是没有选项

**Comment by Tao1x** [comment]
应该是有问题，我更新了之后也是这样。

**Comment by baiyanghk** [comment]
是有问题，更新后没有填写保存信息的地方

**Comment by magicblack** [comment]
点击一下选项卡就会出现配置项目了，默认没显示出来，已经修复，稍后更新，
