### ISSUE TITLE
请问下现在怎么更新，更新文件要下载哪个

### ISSUE THREAD

**Issue by k8dmss** [magicblack/maccms10#334]
请问下现在怎么更新，更新文件要下载哪个请问更新包怎么下载，之前的云盘好像不更新文件了

**Comment by amujie** [comment]
https://cdn.jsdelivr.net/gh/magicblack/maccms_down/

**Comment by magicblack** [comment]
可以请 maccms_down这个库里或者 上边cdn下载。
