### ISSUE TITLE
安装完成后，访问前台出现Connection refused！

### ISSUE THREAD

**Issue by linkala** [magicblack/maccms10#339]
老王，简单叙述一下情况，可能是BUG：访问前台connection refused ，同样域名也无法访问后台，直接IP访问后台后发现（但无法访问前台），点击视频数据还有文章数据同样会出现connection refused！但是留言和评论显示数据。请问是怎么回事？用苹果三四年了，第一次出现。😂

**Comment by magicblack** [comment]
重启下web服务器吧，可能是过载了。和程序无关
