### ISSUE TITLE
1031版本 采集无法绑定分类

### ISSUE THREAD

**Issue by haig233** [magicblack/maccms10#340]
1031版本 采集无法绑定分类了
![image](https://user-images.githubusercontent.com/25719719/86504873-6acf6980-bdf0-11ea-9156-6fb2c2bfb791.png)
![image](https://user-images.githubusercontent.com/25719719/86504875-791d8580-bdf0-11ea-8a76-9fe12dda2ca3.png)
![image](https://user-images.githubusercontent.com/25719719/86504885-95212700-bdf0-11ea-86d7-3cba8cdcc1d9.png)

**Comment by lichen780** [comment]
我的就可以  1032的也可以

**Comment by haig233** [comment]
1032版本也是这样

**Comment by haig233** [comment]
似乎找到问题所在了，只要开启memcache缓存器就会出现这种情况

**Comment by lichen780** [comment]
开Redis 缓存啊

**Comment by haig233** [comment]
> 开Redis 缓存啊

开了，主要是memcache有问题

**Comment by magicblack** [comment]
好的，稍后测试下memcache下的
