### ISSUE TITLE
1032版的url推送还是没显示推送类型没选项

### ISSUE THREAD

**Issue by lichen780** [magicblack/maccms10#341]
![1](https://user-images.githubusercontent.com/39560327/86505229-aec46d80-bdf4-11ea-8d51-8ca45181e58a.png)

**Comment by a419377389** [comment]
对的 我也是这样

**Comment by zbh5359115** [comment]
我的也是这个问题

**Comment by zbh5359115** [comment]
![360截图20200705034501545](https://user-images.githubusercontent.com/67840869/86519894-ef160100-be71-11ea-83ad-98674f7dee05.png)

**Comment by magicblack** [comment]
点击一下上边的选项卡就出现配置项目了。1032已经修复

**Comment by a419377389** [comment]
1032B还是无效

**Comment by zbh5359115** [comment]
> 1032B还是无效

再次覆盖升级就好了
