### ISSUE TITLE
1032版电子邮件发送功能怎么设置不好

### ISSUE THREAD

**Issue by zbh5359115** [magicblack/maccms10#342]
版1032电子邮件发送功能怎么设置不好，PHP扩展都开了，还是提示  `发生错误，请检查是否开启相应扩展库`
运行环境 | Linux (Apache)
PHP版本 | 7.1.33
![360截图20200705033238700](https://user-images.githubusercontent.com/67840869/86519920-39977d80-be72-11ea-9b9e-0d7d279b4083.png)
![360截图20200705034829806](https://user-images.githubusercontent.com/67840869/86519965-6a77b280-be72-11ea-8425-a152baabc918.png)

**Comment by magicblack** [comment]
发信模板是否配置正确，发送配置是否正确，经过测试没有问题呢。
测试标题
【{$maccms.site_name}】测试邮件标题
测试正文
【{$maccms.site_name}】当您看到这封邮件说明邮件配置正确了！感谢支持开源程序！

用户注册标题
【{$maccms.site_name}】的会员您好，请认真阅读邮件正文并按要求操作完成注册
用户注册正文
【{$maccms.site_name}】的会员您好，注册验证码为：{$code}，请在{$time}分钟内完成验证。

用户绑定标题
【{$maccms.site_name}】的会员您好，请认真阅读邮件正文并按要求操作完成绑定
用户绑定正文
【{$maccms.site_name}】的会员您好，绑定验证码为：{$code}，请在{time}分钟内完成验证。

用户找回标题
【{$maccms.site_name}】的会员您好，请认真阅读邮件正文并按要求操作完成找回
用户找回正文
【{$maccms.site_name}】的会员您好，找回验证码为：{$code}，请在{$time}分钟内完成验证。

**Comment by wmxsd123456** [comment]
测试失败：发生错误：SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by wmxsd123456** [comment]
配置完成 也能收到验证码，但收到验证码输入后 总提示错误（验证信息错误，请重试）

**Comment by magicblack** [comment]
把失效时间，设置大一些5分钟以上。

**Comment by zbh5359115** [comment]
重新更新了一下，然后重新配置了发信模板解决了
