### ISSUE TITLE
URL推送错误

### ISSUE THREAD

**Issue by lichen780** [magicblack/maccms10#344]
普通推送一直显示第一页的推送内容 
![1](https://user-images.githubusercontent.com/39560327/86524198-21dbeb80-beaa-11ea-89f1-70ee0070bb5a.png)

**Comment by magicblack** [comment]
什么提示信息没看到呢。

**Comment by lichen780** [comment]
没提示  就一直在第一页无限刷新

**Comment by zbh5359115** [comment]
我的也是，在第一页无限循环，就是不接着跳页，没有任何提示

**Comment by a419377389** [comment]
而且快速收录推送无效，百度后台配额还是原先的，等于就是没有推送成功

**Comment by magicblack** [comment]
修复了，更新到1033
