### ISSUE TITLE
Administrator file upload vulnerability

### ISSUE THREAD

**Issue by whiskey-jj** [magicblack/maccms10#347]
**Vulnerability profile**

Maccms allows remote attackers to upload malicious zip files to load PHP code through plug-in installation function. An attacker needs administrator privileges.

**Recurrence** 

1. Click “应用”-- “应用市场”-- “离线安装”
 ![image](https://user-images.githubusercontent.com/40733224/86571985-e114cd00-bfa4-11ea-98ee-72169e595504.png)

2. Construct a zip file with malicious code, which needs to be in their specified format.We can find an example in /addons
![image](https://user-images.githubusercontent.com/40733224/86572309-55e80700-bfa5-11ea-925e-ad3cc86e94ac.png)
 
3. Upload the zip file. If there is no plugins, the zip will be automatically decompressed.Here I name the plugin admi

![image](https://user-images.githubusercontent.com/40733224/86571842-b460b580-bfa4-11ea-9aec-229d6222926e.png)

4. Files are stored in
 /maccms10-master\addons\admi/1.php 
 ![image](https://user-images.githubusercontent.com/40733224/86571878-bfb3e100-bfa4-11ea-8814-3231336fb503.png)

5. http://127.0.0.1/maccms10-master\addons\admi/1.php 
 ![image](https://user-images.githubusercontent.com/40733224/86572503-9f385680-bfa5-11ea-99ec-312c3ceb9b01.png)

**correlation function**
/application/admin/controller/Addon.php
`public function local()`
The security of the uploaded file was not detected.

**Comment by magicblack** [comment]
The local plug-in is uploaded by the webmaster himself, so it is not easy for us to make excessive judgment, because it is open here. All extensions to the online app store are subject to strict scrutiny.
-----------------------------------------------------------------------
本地插件由站长自行上传，所以我们不好做过度判断，因为这里是开放的  。   
在线应用商店的扩展都会经过严格的审查。
