### ISSUE TITLE
TAG自动生成时能否改成第一个关键词自动获取片名

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#348]
TAG自动生成时能否改成第一个关键词自动获取片名，目前基本是随意拆分片名或者简介成TAG，实际使用TAG时，调用的TAG数据根本是没办法做到相关，例如：关于一篇亮剑剧情的文章，然后想在该页面调用亮剑的电视剧出来，TAG把亮剑自动拆分成亮和剑，那么我们就没办法通过TAG调用出来相应的剧名

**Comment by linkala** [comment]
同求，目前随机生成TAG标签太紊乱了。

**Comment by magicblack** [comment]
这块后续会继续优化。
