### ISSUE TITLE
你好~蘋果站長

### ISSUE THREAD

**Issue by ajkick** [magicblack/maccms10#349]
抱歉~想請問您~如何將採集回來的數據在入庫前轉成UTF8繁中呢?~因為我採集的都是簡體中文的資源站~
我使用您的程式很久~但一直沒機會問你~我不會用火車頭~都是使用資源網的API
能否教學?

還有一個問題"二次更新規則"我只勾選播放地址跟備註..常常會因為來源備註的內容不一而產生了2-3個相同數據
到底該如何解決呢....拜託困惱我很久了

**Comment by ajkick** [comment]
抱歉~想請問您~如何將採集回來的數據在入庫前轉成UTF8繁中呢?~因為我採集的都是簡體中文的資源站~
我使用您的程式很久~但一直沒機會問你~我不會用火車頭~都是使用資源網的API
能否教學?

還有一個問題"二次更新規則"我只勾選播放地址跟備註..常常會因為來源備註的內容不一而產生了2-3個相同數據
到底該如何解決呢....拜託困惱我很久了

**Comment by magicblack** [comment]
程序本身，数据库编码都是utf8的不需要转换。
产生重复内容很正常，尽量不要从多个站点获取数据来源，避免重复。
