### ISSUE TITLE
火车头采集剧情会自动过滤HTML标签

### ISSUE THREAD

**Issue by ws4liu** [magicblack/maccms10#35]
剧情采集会自动过滤HTML标签，手动复制过去不会过滤掉标签。已经下载最新更新包更新了。

**Comment by magicblack** [comment]
经测试没有问题~   可以入库html标签。
![image](https://user-images.githubusercontent.com/20452515/64659629-5855ff00-d46f-11e9-9b47-d349fdc91789.png)

请检查你那边的火车头采集里是否过滤了~

**Comment by ws4liu** [comment]
![image](https://user-images.githubusercontent.com/31585100/64663372-26986480-d47e-11e9-9148-060e38ce4075.png)火车头采集里面是有标签的，发布后，mac10系统里面的内容没有标签了，重新下了新版本MAC10本地安装测试也是一样的。模块测试那里发布测试也一样的。

![微信图片_20190911102930](https://user-images.githubusercontent.com/31585100/64663634-11700580-d47f-11e9-81e0-e98df5fc1b1c.png)
![微信截图_20190911103019](https://user-images.githubusercontent.com/31585100/64663688-33698800-d47f-11e9-8d03-22c19312627a.png)

**Comment by magicblack** [comment]
百度编辑器会自动重新整理html标签，实际数据库里入库的时候是没问题的。 你可以切换其他 编辑器试试。

**Comment by ws4liu** [comment]
数据库(vod_plot_detail)里面也没html标签。
