### ISSUE TITLE
请问sql数据库文件过大导致查询缓慢，有办法解决吗？

### ISSUE THREAD

**Issue by X-Empire** [magicblack/maccms10#353]
如题，苹果cmsv10搭建的资讯网站，服务器配置4H8G5M，数据库有15G大小，网页打开速度很慢，伪静态模式使用Redis不太理想。
有什么办法重建表索引、优化sql语句吗？

**Comment by baiyanghk** [comment]
增加配置，其它方法治标不治本

**Comment by magicblack** [comment]
首页静态 + redis缓存 + cdn加速 一般都没问题。
