### ISSUE TITLE
伪静态下百度蜘蛛等显示异常

### ISSUE THREAD

**Issue by zbh5359115** [magicblack/maccms10#355]
正常的应该是这样的
![1](https://user-images.githubusercontent.com/67840869/87125907-d8323d00-c2bd-11ea-9399-f8ae8bdd5327.png)
伪静态后显示成了这样（到RSS订阅了）
![2](https://user-images.githubusercontent.com/67840869/87125975-fa2bbf80-c2bd-11ea-8b40-3b4ebdad2da0.png)

**Comment by xqd360** [comment]
xml在伪静态下全站数据不能分割多个文件显示吗？伪静态下就看到一个xml文件，必须得生成静态才能分页

**Comment by magicblack** [comment]
伪静态路由引起的不对吧。  xml建议自定义一个sitemapindex 索引自定义页中的xml 分页。可使用page分页
