### ISSUE TITLE
cms10版本能不能添加永久会员 的选项

### ISSUE THREAD

**Issue by ofdjonf** [magicblack/maccms10#356]
里面有天，周，月，年，或者能不能设置一个永久的选项啊。求教。

**Comment by magicblack** [comment]
这个用的很少呢，暂时没有。你可以在用户模板中修改下，一次性必须购买 99年 。

**Comment by ofdjonf** [comment]
最新版的cms10有问题，邮箱又用不了了，邮箱发送成功了，注册或者绑定邮箱时明明收到验证码了，填写正确却提示验证信息错误，请重试。

magicblack <notifications@github.com> 于 2020年7月17日周五 20:33写道：
