### ISSUE TITLE
最新更新 右键验证码使用错误

### ISSUE THREAD

**Issue by wmxsd123456** [magicblack/maccms10#358]
最新更新 右键验证码使用错误
收到邮件后（验证码）无法使用

**Comment by magicblack** [comment]
后台用户配置里边 设置一下验证码过期时间。 建议为5分钟

**Comment by wmxsd123456** [comment]
验证信息错误，请重试，邮件那里设置验证码为5分钟 提交时候海视 提示：验证信息错误，请重试
