### ISSUE TITLE
附件参数配置三方访问协议问题

### ISSUE THREAD

**Issue by zbh5359115** [magicblack/maccms10#359]
设为本地保存，为什么出来的页面图片是以MAC开头呢搞不懂
![360截图20200712013531813](https://user-images.githubusercontent.com/67840869/87230159-6c94c080-c3e0-11ea-869c-0eca587e000f.png)
![360截图20200712013548349](https://user-images.githubusercontent.com/67840869/87230160-6c94c080-c3e0-11ea-91d6-ba731552d8fe.png)

**Comment by magicblack** [comment]
正常的，前台使用系统函数处理显示就可以了。
