### ISSUE TITLE
老王，7.8最新的两个BUG，反馈一下。

### ISSUE THREAD

**Issue by linkala** [magicblack/maccms10#362]
1.批量操作视频，其中批量操作版权处理的无法执行
2.采集资源站数据，勾选只更新不新增，同样会新增数据。
麻烦大佬修复一下，谢谢

**Comment by xqd360** [comment]
借楼反馈：批量操作删除视频，一次删除不完，反复操作起码3次以上

**Comment by magicblack** [comment]
1修复了。
2测试没问题呢额，具体描述附加截图。
2楼这个 暂时增加一个选项 可以自己设置每页处理条数  ，还不能完全避免反复操作
