### ISSUE TITLE
请帮忙看看我需要怎么做才能安装

### ISSUE THREAD

**Issue by jieshao098** [magicblack/maccms10#369]
![捕获](https://user-images.githubusercontent.com/29919886/87854503-c7fc0c80-c912-11ea-9d11-6df3dd9f1455.PNG)
![捕获](https://user-images.githubusercontent.com/29919886/87854518-dea26380-c912-11ea-8a61-6793592c498a.PNG)

**Comment by magicblack** [comment]
就开启php zip支持库就可以里呢。
