### ISSUE TITLE
王总,分集剧情链接第一集和第二集的URL是一样的,请修复下啊,谢谢!

### ISSUE THREAD

**Issue by xixihaha806** [magicblack/maccms10#370]
RT,请看下面截图
![捕获](https://user-images.githubusercontent.com/68390320/87856653-fe597c00-c952-11ea-9a04-464ddc90d7c7.JPG)

**Comment by magicblack** [comment]
参考默认模板vod/plot.html ，是模板标签 写法有问题， 最近一次更新  已经修复了呢。
