### ISSUE TITLE
请求帮忙，本地测试时，在后台使用“”分类管理”，更改顶部分类+修改数据时，分类ID20消失。

### ISSUE THREAD

**Issue by Mydong** [magicblack/maccms10#371]
请求帮忙，昨天本地测试，后台使用“”分类管理”，更改顶部分类+修改数据保存时，原添加分类ID20消失，不见。
分类管理中的分类直接从18变成了21，找不到修改的名字和ID，早上发现绑定20分类的资源，依然在采集，但是没有访问权限。

备注：只有这一个id消失，后面在做同样的操作，均正常。

![image](https://user-images.githubusercontent.com/14023137/87866134-72763d00-c9b0-11ea-8bf5-4db9c31a6f90.png)

**Comment by magicblack** [comment]
自行到phpmyadmin里修改一下  20的  type_pid为0   ,type_status为1 。 
可能你误操作 导致这个id数据无法显示了。

**Comment by Mydong** [comment]
> 自行到phpmyadmin里到 mac_type表中 找到数据，修改一下 20的 type_pid为0 ,type_status为1 。
> 可能你误操作 导致这个id数据无法显示了。

好，我试试。谢谢哈
