### ISSUE TITLE
最新版苹果，火车头入库，无法越过系统后台二次更新设置规则发布入库

### ISSUE THREAD

**Issue by linkala** [magicblack/maccms10#372]
如影片战狼剧情介绍是“小明是个好学生”演员是”1,2,3,4”
火车头采集到的信息为“小明胡大大大”演员是“8,9,7”
后台设置二次勾选没有选中 剧情介绍 还有 演员时 无法进行成功入库 提示信息

`源代码:{"code":1001,"msg":"无需更新。"}`

不知道算不算BUG。麻烦大佬看一下，谢谢~

**Comment by magicblack** [comment]
测试没问题呢，  采集配置  二次更新规则选中    【详情】  可以正常更新呢。

**Comment by linkala** [comment]
额，我的意思是火车头采集入库，能否不受采集配置的二次更新规则限制，即采集到的信息都可以成功发布更新。

**Comment by magicblack** [comment]
目前不可以。统一配置的。
