### ISSUE TITLE
cms10最新版邮箱功能用不了了

### ISSUE THREAD

**Issue by ofdjonf** [magicblack/maccms10#373]
发送成功，但是注册或者绑定邮箱时填写验证码提示验证信息错误，请重试。验证码收到了，也填写正确的。

**Comment by zbh5359115** [comment]
我试了下，我的也是

**Comment by magicblack** [comment]
后台邮件配置， 输入一下  有效时长 建议5分钟以上。

**Comment by zbh5359115** [comment]
我设置都是10分钟啊，为什么不行呢

**Comment by ofdjonf** [comment]
> 后台邮件配置，输入一下有效时长建议5分钟以上。

试了，没用的。而且注册时发送的邮箱验证发件人昵称也有问题，不是系统设置的

**Comment by ofdjonf** [comment]
试了，没用的。而且注册时发送的邮箱验证发件人昵称也有问题，不是系统设置的

**Comment by magicblack** [comment]
更新到1034b 试试看
