### ISSUE TITLE
百度主动推送API格式变更，请及时升级

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#377]
普通收录API提交接口调整通知 2020-07-20
尊敬的搜索合作伙伴：

为了保证普通收录工具的稳定性与处理效率，即日起API提交接口调用地址统一为http://data.zz.baidu.com/urls?site=xxx&token=xxx ，可在“资源提交-普通收录-API提交”界面查看；http://data.zz.baidu.com/urls?appid=xxx&token=xxx&type=batch 将不再支持提交数据。给您造成的不便敬请谅解，感谢您的关注与支持

**Comment by magicblack** [comment]
应该没问题，只有上面这个http://data.zz.baidu.com/urls?site=xxx&token=xxx ，不用升级。
