### ISSUE TITLE
SMTPSecure的问题

### ISSUE THREAD

**Issue by amujie** [magicblack/maccms10#379]
建议将邮件发送的SMTPSecure设置添加到系统设置作为可选项
maccms10\application\common\extend\email\Phpmailer.php
$mail->SMTPSecure = 'ssl';

**Comment by magicblack** [comment]
大部分邮件服务都要求ssl ~ 这个有需要自行改一下吧。

**Comment by amujie** [comment]
那把默认值改成ssl把 现在默认是tls

**Comment by magicblack** [comment]
配置加上了，稍后更新。
