### ISSUE TITLE
老王，视频模块剧情介绍BUG

### ISSUE THREAD

**Issue by linkala** [magicblack/maccms10#381]
经过测试了多次，发现视频内剧情介绍和分集剧情介绍无法通过采集软件采集到“图文”，如采集内容`<p><img src=“http://***.jpg></p>’到剧情介绍，发布成功后，该处为空白，即无图片无内容。但通过手动在后台输入上述代码，再点击编辑器html代码，图片却能显示出来。

**Comment by magicblack** [comment]
详情介绍目前支持富媒体。  
 分集剧情理论上也支持富媒体，可以直接入库，前台展示没问题， 但是目前后台编辑的时候不支持后续会支持。

**Comment by linkala** [comment]
好的，感谢大佬的答复，我再测试一下吧。
