### ISSUE TITLE
后台，执行sql语句，是否有某一播放组的语句，某些资源站倒闭了。。。

### ISSUE THREAD

**Issue by sd231902** [magicblack/maccms10#386]
某些资源站倒闭了。。。比如wlm3u8
目前删除了他的播放器，前台不显示了，但是数据库里其实还是有这个播放组的
后台，执行sql语句，是否有某一播放组的语句，有的话，方便告知一下么

**Comment by magicblack** [comment]
执行sql无法完成删除组的操作，建议使用 后台的批量操作。
