### ISSUE TITLE
要做投屏，请问获取播放地址引用的标签是什么

### ISSUE THREAD

**Issue by wmxsd123456** [magicblack/maccms10#388]
要做投屏，请问获取播放地址引用的标签是什么

**Comment by wmxsd123456** [comment]
<li><a class="btns-info" href="#" onclick="BSL.OpenProjection('获取动态播放地址">开启投屏</a></li>

**Comment by wmxsd123456** [comment]
`<li><a class="btns-info" href="#" onclick="BSL.OpenProjection('{$obj.vod_play_url}">开启投屏</a></li>`

**Comment by magicblack** [comment]
查看标签文档。

**Comment by magicblack** [comment]
查看标签文档。
