### ISSUE TITLE
【已确定为BUG】您没有权限访问此页面，请升级会员组

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#391]
我都已经去把游客会员组，全部选上保存了，为什么还是提示这个问题？不知道怎么回事

**Comment by ycgz2008** [comment]
我去后台把会员模块关闭，然后正常可以浏览了，这我就有点不明白了

**Comment by ycgz2008** [comment]
好像找到点问题，就是我全新安装，然后恢复数据库，然后打开栏目，是不存在问题的。
然后我修改网站参数点击保存后，然后再打开栏目出现“您没有权限访问此页面，请升级会员组”
去查看游客权限，全部都选上了，没有问题啊，郁闷了我

**Comment by ycgz2008** [comment]
找到问题所在了，原来是一个BUG，我晕了，重装了不下10遍啊
这个BUG就是：

伪静态分类ID设置为“”数字ID“ 这个是没有问题的
伪静态分类ID设置为“拼音” 那么就会提示“您没有权限访问此页面，请升级会员组”

请大佬修复一下这个BUG

**Comment by magicblack** [comment]
php5.x -7.x + nginx 伪静态下测试没有发现此情况，默认会员分类不要动，否则会出现问题。
1 | 游客
2 | 默认会员
3 | VIP会员

**Comment by ycgz2008** [comment]
我的是飞飞CMS升级过来的，显示普通会员，我修改成默认会员重新选上权限，还是存在问题
自己本地全新安装测试，也正常，看来不是程序问题
但我全新安装操作后台恢复数据后，就出现这个BUG，登录PHPMYADMIN对照，全部正确没有问题啊，程序也是下载的最新啊，郁闷了
伪静态分类我设置为拼音后，打开所有分类都是使用的同一个文件分类模板
但使用 数字ID 就没有问题
升级后其他问题倒是没有碰到
这是真找不到原因了，不过还好数字ID能正常使用，没有问题，还能接受吧
分类权限问题，我可以直接关闭会员注册，也正常了，也还能接受吧
