### ISSUE TITLE
搜索联想伪静态bug

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#393]
举例说明bug：
比如打开网站 http://www.giys.cn/ 我们搜索“”寄生虫“
显示网址：http://www.giys.cn/vodsearch/-------------.html?wd=%E5%AF%84%E7%94%9F%E8%99%AB&submit=
寄生虫内容网址显示：http://www.giys.cn/voddetail/137916.html
一切正常，没有问题。

我们重新回到http://www.giys.cn 我们搜索输入”寄生虫“ 然后打开搜索联想的“寄生虫”链接进入
显示网址：http://www.giys.cn/index.php/vodsearch/%E5%AF%84%E7%94%9F%E8%99%AB-------------.html
寄生虫内容网址显示：http://www.giys.cn/index.php/voddetail/137916.html

上面网站不是我的，因为我是通过转换程序转换过来的，所以不确定是不是我的问题，在百度找的其他苹果CMS网站，我看是存在和我一样的问题的

其实我的还存在有时候不使用搜索联想搜索影片，网址显示http://www.giys.cn/index.php/vodsearch/%E5%AF%84%E7%94%9F%E8%99%AB-------------.html的，但我不确定这是不是我一个人的问题

另外搜索联想怎么关闭呢？如果这个bug暂时无法解决，我想着搜索联想关闭也是一个临时办法

另外一个问题：12，nginx下除了首页其他都是404怎么办？修改一下伪静态规则，一般都可以解决了。 如果修改了后台文件入口admin.php，则改为对应的文件名。
 if (!-e $request_filename) {
        rewrite ^/index.php(.*)$ /index.php?s=$1 last;
        rewrite ^/admin.php(.*)$ /admin.php?s=$1 last;
        rewrite ^/api.php(.*)$ /api.php?s=$1 last;
        rewrite ^(.*)$ /index.php?s=$1 last;
        break;
        }

我的后台文件修改为admin123.php，修改为下面的，这样对吗？因为官方说的不是很明确，不确定是不是二个admin都修改

 if (!-e $request_filename) {
        rewrite ^/index.php(.*)$ /index.php?s=$1 last;
        rewrite ^/admin123.php(.*)$ /admin123.php?s=$1 last;
        rewrite ^/api.php(.*)$ /api.php?s=$1 last;
        rewrite ^(.*)$ /index.php?s=$1 last;
        break;
        }

**Comment by magicblack** [comment]
以上2种地址都没问题~ 伪静态开启后  
http://xxx/index.php/vodsearch/aaa-------------.html 或 http://xxx/vodsearch/aaa-------------.html
或 http://xxx/index.php/vodsearch/-------------.html?wd=aaa
至于为什么要出现index.php，是因为担心静态首页。
为什么会出现 ?wd= 因为表单提交，可自行修改模板中的搜索处理方式改为拼接url

**Comment by ycgz2008** [comment]
搜索会收录搜索结果，如果收录带/index.php的地址，那不是数据重复了？搜索结果出来的视频内容页也是带/index.php，搜索同样会收录，是不是不利于收录优化？

**Comment by magicblack** [comment]
已经做了一些优化调整。稍后更新
