### ISSUE TITLE
站群模式，页面缓存时间设置无效！

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#394]
站群模式，页面缓存时间设置无效！页面缓存数据占用空间也太大了(只有两个站点)。。两天时间不到，就占用了服务器硬盘100多G，服务器直接卡死了，，，有办法优化吗？

**Comment by magicblack** [comment]
升级到最新版本使用 redis 或者 memcache缓存

**Comment by klmahua** [comment]
用redis和memcache，服务器内存会不会爆满，，不够用

**Comment by magicblack** [comment]
一般情况下不会的，redis比较省的
