### ISSUE TITLE
升级系统有对数据库变动吗

### ISSUE THREAD

**Issue by baiyanghk** [magicblack/maccms10#395]
现在没有在线升级了，自己手动升级都是直接看github的更新文件去修改对应内容，不知道有没有对数据库进行升级，如果有升级会在更新说明里介绍吗，像我这样光看升级文件去更新的，不下载更新包的会有影响吗

**Comment by baiyanghk** [comment]
另外后台的数据库管理里，冗余这类全部显示 83968 kb，是显示错误吗，查看数据库里没这些多余内容

**Comment by magicblack** [comment]
离线升级包覆盖即可， https://github.com/magicblack/maccms_down
