### ISSUE TITLE
苹果cms v10最新版怎么配置邮件发送？

### ISSUE THREAD

**Issue by X-Empire** [magicblack/maccms10#397]
使用2020.1000.1034之前的版本设置简单可以发送邮件。
宝塔默认开启sockets ,openssl扩展库，2020.1000.1035版本PhpMailer配置失败，无法发送。
有详细的教程吗？

**Comment by X-Empire** [comment]
提示信息：
发送邮件请开启sockets ,openssl扩展库，否则可能发送失败
服务器：smtp.exmail.qq.com
端口：465
传输协议：SSL

**Comment by magicblack** [comment]
邮件配置 传输协议设置为 tsl  试试看。

**Comment by X-Empire** [comment]
新建一个测试环境之后，重新配置找到原因了，现在已经可以发送邮件了

**Comment by X-Empire** [comment]
阿里巴巴云存储失效了？
