### ISSUE TITLE
阿里图床挂了还是限制上传呢？

### ISSUE THREAD

**Issue by X-Empire** [magicblack/maccms10#399]
昨天下午16点发现新采集的内容图片会自动保存到本地服务器/upload/，有办法解决吗？谢谢

**Comment by akaqing** [comment]
建议出一个检测功能，删除没有关联的图片

**Comment by magicblack** [comment]
手工上传下看看提示什么

**Comment by X-Empire** [comment]
没有任何提示，直接上传到本地服务器/upload/，阿里巴巴云存储（阿里图床api）和优启梦云存储（所有图床api）已经无效了。
新建测试环境也是无效

**Comment by magicblack** [comment]
图床官网提示已经关闭，建议更换其他图床。
