### ISSUE TITLE
显示安装成功，跳不到首页

### ISSUE THREAD

**Issue by 2009wyld** [magicblack/maccms10#4]
![image](https://user-images.githubusercontent.com/32028978/62201867-cad8b700-b3ba-11e9-9056-fdaa00860e4a.png)
![image](https://user-images.githubusercontent.com/32028978/62201885-d3c98880-b3ba-11e9-8106-ac0952451aa4.png)

**Comment by andyhuai** [comment]
我也是这个问题，怎么解决的

**Comment by vimcwal** [comment]
同是这个问题，怎么解决？

**Comment by andyhuai** [comment]
@vimcwal 目录权限不够，无法创建install目录

**Comment by vimcwal** [comment]
application/data/backup 缺少这个文件手动创建一个吗？

**Comment by vimcwal** [comment]
> @vimcwal 目录权限不够，无法创建install目录

application/data/backup 缺少这个文件手动创建一个吗？目录读写执行都给了

**Comment by vimcwal** [comment]
@andyhuai application/data/backup 缺少这个文件手动创建一个吗？目录读写执行都给了

**Comment by andyhuai** [comment]
@vimcwal 可以
