### ISSUE TITLE
为什么定时采集点击保存，提示数据提交中？一直这样

### ISSUE THREAD

**Issue by 583455189** [magicblack/maccms10#40]
为什么定时采集点击保存了， 提示数据提交中？一直这样
![QQ图片20190915125848](https://user-images.githubusercontent.com/20038296/64916823-a7c26500-d7b8-11e9-9c45-25f38a172712.png)

**Comment by magicblack** [comment]
F12看下提交返回信息，是不是因为 没有写入权限
