### ISSUE TITLE
管理能整合个Github+jsDelivr+PicGo图床模块吗？

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#401]
管理能整合个Github+jsDelivr+PicGo图床模块吗？图片放到本地感觉附近太多，速度也慢，提到的这些空间和cdn都是免费的

**Comment by songguowei** [comment]
Github+jsDelivr   最高50M

**Comment by klmahua** [comment]
看到这个教程上面（https://blog.retao5.com/jianzhan/1410.html）没有说到空间限制，，github空间没限制的吧

**Comment by songguowei** [comment]
> 看到这个教程上面（[https://blog.retao5.com/jianzhan/1410.html）没有说到空间限制，，github空间没限制的吧](https://blog.retao5.com/jianzhan/1410.html%EF%BC%89%E6%B2%A1%E6%9C%89%E8%AF%B4%E5%88%B0%E7%A9%BA%E9%97%B4%E9%99%90%E5%88%B6%EF%BC%8C%EF%BC%8Cgithub%E7%A9%BA%E9%97%B4%E6%B2%A1%E9%99%90%E5%88%B6%E7%9A%84%E5%90%A7)

你可以试一下  50M以后的文件 用jsDelivr就访问不了了

**Comment by klmahua** [comment]
哦。。。看到很多人都在用gihub做图床。。不知道他们发现限制了没有。。。给管理推荐个别人做好的源码
https://github.com/yumusb/autoPicCdn

**Comment by magicblack** [comment]
可以结合图床自动回源的方式来加速~
