### ISSUE TITLE
PHP7.4不再支持使用大括号访问数组以及字符串的偏移

### ISSUE THREAD

**Issue by dzhuqi** [magicblack/maccms10#402]
大神能不能修复下common.php 299行的代码。。。PHP7.4不再支持使用大括号访问数组以及字符串的偏移

**Comment by magicblack** [comment]
是mac_get_rndstr这个函数吗，早就修改了啊。更新到最新版本试试。

**Comment by dzhuqi** [comment]
嗯 ，我升级更新一下，首页的电视剧和动漫这些 的集数显示  连载
0集/共0集   获取不到正常集数

**Comment by magicblack** [comment]
那些事模板调用字段的事情和程序无关。
