### ISSUE TITLE
可以集成下头条的图床吗？

### ISSUE THREAD

**Issue by songguowei** [magicblack/maccms10#403]
阿里的最近狂删图片！！！

**Comment by magicblack** [comment]
看看第三方达人有咩有搞的

**Comment by X-Empire** [comment]
图片外链（图床）可以用于论坛、网站、评论、聊天等；免费稳定好用的永久图片外链图床https://hao.su/pic.html

**Comment by X-Empire** [comment]
https://blog.hidove.cn/post/594
https://wangdalao.com/3337.html
感觉都没有阿里图床快

**Comment by linkala** [comment]
@songguowei 这东西还需要老王开发的么？那估计他要忙成狗了。
