### ISSUE TITLE
伪静态规则突然失效，自动变成的伪静态路径

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#404]
伪静态规则突然失效，自动变成的伪静态路径，伪静态规则数据也都还在，在后台重新保存了下伪静态规则后恢复正常，目前已有两个站点出现这样的问题，目前使用程序版本号：2020.1000.1035 ，请及时修复，太伤排名了

**Comment by xqd360** [comment]
伪静态失效后：
a.com/voddetail/41329.html  自动变成了默认的伪静态路径
a.com/index.php/xplay/3140-1-1.html   播放页面也收录了很多这种动态路径

**Comment by xqd360** [comment]
表述有漏字，以下更正
修改过的伪静态规则突然失效，自动变成默认的伪静态路径，伪静态规则数据也都还在，在后台重新保存了下伪静态规则，就恢复正常，目前已有多个站点出现这样的问题，目前使用程序版本号：2020.1000.1035 ，请及时修复，太伤排名了，突然站点的路径就发生了变化

**Comment by magicblack** [comment]
1035 之前的版本可能进入 http://aaa.cn/index.php   首页或其他内页带了 index.php , 这样的情况下可能会出现 页面上其他链接也带idnex.php 。 
目前还没有发现其他引起的原因。

**Comment by xqd360** [comment]
错误类型 | 网址 | 响应代码 | 错误时间 |  
-- | -- | -- | -- | --
找不到页面 | www.abc.com/voddetail/47340.html | 404 | 2020-08-14 23:57:10 |  
找不到页面 | www.abc.com/vodtype/kehuanpian.html | 404 | 2020-08-14 23:18:57 |  
找不到页面 | www.abc.com/voddetail/48177.html | 404 | 2020-08-14 21:30:00 |  
找不到页面 | www.abc.com/voddetail/45502.html | 404 | 2020-08-14 20:41:20 |  
找不到页面 | www.abc.com/voddetail/47840.html | 404 | 2020-08-14 20:03:58 |  
找不到页面 | www.abc.com/voddetail/46575.html | 404 | 2020-08-14 14:28:03 |  
找不到页面 | www.abc.com/voddetail/46109.html | 404 | 2020-08-13 22:24:34 |  
找不到页面 | www.abc.com/voddetail/48165.html | 404 | 2020-08-13 22:12:34 |  
找不到页面 | www.abc.com/voddetail/47342.html | 404 | 2020-08-13 17:31:14 |  
找不到页面 | www.abc.com/vodplay/47834-1-1.html | 404 | 2020-08-13 13:54:20 |  
找不到页面 | www.abc.com/vodtype/aiqingpian.html | 404 | 2020-08-13 13:13:29 |  
找不到页面 | www.abc.com/vodtype/rihanju.html | 404 | 2020-08-13 13:13:17 |  
找不到页面 | www.abc.com/vodtype/xijupian.html | 404 | 2020-08-13 13:13:05 |  
找不到页面 | www.abc.com/voddetail/46873.html | 404 | 2020-08-13 13:12:29 |  
找不到页面 | www.abc.com/voddetail/41761.html | 404 | 2020-08-13 13:10:55 |  
找不到页面 | www.abc.com/voddetail/39648.html | 404 | 2020-08-13 05:12:02 |  
-----------------------分割线---------------------------------------------------
找不到页面 | www.abc.com/xdetail/46109.html | 404 | 2020-08-12 13:49:03 |  
找不到页面 | www.abc.com/xdetail/47849.html | 404 | 2020-08-12 13:48:54 |  
找不到页面 | www.abc.com/xdetail/47001.html | 404 | 2020-08-12 13:48:48 |  
找不到页面 | www.abc.com/xdetail/46570.html | 404 | 2020-08-12 13:48:34 |  
找不到页面 | www.abc.com/index.php/xplay/47340-1-41.html | 404 | 2020-08-12 13:48:26 |  
找不到页面 | www.abc.com/index.php/xplay/45797-1-3.html | 404 | 2020-08-12 13:48:12 |  
找不到页面 | www.abc.com/xdetail/45459.html | 404 | 2020-08-12 13:47:58 |  

以上数据为百度站长平台导出404数据，分割线下是我需改过的伪静态规则路径，分割线以上是由于伪静态失效，导致自动变成了系统默认的伪静态规则，被百度收录了默认的链接，当发现异常后重新保存了伪静态规则，结果和一来二去都被百度抓取到了404错误，伪静态失效却属事实，出现此问题前有搬家的操作，搬家后没有去保存过后台伪静态设置，不知是否是因为搬家导致的伪静态规则失效，但是后面又有反复出现伪静态丢失的问题，问过其他朋友也有出现伪静态丢失的经历，情况一模一样，都是失效后变成默认的伪静态路径

**Comment by magicblack** [comment]
建议你修改配置完伪静态规则后，把application/route.php 改成只读的 试试先

**Comment by klmahua** [comment]
我的前几天伪静态也突然失效了。。。不知道是不是被后面攻击了！！

**Comment by xqd360** [comment]
被攻击，站点会崩溃，但是不可能说就失效吧，如果会那就是系统的BUG




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "magicblack/maccms10"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月18日(星期二) 下午4:57
收件人:&nbsp;"magicblack/maccms10"<maccms10@noreply.github.com&gt;;
抄送:&nbsp;"xqd360"<xqd360@gmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms10] 伪静态规则突然失效，自动变成的伪静态路径 (#404)





 
我的前几天伪静态也突然失效了。。。不知道是不是被后面攻击了！！

**Comment by magicblack** [comment]
找到原因了，之前提供的升级包内有路由文件。已经删除了。
