### ISSUE TITLE
为什么后台会自动更新啊！,之前一直用的1030版本。

### ISSUE THREAD

**Issue by laji888999** [magicblack/maccms10#407]
为什么后台会自动更新啊！,之前一直用的1030版本。
自己加了点小功能,突然发现什么都变了,后台一看更新到1035了。
那里可以关闭自动更新

**Comment by magicblack** [comment]
不建议修改系统自带的文件，以免升级遇到问题。  如需整合定制功能建议 采用 开发应用扩展来实现。
