### ISSUE TITLE
修复图片为空页面加载两次的问题

### ISSUE THREAD

**Issue by kv163** [magicblack/maccms10#409]
模板使用lazyload后，如果一张图片地址为空，页面会重新加载一次首页。使得页面打开时间变长
修复方案
function mac_url_img($url)
{
	 if(empty($url)){ //图片地址为空就使用默认图片
	 	 $url = '/template/21/statics/image/loading.gif';
	 }else{
        if(substr($url,0,4) == 'mac:'){
            $protocol = $GLOBALS['config']['upload']['protocol'];
            if(empty($protocol)){
                $protocol = 'http';
            }
            $url = str_replace('mac:', $protocol.':',$url);
        }
        elseif(substr($url,0,4) != 'http' && substr($url,0,2) != '//' && substr($url,0,1) != '/'){
            if($GLOBALS['config']['upload']['mode']=='remote'){
                $url = $GLOBALS['config']['upload']['remoteurl'] . $url;
            }
            else{
                $url = MAC_PATH . $url;
            }
        }
	}
    return $url;
}

**Comment by magicblack** [comment]
不建议这么搞啊。完全可以在模板显示默认图片然后lazyload加载。
