### ISSUE TITLE
苹果CMS10--2020.1000.1035 本地化图片白屏。。。

### ISSUE THREAD

**Issue by hoa1999** [magicblack/maccms10#410]
我使用的是苹果CMS10     当前版本：2020.1000.1035

然后我的数据采集了10万条。。所以需要本地化的图片是10万条。。

但是每次下载2000-3000张图片的时候。。。本地化图片窗口就会白屏。。。然后手工再点本地化图片。。这样反复重复操作。

都不能睡觉了。。一直要盯着电脑。。。为什么越升级 BUG越多。。。以前这个问题苹果8都不会出现的。

**Comment by magicblack** [comment]
建议每次同步10条 ，不要太多否则 web服务器不支持 会卡死

**Comment by hoa1999** [comment]
> 建议每次同步10条 ，不要太多否则 web服务器不支持 会卡死

服务器是每次10条的。。。默认的10条 每次间隔3秒钟  全都是默认的。。

最开始以为是服务器差了。。因为最开始是VPS。。。然后我买了一台独立服务器  E3 1230   16G内存。。

一样会存在这样的问题。。下载图片白屏。。。  你可以自行测试下的。。。

一定会白屏。。。我全都是默认数据 没改。。 每次同步是10条

**Comment by magicblack** [comment]
更新到最新试试，实时输出内容~ 不会一直卡住不动等全部结果了。
