### ISSUE TITLE
升级最新版之后，视频播放无法使用解析了

### ISSUE THREAD

**Issue by dingzhengjie** [magicblack/maccms10#411]
升级最新版之后，视频播放无法使用解析了，如下图
![SharedScreenshot](https://user-images.githubusercontent.com/53457219/90325253-dab63f80-dfab-11ea-86df-d9e8b40cdbdb.jpg)

**Comment by magicblack** [comment]
播放器接口部分没有做调整，请检查配置 和 解析接口状态

**Comment by dingzhengjie** [comment]
自从更新1034之后就是这样了，有之前版本么，发个链接，谢谢

**Comment by magicblack** [comment]
下载离线包覆盖一下 static目录，清理下浏览器缓存  再试试 这部分最后修改是7月份。
