### ISSUE TITLE
现在变成自动升级了？？我记得我没升级啊就变成35版本了

### ISSUE THREAD

**Issue by lichen780** [magicblack/maccms10#413]
现在变成自动升级了？？我记得我没升级啊就变成35版本了

**Comment by magicblack** [comment]
已经关闭自动升级，切换为原来的提示升级。
警告，补丁包【2020.1000.1035】发布，请及时升级相应补丁！【点击进入在线升级】 【点击下载离线升级包】

**Comment by magicblack** [comment]
已经关闭自动升级，切换为原来的提示升级。
警告，补丁包【2020.1000.1035】发布，请及时升级相应补丁！【点击进入在线升级】 【点击下载离线升级包】
