### ISSUE TITLE
hi，老哥，怎么取消定时任务采集的限制

### ISSUE THREAD

**Issue by a419377389** [magicblack/maccms10#414]
你好，怎么修改文件可以取消定时任务的限制
采集的多，而且还有每个小时生成首页
有时候采集生效，生成首页不行，
而且每天采集丢失的数据很多

**Comment by magicblack** [comment]
调用定时任务时加个参数就可以强制执行了  enforce=1

**Comment by a419377389** [comment]
加在定时任务哪里？附加参数的前面还是后面

**Comment by a419377389** [comment]
这个是采集 ac=cj&cjflag=54ee0b73b8d1cb318fa045b1dbdc3d79&cjurl=http%3A%2F%2Fcj.okzy.tv%2Finc%2Fapickm3u8s.php&h=24&t=&ids=&wd=&type=1&mid=1&opt=0&filter=0&filter_from=&param=
这是生成首页
ac=index

请问怎么写法可以强制执行
