### ISSUE TITLE
请问定时任务中设置了执行周期，还需要配置宝塔定时器来触发吗？

### ISSUE THREAD

**Issue by chenzhikang** [magicblack/maccms10#42]
![image](https://user-images.githubusercontent.com/9971827/65117247-53b7ba80-da1c-11e9-9208-3a1f4f8fe87c.png)

**Comment by magicblack** [comment]
参考包里的说明文档，要么选择 第三方定时器，要么选择 网页浏览触发。

**Comment by chenzhikang** [comment]
明白了谢谢！
刚才看源码看到：<span style="display: none;" class="mac_timming" data-file="" ></span>

也就是指网页浏览触发哈，那么流量小的网站还是用第三方定时器触发。
