### ISSUE TITLE
演员“地区”权限问题

### ISSUE THREAD

**Issue by tangshaochun666** [magicblack/maccms10#423]
http://localhost/index.php/actor/show/area/大陆.html 

/index.php/actor/show/area/(大陆、欧美、日本).html 
远远的这种样式的链接 会提示无权限。后台会员权限设置后 无用处~

**Comment by magicblack** [comment]
由于演员模块升级带分类后，模板没有及时升级造成的。show页面是筛选页面，需要传入分类id才可以。
默认模板演员首页部分已修复稍后发布，可参考如下 

{maccms:type mid="8" ids="child"}
  <div class="channel-item btop">
    <div class="ui-title fn-clear"><span><a href="{:mac_url('actor/show',['id'=>$vo['type_id']])}">查看更多&gt;</a></span>
      <h2>{$vo.type_name}</h2>
    </div>
    <div class="box_con">
      <ul>
        {maccms:actor num="12" type="'.$vo['type_id'].'" order="desc" by="time"}
        <li> <a href="{$vo|mac_url_actor_detail}"><span><img src="{$vo.actor_pic|mac_url_img}" alt="{$vo.actor_name}"></span></a> <a href="{$vo|mac_url_actor_detail}">
          <h3>{$vo.actor_name}</h3></a>
        </li>
        {/maccms:actor}
      </ul>
    </div>
  </div>
  {/maccms:type}

**Comment by tangshaochun666** [comment]
您好 不好意思 我这是{:mac_url_type($obj,['area'=>$vo2,'by'=>$param['by'] ],'show')}
{:mac_url_type($obj,['area'=>$param['area'],'sex'=>$param['sex'],'blood'=>$vo2,'starsign'=>$param['starsign'],'letter'=>$param['letter'],'letter'=>$param['letter'],'by'=>$param['by'] ],'show')}
这样子弄的。没有把这个共享出来 不好意思哈~~
