### ISSUE TITLE
如何用MYSQL删除倒闭的资源数据？

### ISSUE THREAD

**Issue by hoa1999** [magicblack/maccms10#424]
第1集$https://play.haoyilai168.com/20200727/5gkptHDR/index.m3u8  这个资源站倒闭了。

怎么删除包含play.haoyilai168.com 所有的数据？只要包含有这个的就删除。。。

MYSQL命令是什么呢？  根据播放器删除不行。。。因为我把几个资源站的数据都整合到一个播放器了。。

**Comment by lqhi** [comment]
自己学mysql语法，或借助第三方工具，本身又不难。而且你自己改了东西，还要别人告诉你解决方案，再给你写好命令语句？要人人都这样，作者不得累死？
