### ISSUE TITLE
判断  play_from 是否已存在的代码有问题

### ISSUE THREAD

**Issue by TianLanSky** [magicblack/maccms10#426]
`strpos("," . $info['vod_play_from'], $cj_play_from) <= 0`

文件 application/common/model/Collet.php

假设我有两个 from，分别为 qq、qqasd

采集qq的时候，原先qqasd的 play url 就可能会被替换了

**Comment by magicblack** [comment]
嗯，已经做了相应调整稍后更新。
elseif (strpos(','.$info['vod_play_from'].',', ','.$cj_play_from.',') <= 0) {
