### ISSUE TITLE
影片详情页如何获取主演的链接

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#427]
例如：影片详情页是主演是刘德华 ，点开后不是进入搜索页面，而是进入明星库刘德华详细页面
目前使用的标签是这个：{$obj.vod_actor|mac_substring=25|mac_url_create='actor'|mac_default='未知'}，但是会进入到搜索页面

**Comment by magicblack** [comment]
使用actor标签获取演员详情，并进入
{maccms:actor num="10" paging="no" name="刘德华,刘若英" order="asc" by="sort"}
      {$vo|mac_url_actor_detail} 获取演员详情页链接
{/maccms:actor}

其中name参数可以在视频详情页面传入~

**Comment by xqd360** [comment]
可能以上表达有误，重新表述下：
主演：尼查坤·抔勒威查固 蒋劲夫 徐璐 朱丹 孟佳 于文文 周晓鸥 
目前点击主演中的明星就会自动进入搜索中去，因为明星资源已经有数据了，我希望能点击明星的名字能直接进入对应的明星详情的页面
目前目前的标签：{$obj.vod_actor|mac_substring=25|mac_url_create='actor'|mac_default='未知'}，请问下如何修改成我上面表述的效果
