### ISSUE TITLE
能否添加个全站需登录才能访问的功能

### ISSUE THREAD

**Issue by lcmqlcmq** [magicblack/maccms10#428]
没有登录的情况下自动跳转到登录页面。后台加个这个功能的控制开关

**Comment by magicblack** [comment]
非静态模式下可以用标签来判断。在head或include模板里加入

  {if condition="$user.user_id lt 1"}
    未登录
 {else}
   已登录
  {/if}

也可以在这2个模板里插入js代码判断，必须在引入jquery和home.js后面

<script>
if(MAC.Cookie.Get('user_id') !=undefined && MAC.Cookie.Get('user_id')!=''){
  已登录
}else{
未登录
}
</script>
