### ISSUE TITLE
发现有后台播放器参数丢失

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#429]

**Comment by aruoop** [comment]
有好几个网站 发现升级更新后个别网站 后台的播放器参数会空白 导致前台无法播放
重置后报错也无效！
打开/application/extra/maccms.php
里面的播放器参数设置是正常的
请问下
这种应该直接修改那个文件呀！？

**Comment by magicblack** [comment]
如何丢失的呢，做过其他操作吗。建议升级的时候 升级包要全部覆盖包含static目录，否则可能升级出现问题。
