### ISSUE TITLE
老王能针对cdn做优化吗？

### ISSUE THREAD

**Issue by anglesgirl** [magicblack/maccms10#43]
某些cdn可以缓存指定页面
我希望缓存的时候，导航条，评论，登录状态是axjx获取的不缓存
其他的全缓存

**Comment by magicblack** [comment]
一般cdn都可以设置哪些路径不缓存的。

**Comment by anglesgirl** [comment]
我的意思是，当我缓存路径和页面的时候，页面加载的导航条，登录状态，评论留言是不被缓存的，固定数据是cdn，不固定的从源获取，这样优化后，效果会更好，可以放心设置各种cdn缓存，不会导致页面数据不更新

**Comment by magicblack** [comment]
登录状态 是ajax获取的 不会被cdn缓存下来的。
其他非ajax操作的， 在页面上直接以html元素方式呈现的内容会被cdn缓存下来~~~
不想被缓存的地方，建议你修改为 ajax方式获取数据。
