### ISSUE TITLE
我希望能点击明星的名字能直接进入对应的明星资料详情的页面

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#434]
可能之前表达有误，重新表述下：
举例：影片主演： 蒋劲夫 徐璐 朱丹 孟佳 于文文 周晓鸥
目前点击主演中的明星就会自动进入搜索中去，明星资源目前已经采集有数据了，我希望能点击明星的名字能直接进入对应的明星资料详情的页面
目前目前的标签：{$obj.vod_actor|mac_substring=25|mac_url_create='actor'|mac_default='未知'}，请问下如何修改成我上面表述的效果

**Comment by magicblack** [comment]
参考上次回答。没有问题。改成系统标签来实现。

**Comment by xqd360** [comment]
使用actor标签获取演员详情，并进入
{maccms:actor num="10" paging="no" name="刘德华,刘若英" order="asc" by="sort"}
{$vo|mac_url_actor_detail} 获取演员详情页链接
{/maccms:actor}

其中name参数可以在视频详情页面传入~

---------------------------------------------------------------------------------------------------

name="刘德华,刘若英" 这里的值是使用这个标签调用吗？{$obj.vod_actor}，怎么不显示任何的演员数据数据和链接
我放的标签是这样的：{maccms:actor num="10" paging="no" name="$obj.vod_actor" order="asc" by="sort"} {$vo|mac_url_actor_detail {/maccms:actor}
请问是否有什么问题？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "magicblack/maccms10"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午4:35
收件人:&nbsp;"magicblack/maccms10"<maccms10@noreply.github.com&gt;;
抄送:&nbsp;"xqd360"<xqd360@gmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms10] 我希望能点击明星的名字能直接进入对应的明星资料详情的页面 (#434)





 
参考上次回答。没有问题。改成系统标签来实现。
