### ISSUE TITLE
三级分销存在严重BUG

### ISSUE THREAD

**Issue by yougonglin** [magicblack/maccms10#435]
目前提现和分销的机制都是使用的积分。此时如果出现A发展了下线B，当B充值后A获得了分销提成。然后A去提现了。后来B也去提现。这就造成了一个严重的白给问题。

**Comment by magicblack** [comment]
不适用可以关闭，或者 配置三级分销    一二三级都 给0 。

**Comment by yougonglin** [comment]
> 不适用可以关闭，或者配置三级分销一二三级都给0。

我觉得可以增加一个字段为佣金，然后把用户充值后的分销提成逻辑中增加积分的地方变为增加佣金，然后提现时判断佣金。你觉得怎么样。。有没有计划在接下来的版本中优化下

**Comment by magicblack** [comment]
暂时不会改动，设计初衷没有什么毛病啊。 积分就是钱 钱就是积分。
