### ISSUE TITLE
后台设置保存的时候，显示保存成功实际上是没保存

### ISSUE THREAD

**Issue by deyi80** [magicblack/maccms10#44]
出现一个BUG，就是在后台设置相关参数的完成后，点击保存，提示保存成功，但是回到页面的时候，还是默认的参数，新修改的参数没保存，在不同浏览器都是这样的，希望老王能够测试下是否有这方面的问题。谢谢~~~

**Comment by magicblack** [comment]
检查你的服务器是否开启了缓存组件，或者 检查配置文件写入权限。

**Comment by deyi80** [comment]
好，我在试试看。
