### ISSUE TITLE
采集参数配置中的自动生成TAG无限制生成词语

### ISSUE THREAD

**Issue by baiyanghk** [magicblack/maccms10#440]
开启此项功能后自动把介绍内容给生成TAG，如果介绍内容有很多这个生成就会有很多，系统会超出限制大小，能否设置一个自动生成的数量，随机生成词语限制数量大小防止超限

**Comment by magicblack** [comment]
可以修改mysql配置来实现，
-
4，SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column '' at row 1  或者 Warning: 1265 Data truncated for column 类似错误**
RE:############################################
该错误就插入字段长度超过设定的长度，一般程序会在数据库字段设置字符长度在插入之前程序很少会先判断数据长度和截取数据 这样会影响性能，所以你就需要修改你数据库的配置文件一般在MYSQL 安装目录中的my.ini中 搜索sql-mode
sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
 把其中的STRICT_TRANS_TABLES,去掉 建议使用该方法
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
或者把
sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" 直接删除
############################################
