### ISSUE TITLE
MYSQL 5.7版本的重名视频数据查询会出错

### ISSUE THREAD

**Issue by baiyanghk** [magicblack/maccms10#441]
点击 重名视频数据 查询出现错误提示`SQLSTATE[HY000]: General error: 1786 Statement violates GTID consistency: CREATE TABLE ... SELECT.`

网上看到说是因为在5.6及以上的版本内，开启了 enforce_gtid_consistency=true 功能导致的，MySQL官方解释说当启用 enforce_gtid_consistency 功能的时候，MySQL只允许能够保障事务安全，并且能够被日志记录的SQL语句被执行，像create table … select 和 create temporarytable语句，以及同时更新事务表和非事务表的SQL语句或事务都不允许执行。

是否能够修复下支持下高版本数据库兼容性

**Comment by magicblack** [comment]
已经做了一些调整稍后试试看。
