### ISSUE TITLE
安装完成后，一直重复跳转到安装界面，无法进入后台

### ISSUE THREAD

**Issue by herkoy** [magicblack/maccms10#443]
我的环境都符合要求，不知道为什么一直在重复安装，无法进入后台。希望大佬能解答一下

OS: Linux

Apache: Apache/2.4.7 (Ubuntu)

MySQL Version: 5.5.62-0ubuntu0.14.04.1-log

PHP Version: 7.3.3-1+ubuntu14.04.1+deb.sury.org+1

![image](https://user-images.githubusercontent.com/24191851/93694920-24162380-fb44-11ea-9bf8-eb3bae9f6bf5.png)
![image](https://user-images.githubusercontent.com/24191851/93694929-3ee89800-fb44-11ea-8c6b-ce214c2eeb3f.png)
![image](https://user-images.githubusercontent.com/24191851/93694935-4b6cf080-fb44-11ea-8832-319aa197ea29.png)
![image](https://user-images.githubusercontent.com/24191851/93694939-558eef00-fb44-11ea-9fb8-18ca1edd7992.png)

**Comment by magicblack** [comment]
检查 \application\data\install 目录下是否有写入权限
