### ISSUE TITLE
cookie太多导致网站无法访问。

### ISSUE THREAD

**Issue by taobao007** [magicblack/maccms10#444]
最近发现只要在网站观看一定数量影片然后就会出现网站突然无法访问的情况，发现是由于cookie太多导致，清理后即可访问；查看了cookie后发现，每个视频的播放链接都被存到了cookie，累积到一定数量后，导致网站无法访问，请问有没有什么方法解决，还是我模板或者其他问题？

**Comment by magicblack** [comment]
这个好像还真没有遇到过呢。 继续保持关注。

**Comment by h175h32** [comment]
> 最近发现只要在网站观看一定数量影片然后就会出现网站突然无法访问的情况，发现是由于cookie太多导致，清理后即可访问；查看了cookie后发现，每个视频的播放链接都被存到了cookie，累积到一定数量后，导致网站无法访问，请问有没有什么方法解决，还是我模板或者其他问题？
那是你的播放器存的cookie，存的时间太久了。设置存7天就行了。我知道ckplayer默认存的是30天。
