### ISSUE TITLE
老大老大进来看下~~~！！！

### ISSUE THREAD

**Issue by 1048562717** [magicblack/maccms10#445]
后台-视频-视频数据-同步图片的时候经常同步同步就变空白页了，一共九七多页五天才同步了三千多页，而且经常容易空白停止同步，希望可以增加个定时任务配置那种，可以选择时间系统自动同步，不然真的好痛苦。好几天时间基本都是在电脑旁呆着，必须时时盯着，同步的是七牛，希望能优化。。。

**Comment by magicblack** [comment]
耐心等待，另外需要提高服务器性能。
