### ISSUE TITLE
v10采集v8提示xml错误

### ISSUE THREAD

**Issue by skin007** [magicblack/maccms10#45]
是什么字符导致的xml提示失败

**Comment by magicblack** [comment]
以下是XML中需要的转义字符:
&(逻辑与)  &amp;        
<(小于)    &lt;        
>(大于)    &gt;        
"(双引号)  &quot;      
'(单引号)  &apos; 

遇到这个可能会无法显示

**Comment by skin007** [comment]
奥 那么这个是全局限制还是局限于简介字段？

**Comment by skin007** [comment]
通过cms 提供的api 接口获取到的简介 内容带有html 元素 这个怎么批量去掉？

**Comment by magicblack** [comment]
建议资源站使用最新的cms程序搭建资源，都有过滤掉非法字符的。 一般不会出现问题。 个别数据出现问题建议联系资源提供者修改数据。

**Comment by skin007** [comment]
我这边也用最新版V8 测试过 问题依旧存在

**Comment by skin007** [comment]
空から降ってきてパニック状態のアンノーンは「どこから来たの？」と聞いても「キラキラしたとこ」という以外分からない。仲間の場所を知っているというエネコの案内で向かった先は、行き止まりの地下水路。しかも、壁にあったおかしな柱のパズルを押してみると突然不思議な光に吸い込まれてしまう。気付くとそこは、空の上に浮かぶ石の迷路があったり、ポケモンが大きくなったりする、とっても不思議な場所。さらにニャースたちも追いかけてきた果たしてピカチュウたちは無事アンノーンを仲間のところへ連れて行くことが出来るの？

**Comment by skin007** [comment]
这算非法字符么？

**Comment by magicblack** [comment]
xml返回字段如果有大量的特殊字符，可以在返回字段外层加 CDATA 来加强兼容性。
