### ISSUE TITLE
播放器排序与sid问题

### ISSUE THREAD

**Issue by TianLanSky** [magicblack/maccms10#451]
sid顺序不会按照播放器排序设置的来，而是数据库中的顺序。

详细说明
比如数据库中 from1$$$from2
后台设置from2排序靠前

因为sid排序依据是数据库，所以from1.sid=1，from2.sid=2。
在vod/detail页面点击【立即播放】，会使用sid=1的from1，而非预期的后台中排序靠前的from2

**Comment by magicblack** [comment]
sid不会改动，只是改变显示顺序。
