### ISSUE TITLE
大家是怎么样优化这种sql语句的？

### ISSUE THREAD

**Issue by 30416530** [magicblack/maccms10#452]
正在显示第 0 - 1 行 (共 2 行, 查询花费 1.8841 秒。) [vod_time: 1587477797 - 1584783910]
SELECT * FROM `mac_vod` WHERE `vod_name` LIKE '%苍穹之昴%' AND ( vod_status=1 ) ORDER BY `vod_time` DESC LIMIT 0,20

这种like语句怎么样优化？  因为现在数据越来越多， 越来越多mysql慢查询了。

**Comment by magicblack** [comment]
优化mysql配置，提高缓存命中率。  数据太多的话就只能二开 使用第三方 搜索引擎 了。
