### ISSUE TITLE
虚拟主机只能使用PHP7.4，但是程序不支持，麻烦优化

### ISSUE THREAD

**Issue by chen5410178** [magicblack/maccms10#453]
[8192] ErrorException in common.php line 299
Array and string offset access syntax with curly braces is deprecated
    if($f=='num'){
        $pattern = '1234567890';
    }
    elseif($f=='letter'){
        $pattern = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    }
    $len = strlen($pattern) -1;
    $res='';
    for($i=0; $i<$length; $i++){
        $res .= $pattern{mt_rand(0,$len)};
    }
    return $res;
}

function mac_convert_encoding($str,$nfate,$ofate){
    if ($ofate=="UTF-8"){ return $str; }
    if ($ofate=="GB2312"){ $ofate="GBK"; }

    if(function_exists("mb_convert_encoding")){

**Comment by magicblack** [comment]
没有问题的，你用的不是最新版本。
