### ISSUE TITLE
获取IP为0.0.0.0

### ISSUE THREAD

**Issue by TianLanSky** [magicblack/maccms10#454]
很多IP都是0.0.0.0，不知道原因...

这就会导致：如果我开启了一个IP只能注册一次，那就会有许多IP被判定为0.0.0.0的用户无法注册

**Comment by lichen780** [comment]
加了cdn了吧？？

**Comment by TianLanSky** [comment]
没有

**Comment by magicblack** [comment]
这个很正常，因为暂时不支持存储ipv6地址。 还有一些ipv4的也不行。 稍后会改进ip存储方式。
