### ISSUE TITLE
采集资源站，由于有的明星采用单'符号，导致前台无法显示，这个有办法解决吗

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#455]
采集资源站，由于有的明星采用单'符号，导致前台无法显示，这个有办法解决吗
前台显示
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' ) LIMIT 0,12' at line 1

**Comment by aruoop** [comment]
比如这样的  D'Arcy

**Comment by chengshunwei** [comment]
建议转义下，存成D\'Arcy

**Comment by magicblack** [comment]
简单测试没有发现问题，你前台使用的什么标签，地址什么。
