### ISSUE TITLE
能不能增加一个一键生成全部视频TAG的按钮？

### ISSUE THREAD

**Issue by haig233** [magicblack/maccms10#456]
能不能增加一个一键生成全部视频TAG的按钮？因为设置在采集的时候生成，很容易采集的时候卡死，如果有这个按钮，就可以采集完再生成，方便很多

**Comment by h175h32** [comment]
还有个问题 如果电影说明太长，生成的tag就会上百个太多了字段也存不下。不科学。

**Comment by haig233** [comment]
> 还有个问题 如果电影说明太长，生成的tag就会上百个太多了字段也存不下。不科学。

难道是拆分文本?

**Comment by magicblack** [comment]
后续会考虑此功能的
