### ISSUE TITLE
老哥，请教下为什么我的站都加载完了，浏览器一直在请求数据转圈

### ISSUE THREAD

**Issue by ofdjonf** [magicblack/maccms10#457]
站点都加载完了，浏览器上面一直在请求转圈圈，怎么办这个咋回事？生成的纯静态页面也是这样子，进入速度也很快，全加载完了。模板是海螺模板。那里没弄好呀，求教

**Comment by haig233** [comment]
> 站点都加载完了，浏览器上面一直在请求转圈圈，怎么办这个咋回事？生成的纯静态页面也是这样子，进入速度也很快，全加载完了。模板是海螺模板。那里没弄好呀，求教

图片用的是外链吧。。。这个很正常啊

**Comment by magicblack** [comment]
很多原因肯定有链接打开慢
