### ISSUE TITLE
苹果cms10搜索查询导致cpu爆满怎么办呀，唉

### ISSUE THREAD

**Issue by ofdjonf** [magicblack/maccms10#458]
如题，使用搜索后数据库查询需要4秒多，而且网站只有几个人同时搜索的情况下，cpu就会直接飙到才百分之百。测试了，只有搜索才会出现这种情况。其他正常浏览都正常，速度也很快。这个有办法优化吗？网站30万条数据，开启了演员搜索和标题搜索，配置是4g2h，Li的系统。开启缓存没什么用，不可能每个人都搜索同样的标题。

**Comment by ofdjonf** [comment]
求大佬出来教下有什么办法。

**Comment by chengshunwei** [comment]
搜索肯定会崩溃的，另外部署一套php搜索引擎框架

**Comment by baiyanghk** [comment]
貌似很多系统都有这个问题，搜索的时候数据库会CPU超载，优化方案好像也就两种，改站内搜索引擎或者堆砌硬件，优化数据库查询方式效果不大，设置索引缓存效果也不是很好

**Comment by klmahua** [comment]
遇到同样的问题，，希望管理能加速中文分词搜索引擎技术

**Comment by klmahua** [comment]
给管理推荐个中文全文搜索引擎软件 迅搜：http://www.xunsearch.com/

**Comment by magicblack** [comment]
整合第三方搜索扩展如 xunsearch,sphinx 等等。
