### ISSUE TITLE
又拍云怎么用？。。

### ISSUE THREAD

**Issue by likele001** [magicblack/maccms10#461]
所有的项目都填好了，就是不上传啊

**Comment by magicblack** [comment]
填写好申请的配置信息后，单独上传个图片试试看。

**Comment by a2750309601** [comment]
你哪位？发错了吧？



---原始邮件---
发件人: "magicblack"<notifications@github.com&gt;
发送时间: 2020年10月26日(周一) 上午9:15
收件人: "magicblack/maccms10"<maccms10@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [magicblack/maccms10] 又拍云怎么用？。。 (#461)




 
填写好申请的配置信息后，单独上传个图片试试看。
