### ISSUE TITLE
下载图片函数有点小问题

### ISSUE THREAD

**Issue by TianLanSky** [magicblack/maccms10#462]
http://222.186.12.235:41011/Uploads/news/2019-09-02/5d6c6bc6e2d50.jpg

比如就上面这个图片网址，下载下来的图片是损坏的

model('Image')->down_load('http://222.186.12.235:41011/Uploads/news/2019-09-02/5d6c6bc6e2d50.jpg', $GLOBALS['config']['upload'], 'art');

**Comment by magicblack** [comment]
比较怪事哦是不是加了防盗链之类的，多测试几次看看。

**Comment by TianLanSky** [comment]
测试很多次了 ，您试试看

**Comment by magicblack** [comment]
这里做了一些防盗链处理，所以无法直接程序弄下来。

**Comment by TianLanSky** [comment]
这样啊，建议修改一下代码，可以传入referer参数
