### ISSUE TITLE
10.28 更新苹果CMS 到2020.1000.1038 版本无法播放 请问我是否用到了盗版？在线等，急

### ISSUE THREAD

**Issue by rixiaomei1** [magicblack/maccms10#466]
更新后点击播放 无法加载 其余暂时未发现还有哪不正常！为何有三个站 两个站提示需要更新后台 有一个没提示？难道我用的是盗版？

**Comment by jing5460** [comment]
你播放的是官方资源还是m3u8
测试过了,都正常播放
你可以更换的的模板试试

**Comment by 2757227663** [comment]
这是因为他把你之前设置的解析接口重设了，得重新添加解析接口，然后清除浏览器缓存

**Comment by rixiaomei1** [comment]
> 你播放的是官方资源还是m3u8
> 测试过了,都正常播放
> 你可以更换的的模板试试

我把网站跳了 准备重做了  你们都没有提示要更新吗 我估计我当初下到盗版了

**Comment by rixiaomei1** [comment]
> 这是因为他把你之前设置的解析接口重设了，得重新添加解析接口，然后清除浏览器缓存
请问你有提示更新吗 今天 我有几个站提示要更新 有的没有更新提示 奇怪了

**Comment by 2757227663** [comment]
> > 这是因为他把你之前设置的解析接口重设了，得重新添加解析接口，然后清除浏览器缓存
> > 请问你有提示更新吗 今天 我有几个站提示要更新 有的没有更新提示 奇怪了

我有提示更新，不提示更新可能是服务器不稳定

**Comment by rixiaomei1** [comment]
> 这是因为他把你之前设置的解析接口重设了，得重新添加解析接口，然后清除浏览器缓存

你这么一说我去看了一下 解析地址设置那 播放器参数 那里 此次升级的这个网站后台显示是 接口地址  那些正常的没有提示要升级的，我能确定官方原版程序的 显示都是 解析地址  我可能真的是当初用到盗版了 md

**Comment by rixiaomei1** [comment]
> > > 这是因为他把你之前设置的解析接口重设了，得重新添加解析接口，然后清除浏览器缓存
> > > 请问你有提示更新吗 今天 我有几个站提示要更新 有的没有更新提示 奇怪了
> 
> 我有提示更新，不提示更新可能是服务器不稳定

多谢老哥 没注意到这里 我把系统默认的解析 删掉 现在正常了

**Comment by rixiaomei1** [comment]
> > > 这是因为他把你之前设置的解析接口重设了，得重新添加解析接口，然后清除浏览器缓存
> > > 请问你有提示更新吗 今天 我有几个站提示要更新 有的没有更新提示 奇怪了
> 
> 我有提示更新，不提示更新可能是服务器不稳定

而且真的发现 没有提示要更新的都是几个站放在一起的服务器 提示需要更新的站都是单独的服务器.....

**Comment by rixiaomei1** [comment]
> > > 这是因为他把你之前设置的解析接口重设了，得重新添加解析接口，然后清除浏览器缓存
> > > 请问你有提示更新吗 今天 我有几个站提示要更新 有的没有更新提示 奇怪了
> 
> 我有提示更新，不提示更新可能是服务器不稳定

才开始做的时候 啥也不懂 瞎搞就搞到过盗版程序 现在有点风声鹤唳了....

**Comment by ibearjun** [comment]
我也是，更新后，所有的视频都播放不了？求解？播放的加载页面都没有动画

**Comment by magicblack** [comment]
如果使用了cdn加速，需要更新下 /static/目录的缓存。 
1038更新必须替换更新所有升级包内的文件，否则无法正常使用。
