### ISSUE TITLE
关于缓存问题

### ISSUE THREAD

**Issue by 2757227663** [magicblack/maccms10#467]
就是我在播放器更换了解析接口，然后打开浏览器不能播放，得清除浏览器缓存才能播放。我已经把runtime文件删了和清除了cms缓存。怎么才可以不清除浏览器缓存就能播放视频

**Comment by magicblack** [comment]
解析接口配置后，后台更新下缓存。然后前台强制刷新即可。
是浏览器缓存造成的，跟程序无关
