### ISSUE TITLE
为什么每次打开视频需要等一会才能点击播放器播放按钮？

### ISSUE THREAD

**Issue by longmaoxiazai** [magicblack/maccms10#469]
为什么每次打开视频需要等一会才能点击播放器播放按钮？（点了没反应）刚加载完页面点播放器点任何按钮没有反应，等个3分钟左右就能正常使用了，刷新网页又不能点击播放器按钮了（点了没反应）还要等待3分钟才行，这是为什么呢？

**Comment by magicblack** [comment]
检查自己整合的播放器，这个和程序无关。
