### ISSUE TITLE
你好，请问用户组权限只能看95个分类，是什么问题？

### ISSUE THREAD

**Issue by renshuaibing** [magicblack/maccms10#47]
①我设置了10个大分类（电影、电视剧、动漫等），大概120个小分类（动作片、爱情片、日韩电视剧、欧美动漫等），保存用户权限时，最多只能设置95个分类项，其他分类无法保存，请问是什么问题，谢谢！
②如果电影分类如果有23个小项，但打开网站电影页面只能看到20个，请问是什么问题？可以指出代码在哪吗？谢谢！

**Comment by magicblack** [comment]
1，数据库管理软件修改 mac_group表的 group_type字段改为 text类型即可。
2，修改标签参数 num="99"  ，因为默认是20条。

**Comment by renshuaibing** [comment]
- ### # #

**Comment by renshuaibing** [comment]
谢谢，数据库已修改

**Comment by renshuaibing** [comment]
修改标签参数 num="99"，请问是哪个文件?谢谢
