### ISSUE TITLE
关于试看和会员权限的几个问题不知是不是bug

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#477]
1、开启页面压缩后，试看功能无效可以一直看。
2、开启数剧缓存开关后，试看结束点击登录，但还是只能试看。
3、在后台修改了会员数据，比如说修改积分或者把默认会会员改为VIP，退出再登录会提示，查找用户信息失败。
4、生成首页后，在移动端用chrome打开显示的是PC端网页，用的是默认模板。

**Comment by magicblack** [comment]
1，页面压缩可能会对有注释和不标准的js写法有影响。
2，这个没有遇到过后续继续观察
3，密码，状态选项正常吗，没有遇到过
4，是的建议分别建立pc和wap两个站。或者使用一套自适应模板。

**Comment by dd0072** [comment]
2、反复测试，是在开启页面缓存后，试看结束后登录刷新还是只能试看。强制刷新则正常。
3、在后台添加会员后，在前台登录提示：查找用户信息失败。前台注册用户后，在后台修改任何用户信息再登录也提示：查找用户信息失败。版本是1041，模板是默认的模板。

**Comment by magicblack** [comment]
再次本地测试了
 在后台添加会员后，在前台登录提示：查找用户信息失败。前台注册用户后，在后台修改任何用户信息再登录也提示。
 都没有问题啊。

**Comment by dd0072** [comment]
默认的模板就会出现这样的问题，首涂的模板是正常的。这应该是哪的问题，要怎么改？
