### ISSUE TITLE
自动无缝播放下一集，能不能整合整合进去？还有试看功能改进一下，监控播放器播放时间为主

### ISSUE THREAD

**Issue by dzhuqi** [magicblack/maccms10#479]
自动无缝播放下一集，能不能整合整合进去？还有试看功能改进一下，监控播放器播放时间为主，才不会让人任意拉到任何一处播放，（目前可以直接拉到中间，或者结尾处观看）

**Comment by magicblack** [comment]
自行在第三方播放器提供的js api内部操作。
