### ISSUE TITLE
（疑问）自定义新增资源库

### ISSUE THREAD

**Issue by moyan73807** [magicblack/maccms10#48]
新增是本就有相同的影视也增加一个吗
更新如果原视频没有的会不会新增

**Comment by magicblack** [comment]
1011 新功能解析：
1，实现1个或N个主资源（新增视频数据+更新原有地址数据） 多个辅助资源（更新原有地址数据 -- 不会新增视频数据）数据~~~避免数据乱七八糟没有章法
2，资源里有N个播放器的数据，只想要其中的部分，比如youku,qq,iqiyi,sohu,mp4,m3u8   只想要 youku,mp4
