### ISSUE TITLE
缓存方式Memcache,Redis,MemcacheD无效

### ISSUE THREAD

**Issue by cainiao8899** [magicblack/maccms10#480]
缓存方式用Memcache,Redis,Memcached这三个测试链接成功，但缓存无效
开启这3个缓存器中的一个在runtime/cache目录下只有一个目录4e，没有其它缓存目录和文件
用 file就不会，在runtime/cache目录下就有很多缓存的目录

**Comment by cainiao8899** [comment]
以前旧版本只有file和Redis能用，但是缓存目录下runtime/cache也不会只有一个4e目录

**Comment by magicblack** [comment]
Memcache,Redis,Memcached 不需要file缓存。 唯一那一个文件是 addons插件的~ 不用管

**Comment by cainiao8899** [comment]
版本号 2020.1000.1041

發發發 <bbin16779@gmail.com> 于2020年11月13日周五 下午9:31写道：

**Comment by cainiao8899** [comment]
用旧版本 2019.03.06.1617 开启 Redis 就不会

發發發 <bbin16779@gmail.com> 于2020年11月13日周五 下午9:33写道：
