### ISSUE TITLE
这个站群配置导入240个保存后，清楚缓存后只有显示143

### ISSUE THREAD

**Issue by cainiao8899** [magicblack/maccms10#481]
这个站群配置导入240个保存后，清楚缓存后只有显示143

**Comment by magicblack** [comment]
是不是有重复域名，或者post提交数据多大造成了丢失

**Comment by cainiao8899** [comment]
域名没有重复，还有就是域名www.baidu.com和baidu.com词不一样，不知道是不是数据太多丢失
