### ISSUE TITLE
1040入库播放组重复问题依然存在

### ISSUE THREAD

**Issue by akaqing** [magicblack/maccms10#483]

**Comment by akaqing** [comment]
举例：采集以后线路1覆盖线路2，线路2覆盖线路1

**Comment by dd0072** [comment]
采集参数，二更规则改为：合并。

**Comment by magicblack** [comment]
一直都是这样啊， 同样的播放组类型，只会保留一组。

**Comment by akaqing** [comment]
不是同样的播放组类型，编码也不一样，之前都是正常的  线路A是一个采集点，线路B是另一个采集点，各自的地址，现在是采集A会覆盖B

**Comment by magicblack** [comment]
1041发布，修复采集入库覆盖问题。 试试看
