### ISSUE TITLE
后台升级最新版后重名视频数据还是不行

### ISSUE THREAD

**Issue by baiyanghk** [magicblack/maccms10#486]
之前反映的新版数据库使用重名视频数据查重功能异常的问题，后台更新最新版后还是报错：
`SQLSTATE[HY000]: General error: 1786 Statement violates GTID consistency: CREATE TABLE ... SELECT.`

当前更新后版本：2020.1000.1041   还是有问题

**Comment by magicblack** [comment]
解决：

  在my.cnf 中将

gtid_mode = ON
enforce_gtid_consistency = ON

改为

gtid_mode = OFF
enforce_gtid_consistency = OFF
