### ISSUE TITLE
缓冲器Memcache,Redis,Memcached 经过测试确实无效，版本号 2020.1000.1041

### ISSUE THREAD

**Issue by cainiao8899** [magicblack/maccms10#495]
缓冲器Memcache,Redis,Memcached 经过测试确实无效，版本号 2020.1000.1041

服务器E7 8895 V2 60核120线程 内存512  CPU都能飙到100%，开启Redis服务器直接卡死 

这个要怎样解决！然道没人跟我遇到同样情况吗？

用旧版本 2019.03.06.1617 开启 Redis 就不会

**Comment by magicblack** [comment]
某些情况下，2019版本的redis缓存不会生效，你可以开启后用redis管理工具查看一下。
至于cpu100%这个要看看具体是什么进程引起的 什么请求引起的 再做分析

**Comment by likele001** [comment]
我遇到过  cpu基本都被redis占了  所以关闭了redis

**Comment by cainiao8899** [comment]
> 建议使用linux + php7+
> 某些情况下，2019版本的redis缓存不会生效，你可以开启后用redis管理工具查看一下。
> 至于cpu100%这个要看看具体是什么进程引起的 什么请求引起的 再做分析。

Memcache,Redis,Memcached   这3个缓冲器随便开启一个都会卡死
