### ISSUE TITLE
会员权限能增加一个假如某个视频资源设置的只有会员才能看到，如果游客在网站搜索这个视频的时候，搜索结果为空

### ISSUE THREAD

**Issue by dguofeng** [magicblack/maccms10#496]
有些视频不想让游客搜索到或者搜索引擎收录，只有会员才能搜索或者查看到，能增加这个功能吗？或者这个功能如果有了求个开启教程

**Comment by anglesgirl** [comment]
自己加个分类，用户组权限不要给游客添加
把视频拉入这个分类

**Comment by tangshaochun666** [comment]
可以给随便一个表单一个数值，然后再模板上调用 然后if判断，如果当前会员组ID为3 则显示 否则不显示，或者
如果当前会员组ID为3则执行以下：
   如果{$vo.vod_XXX} 等于1 则显示

**Comment by dguofeng** [comment]
我试试

tangshaochun666 <notifications@github.com> 于2020年12月26日周六 下午1:36写道：
