### ISSUE TITLE
视频页面怎么调用视频的名称的相关文章，试了几种办法都不行  要改什么东西么

### ISSUE THREAD

**Issue by likele001** [magicblack/maccms10#498]
视频页面怎么调用视频的名称的相关文章，试了几种办法都不行  要改什么东西么

**Comment by magicblack** [comment]
参考标签文档 =======获取与当前文章相关联视频和关联文章数据======  。自行修改为 当前视频的关联数据。 前提是必须管理数据中配置好关联的内容。
