### ISSUE TITLE
邮箱发送配置提示错误

### ISSUE THREAD

**Issue by design-1996** [magicblack/maccms10#499]
测试失败：发生错误：Invalid address: (From): root@localhost   提示这个，请问是什么问题导致的？

**Comment by design-1996** [comment]
才发现是账号配置错误，账号正确后，一直提示  数据提交中。。   然后就没反应了，也收不到邮件。账号密码配置是正确的

**Comment by magicblack** [comment]
是否开启ssl扩展 。 另外配置一下phpmailer发送协议 试试

**Comment by design-1996** [comment]
已开启这些，测试失败：发生错误：SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting&nbsp; &nbsp; ssl和tSL都一样，都是这个提示


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "magicblack/maccms10"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月6日(星期天) 下午3:49
收件人:&nbsp;"magicblack/maccms10"<maccms10@noreply.github.com&gt;;
抄送:&nbsp;"1361824599"<myeatfish@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magicblack/maccms10] 邮箱发送配置提示错误 (#499)





 
是否开启ssl扩展 。 另外配置一下phpmailer发送协议 试试

**Comment by design-1996** [comment]
> [ssl][邮件]

还是失败   测试失败：发生错误：SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting    我重新安装苹果cms  依旧这样，使用的是宝塔面板。typecho博客也是用的这套邮箱发送，那个配置没问题，能够正常发送。就苹果cms无法发送

**Comment by magicblack** [comment]
再次测试没有问题。 测试用的qq邮箱，配置phpmailer的 帐号：123456@qq.com  密码：qq邮箱里获取的操作码。 测试发送邮件正常收取。
