### ISSUE TITLE
苹果cms什么时候开发漫画系统呢

### ISSUE THREAD

**Issue by Yeshdl** [magicblack/maccms10#5]
之前听好多人说过，苹果cms会开发漫画cms ，请问什么时候开发呢

**Comment by s7webroot** [comment]
v10就可以做

**Comment by magicblack** [comment]
现有的文章系统就可以做图片和漫画站点。 后续可能会出单独的版本。

**Comment by s7webroot** [comment]
> 现有的文章系统就可以做图片和漫画站点。 后续可能会出单独的版本。

是用视频系统和角色库做，这样才方便

**Comment by Yeshdl** [comment]
> 现有的文章系统就可以做图片和漫画站点.后续可能会出单独的版本.
现在市场上的免费漫画cms用的人最多的就是小浣熊cms，但是他的cms很多都不完善，如果苹果cms后期要开发的话，可以看下这个cms的功能结构，然后在根据苹果cms的功能做调整和更好的美化，这个小浣熊cms 作者技术不成熟，如果是你们来开发的话肯定是会更好
