### ISSUE TITLE
幻兮支付出现问题

### ISSUE THREAD

**Issue by jesusjsc** [magicblack/maccms10#50]
maccms10版本：2019.1000.1011
幻兮支付对接后，当用户付款后，幻兮平台会显示“已支付”，但cms系统扔显示“未支付”。请修复

**Comment by magicblack** [comment]
稍后测试

**Comment by jesusjsc** [comment]
应该是设计上的问题吧。比如这样的一个情形：
内部搭建的时候使用docker+php，只采用http，而没采用https，那么支付回调通知地址为：http://xxxxxx.com/index.php/payment/notify.html

但在外网访问的时候有这样一种情形，将http全部转为https，导致支付回调不起作用，出现支付平台显示“已支付"，但cms系统仍显示“未支付”：
http访问支付回调通知接口  =>  nginx（全部转成https）=> 内部

解决办法：
nginx转https的时候，只让部分uri生效，支付回调通知的uri只走http
