### ISSUE TITLE
苹果用默认模板有BUG。。

### ISSUE THREAD

**Issue by hoa1999** [magicblack/maccms10#500]
我想用默认的苹果模板，但是有个问题。。只能站群设置一个域名  比如我的域名是123.com  

那么我只能在站群设置 123.com    模板选PC。。 但是问题来了。。

手机用户怎么跳转到手机模板？？

后台首页设置的单域名  多域名  已经无效了。。。。希望修复下

**Comment by hoa1999** [comment]
默认模板要这样才能打开。。。    /index.php/vod/index.html   

有没有办法  直接输入123.com 这样的方式打开？

**Comment by magicblack** [comment]
默认模板仅供学习测试不建议正式使用。
