### ISSUE TITLE
王总,还是关于分集剧情过滤html标签的问题,我表示排查很久,不是我采集的问题

### ISSUE THREAD

**Issue by xixihaha806** [magicblack/maccms10#503]
**上图1,这是介绍标签,我确定我在火车头里没有过滤掉html标签**

![捕获1 1](https://user-images.githubusercontent.com/68390320/100424319-5f931800-30c8-11eb-856a-86b5f25df7f1.JPG)

**上图2,这是分集剧情标签,同样没有过滤html标签**

![捕获2 1](https://user-images.githubusercontent.com/68390320/100424551-b567c000-30c8-11eb-8a19-e25fd7fac349.JPG)

**上图3,这是在火车头测试采集的介绍,html标签存在,没毛病!**

![捕获1](https://user-images.githubusercontent.com/68390320/100424868-2dce8100-30c9-11eb-859d-adece457133b.JPG)

**上图4,这是在火车头测试采集的分集剧情,html标签也存在,也没毛病!**

![捕获2](https://user-images.githubusercontent.com/68390320/100424983-5c4c5c00-30c9-11eb-8d38-4893edc7eb71.JPG)

**上图5.这是发布到网站上的介绍,html标签也存在,没毛病!**

![捕获3](https://user-images.githubusercontent.com/68390320/100425142-a33a5180-30c9-11eb-92f9-27f6a5b0572a.JPG)

**上图6,这是发布到分集剧情的,html过滤掉了,而且全部5个编辑器我都换过了,采集了5次,都是一样的结果,我怀疑是入库接口地址 视频/api.php/receive/vod  这个文件是不是分集剧情的标签忘记写了?**

![捕获4](https://user-images.githubusercontent.com/68390320/100425354-01ffcb00-30ca-11eb-9d69-36fd78b5f1a4.JPG)

**Comment by magicblack** [comment]
点击编辑器的第一个按钮html，  查看源码看看到底有没有html内容。

**Comment by xixihaha806** [comment]
**以下两张图是介绍和分集剧情编辑器下的HTML内容**

![捕获5](https://user-images.githubusercontent.com/68390320/101273258-8d661400-37ce-11eb-9fa8-75d35b1969ce.JPG)

![捕获6](https://user-images.githubusercontent.com/68390320/101273263-948d2200-37ce-11eb-8540-78e6d17fa3e1.JPG)

**Comment by magicblack** [comment]
之前是为了安全避免采集挂马，过滤了html代码。稍后更新放开这个字段
