### ISSUE TITLE
这么多人用 没人发现 定时任务不能用吗？始终不执行

### ISSUE THREAD

**Issue by zubeeee** [magicblack/maccms10#506]
这么多人用 没人发现 定时任务不能用吗？始终不执行

**Comment by baiyanghk** [comment]
模版要放执行代码，模版要放执行代码，模版要放执行代码，重要的事情说三遍，原版模版没放定时任务代码

**Comment by magicblack** [comment]
模板里或者其他定时请求api接口才能触发 参考说明文档
