### ISSUE TITLE
加载的js文件太多了最多十来个文件 希望优化一下整合到1-2个js文件里面

### ISSUE THREAD

**Issue by hongdaoping** [magicblack/maccms10#508]
js文件加载的太多了，播放页面最多能到达十来个js文件，js太多对服务器应答get请求需要更多的系统资源。希望能整合在一起，这样能减轻服务器的负载。

**Comment by magicblack** [comment]
系统必备js只有2-3个。其他都是 模板里自定义的。

**Comment by hongdaoping** [comment]
不敢改动和乱删怕出问题，最好能把涉及到模版的js 分离出来放到模版文件夹里面
