### ISSUE TITLE
百度普通推送的定时任务推送时不跳转翻页，

### ISSUE THREAD

**Issue by yuwoa** [magicblack/maccms10#509]
https://github.com/magicblack/maccms10/releases/tag/v2020.1000.1042

这个版本的，百度普通推送的定时任务推送时不跳转翻页，每次都是第一页。
后台应用市场-URL推送-当天视频。。推送没有保存断点。。每次都是从第一页开始推送。

上传最新版本的更新包后也不行

**Comment by magicblack** [comment]
已经做了调整，稍后更新。
