### ISSUE TITLE
51、52版本的BUG希望修复

### ISSUE THREAD

**Issue by 1048562717** [magicblack/maccms10#516]
在51、52版本中 发现了二级筛选下不显示分类的情况，希望可以修复

**Comment by 1048562717** [comment]
还有同步图片选项中第二个选项的字段显示问题为路径，不显示文字，

**Comment by magicblack** [comment]
同步图片选项中第二个选项的字段显示问题为路径，不显示文字，   已修复。
第一个二级筛选没有发现问题，后台视频管理，文章管理 都正常呢
