### ISSUE TITLE
51、52版本中bug问题二贴，希望老大再次了解下！！！！

### ISSUE THREAD

**Issue by 1048562717** [magicblack/maccms10#517]
对上一个帖子的问题一样，后台-基础-分类 例：电影为顶级分类，二级分类有动作片、喜剧片、剧情片等，后台增加分类正常。打开前台后点击电影-更多-筛选 则分类只显示全部，而不显示动作片、喜剧片、剧情片的小分类问题（地区、年份、语言、字母一切正常）此问题都在前台的筛选页发生，希望老大了解修复，感激不尽!!

**Comment by 1048562717** [comment]
[https://tining.top/Screenshot_3.png](url) 老大 麻烦看一下我截图的地方就是问题所在的地方

**Comment by magicblack** [comment]
这个应该是模板的事情吧。

**Comment by 1048562717** [comment]
> 应该是模板的事情。老大 不是啊 我看默认模版也不显示，41的版本一切正常呢

**Comment by magicblack** [comment]
发下模板中调用此处的相关标签分析下。

**Comment by 1048562717** [comment]
> 发下模板中调用此处的相关标签分析下。

老大 我发域名麻烦你看下可以吗 www.lzitv.com确实不显示，也有其他人在群里反馈52版本不显示的情况

**Comment by 1048562717** [comment]
> 发下模板中调用此处的相关标签分析下。

如果是老版本升级上来的不影响 全新安装51、52版本的话就是这样的

**Comment by 1048562717** [comment]
确实可能模板问题吧。。。老大是不是改过标签了啊

**Comment by 1048562717** [comment]
> 发下模板中调用此处的相关标签分析下。

我知道问题所在了老大，原来是51、52版本中后台-url地址配置-加密key的问题，如果把默认的数字id或者拼音id更换成加密id的话，前台筛选页面就不显示二级分类了

**Comment by 1048562717** [comment]
因为模板是调用的id 如果使用加密的key的话就调用不到 所以就会出现不显示的问题呢

**Comment by magicblack** [comment]
模板标签中改为用 $GLOBALS['type_id'] 、$GLOBALS['type_pid']   获取当前分类id，再获取子分类。不要直接使用param获取就可以了
