### ISSUE TITLE
关于分集剧情的分页规则

### ISSUE THREAD

**Issue by likele001** [magicblack/maccms10#519]
剧情做了伪静态
juqing-<page?>   => plot/index
juqing$ => plot/index
juqing/<id>  => vod/plot/

现在是在分集剧情页的url规则怎么写？
juqing/<id>/<page?>  => plot/detail

这样写 不对啊

**Comment by magicblack** [comment]
所有规则不能有冲突。可以试试
jqxq/-<?id>-<page?> => plot/detail

**Comment by likele001** [comment]
> 所有规则不能有冲突。可以试试
> 
> `jqxq-<?id>-<page?> => plot/detail`


我设置这样可以。。   可以是url链接怎么在模板里换？

juqing-<page?>   => plot/index
juqing$ => plot/index
juqing/<id>  => vod/plot/
juqing-<id?>-<page?> => plot/detail


{:mac_url_vod_plot($vo1)}  这样获取的还是设置之前的url  现在只能手写在模板么？

**Comment by magicblack** [comment]
这可是在标签文档里都有的 搜索 =======视频分集剧情页独有标签=======
  mac_url_plot_detail($vo1,['page'=>1])  分集剧情详情页地址
