### ISSUE TITLE
建议“简介”不用在入库为空的时候自动截取“内容”字段，内容标签本身就支持len=截取，自动截取浪费数据库

### ISSUE THREAD

**Issue by s7webroot** [magicblack/maccms10#52]
建议“简介”blurb不用在入库为空的时候自动截取“内容”字段，内容标签本身就支持len=截取，自动截取有点浪费数据库了

**Comment by magicblack** [comment]
不用纠结，除了作为简介外，还有人用把这个字段自己可以输入一些内容作为他用。。。
