### ISSUE TITLE
开启站群后，自定义404页面功能无效！

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#520]
开启站群后，自定义404页面功能无效！在后台设置了404页面模版名字，但是访问不存在的页面还是原来的跳转404页面模版！！

**Comment by magicblack** [comment]
应该不会吧，因为404页是获取当前模板目录下的文件。只要前台模板显示正确，404页应该对。

**Comment by klmahua** [comment]
哦。。。现在正常了
