### ISSUE TITLE
后台添加不了自定义资源库

### ISSUE THREAD

**Issue by 1638523919** [magicblack/maccms10#523]
maccms10/blob/master/application/admin/controller/Collect.php   这个文件的 info方法进行了token验证，然后前端又没有传入_token_ 参数，无法通过验证

**Comment by magicblack** [comment]
没有问题，请检查是不是升级包替换问题。 没有替换 /application/admin/view/collect/info.html

**Comment by 1638523919** [comment]
你好，事情的经过是这样的，我下载的你v2020.1000.1042这个版本，这个版本info.html文件确实存在__token__这个参数，然后我记得第一次登陆到后台的时候看到有个升级，我就点击了一下，估计就是这个操作把我又__tokken__的info.html页面替换成了没有的了
![image](https://user-images.githubusercontent.com/47804646/101875481-ab17ec80-3bc5-11eb-9499-35b8669776e0.png)

git 记录如下 有个减号，应该是升级的时候被删除了 token 隐藏域

@@ -2,7 +2,6 @@
 <div class="page-container p10">
     <form class="layui-form layui-form-pane" method="post" action="">
         <input id="collect_id" name="collect_id" type="hidden" value="{$info.collect_id}">
-        <input type="hidden" name="__token__" value="{$Request.token}" />
         <div class="layui-form-item">
             <label class="layui-form-label">资源名称：</label>
             <div class="layui-input-block  ">
@@ -56,8 +55,8 @@
             <div class="layui-input-block">
                 <input name="collect_filter" type="radio" value="0" title="不过滤" {if condition="$info['collect_filter'] e
                 <input name="collect_filter" type="radio" value="1" title="新增+更新" {if condition="$info['collect_filter'
-                <input name="collect_filter" type="radio" value="1" title="新增" {if condition="$info['collect_filter'] eq
-                <input name="collect_filter" type="radio" value="2" title="更新" {if condition="$info['collect_filter'] eq
+                <input name="collect_filter" type="radio" value="2" title="新增" {if condition="$info['collect_filter'] eq
+                <input name="collect_filter" type="radio" value="3" title="更新" {if condition="$info['collect_filter'] eq
             </div>
         </div>
         <div class="layui-form-item row_filer" {if condition="$info['collect_mid'] neq '1'"} style="display:none;" {/if}>
~
~

**Comment by magicblack** [comment]
可以去https://github.com/magicblack/maccms_down 下载离线升级包覆盖即可。

**Comment by 1638523919** [comment]
感谢，我担心下次升级，会不会存在这些问题。
