### ISSUE TITLE
老版本如何升级

### ISSUE THREAD

**Issue by freeporm** [magicblack/maccms10#524]
用的版本比较老了，19年初的版本，想升级到最新的版本，可是直接覆盖文件后全时各种报错，想问一下在已经运行一段时间的网站上如何升级苹果cms10到最新系统。

**Comment by magicblack** [comment]
到https://github.com/magicblack/maccms_down 下载 离线升级包覆盖即可。 maccms10_update.zip 直接覆盖，然后刷新后台首页 按提示升级数据库。
