### ISSUE TITLE
创建新专题后相关文章不显示

### ISSUE THREAD

**Issue by freeporm** [magicblack/maccms10#525]
创建新专题后，在相关文章表格框中已经填写了相关文章ID，但在专题页面里并不显示任何相关文章，如何解决？

**Comment by magicblack** [comment]
这个要看你前台的专题模板如何写的，是否罗列出来 文章部分。

**Comment by freeporm** [comment]
模板上确实没有罗列出来，如何罗列出来 文章部分？通用标签是？

**Comment by magicblack** [comment]
参考标签文档和默认模板即可。
