### ISSUE TITLE
后台上部导航那里右上角清理缓存边上的网站首页项能否加回来？

### ISSUE THREAD

**Issue by freeporm** [magicblack/maccms10#526]
后台上部导航那里右上角清理缓存边上的网站首页项能否加回来？以前的老版本是清理缓存边上网站首页并列，站长设置后看站效果点击比较方便，后来那网站首页被收到下拉菜单了，点击不方便，体验不好，而且右侧上部空间很大，和清理缓存并列显示网站首页完全不影响布局，能否改回来？

**Comment by magicblack** [comment]
看情况改动，因为要兼容手机端显示。

**Comment by freeporm** [comment]
一般用后台管理还是PC操作的多一些吧

**Comment by magicblack** [comment]
做了一些调整静等更新
