### ISSUE TITLE
新版本问题，后台刷新后退出登陆

### ISSUE THREAD

**Issue by akaqing** [magicblack/maccms10#527]
最新的版本刷新缓存后就自动退出后台，很麻烦 望修复

**Comment by akaqing** [comment]
最新版和宝塔的网站加速也有冲突

**Comment by magicblack** [comment]
53启用 session验证后台登录，清理缓存按说对这个没影响，本地测试也没有问题呢

**Comment by akaqing** [comment]
> 53启用 session验证后台登录，清理缓存按说对这个没影响，本地测试也没有问题呢

切换52正常

**Comment by magicblack** [comment]
升级后由于切换了验证登录方式，需要重新登录下后台  再试试看。
