### ISSUE TITLE
鎖屏輸入管理員密碼是錯誤的，導入播放器非法訪問

### ISSUE THREAD

**Issue by qin2006** [magicblack/maccms10#529]
導入播放器提示我非法訪問，還有鎖屏の時候無論輸入任何密碼按解鎖沒動靜

**Comment by magicblack** [comment]
可能是升级失败，下载离线升级包覆盖后，重新登录后台 测试下。

**Comment by qin2006** [comment]
> 可能是升级失败，下载离线升级包覆盖后，重新登录后台 测试下。

覆蓋離綫包在哪裏下載

**Comment by qin2006** [comment]
> 可能是升级失败，下载离线升级包覆盖后，重新登录后台 测试下。

覆蓋了，輸入密碼按解鎖也是沒動靜

**Comment by qin2006** [comment]
服務器是Windows操作系統，PHP7.2.然後請求非法，非法訪問，鎖屏了，解鎖用不了

**Comment by magicblack** [comment]
清理下浏览器缓存包括cookie试试。win+php7.2 测试没有问题。

**Comment by qin2006** [comment]
> 清理下浏览器缓存包括cookie试试。win+php7.2 测试没有问题。

試過了，換了設備還是不行

**Comment by qin2006** [comment]
鎖屏有點很困難解決，播放器導入文件時它提示非法訪問，重裝幾次都是這樣。
