### ISSUE TITLE
邮箱注册问题！！！

### ISSUE THREAD

**Issue by 52xd** [magicblack/maccms10#530]
后台已经配置好邮件发送，测试是可以发送的，但是在前端注册的时候，获取邮件验证码错误，提示：验证码发送失败：发生错误：SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting   我用了苹果CMS自带模板和自己的模板都试过了，验证码获取都是失败！下面是测试图片链接：
https://cdn.52xd.tv/image/5fd6960144544.jpg
https://cdn.52xd.tv/image/5fd696018bfb8.jpg
https://cdn.52xd.tv/image/5fd696018cbee.jpg

**Comment by magicblack** [comment]
比较怪本地测试完全正常。实在不行你下载离线升级包 覆盖下试试。

**Comment by magicblack** [comment]
建议排查下邮箱连接参数，确认网站部署的主机没有屏蔽对应端口后再试。
