### ISSUE TITLE
最新版本清除缓存会退出登录

### ISSUE THREAD

**Issue by 2CW** [magicblack/maccms10#531]
最新版本清除缓存会退出登录

commit: ce6f8bd

**Comment by magicblack** [comment]
53开始后台登录状态改为session判断。 缓存和session没直接关系。 为什么会退出登录呢。。。有待继续观察

**Comment by akaqing** [comment]
我之前就反馈了，我自己大致可能是网站用了CDN，本地都是回源访问，可能是这个引起的

**Comment by haig233** [comment]
> 我之前就反馈了，我自己大致可能是网站用了CDN，本地都是回源访问，可能是这个引起的，另外和宝塔网站加速也有冲突

我没有用任何CDN，也碰到了这个问题
