### ISSUE TITLE
新版本cms之后模板不能设置不能保存了 总提示登录

### ISSUE THREAD

**Issue by tiqun** [magicblack/maccms10#533]

**Comment by qin2006** [comment]
什麽模板？應該找模板的作者，提示登陸應該是你換新設備了

**Comment by tiqun** [comment]
> 什么模板？应该找模板的作者，提示登陆应该是你换新设备了

好几个模板不知道是不是因为破解版原因 而且最近服务器经常异常满载

**Comment by qin2006** [comment]
> > 什么模板？应该找模板的作者，提示登陆应该是你换新设备了
> 
> 好几个模板不知道是不是因为破解版原因 而且最近服务器经常异常满载

網站模板不能保存的話，把其他模板刪了試試？
