### ISSUE TITLE
後台開放API 配置成收費授權模式 無法使用

### ISSUE THREAD

**Issue by ajkick** [magicblack/maccms10#535]
開放API 配置"收費授權模式" 無法使用

開啟收費模式 填寫"域名"以及"IP"都無法使用 

關閉收費模式後就正常

麻煩幫忙看一下問題出在哪?

**Comment by qin2006** [comment]
API還有收費功能？我只知道CMS只有視頻收費哈哈

**Comment by likele001** [comment]
填写IP

**Comment by ajkick** [comment]
> 填写IP

填寫IP一樣不行喔

**Comment by linkala** [comment]
@ajkick 我也是，你是不是采集站开了CDN，暂时我也没找到解决办法～

**Comment by magicblack** [comment]
api开放站点，  不能开启cdn否则无法正确获取到 请求ip ~~~
