### ISSUE TITLE
附件保存失败

### ISSUE THREAD

**Issue by haig233** [magicblack/maccms10#536]
54版本，附件保存设置为阿里巴巴图床，采集时，后台显示了阿里图床的图片链接，但是打开数据库查看vod表，pic字段是本地图片文件的链接

**Comment by magicblack** [comment]
阿里巴巴图已经失效了吧，换其他的试试。

**Comment by haig233** [comment]
> 阿里巴巴图已经失效了吧，换其他的试试。

并没有，老版本都可以保存到阿里巴巴图床的，就最新的不行，而且是全部都是显示本地图片链接（也就是说没有一张成功的）
