### ISSUE TITLE
API不显示 电影 连续剧数据 建议增加 模糊搜索 app API首字母搜索

### ISSUE THREAD

**Issue by qq79115085** [magicblack/maccms10#537]
ALTER TABLE `mac_vod`
ADD COLUMN `vod_first_letter` varchar(30) NOT NULL DEFAULT '' AFTER `vod_status`   //建议增加  模糊搜索 app API首字母搜索
这行代码  有可能错误  请官方 修正
----------------------------------------------------------------------------------------------------------------------------------------------
/api.php/provide/vod/?ac=videolist&t=1  
/api.php/provide/vod/?ac=videolist&t=2
/api.php/provide/vod/?ac=videolist&t=3
/api.php/provide/vod/?ac=videolist&t=4
API  不显示 电影  连续剧 数据  或 不显示 综艺 动画片
{"code":1,"msg":"数据列表","page":1,"pagecount":0,"limit":"20","total":0,"list":[]}
是服务器 SSL CDN问题吗 还是苹果CMSV10问题 
----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by magicblack** [comment]
本身包含首字母字段vod_letter ，但是api接口目前没有提供该参数的查询。

**Comment by qq79115085** [comment]
别名 xiyouji   首字母 xyj    这样显示 好像不支持

**Comment by magicblack** [comment]
暂时不支持这种方式。
