### ISSUE TITLE
1055版本-插件应用，部分安装后无效，全部跳转首页

### ISSUE THREAD

**Issue by 52xd** [magicblack/maccms10#538]
addons目录下安装的插件应用很多都无效，总结一个规律：后台-自定义菜单配置中*.php结尾的插件都失效，直接跳转首页。
下面是测试图：
https://cdn.52xd.tv/image/5fda431fe656c.jpg
而那些不是*.php结尾的插件是没问题的，我测试是没问题哈，不知道其他人有没这情况！
以上情况是自己测试过得，浏览器缓存都清理过，也换过其他浏览器测试过，不知道各位的如何！

**Comment by magicblack** [comment]
测试没问题，以下地址 都可以访问
啊啊,/addons/aaa/
啊啊,/addons/aaa/index.php

**Comment by qin2006** [comment]
我也跟你一样类似的这种情况

**Comment by 52xd** [comment]
> 测试没问题，以下地址都可以访问
> 啊啊，/ addons / aaa /
> 啊啊，/ addons / aaa / index.php

刚刚我试过了，1055和1056版本一样，安装插件后还是跳首页，好像是1055开始就不行了，1055以前的版本还OK

**Comment by 52xd** [comment]
> 我也跟你一样类似的这种情况

我还以为就我一个会这样呢，刚刚我又试了1056版本，还是一样安装插件后还是跳首页，好像是1055开始就不行了，1055以前的版本还OK

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> 测试没问题，以下地址 都可以访问
> 啊啊,/addons/aaa/
> 啊啊,/addons/aaa/index.php

版本 `2020.1000.1069`

安装后 `/addons/adminloginbg/` 和 `/addons/adminloginbg/index.php` 均无法显示



![image](https://user-images.githubusercontent.com/64393724/110770822-be098e00-8294-11eb-8343-7926cb07d4d4.png)

![image](https://user-images.githubusercontent.com/64393724/110770946-eb563c00-8294-11eb-8682-57347c09c89a.png)

![image](https://user-images.githubusercontent.com/64393724/110771012-00cb6600-8295-11eb-9239-0b99d44fd760.png)

**Comment by magicblack** [comment]
更新到最新版本试试看

**Comment by dalaolala** [comment]
最新版还是不行 插件直接强制跳转首页
