### ISSUE TITLE
能否针对移动和pc优化现有模版，模版过于老旧

### ISSUE THREAD

**Issue by hongdaoping** [magicblack/maccms10#539]
希望能针对搜索引擎 来优化一下现有的移动和pc模版，增加一些有利于搜索引擎的标签，优化js和css，使用h5标签，。各种来源模版是很多，买的模版不放心，找第三方制作模版费用太高，第三方模版太多相同的模版不利于收录，自己做学习周期太长不规范，对于基本是靠搜索引擎带来流量的网站，友好的模版比后台核心更重要。希望大佬能优化下模版，这样菜鸟和小白 只要稍微修改调整下模版 折腾的效率就高很多。

**Comment by qin2006** [comment]
自已试一下改源码，给作者一点时间就好

**Comment by magicblack** [comment]
后面默认程序不会自带模板了。建议搜索寻找模板
