### ISSUE TITLE
自适应手机开启多域名时手机Firefox会不停的刷新

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#544]
自适应手机开启多域名时手机Firefox浏览器会不停的刷新，开启单域名正常。手机Firefox浏览器版本号为84.1.1。苹果 CMS版本号1055。

**Comment by magicblack** [comment]
pc端域名  wap端是否配置正确 不一样。

**Comment by dd0072** [comment]
PC端域名：www.xxxx.com，WAP端域名m.xxxx.com。测试了UC浏览器，chrome,夸克,Firefox,只有Firefox会出现这样的情况。
