### ISSUE TITLE
dplayer播放器怎么禁用右键菜单

### ISSUE THREAD

**Issue by qin2006** [magicblack/maccms10#548]
请问哪里改掉？CMS有几个BUG：播放器导入文本后的第二天开始提示请求非法，插件保存文本后第二天也出现跳转首页的情况。还有就是锁屏就是摆设。。。。。一旦进了，想解锁都解锁不了

**Comment by magicblack** [comment]
你的升级是否完整。建议你下载离线升级包， 手动覆盖升级。
