### ISSUE TITLE
like查询太慢

### ISSUE THREAD

**Issue by chengzf** [magicblack/maccms10#549]
慢日志里全是like查询，会把CPU占到100%...

**Comment by magicblack** [comment]
建议生成首页，开启缓存，优化mysql配置。  后续也会优化大数量查询性能

**Comment by chengzf** [comment]
已经是按照你说的做的。
查了一下，发现是like %wd%不会使用索引。
我现在才20多万条数据，查询速度就要几秒到十几秒，遇到访问量高的时候，cpu一下就卡到100%了。
# Query_time: 3.313785  Lock_time: 0.000076 Rows_sent: 0  Rows_examined: 214392
SET timestamp=1609203999;
SELECT * FROM `mac_vod` WHERE  `vod_status` = 1  AND `vod_area` IN ('日本')  AND `type_id` IN ('11')  AND (`vod_class` LIKE '%农村%') ORDER BY `vod_time` DESC LIMIT 0,60;

**Comment by jackrebel** [comment]
@chengzf  楼主解决没有？ 我数据才14万，  把视频详情、首页、列表这些地方都静态化了， 也开了redis， 访问量稍高一点，mysql就占cpu100%全站502了。   mysql的配置优化了无数遍都解决不了。 可是4核8G10M带宽的机器啊。。。

**Comment by chengzf** [comment]
> @chengzf 楼主解决没有？ 我数据才14万， 把视频详情、首页、列表这些地方都静态化了， 也开了redis， 访问量稍高一点，mysql就占cpu100%全站502了。 mysql的配置优化了无数遍都解决不了。 可是4核8G10M带宽的机器啊。。。

我把google的蜘蛛屏蔽后问题得到明显改善，你可以试试。
