### ISSUE TITLE
有啥办法可以防止挂马吗

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#553]
网站经常挂马
以前是挂在模板JS文件里面
后面我吧js放到cdn了就转挂到html里面
现在直接是挂到缓存文件里面去了

我开启了宝塔企业防串改功能也没用
 厉害的就是修改文件了日期都不变 
请问下有啥办法可以防止挂马吗？
木马js域名是maccms.cm

**Comment by magicblack** [comment]
你之前可能用的盗版程序，另外第三方模板和插件里可能有后门，建议仔细检查。
另外按照wiki里的清理挂马的方法进行重置。

**Comment by klmahua** [comment]
所有的文件只给读取权限，，不给写入权限，缓存换成redis

**Comment by zhangchenglin** [comment]
请问一下，如何发现自己被挂马？

**Comment by aruoop** [comment]
> 所有的文件只给读取权限，，不给写入权限，缓存换成redis

没用 试过，修改权限555
然后宝塔还开起了企业版的防篡改，照样被挂上

**Comment by aruoop** [comment]
> 请问一下，如何发现自己被挂马？

弹广告，转跳，调试发现未知js啥的

**Comment by freeporm** [comment]
我也遇到了，一个模板调试的很好用了一年了结果直接挂马劫持wap量跳转，没办法就是换模板，估计未来也防不住还得继续换

**Comment by aruoop** [comment]
> 你之前可能用的盗版程序，另外第三方模板和插件里可能有后门，建议仔细检查。
> 另外按照wiki里的清理挂马的方法进行重置。

已经按照wike操作了，一样有被挂
发现只要有点流量就被挂，没有流量的屁事没有

**Comment by magicblack** [comment]
建议全面检查 模板，和插件 ~

**Comment by woaibooks** [comment]
wike操作是怎么操作
有没有网址

**Comment by magicblack** [comment]
> wike操作是怎么操作
> 有没有网址

https://github.com/magicblack/maccms10/wiki/%E5%B0%8F%E7%99%BD%E9%80%9A%E7%94%A8%E6%B8%85%E7%90%86php%E5%90%8E%E9%97%A8%E5%8A%9E%E6%B3%95%E7%AE%80%E5%8D%95%E6%98%93%E6%87%82
