### ISSUE TITLE
采集视频的时候，能替换掉主演里面的特定字符吗？

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#554]
采集视频的时候，能替换掉主演里面的特定字符吗？
发现有部分资源站主演有单引号，会导致访问该视频出现数据库SQLSTATE[42000]: Syntax error or access violation:错误，
想要替换特定字符，后台采集只能替换标题

**Comment by hercolor** [comment]
可以，修改代码。/application/common/model/Collect.php

**Comment by aruoop** [comment]
> 可以，修改代码。/application/common/model/Collect.php

看不懂代码....
