### ISSUE TITLE
关于搜索优化的建议

### ISSUE THREAD

**Issue by 1048562717** [magicblack/maccms10#556]
希望搜索功能增加模糊搜索，如电影名叫：如懿传，用户搜索如意转或如易传时可以直接显示发音差不多的对应电影，这样可以更好的留存用户，不会因为因为因为错别字让用户认为没有对应的片源而流失，希望老大可以增加此功能。

**Comment by magicblack** [comment]
网站配置，性能优化  下拉 找到 搜索配置相关字段 即可
