### ISSUE TITLE
如何判断用户是否是vip用户

### ISSUE THREAD

**Issue by freeporm** [magicblack/maccms10#557]
调试模板需要一个判断语句，就是判断用户是否为vip用户，如果不是VIP用户则执行之后的语句，如果是则不执行。现在需要对是否为VIP用户返回一个值，然后用IF语句。但标签里没有找到，只找到VIP到期时间{$user.user_end_time} vip截止期限 。想问下如何调用用户组是否为VIP，有专门的标签对应吗？

**Comment by magicblack** [comment]
标签文档中搜索   非静态模式下，可获取到的当前登录用户的信息  可以获取当前 用户组ID 用这个来判断就行

**Comment by freeporm** [comment]
好的
