### ISSUE TITLE
希望在模板标签增加自定义mysql 语句

### ISSUE THREAD

**Issue by 63626085** [magicblack/maccms10#558]
{maccms:vod num="6" tag='.$obj['vod_tag'].' order="desc" by="time"}
       <li><a href="{:mac_url_vod_detail($vo)}" title="{$vo.vod_name}"><h2>{$vo.vod_name}</h2></li>
    {/maccms:vod}
希望增加自定义sql语句
   {maccms:vod sql=”语句“}
       <li><a href="{:mac_url_vod_detail($vo)}" title="{$vo.vod_name}"><h2>{$vo.vod_name}</h2></li>
    {/maccms:vod}

**Comment by 63626085** [comment]
{maccms：vod num =“ 6” tag ='。$ obj ['vod_tag']。” order =“ desc” by =“ time”}
{$ vo.vod_name}
{/ maccms：vod}
希望增加自定义sql语句
{maccms：vod sql =“语句”}
{$ vo.vod_name}
{/ maccms：vod}

**Comment by magicblack** [comment]
建议直接使用php区块，直接调用系统函数获取数据。
