### ISSUE TITLE
王哥，v10出个站群插件呗

### ISSUE THREAD

**Issue by xingchenwl** [magicblack/maccms10#56]
v8有站群插件，但是感觉性能不如v10，v10也出个站群插件呗

**Comment by magicblack** [comment]
v10的站群2018年已经开发完毕，只是暂时没有发布而已。预计官方重开后免费发布！敬请期待！

**Comment by s7webroot** [comment]
> v10的站群2018年已经开发完毕，只是暂时没有发布而已。预计官方重开后免费发布！敬请期待！

王大哥，别等了，先内测也好哈，V10是最好的影视CMS，没有之一~~~
不像那个笑话那样，修了几十个版本还是让人挂马。

**Comment by fulidhw** [comment]
> v10的站群2018年已经开发完毕，只是暂时没有发布而已。预计官方重开后免费发布！敬请期待！

大哥。maccms10站群插件什么时候上线？
