### ISSUE TITLE
数据超过15w， mysql占用cpu100%曝了。 

### ISSUE THREAD

**Issue by jackrebel** [magicblack/maccms10#560]
什么时候能优化一下数据库？  后台的表优化用了。 
大概是这些索引， 
 
![QQ截图20210103171533](https://user-images.githubusercontent.com/3348236/103475409-e209a880-4de7-11eb-96a7-7bedc46cee1d.png)

有没有什么优化的措施？

**Comment by hercolor** [comment]
使用数据缓存就能缓解。

**Comment by aruoop** [comment]
只能缓解，可以cdn缓存为静态文件，会有加速效果，反正我的经常红 24h48线程的U

**Comment by magicblack** [comment]
#549
