### ISSUE TITLE
最新版为什么去掉了插件包的离线安装，可以恢复下吗

### ISSUE THREAD

**Issue by 515445681** [magicblack/maccms10#562]
我们这边针对您的苹果CMS做插件开发，给客户的教程也是通过离线安装这种比较方便的形式进行的。
但是最近客户反馈找不到离线安装的按钮了。
可以在下个版本恢复这个功能吗。

**Comment by magicblack** [comment]
看情况吧，这个插件建议手动安装下。后台上传无法验证安全性 ，上传后门很容易 所以关闭了。
