### ISSUE TITLE
邮箱注册验证问题。

### ISSUE THREAD

**Issue by tangshaochun666** [magicblack/maccms10#563]
本地还有服务器上测试过了，后台测试可以发送，但是前台提示：
验证码发送失败：发生错误：SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

我的模板还有苹果CMS自带的模板都测试了，发送不了。端口正常
请问是怎么回事 如何解决。

**Comment by tangshaochun666** [comment]
也拿最新一期的安装测试过了，也下载离线升级包覆盖测试过了，问题一样

**Comment by magicblack** [comment]
修复里等待更新。
