### ISSUE TITLE
增加sql语句吧

### ISSUE THREAD

**Issue by 63626085** [magicblack/maccms10#565]
{maccms：vod num =“ 6” tag ='。$ obj ['vod_tag']。” order =“ desc” by =“ time”}
{$ vo.vod_name}
{/ maccms：vod}
希望增加自定义sql语句
{maccms：vod sql =“语句”}
{$ vo.vod_name}
{/ maccms：vod}

**Comment by magicblack** [comment]
安全问题比较不好控制，认真研究后续功能。
