### ISSUE TITLE
建议：当缓存开启了Redis， Redis由于某些原因挂了全站报错。 是否可以增加判断，如果Redis等缓存挂了不读缓存？

### ISSUE THREAD

**Issue by jackrebel** [magicblack/maccms10#567]
当缓存开启了Redis， Redis由于某些原因挂了， 全站错了。 是否可以增加判断，如果Redis等缓存挂了能不读缓存？ 增加稳定性，

**Comment by jackrebel** [comment]
如果缓存服务器挂掉,  就全完了， 希望能加上缓存服务器挂了， 能自动切换到文件缓存上。

**Comment by magicblack** [comment]
这个建议使用redis集群。

**Comment by xingchenwl** [comment]
集群需要至少6台服务器吧？

**Comment by xingchenwl** [comment]
> 这个建议使用redis集群。
集群需要至少6台服务器吧？
