### ISSUE TITLE
playerconfig.js文件经常空白，导致播放器无法载入

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#569]
发现多个网站的无法播放
后面排查发现
playerconfig.js文件空白，
导致播放器无法载入

已经多次出现

**Comment by magicblack** [comment]
在此期间是否 在后台点击过 更新缓存 ？

**Comment by aruoop** [comment]
> 在此期间是否 在后台点击过 更新缓存 或 播放器配置 ？

没有操作过播放器配置
有设置定时任务大约每天清理下缓存
然后就发现不定时的出现文件js空白
播放器配置全都是空白，设置保存无效
需要从新替换备份文件才正常播放

**Comment by magicblack** [comment]
应该是定时清理缓存造成的，你可以先关掉。 稍后测试下。
