### ISSUE TITLE
邮箱发送{$time}有效时间标签获取不到值，发送人昵称也不起作用

### ISSUE THREAD

**Issue by wangyiemail** [magicblack/maccms10#570]
邮件发送{$time}有效时间标签获取不到值；发件人使用的是账号，发送人昵称不起作用，单独点击测试按钮的时候发件人昵称起作用
版本为maccms10   1058版本，另外要是能配回信地址就好啦

**Comment by qin2006** [comment]
我在后台测试可以发送，但是前端就没反应

**Comment by magicblack** [comment]
修复了， 稍后发布59版本。
