### ISSUE TITLE
都是like查询，吓跑了我

### ISSUE THREAD

**Issue by nowinkey** [magicblack/maccms10#573]
筛选列表、搜索查询都使用效率极低的like查询，生成静态也只能对默认排序有效，这极大限制了系统的效能，这是整个系统的数据库结构基础，随着功能的不断添加，越迟改造它，修复它的工作量就越多。

盼望有改造优化此问题的时间表。

**Comment by klmahua** [comment]
搜索的确越来越慢。。。数据量一大，，，搜索一个关键词夸张的好几分钟都不出来数据

**Comment by jackrebel** [comment]
是的， 数据超过十万后， 搜索时mysql好多慢查询,   就算开了redis，也解决不了这种问题。 
maccms用的是thinkphp框架， 建议使用，迅搜(XunSearch)+ThinkPHP来优化搜索问题。

**Comment by nowinkey** [comment]
改造自身的数据结构是治本的方法，例如建立数据表，存储tag和vod的id对应关系，等

**Comment by qiyue520** [comment]
搞个索引

**Comment by magicblack** [comment]
#549
