### ISSUE TITLE
关于一些疑问

### ISSUE THREAD

**Issue by qin2006** [magicblack/maccms10#575]
豆瓣查询数据功能什么时候能更新？邮箱的注册，绑定正文有示例吗？{$maccms.***}标签， {$user.***}标签， {$code}验证码， {$time}有效时间。不知道怎么用，发的邮箱过来还是原本的

**Comment by qin2006** [comment]
反馈一下，采集的越多（6w条视频数据），后面再采集和搜索速度会越差

**Comment by magicblack** [comment]
请更新到最新版本测试。
