### ISSUE TITLE
清除缓存会退出登录问题，解决下吧

### ISSUE THREAD

**Issue by akaqing** [magicblack/maccms10#576]
2020.1000.1060  历史问题了依然存在，升级版本

只要刷新缓存，就自动跳到登陆页面重新登陆

**Comment by freeporm** [comment]
这个还是很影响已经登陆用户的，支持解决一下啊

**Comment by magicblack** [comment]
php配置-》 session配置 -》 存储方式：files文件存储。 这样配置就ok了。
