### ISSUE TITLE
数据缓存具体缓存了什么数据，占硬盘如此巨大？

### ISSUE THREAD

**Issue by freeporm** [magicblack/maccms10#577]
由于CPU占比较高打开了系统网站参数设置的数据缓存功能，CPU占比问题得到缓解，但缓存占硬盘空间巨大，几个小时下来已经多了25个G了，而且还在不断增加。想具体问下，这数据缓存具体缓存了什么数据。可否经常删除。

**Comment by hercolor** [comment]
安装使用redis就好。

**Comment by freeporm** [comment]
那个redis不太起作用啊，就缓存7MB，而且连接的数也不多。

**Comment by klmahua** [comment]
缓存文件多了，，，redis也扛不住，cpu经常100%
