### ISSUE TITLE
使用其它模版出现未登陆提示

### ISSUE THREAD

**Issue by linqgang** [magicblack/maccms10#579]
第三方模版修改保存时提示没有登陆

**Comment by linqgang** [comment]
> 第三方模版修改保存时提示没有登陆
大佬们，看看是什么原因，之前很正常

**Comment by magicblack** [comment]
有些站点升级到50+版本之后，在后台部分自定义菜单有第三方模板配置、插件配置的时候提示未登录【是因为模板作者没有正确判断登录后台状态】会导致伪造cookie直接攻击，请立刻删除模板配置管理文件，避免被共计。 请自行联系模板作者升级修复！！！
