### ISSUE TITLE
文章入库问题

### ISSUE THREAD

**Issue by moyan73807** [magicblack/maccms10#58]
火车头采集入库不支持html代码入库吗？
我入库的结果就变成了这样了

https://s2.ax1x.com/2019/09/30/uYBnk4.png
https://s2.ax1x.com/2019/09/30/uYB2NQ.png
https://s2.ax1x.com/2019/09/30/uYBgAg.png

**Comment by moyan73807** [comment]
后台分页内容显示没有  但页面又有文字

**Comment by magicblack** [comment]
百度编辑器 编辑时会自动改变html标记， 可以点击 html 查看代码。 或者 直接进入数据库 查看是否正确。

**Comment by moyan73807** [comment]
> 百度编辑器 编辑时会自动改变html标记， 可以点击 html 查看代码。 或者 直接进入数据库 查看是否正确。

HTML代码查看 结果 没内容。。。   https://s2.ax1x.com/2019/09/30/uYBgAg.png
