### ISSUE TITLE
邮箱验证依然不行~

### ISSUE THREAD

**Issue by tangshaochun666** [magicblack/maccms10#581]
刚刚测试了一下邮箱验证，还是老问题，之前后台还可以测试发布成功，现在前后端都无法发送验证邮件

后台测试：测试失败：发生错误：SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
前端测试：验证码发送失败：发生错误：SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by tangshaochun666** [comment]
我是下载的最新的，然后更新包也用过了，依然还是不可以

**Comment by magicblack** [comment]
进入邮件配置： phpmailer选型卡 ， 更改一下传输协议改为 TSL ， 如果不行就切换到SSL， 不要留空。然后点击测试。

**Comment by tangshaochun666** [comment]
感谢作者，作者辛苦~~TSL可以了，没问题了，SSL暂时不行，期待后续更新
