### ISSUE TITLE
升级到最新版时，数据库脚本执行失败。

### ISSUE THREAD

**Issue by chengzf** [magicblack/maccms10#584]
升级到最新版时，数据库脚本执行失败。

发现数据库升级脚本文件，正在处理...
ALTER TABLE `mac_website` ADD `website_pic_screenshot`  text  DEFAULT  ''    ---失败

ALTER TABLE `mac_art` ADD `art_pic_screenshot`  text DEFAULT  ''    ---失败

ALTER TABLE `mac_vod` ADD `vod_pic_screenshot`  text  DEFAULT  '';    ---失败

**Comment by magicblack** [comment]
新的升级包已经修复，从新下载升级包覆盖，然后执行数据库升级。
或者手动执行sql：
ALTER TABLE mac_website ADD website_pic_screenshot text;
ALTER TABLE mac_art ADD art_pic_screenshot text ;
ALTER TABLE mac_vod ADD vod_pic_screenshot text;
