### ISSUE TITLE
打开后台页面404

### ISSUE THREAD

**Issue by hoa1999** [magicblack/maccms10#585]
我的苹果是V10  有3个月没登录后台了  具体是什么版本我也不太清楚了。。

我登录修改后的后台地址提示  404   如果我把后台文件改为 admin.php  他提示必须改成其他文件名字才可以访问。

我改成其他文件  又提示404

我的宝塔自定义伪静态规则是官方的 如下：

location / {
 if (!-e $request_filename) {
        rewrite ^/index.php(.*)$ /index.php?s=$1 last;
        rewrite ^/admin.php(.*)$ /admin.php?s=$1 last;
        rewrite ^/api.php(.*)$ /api.php?s=$1 last;
        rewrite ^(.*)$ /index.php?s=$1 last;
        break;
   }
}

除了后台不能登录404以外  其他都正常  搜索页面能用   分类伪静态 也可以用

**Comment by magicblack** [comment]
规则里的admin.php 地应该为你自己的文件名就可以了 
录入rewrite ^/admin222.php(.)$ /admin222.php?s=$1 last;
