### ISSUE TITLE
缓存和session同时使用memcached或者redis的时候，更新缓存会导致所有登陆退出包括后台。

### ISSUE THREAD

**Issue by kkdysite** [magicblack/maccms10#586]
php配置使用memcached或者redis管理session的话。
如果maccms的缓存也同时使用。
maccms的清理缓存功能，会导致session丢失。

session使用memcached 缓存使用redis，或者反过来 都没有这个问题。
但是因为memcached不支持持久化，还是希望只使用redis。希望能改进。

**Comment by magicblack** [comment]
目前好办法，建议session用文件存储。 不影响性能。
