### ISSUE TITLE
最新版两个小bug

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#590]
1、前台调用播放数据obj.vod_play_list时，key不按顺序走，而是跟着sid了
![1](https://user-images.githubusercontent.com/55046423/108616817-ffeca480-744b-11eb-816b-40b786d470a3.png)

2、视频数据页面的下载翻译出了个小错，下载1、下载2翻译成了踩1、踩2，哈哈哈~
![2](https://user-images.githubusercontent.com/55046423/108616832-2f9bac80-744c-11eb-92cd-d0d9a6dc3995.png)

**Comment by magicblack** [comment]
1，看下播放器管理中每个播放器顺序号，然后看下是否开启全局排序。
2，修复。

**Comment by lixuehan1234** [comment]
问题1我看了，有开启全局排序的，并且为了防止出问题我又重新设置了一下，仍然如此。
其实调用出来的播放数据顺序是对的，是按播放器序号进行排序的，只是key的值没有重新排序，还是按添加的顺序排列的序号，还是跟sid相等

**Comment by magicblack** [comment]
系统本身就是这么设计的~~~没毛病~~需要自定义key，可以嵌入php代码 $i++;来计数
