### ISSUE TITLE
上传截图后没有自动填写地址

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#591]
如图，上传完截图后并没有自动填写地址，也没法获得已上传的截图地址
麻烦作者大人处理一下

![3](https://user-images.githubusercontent.com/55046423/108620202-806bcf00-7465-11eb-8276-b03fd36c6165.png)

**Comment by lixuehan1234** [comment]
且手动进行填写手，保存后再打开此视频进行编辑，截图都无法正常显示
![4](https://user-images.githubusercontent.com/55046423/108621060-59b09700-746b-11eb-963e-706dd98cbde8.png)

**Comment by magicblack** [comment]
你那边是升级的吗，应该没有升级数据库脚本。

**Comment by lixuehan1234** [comment]
是正常升级的，数据库部分是正常的。
定位到了问题，大神可以看一下。

application\admin\view\vod\info.html

1、上传完成没有自动填写地址的问题在576行，当前只判断了文本框里有值的情况才增加地址，没有判断原本文本框为空的情况
2、图片不正常显示的问题在310行，没有加mac_url_img处理图片地址

麻烦作者大人处理一下吧~

**Comment by magicblack** [comment]
已处理
