### ISSUE TITLE
怎么自动推送链接给百度

### ISSUE THREAD

**Issue by 2757227663** [magicblack/maccms10#593]
定时任务怎么设置自动推送链接给百度

**Comment by magicblack** [comment]
程序包内说明文档里有的
5，网址推送
执行文件：选择 网址推送urlsend

附加参数：
百度主动推送当天视频 ac=Baidu&limit=50&page=1&ac2=today&mid=1
百度主动推送当天文章 ac=Baidu&limit=50&page=1&ac2=today&mid=2
百度主动推送当天专题 ac=Baidu&limit=50&page=1&ac2=today&mid=3
百度主动推送当天演员 ac=Baidu&limit=50&page=1&ac2=today&mid=8
百度主动推送当天角色 ac=Baidu&limit=50&page=1&ac2=today&mid=9

百度快速推送当天视频 ac=Baidufast&limit=10&page=1&ac2=today&mid=1
百度快速推送当天文章 ac=Baidufast&limit=10&page=1&ac2=today&mid=2
百度快速推送当天专题 ac=Baidufast&limit=10&page=1&ac2=today&mid=3
百度快速推送当天演员 ac=Baidufast&limit=10&page=1&ac2=today&mid=8
百度快速推送当天角色 ac=Baidufast&limit=10&page=1&ac2=today&mid=9
