### ISSUE TITLE
注册sms发送频繁的bug

### ISSUE THREAD

**Issue by TianLanSky** [magicblack/maccms10#594]
application/common/model/User.php

` $where=[];
        $where['user_id'] = $GLOBALS['user']['user_id'];
        $where['msg_time'] = ['gt',$stime];
        $where['msg_type'] = ['eq', $param['type'] ];
        $res = model('msg')->infoData($where);
        if($res['code'] ==1){
            return ['code'=>9002,'msg'=>'请不要频繁发送'];
        }`

因为注册的时候是游客，user_id==0，所以上一个游客获取验证码后，下一个游客会受影响而频繁

建议在数据库中检查重复数据的时候，加上字段 msg_to
`$where['msg_to'] = ['eq', $param['to'] ];`

**Comment by magicblack** [comment]
已采纳
