### ISSUE TITLE
关于功能用不了的反馈，望修复

### ISSUE THREAD

**Issue by 791813752** [magicblack/maccms10#6]
在后台-采集-自定义采集功能用不了，就是类似于火车头的那个功能用不了，我点击保存提示错误代码：SQLSTATE[HY000]: General error: 1364 Field 'page_base' doesn't have a default value，如果套了CDN，则会提示502源错误，望修复一下

**Comment by magicblack** [comment]
需要修改你数据库的配置文件一般在MYSQL 安装目录中的my.ini中 搜索sql-mode
sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
 把其中的STRICT_TRANS_TABLES,去掉 建议使用该方法
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
或者把
sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" 直接删除
############################################
