### ISSUE TITLE
Player.js加密问题

### ISSUE THREAD

**Issue by BloveDawn** [magicblack/maccms10#60]
不知这个核心文件为什么有加密的必要。
之前的发行版本解密后发现它加载了路径为union.maccms.com/html/top10.js的js，但是在六月份左右此文件中被添加了广告代码，导致苹果CMS全线跳广告
您可以处理一下这个加密的问题吗？

**Comment by magicblack** [comment]
没有问题不必在意。 6月份是域名被盗了。 官方是不会放广告的。

**Comment by BloveDawn** [comment]
明白了，感谢老王！愿您做的产品越来越好
