### ISSUE TITLE
程序版本 2020.1000.1068无法执行定时任务

### ISSUE THREAD

**Issue by xx599** [magicblack/maccms10#600]
程序版本 2020.1000.1068还是无法执行定时任务，目前只有 版本2020.1000.1042会执行。

**Comment by magicblack** [comment]
具体操作和返回信息是什么，具体描述

**Comment by xx599** [comment]
没有具体的报错，就是不执行定时任务，设置好后，退出后台，到了时间，不执行










|
金沙网络客服
lzw_137@163.com
公司名称：金沙网络科技发展有限公司
网址：http://6322.taobao.com
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|




在 2021-03-06 09:27:36，"magicblack" <notifications@github.com> 写道：

具体操作和返回信息是什么，具体描述

**Comment by magicblack** [comment]
定时任务需要第三方服务 定时请求触发~~~ 宝塔定时任务，或者其他第三方

**Comment by isold23** [comment]
> 定时任务需要第三方服务 定时请求触发~~~ 宝塔定时任务，或者其他第三方

crontab 不能搞定吗
