### ISSUE TITLE
使用cms版本2020.1000.1067升级老版本后大橙子主题vfed出现问题

### ISSUE THREAD

**Issue by lijinlong2baby** [magicblack/maccms10#605]
后台进入大橙子主题设置 修改设置点保存显示未登录，求救！！！

**Comment by lijinlong2baby** [comment]
[Uploading maccms10-2020.1000.1069.tar.gz…]()

**Comment by lijinlong2baby** [comment]
![微信截图_20210308171547](https://user-images.githubusercontent.com/47732238/110300700-24db3d00-8032-11eb-8126-2d60dddaaed9.png)

**Comment by lijinlong2baby** [comment]
升级到2020.1000.1069还是这样，使用手机UC浏览器可以保存，电脑端所有浏览器都不行，换别的电脑也不行

**Comment by 2757227663** [comment]
只支持老版本

**Comment by magicblack** [comment]
第三方模板制作未采用系统内置的登录验证，自己写的有问题。 请自行处理。
