### ISSUE TITLE
后台>视频>批量操作视频 “参数错误”

### ISSUE THREAD

**Issue by roythia** [magicblack/maccms10#607]
**v10 版本号为2020.1000.1067**

![image](https://user-images.githubusercontent.com/48576069/110331904-a5ae2f00-805a-11eb-8a37-f3bf7874ab86.png)

**Comment by magicblack** [comment]
具体选择的什么内容~~点击的哪个按钮

**Comment by roythia** [comment]
点击“批量操作视频”的菜单按钮就出现参数错误。

**Comment by magicblack** [comment]
最新版本测试没有发现此问题。请下载离线升级包覆盖下试试。
