### ISSUE TITLE
附件图片使用FTP存储，本地服务器没有留存影视图片

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#609]
使用FTP存储，采集新影片，图片上传到了FTP存储上面，但本地服务器没有图片留存，请问怎么让本地也有图片留存？如果FTP储存挂掉，本地又没有留存图片，那不是悲剧了

**Comment by ycgz2008** [comment]
以前数据自己按照以前的方法已解决！

现在出现的问题是，采集新数据显示远程图片采集上传成功，但远程服务器上面没有上传成功的图片

**目前需要解决的问题是：**

1，采集新数据显示图片上传成功，但影视图片是空白，查看远程服务器上面没有上传成功的图片，远程服务器使用的宝塔面板，安装的ftp，还以为是目录权限问题，直接设置为777，还是不行

2，使用FTP存储，比如：采集一个新影片，影片图片应该是本地保存一份，远程ftp服务器也保存一份，远程服务器失效，自己可以后台直接切换本地。目前的情况是采集新影片，本地没有图片，直接上传到远程ftp服务器了，不知道是不是这个功能还不是很完善的问题或者是存在bug，还请大佬修正

**Comment by magicblack** [comment]
使用远程存储或第三方存储本地不留存文件，FTP存储也一样。 自行定时备份。
