### ISSUE TITLE
想做漫画站问题求解答

### ISSUE THREAD

**Issue by a1642997310** [magicblack/maccms10#614]
最近想尝试用苹果cms建个漫画站
能不能实现点击详情页视频集数链接到文章页地址的功能，这样可以把程序当成漫画程序用了。希望老大考虑一下

**Comment by magicblack** [comment]
编辑数据时填写   关联文章， 关联视频字段 即可实现。
标签文档里搜索   获取与当前视频相关联视频和关联文章数据
