### ISSUE TITLE
积分购买BUG提交

### ISSUE THREAD

**Issue by a1642997310** [magicblack/maccms10#615]
版本：最新版

 问题：1、当账户积分不足购买时点击马上购买，显示已购买过，而不是提示积分不足
![360截图20210314134532268](https://user-images.githubusercontent.com/56704086/111058820-ff628f00-8488-11eb-9865-26f08b718a61.jpg)

2、手机端中confirm.html页的用户登录判断不能用（即使没登录也是显示马上冲值和确认购买按钮，而不是马上登录。电脑端则可以实现未登录状态下显示马上登录按钮）模板为wap默认模板

**Comment by magicblack** [comment]
1已经确认修复。
2，直接使用默认pc端模板里的confirm.html 覆盖到 wap模板里即可。通用的
