### ISSUE TITLE
文章正文中的中文文件名图片无法同步

### ISSUE THREAD

**Issue by wangsclub** [magicblack/maccms10#620]
我使用的是WIN主机，安装的版本为V10 v2020.1000.1069版本，故障描述：
1、文章分为两页，如果第二页不包含图片，则第一页包含的图片无法同步，进行详情图片同步时，直接跳转到同步完成提示。
2、文章正文远程图片文件名为**249_東海市立横須賀中学校.jpg**，同步后变成**3193450f0dc56204550a269c9888673c.jpg東海市立横須賀中学校.jpg**，图片文件错误！同样，**2361_seihuku2_(2).jpg**，同步后变成了**e5b85d041ad0b46721c3f84305663c05.jpg(2).jpg**！
谢谢您的帮助！

**Comment by magicblack** [comment]
试试72版本已经修正了分析内容图片正则

**Comment by wangsclub** [comment]
您好！我测试了一下，目前正常！另外，还有一个问题需要咨询一下：如果正文中含有object，embed 或者iframe标签，则同步的时候会进入死循环，图片链接会反复添加斜杠/，图片链接会形如<img src="////////////////upload/..........
谢谢！

**Comment by magicblack** [comment]
已经做了一些调整稍后试试
