### ISSUE TITLE
关联视频和关联文章如何调用名称，而不是ids

### ISSUE THREAD

**Issue by linkala** [magicblack/maccms10#622]
`<h2>与<strong>“{$obj.vod_name}”</strong>关联的视频</h2>
<ul class="img-list dis">
    {maccms:vod num="6" ids="'.$obj['vod_rel_vod'].'" order="desc" by="time"}
        <li><a href="{:mac_url_vod_detail($vo)}" title="{$vo.vod_name}"><img src="{:mac_url_img($vo.vod_pic)}" alt="{$vo.vod_name}"/><h2>{$vo.vod_name}</h2><p></p><i>{$vo.vod_version}</i><em></em></a></li>
    {/maccms:vod}
</ul>
<h2>与<strong>“{$obj.vod_name}”</strong>关联的文章</h2>
<ul class="img-list dis">
    {maccms:art num="6" ids="'.$obj['vod_rel_art'].'" order="desc" by="time"}
        <li><a href="{:mac_url_art_detail($vo)}" title="{$vo.art_name}"><img src="{:mac_url_img($vo.art_pic)}" alt="{$vo.art_name}"/><h2>{$vo.art_name}</h2><p></p><i>{$vo.vod_from}</i><em></em></a></li>
    {/maccms:art}
</ul>`
如题，上面是默认官方的 关联文章 和 关联视频写法， 都是采用{$obj.vod_rel_vod} 或者 {$obj.vod_rel_art} 但是这写都是ids，想请教一下大佬如何调用名称，如变形金刚1的影片详细里相关视频“变形金刚”，相关资讯里面为“变形金刚”，下方采用标签则可出来变形金刚一二三，和含有变心金刚关键词的资讯呢？

**Comment by magicblack** [comment]
关联字段  可以填写名称 如  变形金刚。
调用标签把  ids=  改为 rel= 其他不变 。 
标签文档里搜索可见

**Comment by linkala** [comment]
好的 谢谢打咯

**Comment by linkala** [comment]
@magicblack 好的，谢谢王董。
