### ISSUE TITLE
建议:增加本地图片下载或者删除的开关，附件第三方FTP存储时，可以继续保存在本地，以防图片丢失

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#623]
建议:附件第三方FTP存储时，本地下载的图片也可以保存在本地，增加一个的开关设置，按需使用，可以继续保存在本地，以防图片丢失

**Comment by hkvcyber** [comment]
支持你,圖片本址一份,遠程一份,希望作者能加上這功能

**Comment by magicblack** [comment]
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/20452515/153556186-eb7f9967-15b1-43ed-abb5-c28670eed6e9.png">
已支持，下个版本发布。

**Comment by toooooop** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
