### ISSUE TITLE
1070 播放器删除失败

### ISSUE THREAD

**Issue by SAMSUNGO** [magicblack/maccms10#627]
目前发现是1905播放器无法删除，删除后更新缓存，播放器还是存在。
点击编辑 1905 播放器内容是空白的。
![image](https://user-images.githubusercontent.com/65321981/111963391-6be72900-8b2e-11eb-9536-0724dfb45064.png)

**Comment by magicblack** [comment]
不支持纯数字编码的。 有提示的 。 建议手工编辑配置文件 \application\extra\vodplayer.php   删除这个项。
