### ISSUE TITLE
添加mp4视频无法播放

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#628]
后台添加 第01集$http://soft.xiaoz.org/videos/test.mp4 前台无法播放
后台的dplayer【还是无法播放mp4】 videojs【中文名称问题，已测试videojs播放器可以播放】 其他的都试了，无法播放，是不是要设置一下？

**Comment by xx599** [comment]
播放器的问题，不是苹果cms的问题，另外，既然videojs能播放，干嘛不用？有强迫症？

**Comment by ycgz2008** [comment]
> 播放器的问题，不是苹果cms的问题，另外，既然videojs能播放，干嘛不用？有强迫症？

videojs不能自动下一集，不带记忆功能，右键不知道怎么去除

**Comment by magicblack** [comment]
自行整合播放器
