### ISSUE TITLE
关于伪静态路由的问题

### ISSUE THREAD

**Issue by xx599** [magicblack/maccms10#629]
目前测试到，
一、路由开启以后，选择加密ID，就会导致分类页下面无法获取到分类数据，改成数字ID即可显示。（PS：因无法获取分类数据，导致筛选时会提示“没有权限访问该数据”，但该分类是给了权限的）
二、之前提过的试看功能，也是因为开启了加密ID，才导致无法使用试看框架。

所以，希望老王不忙的时候可以修复一下。

**Comment by xx599** [comment]
我就不建新帖子了，浪费资源，再提一个建议，
目前“系统”-“网站参数配置”-“性能优化”里，搜索间隔时间那里，希望可以修复为全局强制限制，
因为目前设置时间后，如果前台搜索的时候，只要更换了搜索词，就可以无视后台的这时间限制，一直都可以搜索，所以，请修复一下

**Comment by magicblack** [comment]
问题1可tg反馈下，在你的场景下重现解决；
问题2无法重现，换关键词依然受间隔时间限制。
