### ISSUE TITLE
邮箱注册重复

### ISSUE THREAD

**Issue by shifuf** [magicblack/maccms10#63]
突然发现了一个问题，在好久之前在QQ反馈过。后才得知QQ已不在使用。具体原因就是：注册的时候填写邮箱的时候，数据库原先已经有填写过的邮箱，然后已经也可以进行。就是邮箱重复了，依旧可以注册。不提示邮箱已注册

**Comment by magicblack** [comment]
邮箱是需要在用户中心里绑定的，注册点时候填写点那个没用吧啊

**Comment by shifuf** [comment]
注册的时候填写邮箱，在用户中心里面显示已经绑定了的。注册新的用户填写已注册过的邮箱不提醒邮箱已注册，会直接绑定到新注册的账户 原注册账户会自动解绑.......即使在用户中心里面绑定了邮箱。在注册的时候填写该邮箱依旧可以使用该邮箱注册.....一个邮箱可以反复的注册。您那边可以进行测试一下！

**Comment by magicblack** [comment]
已经做了微调，注册的时候会判断是否已经有用户使用了邮箱，否则不让注册。
