### ISSUE TITLE
站群配置修改建议

### ISSUE THREAD

**Issue by freeporm** [magicblack/maccms10#631]
站群配置中应该有两个自定义项目增加修改
第一个是增加LOGO所在位置，可以自定义不同网站域名所对应的网站logo，现在不同的域名网站全都使用原始网站logo这明显无法体现不同网站。
第二个是网站地图和统计代码配置，不同的网站应该有不同的预留头部或者底部代码位置，加载自定义网站地图路径代码和相应的统计代码或者广告代码，体现出不同网站的特性。

**Comment by magicblack** [comment]
建议你在模板中采用当前域名的方式来保存相关文件。调用方法直接在模板里写好就可以了。自动根据域名访问对应文件。
例如域名a.cn 
<img src="/images/<?php echo $_SERVER['HTTP_HOST']; ?>.png" />
<script src="/tj/<?php echo $_SERVER['HTTP_HOST']; ?>.js"></script>
那么解析出来的结果就是 


  <img src="/images/a.cn.png" />
   
 <script src="/tj/a.cn.js"></script>

**Comment by freeporm** [comment]
好的，明白了，感谢
