### ISSUE TITLE
剧情怎么调用下一集的剧情？

### ISSUE THREAD

**Issue by lsj5492** [magicblack/maccms10#633]
剧情怎么调用下一集的剧情？

**Comment by magicblack** [comment]
参考标签文档，传入页码参数
=======视频分集剧情页独有标签=======   
{$obj['vod_plot_list'][$param['page']]['name']} 分集剧情名称
{$obj['vod_plot_list'][$param['page']]['detail']} 分集剧情详情

mac_url_plot_detail($obj,['page'=>1])  分集剧情详情页地址
mac_url_plot_index()  分集剧情首页，建议放一些热门剧包含剧情分类的数据
mac_url_vod_plot($obj)   某个视频的分集剧情列表
