### ISSUE TITLE
PHP 8  implode(): Argument #2 ($array) must be of type ?array, string given

### ISSUE THREAD

**Issue by ChasLeung** [magicblack/maccms10#634]
PHP 8 安装提示implode(): Argument #2 ($array) must be of type ?array, string given

**Comment by magicblack** [comment]
已修复~等待更新即可。

**Comment by WangXing0801** [comment]
大哥，，现在都2023年了。。php8.2 install报 类型错误: implode(): Argument #2 ($array) must be of type ?array, string given
。。。。。。。
