### ISSUE TITLE
会员组功能咨询求解答

### ISSUE THREAD

**Issue by a1642997310** [magicblack/maccms10#637]
老王v10有没有v8的特定会员组可见功能(
v10设置会员组权限只能限制访问权限，不能隐藏资源)
如果有请问在哪里设置，若果没有希望下个版本能不能考虑加一下谢谢

**Comment by magicblack** [comment]
v10权限和数据分离，实现隐藏资源比较麻烦~

**Comment by magicblack** [comment]
试试开启 系统 - 网站参数配置 - 性能优化 - 数据权限过滤。
