### ISSUE TITLE
开启广告后网站显示require(): Failed opening required 

### ISSUE THREAD

**Issue by wohawohaa** [magicblack/maccms10#644]
开启广告后网站一直显示require(): Failed opening required './addons/farad/html/farad1.html' (include_path='.:/www/server/php/71/lib/php')
![图片](https://user-images.githubusercontent.com/47924441/114180570-ed361c80-9972-11eb-8926-e505a7c97525.png)

**Comment by magicblack** [comment]
插件问题，请联系插件作者。

**Comment by wohawohaa** [comment]
> 
> 
> 插件问题，请联系插件作者。

好的
