### ISSUE TITLE
苹果CMS本地化图片的生成路径怎么修改？

### ISSUE THREAD

**Issue by hoa1999** [magicblack/maccms10#646]
从资源站采集来的图片是远程的。。然后我选择全部本地化。。

苹果CMS10 会自动生成这样的图片路径。。

/upload/vod/20210412-1/xxxxxxxxx.jpg     请问我怎么自定义这个路径？？

比如我要修改成

/1/2/3/日期/xxx.jpg 类似这样的。。。

**Comment by magicblack** [comment]
目前不支持
