### ISSUE TITLE
采集参数配置里的地址二更规则，对下载链接无效

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#648]
采集参数配置里的地址二更规则，设置成“合并”时，只对播放地址有效，下载地址无效，依然会直接替换
看了下源码，源码里也仅仅对采集播放地址的时候进行了判断和处理，下载地址的部分没有进行处理
麻烦作者大人修复一下吧

**Comment by lixuehan1234** [comment]
不知道作者大人会不会处理一下这个问题呢

**Comment by magicblack** [comment]
采集参数配置 - 二次更新规则，勾选下载地址。
