### ISSUE TITLE
v10，百度熊掌号的token无法成功保存

### ISSUE THREAD

**Issue by aliyun01** [magicblack/maccms10#649]
其他内容可以保存，但是，将token粘贴到输入框后，点击保存，刷新，就会显示其他内容了。是咋回事？
是后台程序不支持最新的熊掌号的格式吗，校验不通过吗？急！

**Comment by magicblack** [comment]
具体是哪个页面，截图看看。我看别人是能正常保存的，如果有问题反馈到tg实时看下吧
