### ISSUE TITLE
关于会员相关问题

### ISSUE THREAD

**Issue by waijutv** [magicblack/maccms10#65]
关于会员相关问题
目前会员功能不完善
网站几万会员 账号不记得 无法通过其他途径帮助用户找回

1、希望后台搜索 可以选择 按相关标签搜索 （比如用户资料中的手机号、邮箱号等）
2、后台用户自定义昵称，增加前台昵称显示（或提供标签），目前后台用户可以编辑昵称却无法调用。
3、希望增加用户邀请码机制，通过邀请码邀请来注册的 可以指定给与积分

目前就这些，也是急需解决的

**Comment by magicblack** [comment]
以上内容v10均已经支持。请详细查看程序说明，多熟悉程序功能。
