### ISSUE TITLE
用户上传头像的返回值一下显示为“返回数据格式不正确”

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#656]
用户上传头像的返回值一下显示为“返回数据格式不正确”，不知道是什么原因造成的

**Comment by magicblack** [comment]
模板中提交头像文件或格式不对吧。

**Comment by lixuehan1234** [comment]
> 模板中提交头像文件或格式不对吧。

是正常的图片格式，jpg和png都试过，都会显示这个错误提示，不知道什么原因

**Comment by magicblack** [comment]
F12查看下接口有没有返回其他字符串。
