### ISSUE TITLE
关于版权处理功能的小建议

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#660]
视频开启版权处理，后台设置为“内容页跳转”或者“iframe播放页跳转”时，必须要设置了跳转url才会成功跳转，但是设置为播放页跳转的时候，却没有这个限制。
个人觉得不需要设置跳转url就显示版权页的形式更合理，因为可以直接在copyright模板页自行控制，而不是强制要求有跳转url才能显示版权。

**Comment by magicblack** [comment]
可以自行根据详情页 $obj['vod_copyright'] 来判断载入显示内容。

**Comment by lixuehan1234** [comment]
> 可以自行根据详情页 $obj['vod_copyright'] 来判断载入显示内容。

我明白的，我的意思是，能否把跳转url不能为空这个限制去掉，这样只要三种跳转情况就统一了，只要开启了版权处理就会调用copyright模板页，这样直接在copyright模板里自行控制也更合理，逻辑也一致

**Comment by magicblack** [comment]
处理了，跳转链接允许为空了。这两天打包升级。
