### ISSUE TITLE
通过苹果CMS后端开发APP及模板是否允许？

### ISSUE THREAD

**Issue by daniel3160636** [magicblack/maccms10#663]
因为业务需要，我们自己开发模板及APP前端，这个修改过程中会修改相应的参数及函数，请问作者，这个允许吗？
我看很多的模板都是自己开发的，不知道他们是否经过作者允许~

**Comment by owenkeyi** [comment]
本身开源的，那他开发APP跟模板的多了！作者信息保留就好！

**Comment by magicblack** [comment]
可以的php程序里的版权信息不要修改即可。
