### ISSUE TITLE
作者有人二次修改苹果cms，进行贩卖怎么处理

### ISSUE THREAD

**Issue by YANYUxs** [magicblack/maccms10#664]
作者有人二次修改苹果cms，进行贩卖怎么处理
![Screenshot_20210518-193954](https://user-images.githubusercontent.com/66113294/118647641-24baa300-b814-11eb-823b-764f3a73de2d.jpg)
![Screenshot_20210518-200401_Samsung Internet](https://user-images.githubusercontent.com/66113294/118647743-4156db00-b814-11eb-9d5b-d5e2c0d31aa2.jpg)

**Comment by 8108905** [comment]
看来你是真的很嫉妒对方哈

**Comment by 8108905** [comment]
开源项目 ，你也可以二次开发销售！

**Comment by magicblack** [comment]
收集证据可以随意发律师函
