### ISSUE TITLE
作者你好，可以增加虎皮椒支付吗？谢谢！

### ISSUE THREAD

**Issue by 8108905** [magicblack/maccms10#665]
https://www.xunhupay.com/

苹果cms。内置 码支付 幻汐支付 都不支持https ，最最主要是国外根本无法访问该网站 @magicblack 
请问下作者的TG 联系方式 是什么？ 有TG群吗 ？》 谢谢

**Comment by magicblack** [comment]
可以参考做一下二次开发。
