### ISSUE TITLE
使用mac_url生成url的时候，能否不对特定页面进行参数限制呢

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#666]
使用mac_url生成url的时候，能否不在特定页面进行参数限制呢？
比如topic/index页面，生成url的时候设置的参数只有page参数有效，其他的所有参数都无效。
还有其他的很多页面都有这个限制，这个限制感觉不是很必要，能否取消呢，这样就可以在topic/index也自行设置排序方式了

**Comment by jclser** [comment]
common.php自己改，如果不懂，那就学习吧，大佬是不会回答你这种问题的。

**Comment by magicblack** [comment]
mac_url('topic/index',['page'=>$param['page'],'aa'=>'new']);
自己加参数
