### ISSUE TITLE
开启会员后，actor访问提示权限不够

### ISSUE THREAD

**Issue by jclser** [magicblack/maccms10#667]
默认路由actor/show是没有ID的，所以当开启会员模块后，访问会被提示访问权限不足！
原因是check_user_popedom($info['type_id'], 1); 为空

**Comment by magicblack** [comment]
修改下路由规则加上id部分就可以了。
actorshow/<id>-<area?>-<blood?>-<by?>-<letter?>-<level?>-<order?>-<page?>-<sex?>-<starsign?>   => actor/show

**Comment by jclser** [comment]
还是要加ID吗，还以为您有更好的解决方案呢。另{:mac_url_vod_play($obj,'first')}在type,show中也只能得到sid=1这点也不好，如果我的sid为1的播放器没启用的话。collect_filter也会采到空的播放组
