### ISSUE TITLE
采集配置tag问题

### ISSUE THREAD

**Issue by xingchenwl** [magicblack/maccms10#67]
王哥，现在cms采集生成的tag没有字数限制，总是出错，能不能优化下，vod_tag这个字段设置成255都不够用

**Comment by magicblack** [comment]
可以修改一下mysql点配置项目，关闭强验证就可以了。
SQLSTATE22001: String data, right truncated: 1406 Data too long for column ’’ at row 1 或者 Warning: 1265 Data truncated for column 类似错误**
RE:############################################
该错误就插入字段长度超过设定的长度，一般程序会在数据库字段设置字符长度在插入之前程序很少会先判断数据长度和截取数据 这样会影响性能，所以你就需要修改你数据库的配置文件一般在MYSQL 安装目录中的my.ini中 搜索sql-mode
sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
把其中的STRICT_TRANS_TABLES,去掉 建议使用该方法
sql-mode=“NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”
或者把
sql-mode=“STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION” 直接删除
############################################
