### ISSUE TITLE
生成wap首页的定时任务参数怎么写？

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#670]
生成wap首页的定时任务参数怎么写？
我这里写成：ac=index&ac2=wap  
怎么生成的是pc端首页html，求哪位大咖指导一下

**Comment by klmahua** [comment]
顶一下，，，知道的大咖指导一下

**Comment by klmahua** [comment]
求助，，，没人知道吗

**Comment by magicblack** [comment]
没毛病就是这个参数

**Comment by klmahua** [comment]
> 
> 
> 没毛病就是这个参数
但是手动执行这个定时任务和自动定时任务一直生成的pc端静态页面。。。如果不走定时任务,直接生成wap首页。，。。这样生成的wap静态首页，。，，是哪里的程序有问题吗
