### ISSUE TITLE
20数据，cpu经常100%下不来， mysql 很多 like ‘%%’的慢查询。  

### ISSUE THREAD

**Issue by jackrebel** [magicblack/maccms10#677]
数据20W， 服务器配置：8H16G，   cpu经常100%下不来， mysql 很多 like ‘%%’的慢查询。  

开启了缓存redis， opcache装了， 首页、详情页面全是静态化了。 

搜索规则： 只启用了“视频名称”搜索。 

mysql中很多很多like的慢查询， 这个怎么解决？    我能不能直接改代码， 将所有like语句改成 ‘视频名%’ 之类的， 或者直接改成"="号， 不再支持like搜索？  有哪个大侠试过吗？

**Comment by magicblack** [comment]
你可以把  like 'a%' 改成  like 'a%'  这样会走索引。

**Comment by jackrebel** [comment]
> 你可以把 like 'a%' 改成 like 'a%' 这样会走索引。

我改了 
1.   application/common.php   1101行的， mac_like_arr 方法。 
2.   application/api/controller/Provide.php  中的  $where['vod_name'] = ['like', '' . $this->_param['wd'] . '%'];
3.   application/index/controller/Ajax.php 中的suggest方法，  $where[$pre.'_name|'.$pre.'_en'] = ['like',''.$wd.'%'];

为什么前台还是有很多like ‘%片名%’ 的慢查询， 我全局搜索， 貌似已经没有调用的地方了。  请问我漏了什么吗？

**Comment by aruoop** [comment]
慢查询很耗资源，经常CPU占满，查看都是mysql占用

**Comment by klmahua** [comment]
这样改治标不治本。。。查询出的数据是不一样的

**Comment by magicblack** [comment]
全文索引版本我们已经开发完毕了，由于近期遇到 com域名被盗问题，近期不会发布避免被盗用。

**Comment by jackrebel** [comment]
> 全文索引版本我们已经开发完毕了，由于近期遇到 com域名被盗问题，近期不会发布避免被盗用。

期待！ 加油~！

**Comment by magicblack** [comment]
#549

**Comment by 1195999342** [comment]
> 全文索引版本我们已经开发完毕了，由于近

全文索引版本呢？ 已经支持了嘛

**Comment by 1195999342** [comment]
我不太懂php 先这样改了 有懂的来优化一下嘛
		
		新增索引
		ALTER TABLE `mac_vod` ADD FULLTEXT INDEX (vod_actor) WITH PARSER `ngram`;
		ALTER TABLE `mac_vod` ADD FULLTEXT INDEX (vod_name) WITH PARSER `ngram`;
		ALTER TABLE `mac_vod` ADD FULLTEXT INDEX (vod_director) WITH PARSER `ngram`;
		ALTER TABLE `mac_vod` ADD FULLTEXT INDEX (vod_name, vod_sub, vod_en)  WITH PARSER `ngram`;
		
		
		application/common/model/Vod.php:460
		`// 不开启搜索优化，使用默认条件
            if(!empty($wd)) {
                $where['_string'] = "MATCH(vod_name, vod_sub, vod_en) AGAINST ('" . $wd ."')";
            }
            if(!empty($name)) {
                $where['_string'] = "MATCH(vod_name) AGAINST ('" . $name ."')";
            }
            if(!empty($tag)) {
                $where['vod_tag'] = ['like',mac_like_arr($tag),'OR'];
            }
            if(!empty($class)) {
                $where['vod_class'] = ['like',mac_like_arr($class), 'OR'];
            }
            if(!empty($actor)) {
                $where['_string'] = "MATCH(vod_actor) AGAINST ('" . $actor ."')";
            }
            if(!empty($director)) {
                $where['_string'] = "MATCH(vod_director) AGAINST ('" . $director ."')";
            }`
		
		application/common/model/Vod.php:541
`        $order= 'vod_'.$by .' ' . $order;
        if(!empty($wd) || !empty($name) || !empty($actor) || !empty($director)) {
            $order = "";
        }`
