### ISSUE TITLE
升级后版本是2021.1000.1081 不是1099

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#679]
升级后版本是2021.1000.1081 
下载文件升级我看最新版本是1099

所以到底选择那个？
还是我升级后，还需要在下载1099版本进行覆盖

**Comment by magicblack** [comment]
这里下载的1080+都是安全可靠的。

**Comment by maccmspro** [comment]
这里下载的都是后门版本 去https://github.com/maccmspro 下载正版
