### ISSUE TITLE
不能使用memcached缓存方式

### ISSUE THREAD

**Issue by ws4liu** [magicblack/maccms10#68]
![image](https://user-images.githubusercontent.com/31585100/67137265-d07cc500-f264-11e9-974a-0a2c22d0ebd5.png)
![image](https://user-images.githubusercontent.com/31585100/67137199-f48bd680-f263-11e9-94fd-90e6c06d3404.png)
![image](https://user-images.githubusercontent.com/31585100/67137203-fce41180-f263-11e9-9d0a-7c4f436d6ba8.png)

测试
![image](https://user-images.githubusercontent.com/31585100/67137271-dd011d80-f264-11e9-92e0-bb6b40538e87.png)

**Comment by ws4liu** [comment]
![image](https://user-images.githubusercontent.com/31585100/67137244-94496480-f264-11e9-8b75-73ecf704650a.png) 测试

**Comment by magicblack** [comment]
memcache  和  memcached  是2个不同点支持库~  选择正确
