### ISSUE TITLE
站群功能不生效

### ISSUE THREAD

**Issue by otary** [magicblack/maccms10#681]
站群配置了2个站点，不知道域名需不需要加https://前缀？模版目录需要填吗？我试了多次，2个网址配置了不同的模版，但是访问都是访问到了主模版，请教要要怎么排查？

![QQ截图20210711211918](https://user-images.githubusercontent.com/3916327/125196798-bdf2bc80-e28d-11eb-934e-6554818bb2f5.png)

**Comment by magicblack** [comment]
只需要填写域名如  www.baidu.com  不需要前缀
