### ISSUE TITLE
v10采集v8接口数据不对还不更新数据 只能手动选中视频才会更新

### ISSUE THREAD

**Issue by skin007** [magicblack/maccms10#69]
v10采集v8接口数据不对还不更新数据 只能手动选中视频才会更新

**Comment by skin007** [comment]
接口是默认json 接口

**Comment by magicblack** [comment]
没明白什么意思呀。。。

**Comment by skin007** [comment]
就是说
我这cms是v10的最新版然后去采集v8的json 接口 获取的数据跟xml 数据不对 json 只有27页   xml却有40多页
然后就是json 点击今日更新  所有视频内容全部跳过 不更新播放地址

**Comment by magicblack** [comment]
v8 是否开启了 动态页面缓存，可以关闭试试。

**Comment by skin007** [comment]
已经查看无cdn 没有开启动态缓存
