### ISSUE TITLE
升级后的错误提示

### ISSUE THREAD

**Issue by chengzf** [magicblack/maccms10#691]
![QQ截图20210801183034](https://user-images.githubusercontent.com/13170156/127767720-25d6e74f-d8fe-4af4-9d67-1ea34fa8be1f.png)

如图，
升级1066版本时，遗留下来关于数据库脚本的错误提示（其实已通过手动更新了数据库），现在升级到最新版了，那个错误提示还在，有什么办法可以清理掉吗？

**Comment by magicblack** [comment]
直接点击进入升级数据库脚本 即可，会自动清理。 不影响已升级数据。

**Comment by chengzf** [comment]
> 直接点击进入升级数据库脚本 即可，会自动清理。 不影响已升级数据。

点过了，也提示升级成功了，但是这提示一直在。

**Comment by magicblack** [comment]
可以不用管，也可以手动删除 \application\data\update\database.php
