### ISSUE TITLE
管理，视频数据人气为什么一直是初始值，不论刷新多少下？

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#692]
管理，视频数据人气为什么一直是初始值，不论刷新多少下？模版中调用的增加人气的代码如下：
`<span style="display:none" class="mac_ulog_set" alt="设置内容页浏览记录" data-type="1" data-mid="{$maccms.mid}" data-id="{$obj.vod_id}" data-sid="{$param.sid}" data-nid="{$param.nid}"></span>`

各位大佬人气增加调用的代码没有问题吧

**Comment by magicblack** [comment]
系统自带的 home.js 是否在模板中引入。

**Comment by klmahua** [comment]
> 
> 
> 系统自带的 home.js 是否在模板中引入。

引入了、、、、切换到官方原来代的默认模版，访问人气也是不增加，，，不知道怎么回事

**Comment by klmahua** [comment]
> 
> 
> 系统自带的 home.js 是否在模板中引入。

问下模版中引入什么标签才能触发点击量增加？

**Comment by klmahua** [comment]
好吧，，，模版中要引入 `<span class="mac_hits hits" data-mid="{$maccms.mid}" data-id="{$obj.vod_id}{$obj.art_id}{$obj.topic_id}"" data-type="hits"></span>`  点击量才增加  但是看官方的标签说明文档，。，，明明这段代码说明是点击量显示标签
