### ISSUE TITLE
关于定时任务的一个奇怪现象

### ISSUE THREAD

**Issue by chengzf** [magicblack/maccms10#693]
最开始我使用定时任务是配合宝塔计划任务一起的，
后来有次CMS升级之后发现定时任务居然会自动执行，
于是我删除了宝塔里的设置，一切也都正常。
这次升级到最新版后（且换了一个新的服务器，源代码和数据库都是旧的），
定时任务就不自动执行了，
求解。

**Comment by magicblack** [comment]
1，要么在模板里加载调用代码。
2，要么在宝塔或其他第三方定时请求任务。
其他情况下不会自动触发
