### ISSUE TITLE
开启伪静态配置后，视频分类页点击跳转到首页(第一页)报错，麻烦看看呢

### ISSUE THREAD

**Issue by taylor0415** [magicblack/maccms10#694]
伪静态的配置用的默认配置：vod/show/<id>-<area?>-<by?>-<class?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<state?>-<tag?>-<year?>   => vod/show

当在视频分类页面选中其他类型如动作片或者年份语言地区等等，选中任何一个，然后点击分页的第2页后面的页数，然后再点击首页发现地址少了一个"-"，当在第二页的时候点击上一页也是一样少了一个"-"，导致页面不存在，麻烦帮忙看看怎么解决呢，谢谢

**Comment by taylor0415** [comment]
已处理，不知道对不对，不会php
调整了common.php里面的
![image](https://user-images.githubusercontent.com/3795318/128617108-3c1aeb66-2f94-40d3-bb2d-ccd3c2acf8a1.png)

**Comment by magicblack** [comment]
访问路径是什么呢，默认路由应该没毛病。 page是可选参数

**Comment by taylor0415** [comment]
就是用的默认的这个路由   vod/show/-<area?>-<by?>-<class?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<state?>-<tag?>-<year?> => vod/show
