### ISSUE TITLE
新搭建后台页面404

### ISSUE THREAD

**Issue by dongkid** [magicblack/maccms10#697]
最新版本cms v10
宝塔版本7.x php版本7.0 已关闭PATH_INFO 权限全部777 已使用官方的伪静态配置并修改admin.php
location / {
 if (!-e $request_filename) {
        rewrite ^/index.php(.*)$ /index.php?s=$1 last;
        rewrite ^/admin222.php(.*)$ /admin222.php?s=$1 last;
        rewrite ^/api.php(.*)$ /api.php?s=$1 last;
        rewrite ^(.*)$ /index.php?s=$1 last;
        break;
   }
}

**Comment by magicblack** [comment]
需要开启 pathinfo 。admin22.php 改为自定义后台文件名。

**Comment by dongkid** [comment]
解决了，谢谢！

**Comment by dongkid** [comment]
解决了，谢谢！
