### ISSUE TITLE
管理后台表单存在xss漏洞

### ISSUE THREAD

**Issue by UiGit** [magicblack/maccms10#698]
![QQ截图20210814205144](https://user-images.githubusercontent.com/35055114/129446957-05563e7f-4a01-4106-bde1-3f37c5d1e320.jpg)

在后台系统配置里任何表单输入框都可以写入：
```
"><img/src=1 onerror=alert('xss')>
```

可以配合csrf 拿管理员session登录状态

**Comment by magicblack** [comment]
已经进入到后台了，还拿什么管理员session？ 多此一举吧。
不过这个问题我们会修复的。
