### ISSUE TITLE
有的采集站采集不了

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#7]
有的采集站采集来的数据是空的

**Comment by dd0072** [comment]
补充一点，这个采集站在没有升级到github版本时是可以采集的。

**Comment by magicblack** [comment]
应该没有问题，采集处理最近没有修改过。

**Comment by dd0072** [comment]
测试了一下，失败的都是综合资源采集站的，比如一个采集站可以采集QQ，PPTV等资源，能单独提供一个升级包吗？我想用宝塔一键安装后再用升级包升级试试。

**Comment by magicblack** [comment]
检查播放器是否整合，未整合的是不显示的。
