### ISSUE TITLE
请问API发布如何添加多组播放设置

### ISSUE THREAD

**Issue by phpc0de** [magicblack/maccms10#70]
请问API发布如何添加多组播放设置，像这种数组不能成功。
vod_play_from[0]=
vod_play_from[1]=

**Comment by magicblack** [comment]
后台添加多组地址后，api输出的也是多组地址。

**Comment by phpc0de** [comment]
> 
> 
> 后台添加多组地址后，api输出的也是多组地址。

可能我没说清楚，我现在的问题是输入不进去（类似火车头发布）
/api.php/receive/vod
自己写的小程序没办法添加多组播放

**Comment by phpc0de** [comment]
> 
> 
> 后台添加多组地址后，api输出的也是多组地址。

利用API发布没法像后台一样能添加多组播放
 vod_play_from[0]=

**Comment by magicblack** [comment]
api发布数据  多组 播放器类型，播放地址    分隔符都是 $$$ 不管是火车头还是其他第三方~~~ 可以研究下 数据库存储结构

**Comment by phpc0de** [comment]
> 
> 
> api发布数据 多组 播放器类型，播放地址 分隔符都是 $$$ 不管是火车头还是其他第三方~~~ 可以研究下 数据库存储结构

谢谢，问题解决了。我还想问问后台加了什么特技为什么我模拟发包会跳到登录地址，cookie和附加头都加上了，我发现有几个附加头前缀都是“::”是不是这个原因，POST评论会500错误不过倒是成功发布了。
