### ISSUE TITLE
搜索验证码问题

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#704]
开启搜索验证码后
网站前台搜索影片，进入验证码页面，输入验证码提交后，还是停留在验证码页面，重新填写验证码提交，还是停留在验证码页面
好吧，刷新一下，还是停留在验证码页面

返回首页，重新搜索影片，不需要验证码了

经过以上测试，验证码还是有用的，但是填写验证码提交后，还是停留在验证码页面，而不是返回搜索的影片页面

**Comment by magicblack** [comment]
验证码页面输入正确后会自动刷新页面， 
如果你开启cdn请配置好不要缓存搜索路径。 宝塔网站加速也一样。
