### ISSUE TITLE
更新最新版本，网站搜索影片一直是空，获取不到输入框里的值了

### ISSUE THREAD

**Issue by DDroser** [magicblack/maccms10#705]
更新最新版本，网站搜索影片一直是空，获取不到输入框里的值了

**Comment by caoboruicbr** [comment]
> 更新最新版本，网站搜索影片一直是空，获取不到输入框里的值了

好使啊

**Comment by philipsc** [comment]
搜索框class插入mac_wd开启搜索联想

**Comment by magicblack** [comment]
应该是你的模板搜索参数默认是post提交引起的。新版本为了安全起见默认只获取get参数。
办法1，后台-》系统-》站点参数配置-》性能-》参数获取方式  改为 get+post
办法2，修改模板搜索框部分form ，把method=post 改为  method=get

**Comment by DDroser** [comment]
确实是这样的，改成Get后就好使了
