### ISSUE TITLE
入库重复规则（演员、导演）判断不生效

### ISSUE THREAD

**Issue by philipsc** [magicblack/maccms10#706]
已经勾选入库重复规则演员、导演的情况下将同名的电影入库到电视剧，希望能修复一下这个BUG

**Comment by magicblack** [comment]
这是为了解决不同资源方提供的信息不完全一致时的兼容措施。
这个场景下可以这样解决：系统 - 采集参数配置 - 入库重复规则，把【分类】或其他规则 勾选上。
