### ISSUE TITLE
一键去重可以增加这个功能吗?

### ISSUE THREAD

**Issue by aTenb** [magicblack/maccms10#709]
一键去重,合并播放组,删除大id,如果小id和大id都包含某个播放组,这大id的播放组资源覆盖小id.

大概就是这么个逻辑.

我说下理由:通常大ID的资源比较新可以播放,小id的播放源可能已经失效,同一个播放器的,合并用大id覆盖小id会比较好.现在单纯的一键去重删id感觉不太合理

**Comment by cyh303** [comment]
是的   建议整加一键合并的功能   多资源站重复的太多了

**Comment by cyh303** [comment]
> 进入重名数据管理 里边有一个键删除

是的建议整加一键合并的功能多资源站重复了

**Comment by aruoop** [comment]
奇怪 采集重复入库 我只勾选了分类和名称  但是也会有很多重复的，我网站只有4个大分类 无小分类的情况下

**Comment by h175h32** [comment]
> 是的 建议整加一键合并的功能 多资源站重复的太多了

一键合并也会出问题，有些名字一样，但是内容不一样的也会合并到一起。

**Comment by magicblack** [comment]
采集的时候配置合适的规则，播放资源会自动合并在一起
