### ISSUE TITLE
苹果cms v10如何快速删重视频，宝塔面板MySQL怎么设置？

### ISSUE THREAD

**Issue by renshuaibing** [magicblack/maccms10#71]
①如题，如果采集配置错误导致出现大量重复数据，一键删重（保留大ID）删除速度太慢了，有其他快速删重的方法吗？删除数据后图片会自动删除吗？苹果cms v10有自带的多余图片删除工具吗？例如老版本的拓展项图片管理
②火车头7.6版本采集视频，如何设置“已完结“？
③一个视频顶级分类在网站页面只能显示20项小分类，请问修改哪个文件的num="20"？
④有比较完美的苹果cms v10--宝塔设置吗？怎么设置nginx、php、MySQL、Redis发挥最大性能，谷歌云vps建议配置是多少？现在的配置是谷歌香港vps，inter Xeon（R）CPU 2.00Ghz,、2核心、8G运存、700GHDD存储，网站不商用
⑤有便宜或免费的免备案cdn推荐吗？网页打开速度确实比较慢
Thanks♪(･ω･)ﾉ

**Comment by magicblack** [comment]
1，mysql一键清空表结构可以使用  truncate table mac_vod，图片需要自己删除upload里文件
2，是否完结字段设置为1
3，修改魔板里调用分类的标签加入num="99"，数量自定义
4，建议缓存使用redis，php7.x + 配置4H8G+SSD云盘基本都可以搞定了
5，不清楚，建议谷歌搜索下
