### ISSUE TITLE
开放API配置开启收费之后，对方采集时一直提示json格式不正确

### ISSUE THREAD

**Issue by ztkink** [magicblack/maccms10#710]
是有一些地方需要更改吗，遇到2个问题~
开放API配置开启收费之后，对方采集时一直提示json格式不正确
<img src = 'https://s3.bmp.ovh/imgs/2021/08/34f44b142c60bd25.png' />

**Comment by magicblack** [comment]
api白名单那块需要填写 过白的   服务器ip 不是域名。
