### ISSUE TITLE
一个十分有必要的小功能：关于后台同步图片选项

### ISSUE THREAD

**Issue by SLi-Man** [magicblack/maccms10#713]
一个十分有必要的小功能：关于后台同步图片选项
希望能够选择只同步我勾选的数据

**Comment by adv443ef** [comment]
同步图片卡得很...

**Comment by SLi-Man** [comment]
> 同步图片卡得很...

卡那是网站服务器跟图床的问题，与程序关系不大，服务器跟图床带宽高，那就秒同步

**Comment by magicblack** [comment]
现在支持对不同的资源站独立配置是否同步图片了，先看看能不能满足。如果再细粒度到vod级别会比较麻烦~
