### ISSUE TITLE
关于api参数拼接问题

### ISSUE THREAD

**Issue by machaoqun0921** [magicblack/maccms10#714]
您好，原始数据库，没有改过系统默认生成的id，但是在url拼接获取json时，t=1或者t=2时的顶级分类返回空集合，但其实我有数据，t=3和t=4的顶级分类下就是正确返回数据，请问我该怎么处理这个问题？谢谢

**Comment by magicblack** [comment]
api参数t 默认查当前参数id的数据，不包含子分类。
