### ISSUE TITLE
关于 base64_decode

### ISSUE THREAD

**Issue by KusakabeSi** [magicblack/maccms10#715]
想请教开源软件为什么要url=base64_decode，类似代码混淆般的行为呢？

在我的认知中，只有商业软件/木马病毒/CTF题目才需要代码混淆

像是wordpress，全球那么多人用，也没有类似的作法
![image](https://user-images.githubusercontent.com/73118488/131636233-9ad4b07b-ae1b-474b-9ea1-e1dabfee258c.png)

在开源软件看到这种代码混淆行为，虽说解开没有多难，但是还是在我心中留下一个疑问，不太懂这么做的目的

所以前来请教，这么做有什么好处吗?

**Comment by magicblack** [comment]
用什么是我们的权利，盗版cms满天飞，我们就是需要做一些处理。  
你这就无理取闹了吧， 觉得有问题可以不用。

**Comment by KusakabeSi** [comment]
原来是这样，另一个版本也的确有一模一样的问题
确实人家wordpress家大业大，不需要防盗版
