### ISSUE TITLE
定时任务，生成wap首页有bug，开启了站群模式

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#720]
定时任务参数ac=index&ac2=wap，执行任务后生成的是pc页面，开启了站群模式，请管理检查一下

**Comment by magicblack** [comment]
都站群了还生成静态干嘛。冲突了。

**Comment by klmahua** [comment]
> 
> 
> 都站群了还生成静态干嘛。冲突了。

主站生成静态首页加快访问速度。。其他站动态访问

**Comment by klmahua** [comment]
如果手动点击生成wap首页是正常的  定时任务就是错误的

**Comment by klmahua** [comment]
已经解决了。。可以结贴了
