### ISSUE TITLE
关于mysql占用CPU100%的问题

### ISSUE THREAD

**Issue by chengzf** [magicblack/maccms10#721]
我现在的系统：

主表数据20W+
开启了redis缓存（数据缓存和页面都启用了）
关闭了筛选功能
启用了首页静态访问（并定时生成首页）
屏蔽了google蜘蛛

在这样的情况下隔三岔五地出现mysql占用CPU100%，
然后系统假死，网站无法访问，
请大佬指条明路。

**Comment by wowo344** [comment]
我也是经常碰到这个问题， 流量一大，mysql就占100%，直接GG，重启mysql都无用。。。高峰时段得守着服务器， kill掉mysql死锁。。。经常不断的努力， 总结了当下的临时解决办法：
1.   屏蔽google， 不一定足够， 因为还有各种垃圾蜘蛛， 最好自己分析下日志，屏蔽所有垃圾蜘蛛后情况会好很多。 
2.   自己测试下来， memcached性能要比redis好一些， 你也可以换成memcached试试。 
3.   你参考这个家伙的， 把like去掉一半，壮士断腕。。。 https://github.com/magicblack/maccms10/issues/677#issuecomment-869711193，  这个不错， 照他的搞源代码， 会少很多like全表扫描语句， 就是查询不是模糊查询了……可能会影响用户体验。  不过20w的数据， maccms光用like全表扫描， 没有全文索引支持， 流量高肯定GG的。 
4.    升级配置。。。。 

欢迎来交流maccms的性能优化。

**Comment by chengzf** [comment]
> 我也是经常碰到这个问题， 流量一大，mysql就占100%，直接GG，重启mysql都无用。。。高峰时段得守着服务器， kill掉mysql死锁。。。经常不断的努力， 总结了当下的临时解决办法：
> 
> 1. 屏蔽google， 不一定足够， 因为还有各种垃圾蜘蛛， 最好自己分析下日志，屏蔽所有垃圾蜘蛛后情况会好很多。
> 2. 自己测试下来， memcached性能要比redis好一些， 你也可以换成memcached试试。
> 3. 你参考这个家伙的， 把like去掉一半，壮士断腕。。。 [https://github.com/magicblack/maccms10/issues/677#issuecomment-869711193，](https://github.com/magicblack/maccms10/issues/677#issuecomment-869711193%EF%BC%8C)  这个不错， 照他的搞源代码， 会少很多like全表扫描语句， 就是查询不是模糊查询了……可能会影响用户体验。  不过20w的数据， maccms光用like全表扫描， 没有全文索引支持， 流量高肯定GG的。
> 4. 升级配置。。。。
> 
> 欢迎来交流maccms的性能优化。

多谢大佬指教。

**Comment by magicblack** [comment]
#549
