### ISSUE TITLE
首页自适应PC端模板无法跳转手机端模板问题

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#723]
困扰了二个星期的问题，终于找到了思路，是这样的：

1、网站配置是：伪静态，苹果CMS默认模板，自适应为多域名，手机站域名m.123xx.com
2、网站使用了cloudflare加速
3、宝塔nginx伪静态

出现的问题是：
手机打开 www.123xx.com 自动转到 m.123xx.com    -----------然而并没有跳转手机端模板，有时候刷新cloudflare缓存，会自动跳转，但等一会就又失效无法跳转手机端，停留在PC端,但是吧，栏目页和视频页都可以正常跳转

百思不得其解，期间网站后台各种设置，cloudflare各种调试，都无法解决
今天也不知道怎么想的，突然用浏览器打开 m.123xx.com/index.php和m.123xx.com/index.html 正常了！！！我查，终于明白为什么栏目页和内页可以正常跳转，首页确时而跳转时而不跳转。因为栏目页和内页是m.123xx.com/lanmuye/shipin.html ，末尾有 .html
但是吧，我本地phpstudy环境测试一切正常，难道是cloudflare加速出现的问题，还是宝塔环境问题

问题是找到了，怎么在原封不动的情况下解决这个问题，难到我了，配置nginx下伪静态？怎么配置？修改自适应跳转JS？如何操作，修改宝塔默认文档？好难

恳请大佬给个解决方法指导，小弟在这里谢谢了！

**Comment by klmahua** [comment]
开启cloudflare移动端自动跳转m域名

**Comment by ycgz2008** [comment]
> 开启cloudflare移动端自动跳转m域名

一直是这样设置的，没用

今天测试后台把移动端域名从m.123xx.com设置为m.123xx.com/index.html，但也是没用
修改宝塔默认文档第一选项为index.html 无效
只剩下最后的伪静态修改了，还没有找到修改方法

**Comment by magicblack** [comment]
不要生成静态首页。 需要分别建立2个站点。

**Comment by ycgz2008** [comment]
> 不要生成静态首页。 需要分别建立2个站点。

测试站群建立m.123xx.com 也是无效
感谢大佬指导，解决！
我是这样操作的，镜像PC站，简单修改下信息，测试跳转移动端正常了，不过，这样搞移动端失去了自动跳转PC端功能，我想着自己找个移动端自动跳转PC端的代码放上？（不好意思，强迫症患者）
多出一个站，维护精力加大了，其实本来的多域自适应百度收录还不错的，除了上面的首页无法跳转，可以的话后期版本建议优化优化
