### ISSUE TITLE
为什么假墙防御开启后，筛选页面的功能不能正常使用？

### ISSUE THREAD

**Issue by klmahua** [magicblack/maccms10#724]
你们的可以正常使用吗？

**Comment by magicblack** [comment]
没问题啊~ 
初级防御： 开启验证码
高级防御：开启假墙关键词防御

**Comment by klmahua** [comment]
开启假墙防御后，筛选页面没有数据，关闭假墙防御，筛选页面有内容   ，而且当前的筛选参数也选不中

**Comment by freebeing-Github** [comment]
我也遇到了同样的问题，我用的是最新的代码包。开启假墙防御后（不论是编码方式，还是空白方式），筛选页面拿不到$param['class']  $param['lang']之类带中文的值，但$param['year']可以正常工作还是能拿到2019这样的数字值。

同样，开启加强防御后，搜索页面的$param.wd也拿不到正确的值了（乱码或者哦空白。）

请给出一些建议。谢谢！

**Comment by freebeing-Github** [comment]
不好意思另一个小白问题：关于假墙防御，如果服务器和ip地址都是国内的，就不会被假墙攻击了，是吗？

**Comment by klmahua** [comment]
中文参数筛选的确有问题，中文给转码了，导致参数不能选中

**Comment by magicblack** [comment]
> 不好意思另一个小白问题：关于假墙防御，如果服务器和ip地址都是国内的，就不会被假墙攻击了，是吗？

假墙攻击原理是指定链接打开后有敏感词（搜索链接敏感词回显），和服务器IP无关

**Comment by magicblack** [comment]
筛选回显问题，开启假墙防御后没有好的办法解决。需要修改模板里的参数对比方式，模板已经不维护了。
