### ISSUE TITLE
这个预留Ajax开关 请求url应该怎么写 我按上面写的不行啊

### ISSUE THREAD

**Issue by poporeki** [magicblack/maccms10#725]
![QQ图片20210912201100](https://user-images.githubusercontent.com/22537106/132987040-53662dca-cee0-49b3-99ac-709cede62174.png)

**Comment by philipsc** [comment]
是不是要加 mac_user 这个参数？我写了个用户登录的ajax弹窗是这样弄的，其他功能应该也有对应的class

**Comment by magicblack** [comment]
调用时参考一下对应controller下的ajax_前缀的方法。
