### ISSUE TITLE
重复入库只勾选了名称和分类，但是还是有超多重复视频入库，是bug吗？

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#727]
重复入库只勾选了名称和分类，但是还是有超多重复视频入库，是bug吗？
只有大分类 没有小分类

**Comment by aruoop** [comment]
![QQ截图20210916104216](https://user-images.githubusercontent.com/42017510/133541171-bf0bc570-caee-476f-b443-dc257bb78016.png)
![QQ截图20210916104234](https://user-images.githubusercontent.com/42017510/133541179-65640530-96ae-40de-87e2-9e94ce9db406.png)

**Comment by aruoop** [comment]
重复视频处理出现这个提示
![QQ截图20210916104809](https://user-images.githubusercontent.com/42017510/133541353-f83cd3be-c21a-40c2-a6bf-7fe85a91a092.png)

**Comment by magicblack** [comment]
重复视频处理参考 #202
