### ISSUE TITLE
关于采集无播放器

### ISSUE THREAD

**Issue by ayanyi** [magicblack/maccms10#73]
在继发布不能采集版本后出现的一个bug，全新安装cms，采集会出现无播放器，即使是已经添加了但是无法采集到播放器和播放地址，回退老版本采集正常，017的版本也有这个问题，麻烦老王修复下

**Comment by ayanyi** [comment]
而且这个版本的百度，掌熊推送失效，如有时间一起修复下，

**Comment by magicblack** [comment]
自定义资源    是否配置了  地址过滤： 和 过滤代码：

**Comment by ayanyi** [comment]
没有配置这些，正常填写采集链接，选的新增+更新，保存

**Comment by ayanyi** [comment]
选择了不过滤，可以正常采集，我记得之前的版本，配置这个也可以采集，还请老王这边能修复下百度站长和掌熊的一个推送

**Comment by magicblack** [comment]
测试了采集没出现问题。主要正确添加了播放器。  相关数据才会在编辑时显示出来。
百度熊掌砸了？
