### ISSUE TITLE
假墙功能开启后，依然还是会被假墙，不起任何的作用

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms10#737]
假墙功能开启后，依然还是会被假墙，不起任何的作用

**Comment by aruoop** [comment]
感觉没效果

**Comment by magicblack** [comment]
目前已知是通过提交的链接里包含有敏感词的方式实现，一般是在搜索结果里反馈出来。可自行找一份敏感词库，内容填到这里：
系统 - 网站参数配置 - 预留参数 - 词语过滤，这个应用于搜索参数、评论、留言的禁用词汇。
