### ISSUE TITLE
批量操作视频，选择删除数据，不会删除采集到本地的图片导致再次采集时会重复采集图片，

### ISSUE THREAD

**Issue by stonegr** [magicblack/maccms10#741]
批量操作视频，选择删除数据，不会删除采集到本地的图片导致再次采集时会重复采集图片，经过实验：
1、在少量视频操作的时候是会连采集的图片一起删除的
2、当选择大量的视频的时候就不能够将采集的图片一起删除（只会删除一部分）

**Comment by magicblack** [comment]
检查对应未删除图片是否有删除权限，或者是否编辑过相关视频。
