### ISSUE TITLE
BUG 这里应该在添加时间范围查询，如果启用限制ip注册，则这个IP 将永久无法注册新用户

### ISSUE THREAD

**Issue by UiGit** [magicblack/maccms10#743]
https://github.com/magicblack/maccms10/blob/190f5cfc3c9df32c5a4426ff6089bc4a720f814c/application/common/model/User.php#L174

这里应该在添加时间范围查询，不然启用限制ip注册时，该IP 将永久无法注册新用户，

合理的逻辑应该是：查询 当天注册时间 + 注册IP 结果数量 大于设定数时 禁止注册，而不是只查询这个IP的数量，

**Comment by magicblack** [comment]
感谢反馈，已修复。
