### ISSUE TITLE
怎样能自动生成多个sitemap

### ISSUE THREAD

**Issue by yumiaoge** [magicblack/maccms10#744]
举例：假设现有15000条视频数据，在 /template/模板名/html/rss/baidu.html 里设置 num="10000"，然后在 后台-生成-生成选项，点击-生成“百度sitemap”，这时会生成文件  baidu.xml（有10000条数据），只有10000条数据，这显然不够，还差5000。改一下，在 后台-生成-生成选项 设置“生成页数=2”，然后点击--生成“百度sitemap”，这时会自动生成两个文件  baidu.xml（有10000条数据） 和 baidu_2.xml（有5000条数据），这就有全部的数据了。但是在 定时任务设置里 就不行了，按照教程设置参数 ac=rss&ac2=sitemap ，他只会生成一个文件baidu.xml（有10000条数据），这里也不是没有解决办法，把 /rss/baidu.html 里设置 num="20000"，不就行了么。确实是行了，但是多了怎么办，有5W，10w怎么弄，总得要分割的。请赐教，定时自动任务怎样设置能生成多个sitemap文件。

**Comment by yumiaoge** [comment]
完了说版本 2022.1000.3024

**Comment by magicblack** [comment]
加个生成页数参数ps=页数。如生成5页，参数如下：
ac=rss&ac2=sitemap&ps=5
