### ISSUE TITLE
网站后台添加视频处存在存储型XSS漏洞(There is a cross-site scripting (XSS) vulnerability in adding videos)

### ISSUE THREAD

**Issue by jelly0930** [magicblack/maccms10#746]
网站后台添加视频处，包括名称、备注等参数位置均可插入xss代码

（There is a Storage XSS vulnerability in adding videos，XSS code can be inserted at parameter positions including name and remarks……）

![image](https://user-images.githubusercontent.com/37065209/141251731-da7148b1-efa0-406f-99f7-a2eb14e8175c.png)

插入的xss代码也会在前台被执行，它将影响访问该网站的所有用户

（The inserted XSS code will executed in the foreground，It will affect all users who visit the site）

![image](https://user-images.githubusercontent.com/37065209/141252001-98ad49f9-5743-4f82-a0d2-3a0e06c187a9.png)

虽然这个存储型xss位于后台，但该漏洞一旦被利用会导致前台众多用户都会收到攻击

另外，后台添加文章处也有相同问题

**Comment by dadawang88** [comment]
这是 是  这个吊毛 故意留的的漏洞 方便资源站挂马

**Comment by magicblack** [comment]
感谢反馈，将统一修复。
