### ISSUE TITLE
苹果cms【重名数据库】报错

### ISSUE THREAD

**Issue by shangxin-lazy** [magicblack/maccms10#749]
使用的是阿里云的数据库，数据库版本是8.0，默认是开启了GTID的，而且无法修改参数关闭

报错信息：
SQLSTATE[HY000]: General error: 1786 Statement violates GTID consistency: CREATE TABLE ... SELECT.

**Comment by magicblack** [comment]
参考 https://www.cnblogs.com/brianlai/p/13556512.html

**Comment by shangxin-lazy** [comment]
阿里云的数据库并不支持修改配置文件，阿里给出的参数修改也没用该问题的解决方法
