### ISSUE TITLE
狗东西挂马还装官方

### ISSUE THREAD

**Issue by aiyounilov** [magicblack/maccms10#751]
狗东西挂马还装官方，日nm全家死绝。
这也是假的，真的老王早没做了
la后缀和pro后缀都是假的， 不过这个la更恶心而已

**Comment by aiyounilov** [comment]
你们两条狗咬狗而已，别装自己好清高了用你的magicblack下载的程序跳转到黄色网站，我已经报案了

**Comment by maigosama** [comment]
你先找一下跳转代码在哪再喷可以吗，证据放上来
