### ISSUE TITLE
开始采集就会导致前后台网站打不开 ，关闭采集网站就能打开了

### ISSUE THREAD

**Issue by dwwl886** [magicblack/maccms10#752]
开始采集就会导致前后台网站打不开 ，关闭采集网站就能打开了
最开始以为是服务器性能不好，换了10核8G内存的服务器还是一样的
在监控里面看 服务器CPU和内存基本没有多大变化，所以排除服务器的问题。

**Comment by magicblack** [comment]
采集是有自动间隔的，更换采集资源站试试。
