### ISSUE TITLE
网站被挂得满目疮痍，怎么搞？

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#755]
全站图片地址挂js  
播放器名称挂js
好奇怎么挂上去的

**Comment by allcdn** [comment]
一样我也是

**Comment by magicblack** [comment]
参考这个先清理：
https://github.com/magicblack/maccms10/wiki/%E5%B0%8F%E7%99%BD%E9%80%9A%E7%94%A8%E6%B8%85%E7%90%86php%E5%90%8E%E9%97%A8%E5%8A%9E%E6%B3%95%E7%AE%80%E5%8D%95%E6%98%93%E6%87%82

如果不行重新下载最新安装包安装一下。

再有遇到请反馈到tg，一起排查下。
