### ISSUE TITLE
maccms的数据接口

### ISSUE THREAD

**Issue by c0dedance** [magicblack/maccms10#756]
想把maccms作为后端服务，自己开发前端vue+ui组件库。目前不知道调到maccms的接口
还请老王指导一下
https://github.com/magicblack/maccms10/blob/master/%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3/API%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E.txt
是这个接口文档吗

**Comment by magicblack** [comment]
这里有部分数据，如果不够需要自己二次开发。
