### ISSUE TITLE
后台的开放api接口采集失效了

### ISSUE THREAD

**Issue by mayHello** [magicblack/maccms10#757]
开启收费后，填写授权域名测试无效！显示链接接口失败。关闭付费采集又可以，之前的版本我测试过，是可以的，希望修复下，谢谢

**Comment by mayHello** [comment]
开启收费后，授权域名也正确填写了，测试，显示xml不正确不支持采集。关闭收费后，测试链接成功！

**Comment by magicblack** [comment]
这里用的其实是服务器的IP。如果对方同一个域名有多个服务器，将对方服务器IP都加进来。
如果你的网站用了CF等CDN，可能获取IP有误，稍后一个版本将修复这个问题。
