### ISSUE TITLE
在PHP8.0环境下，“URL地址配置”内的内容 无法保存

### ISSUE THREAD

**Issue by iamithunk** [magicblack/maccms10#760]
在PHP8.0环境下，“URL地址配置” 里面的“路由伪静态设置”等内容无法保存，再次点击后就提示不要重复提交数据，切换为PHP7.4环境就可以正常保存。

**Comment by magicblack** [comment]
先用php7.4跑一下。8.0需要做兼容。【不要重复提交数据】刷新下页面再提交。

**Comment by iamithunk** [comment]
静等修正。

**Comment by magicblack** [comment]
已修正，感谢反馈，将在下个版本统一更新。
