### ISSUE TITLE
黑屏无法播放

### ISSUE THREAD

**Issue by pipidaxian** [magicblack/maccms10#768]
确认已经采集成功，且添加了播放器，在后台的视频数据页面选中采集的视频，可以看到播放地址，播放地址手动复制到浏览器可以播放。但是在自己的网页中打开就一直是黑屏，电脑手机都是。

电脑上使用查看页面源代码发现了这一句话：

`<a href="javascript:void(0)" onclick="if (!window.__cfRLUnblockHandlers) return false; MAC.Gbook.Report('ID:3 -【名称：二龙湖往事惊魂夜 - HD】无法观看请检查修复')" data-cf-modified-d9d74435c918db408b6f04f7-=""><i class="iconfont">&#xe612;</i>报错</a>`

求助怎么处理？

**Comment by magicblack** [comment]
可以通过浏览器播放说明源没问题。检查模板里是否正常输出播放链接、对应播放器是否正常支持此格式的视频播放。
建议在对应采集源的官方也问一下。

非程序问题，暂时关闭此issue。
