### ISSUE TITLE
播放数据保存问题

### ISSUE THREAD

**Issue by Nothingtodoforma** [magicblack/maccms10#770]
由于之前的服务器出现问题，把网站数据取回来后，重新部署到新服务器，播放数据保存出现问题：播放链接可以保存，但是播放器编码保存不了（已尝试重新创建播放器，保存仍旧失败）
![image](https://user-images.githubusercontent.com/49300630/145704776-75faa034-0eb9-4b4a-a0c3-834fe18931cf.png)

**Comment by magicblack** [comment]
无法重现。你看下是不是按下面截图这样保存的。
![image](https://user-images.githubusercontent.com/20452515/145763642-f1caaa05-8e78-4478-9ac1-e265d664c8a8.png)
![image](https://user-images.githubusercontent.com/20452515/145763717-b876460c-6a85-495d-8c0d-bec2c6fe9e8c.png)

**Comment by magicblack** [comment]
先尝试下清理一下缓存

**Comment by Nothingtodoforma** [comment]
![image](https://user-images.githubusercontent.com/49300630/145819328-440261b7-9536-494f-90b6-fb5406506a0c.png)
清过缓存，不管用
