### ISSUE TITLE
求助，如何修改添加视频数据的时候不重置表单，我找了好久也没找到在哪调用的reset

### ISSUE THREAD

**Issue by Macol999806** [magicblack/maccms10#771]
![QQ图片20211212155435](https://user-images.githubusercontent.com/44579331/145704912-daedab68-bf5d-489e-9098-a2761af99499.png)
![QQ图片20211212155620](https://user-images.githubusercontent.com/44579331/145704922-1209a70f-e8d6-4417-b1cb-4ff4af79e94b.png)

**Comment by magicblack** [comment]
通过ajax提交的，F12看看提交发起的地方。admin_comm.js第232行开始。
