### ISSUE TITLE
首页静态好像设置不了？

### ISSUE THREAD

**Issue by kaili0985** [magicblack/maccms10#775]
老板，静态页面无论设置什么，都是动态页面，那么后台页面生成是动态的吗？是我设置错了吗？
！[截屏2021-12-17 8 43 17]（https://user-images.githubusercontent.com/85415706/146546426-0c14ee65-7d5f-4683-b90f-99412a0a5f90.png）

**Comment by magicblack** [comment]
本地尝试了是正常的，可能你要在设置好静态之后，去后台 【生成】 - 【生成选项】 里把你要生成静态的内容全部生成一遍~
