### ISSUE TITLE
首页如何调用演员相关影片?

### ISSUE THREAD

**Issue by xj811975** [magicblack/maccms10#776]
例如 下面的截图[
![屏幕截图 2021-12-18 154430](https://user-images.githubusercontent.com/95744535/146633695-f8a1196c-0899-4f32-a55f-570c90fb89a8.png)
](url)

**Comment by magicblack** [comment]
需要自行在模板里先查一下演员名对应的视频Id列表，再用 {maccms:vod num="10" ids=“查出来的Id列表用逗号分隔”} 来输出
