### ISSUE TITLE
maccms V10版本开启cf的Rocket Loader就不能加载播放器了

### ISSUE THREAD

**Issue by hioer688** [magicblack/maccms10#777]
maccms V10版本开启cf的Rocket Loader就不能加载播放器了，请问有什么办法解决吗？

**Comment by magicblack** [comment]
开启cf的Rocket Loader会导致js加载顺序发生变化。需要根据js报错内容，将不能后置的js加上以下属性：
`data-cfasync="false"`
如：
`<script data-cfasync="false" src="/javascript.js"></script>`

因不再维护模板，需要模板作者或自行处理。
