### ISSUE TITLE
会员组权限里缺个筛选页权限选项

### ISSUE THREAD

**Issue by baiyanghk** [magicblack/maccms10#778]
打开页面筛选页面提示权限不足，查看后台网站参数配置----基本设置------筛选页开关    已开启，用户组权限里没有筛选页权限选项可以勾选，其它权限都是勾选开启了，前台无法正常打开筛选页面，重新在给用户组所有权限后更新缓存也一样问题，maccms10 2022.1000.3025版本的

**Comment by magicblack** [comment]
提供一下重现步骤，以及对应的网址路由

**Comment by baiyanghk** [comment]
> 提供一下重现步骤，以及对应的网址路由

我的网址是www.5yeb.com
打开名人栏目------点击查看更多，展示网址：https://www.5yeb.com/actorshow/%E4%BA%9A%E6%B4%B2--------.html
然后提示没有权限，是我的模板标签地址错误还是权限问题呢

**Comment by proamo** [comment]
同樣問題, 3005, 3025, 3026我都試過
https://kanba.ga/index.php/vod/type/id/1.html
進去再點 更多
我是跑出 “筛选页功能关闭中”

**Comment by baiyanghk** [comment]
> 同樣問題, 3005, 3025, 3026我都試過 https://kanba.ga/index.php/vod/type/id/1.html 進去再點 更多 我是跑出 “筛选页功能关闭中”

你这个是网站参数配置-----性能优化-------筛选页开关    没开启，开启后在看看是不是提示权限问题，我的是开启了提示权限不足

**Comment by proamo** [comment]
解決了，是我的問題
從非官方版本換成官方版本後，沒注意到多了"筛选页开关"
還以為是BUG
謝謝magicblack!

**Comment by baiyanghk** [comment]
> 解決了，是我的問題 從非官方版本換成官方版本後，沒注意到多了"筛选页开关" 還以為是BUG 謝謝magicblack!

兄弟果然看东西不仔细呀，回复你的不是magicblack 囧

**Comment by proamo** [comment]
> > 解決了，是我的問題 從非官方版本換成官方版本後，沒注意到多了"筛选页开关" 還以為是BUG 謝謝magicblack!
> 
> 兄弟果然看东西不仔细呀，回复你的不是magicblack 囧，另外你的刷选页打开会跳其它网站，不知道你模板问题还是故意的，手机端打开发现的

baiyanghk抱歉!真的是眼瞎了!
再次謝謝您!
另外，我試筛选页的手機端和電腦端都沒發生跳其他網站, 不知是哪出問題了呢!

**Comment by magicblack** [comment]
> > 提供一下重现步骤，以及对应的网址路由
> 
> 我的网址是www.5yeb.com 打开名人栏目------点击查看更多，展示网址：https://www.5yeb.com/actorshow/%E4%BA%9A%E6%B4%B2--------.html 然后提示没有权限，是我的模板标签地址错误还是权限问题呢

感谢提供的更多信息，已解决提交，将在下个版本里发布更新。
