### ISSUE TITLE
XSS vulnerability exists in the background search function.

### ISSUE THREAD

**Issue by 1979139113** [magicblack/maccms10#78]
When the administrator logged in, open the following link.
```
http://127.0.0.1/maccms10/admin.php/admin/link/index.html?wd=%22%3e<svg/onload=alert(document.cookie)>
```
![图片](https://user-images.githubusercontent.com/24983597/67287777-48214d00-f50e-11e9-9e8f-e6013493dfd6.png)

**Can take over the administrator because the value of the cookie is obtained**

**Comment by magicblack** [comment]
进行了过滤，不过这个影响不大，在已经拥有后台权限的情况下这个没多少意思。

**Comment by 1979139113** [comment]
攻击者最开始没有后台权限，让后台管理员在登陆的情况下访问这个链接，那么就可以获取到后台管理员的cookie，也就可以获取到后台的权限。

这相当于一个从无权限到有权限的过程。

**Comment by magicblack** [comment]
了解~稍后发更新~
