### ISSUE TITLE
密码无法使用%特殊符号BUG，

### ISSUE THREAD

**Issue by UiGit** [magicblack/maccms10#781]
## BUG1
https://github.com/magicblack/maccms10/blob/5b54f93a8e58f7baf27b1bd439790bb0ce2ca7d7/application/common/model/User.php#L320

此处位置不该使用 `urldecode` 函数对密码表单进行处理，因为 urldecode 方法会吧%号进行过滤，凡事携带%的密码值都会被清空，导致无法登录，并提示 “请填写必填项”，

## 影响范围，
> 使用百分号`%`特殊符号密码的老会员会不能正常登录，
> 新注册使用百分号`%`特殊符号密码注册后无法正常登录，提示 “获取用户信息失败”

## 修复方法
只需吧
```php
$data['user_pwd'] = htmlspecialchars(urldecode(trim($param['user_pwd'])));
```
修改为
```php
 $data['user_pwd'] = htmlspecialchars(trim($param['user_pwd']));
```
即可完成修复，使用携带百分号密码的老用户可以正常登录了

## 另外还有注册表单也是用了这个函数
https://github.com/magicblack/maccms10/blob/5b54f93a8e58f7baf27b1bd439790bb0ce2ca7d7/application/common/model/User.php#L123

## 修复方法
把
```php
 $data['user_pwd'] = htmlspecialchars(urldecode(trim($param['user_pwd'])));
```
修改为
```php
 $data['user_pwd'] = htmlspecialchars(trim($param['user_pwd']));
```
即可完成修复，密码存在特殊字符可以提高密码的安全级别，不应被过滤。

## 总结

在User 模型中还有多 使用 `urldecode` 函数对密码字段进行处理，会导致以上类似的问题，如果禁止使用%等特殊符号，那么就应该在注册表单提交时，使用正则判断一下是否包含 百分号，并提示跟注册用户  “注册密码不得包含%等特殊符号”，这样可以避免用户注册后无法登录

**Comment by magicblack** [comment]
感谢反馈，将对应修复下，在下一版本更新。
