### ISSUE TITLE
网址排序问题，求解惑！

### ISSUE THREAD

**Issue by mies9527** [magicblack/maccms10#782]
{maccms:website num="20" paging="no"  order="asc"  type="1" by="sort"}
按该代码写入 网址是默认排序，如何实现让网址按后台的其他信息中的 顶的数字高低来排序呢？
by="up" 测试过无效。

.

**Comment by magicblack** [comment]
website模块允许的by为: `['id', 'time','time_add','score','hits','hits_day','hits_week','hits_month','up','down','level','rnd','in','referer','referer_day','referer_week','referer_month']`

可参考这个文件：
application/common/model/Website.php  110行。

**Comment by mies9527** [comment]
你这里不是写了么 他支持'up','down'   我写by="up"没毛病啊    但是实际上却没反应！
{maccms:website num="20" paging="no" order="asc" type="1" by="up"}  后台看了3个链接2个UP=0 一个UP=99 但是还是没用

**Comment by mies9527** [comment]
> 
已经解决，UP数字越大排序越靠后！
