### ISSUE TITLE
會員組權限數量上限問題

### ISSUE THREAD

**Issue by secretwebmaster** [magicblack/maccms10#783]
**描述您的问题**  
當分類數量多於167個時，在編輯會員組時，便不能全選所有權限，似乎多選框最多只能選取1000個

**如何重现**  
1. 新增多於167個分類
2. 前往會員組，隨便選一個進行編輯
3. 點擊「全選」，由於每個分類會有6個勾選框，分類多於167時，勾選框便會多於1000個
4. 發現並不能全部勾選

**预期结果**  
會員組權限不限數量

**截图**  
https://ibb.co/tQ95qGp

**版本信息:**  
 -  程序版本: [如 2022.1000.3026] (已測試過多個版本)

**Comment by secretwebmaster** [comment]
對系統還不太熟悉，嘗試過到/application/common/model/Group.php中查看
找到了public function saveData($data)，這裡的$data['group_popedom']也只有1000個數據，所以儲存到數據庫中的也是只有1000個數據的json

**Comment by magicblack** [comment]
感谢您的详细反馈，我先排查确认下。

**Comment by magicblack** [comment]
重现了，实际上是由于提交的数据数组大于php的默认配置1000被截断了：
`Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini`

一般情况下不会有这么多的权限配置，你可以将服务器php.ini的`max_input_vars`改大、重启php后再重试。
