### ISSUE TITLE
网址怎么直接显示，求解！

### ISSUE THREAD

**Issue by mies9527** [magicblack/maccms10#784]
<li><a class="borderString" target="_blank" href="{:mac_url_website_detail($vo)}" >{$vo.website_name}</a></li>
在首页使用上述代码只能得出 点击该地址后转入https://www.....com/index.php/website/detail/id/4.html 这样的地址在detail页面里面在点击{$obj.website_jumpurl}的代码才能转跳到 目标网址。
那么"{:mac_url_website_detail($vo)} 是可以替换成直接进入网址的标签，求这个标签怎么写？在手册上没有找到！

**Comment by magicblack** [comment]
参考网站里的 `说明文档/标签说明.txt`~ 或者没有你想要的东西可以用php写
