### ISSUE TITLE
今天打开网站突然提示Connection refused

### ISSUE THREAD

**Issue by gradendripar** [magicblack/maccms10#786]
**描述您的问题**  
今天打开网站突然就成这样了，之前什么修改操作都没有
![2](https://user-images.githubusercontent.com/67825668/147625847-627b8d58-8f79-443a-864b-fa22339a91e3.png)

**如何重现**  

**预期结果**  
网站可以正常打开

**截图**  

**版本信息:**  
 - 程序版本: 2022.1000.3025
 - 操作系统: CentOS7
 - 浏览器: Chrome

**其他备注信息**

**Comment by jackrebel** [comment]
你这个应该是redis或者mysql或者memcached挂了。

**Comment by gradendripar** [comment]
> 你这个应该是redis或者mysql或者memcached挂了。

我看了一下的确是redis挂了 这个是正常的吗 还是我哪里设置不对导致redis挂掉

**Comment by magicblack** [comment]
如果是redis挂了要看看服务器是不是内存不够用等等，排查一下服务器自身。可以做个监控脚本自动拉起redis~
