### ISSUE TITLE
12月19号监控到程序加载了个异常链接

### ISSUE THREAD

**Issue by baiyanghk** [magicblack/maccms10#788]
**描述您的问题**  
系统监控查询到12月19日晚我的系统加载了这个脚本：https://union.macoms.la/html/checkcache.js

**如何重现**  
暂时无在检测到

**预期结果**  
想问问这个是官方地址吗，还是挂马了

**版本信息:**  
 -  程序版本:2022.1000.3025
 - 操作系统:iPhone iOS
 - 浏览器: UC 浏览器, safari

**Comment by magicblack** [comment]
注意是mac o ms，不是官方的，大概率被挂马了
