### ISSUE TITLE
管理后台的欢迎页面，Github源码链接指向错了

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#789]
管理后台的欢迎页面，Github源码链接指向错了，指向的是Maccms_down的仓库

虽然是不影响使用的小问题，不过想反应问题点进去都会懵逼半天 TT

![QQ截图20211231185218](https://user-images.githubusercontent.com/55046423/147819397-5f85b472-a69a-402c-a1c5-b8752d7e13b1.png)

**Comment by magicblack** [comment]
改了~
