### ISSUE TITLE
最近数据库无限查询，怎么处理？

### ISSUE THREAD

**Issue by choateyang** [magicblack/maccms10#791]
起初是vps的cpu长时间被mysql占用，1核双线程日常占用50%左右。

进数据库中查看是查询命令一直无限重复，后台中把搜索关闭后，占用情况消失。

打开搜索，延长搜索间隔，还是有这种现象。

**Comment by magicblack** [comment]
可能是爬虫一直在抓取搜索链接，先尝试开启搜索验证码试试，后续优化一下模糊搜索问题~ #549

**Comment by choateyang** [comment]
> 可能是爬虫一直在搜寻链接，开启搜索验证尝试，尝试寻找模糊搜索#549

好的，感谢
