### ISSUE TITLE
关于邮箱注册问题反馈

### ISSUE THREAD

**Issue by a1642997310** [magicblack/maccms10#792]
**描述您的问题**  

网站被用户通过临时邮箱恶意注册

**预期结果**  

不知是否有办法设置只允许常用邮箱如@qq.com @163.com 才能获取验证码

**Comment by magicblack** [comment]
近期实现下~

**Comment by magicblack** [comment]
已支持
<img width="968" alt="image" src="https://user-images.githubusercontent.com/20452515/151524015-8bdc2fd9-01d6-4325-9f1f-8c38f1b74249.png">
