### ISSUE TITLE
后台采集自定义规则，已经采集好文章，导入文章时，一直提示分类未绑定。这种在哪进行绑定分类

### ISSUE THREAD

**Issue by sd231902** [magicblack/maccms10#793]
后台采集自定义规则，已经采集好文章，导入文章时，一直提示分类未绑定。
比如想绑定默认的ID17下，这种情况在哪进行绑定分类。

**Comment by magicblack** [comment]
采集中间页顶部，找到资源站的分类，绑定到你站的分类~

**Comment by sd231902** [comment]
是自定义规则，不是自定义采集。
没有绑定分类这个选项
