### ISSUE TITLE
[建议]：希望采集添加一个来源同义词替换

### ISSUE THREAD

**Issue by SLi-Man** [magicblack/maccms10#794]
有些来自不同资源站，实际上资源是一样的，但是来源的名称不同，希望能在后台的采集词库里加一个采集来源同义词库，这样方便将这样的资源整合到一起

例如：qiyi和iqiyi
实际上相同，希望能对这个做同义词替换

**Comment by magicblack** [comment]
你是指采集时的播放器么？
![image](https://user-images.githubusercontent.com/20452515/150643997-096e38e2-8c75-463e-ba2d-a49ce5c0cdc0.png)

![image](https://user-images.githubusercontent.com/20452515/150643724-a7357212-798a-43db-ab9e-d77da94b32e7.png)
可以在这里加一个”播放器同义库“？

**Comment by SLi-Man** [comment]
没错，是这个意思

**Comment by SLi-Man** [comment]
> 你是指采集时的播放器么？ ![image](https://user-images.githubusercontent.com/20452515/150643997-096e38e2-8c75-463e-ba2d-a49ce5c0cdc0.png)
> 
> ![image](https://user-images.githubusercontent.com/20452515/150643724-a7357212-798a-43db-ab9e-d77da94b32e7.png) 可以在这里加一个”播放器同义库“？

没错，是这个意思

**Comment by magicblack** [comment]
近期开发下，下个版本一起发布~

**Comment by maigosama** [comment]
这个功能我也有强烈需求
