### ISSUE TITLE
Remote command execution vulnerability exists in the management backend

### ISSUE THREAD

**Issue by 1979139113** [magicblack/maccms10#80]
In the ""超级控制台->模板->模板管理"", Add function can bypass suffix whitelist verification, and upload any file.

The way to bypass the whitelist suffix is to add one point at the end of the file name.

Like this.

`1.php.`

![图片](https://user-images.githubusercontent.com/24983597/67292812-16ac7f80-f516-11e9-8737-a9ec0f226e37.png)

Then click Save.

![图片](https://user-images.githubusercontent.com/24983597/67292936-478cb480-f516-11e9-867a-30542d3f144d.png)

File 1.php will be successfully created and written to malicious content.

Then go to http://127.0.0.1/maccms10/template/1.php to get the webshell.

![图片](https://user-images.githubusercontent.com/24983597/67293118-91759a80-f516-11e9-9c84-629d111861d8.png)

**Comment by magicblack** [comment]
已经修复~稍后更新。
