### ISSUE TITLE
在PHP8.0环境下，会出现致命错误: Undefined constant "path_tpl"错误

### ISSUE THREAD

**Issue by iamithunk** [magicblack/maccms10#800]
在PHP8.0环境下，会出现致命错误: Undefined constant "path_tpl"错误，切换为php 7.4正常。Nginx 1.20.2  。用的是第三方模板。

**Comment by magicblack** [comment]
在访问哪个链接的时候出现的？

**Comment by iamithunk** [comment]
访问首页就会出现，应该访问任何页面都会出现这个问题。

**Comment by magicblack** [comment]
本地自测原模板无此报错，可能需要联系第三方模板开发商修复。
