### ISSUE TITLE
采集自定义规则 报错

### ISSUE THREAD

**Issue by xj811975** [magicblack/maccms10#802]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'urlpage' cannot be null
SQLSTATE[HY000]: General error: 1364 Field 'page_base' doesn't have a defaul

**Comment by magicblack** [comment]
数据库版本多少？可能是版本高了，建议先降到5.7，不行再5.6以下

**Comment by magicblack** [comment]
先尝试修复了，等下个版本一起更新~
