### ISSUE TITLE
视频名称同义库如果有特殊字符，采集不能识别

### ISSUE THREAD

**Issue by maigosama** [magicblack/maccms10#803]
**描述您的问题**  
采集参数设置-采集词库设置-视频名称同义库，如果有些视频名称有特殊字符，保存到maccms.php文件里面会被转换成类似 & uuml; & times; 这样的，导致采集不能正确识别同义转换，由于旧版本的苹果cms没有这个问题，所以一直用旧版，但最近经常被黑客光顾，希望新版能修复一下，谢谢了

**Comment by magicblack** [comment]
&uuml; &times; 对应  ü ×，我测下
