### ISSUE TITLE
3027在php8.0.6环境下出现问题

### ISSUE THREAD

**Issue by Carodia** [magicblack/maccms10#805]
问题一：
\application\common\model\Vod.php
更新为新版
// xss过滤、长度裁剪
        $filter_fields = [
            'vod_name'         => 255,
            'vod_sub'          => 255,
            'vod_en'           => 255,
出现后台手动上传图片后，vod_pic链接中的所有英文字符被替换为空格。
恢复为之前的
// xss过滤
        $filter_fields = [
            'vod_name',
            'vod_sub',
……
后恢复正常。

问题二：
\application\common\model\Image.php
当vod_pic地址为远程链接时
// 水印
            if ($config['watermark'] == 1) {
出现错误：
类型错误: Cannot access offset of type string on string

本地测试环境win10 + phpenv

**Comment by magicblack** [comment]
win下面替换会有点问题，我处理下；其他问题也处理下~
