### ISSUE TITLE
请问有没有详细的接口示例可以返回分类的信息

### ISSUE THREAD

**Issue by a250059653** [magicblack/maccms10#807]
我发现直接请求/api.php/provide/vod/后会返回一个class的集合，但是没办法区分大类和子类，请问有何办法可以区分？或者能不能在下版本增加这个数据的返回？
![image](https://user-images.githubusercontent.com/52188308/151530701-7f50a8aa-1d61-47fb-a4d2-e108781f0202.png)

**Comment by magicblack** [comment]
加个type_pid可以吧，父级别的Id，前端自己再遍历一遍兼容一下~

**Comment by a250059653** [comment]
> 加个type_pid可以吧，父级别的Id，前端自己再遍历一遍兼容一下~

可以在父级别id里面在加一个集合，里面加子级别id

**Comment by magicblack** [comment]
不改动老结构了哈，很多采集站已经在用这个接口了。
