### ISSUE TITLE
在前台界面进行影片搜索时候，输入完成电影名称搜索不到，但是输入部分名称就可以搜索到，这是什么原因？

### ISSUE THREAD

**Issue by iamithunk** [magicblack/maccms10#809]
**描述您的问题**  
我在后台添加了一个电影，比如“半生缘”，我搜索全名 半生缘，显示没有电影，但是我输入 半生 搜索就可以出来，不是全部电影输入全名搜索不到，而是有一部分输入全名搜索不到，请问这是什么原因呢？
比如我录入了电影“逃学威龙” 1，2，3三部，名字都确定没有问题，但是我搜索时候输入“逃学威龙” 搜索不到，输入“逃”就可以搜索到，但是输入“逃学”也搜索不到，输入“逃学威”就又可以搜索到，这是什么原因呢？是模板的原因吗？
后台怎么搜索都没有问题。

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]

**Comment by iamithunk** [comment]
后来发现后台设置 视频搜索规则 如果选中 副标 的话就会出现这个问题，不选副标就可以正确搜索了，应该搜索这个还有点小bug，望修复

**Comment by magicblack** [comment]
我这里重现不了。等发版本升级更新一下试试~
