### ISSUE TITLE
请问苹果cms v10怎么快速搬家？

### ISSUE THREAD

**Issue by renshuaibing** [magicblack/maccms10#81]
如题，1.之前我用的是谷歌云的700G HDD硬盘，现在想要换500G SSD硬盘，但谷歌云不能用磁盘快照创建大于500G 的Ssd，所以请问有办法快速复制磁盘里的东西吗？或其他方法达成vps搬家的效果？
宝塔面板的一键迁移太慢了，两天了程序还是处于发送数据库压缩中-33%的状态
2.如果我把原vps里的upload/vod/图片删除一部分，可以再次同步出来吗？

**Comment by s7webroot** [comment]
> 如题，1.之前我用的是谷歌云的700G HDD硬盘，现在想要换500G SSD硬盘，但谷歌云不能用磁盘快照创建大于500G 的Ssd，所以请问有办法快速复制磁盘里的东西吗？或其他方法达成vps搬家的效果？
> 宝塔面板的一键迁移太慢了，两天了程序还是处于发送数据库压缩中-33%的状态
> 2.如果我把原vps里的upload/vod/图片删除一部分，可以再次同步出来吗？

电影站如果不是自己做资源站，有几百G图片吗？还是几百G啥？
数据库应该怎么也就几百M？导出数据库，复制网站程序文件到新的服务器，导入数据，这样不行？是我孤陋寡闻了吗？

**Comment by s7webroot** [comment]
图片同步过一次之后，在数据库了应该已经保存了本地路径了，没法再次同步

**Comment by renshuaibing** [comment]
资讯，漫画，小说，影视，现在占了516G的空间

**Comment by magicblack** [comment]
厉害了。。。好像没什么太好的办法

**Comment by s7webroot** [comment]
确实够厉害
~~大佬

**Comment by s7webroot** [comment]
> 数据库大概12G左右

搜索的时候慢不慢？

**Comment by renshuaibing** [comment]
搜索一次要两三秒一次左右的反应时间，搜索间隔10s，勉强还行

**Comment by s7webroot** [comment]
> 搜索一次要两三秒一次左右的反应时间，搜索间隔10s，勉强还行

大佬有没有100万数据？我正想做一个几千万数据的，不知道用什么CMS好，V10各项功能都很合适，就是数据量大了不知道搜索怎么整合

**Comment by renshuaibing** [comment]
252w左右，整合影视，明星，资讯或其他搜索是吧？看老王有没有好方法适配search/art,/vod,/actor

**Comment by s7webroot** [comment]
> 252w左右，整合影视，明星，资讯或其他搜索是吧？看老王有没有好方法适配search/art,/vod,/actor

我不做影视，想做其他的，但是数据量有点大~怎么着也有几千万的条

**Comment by renshuaibing** [comment]
整合第三方站内搜索₍ᐢ •⌄• ᐢ₎

**Comment by s7webroot** [comment]
> 整合第三方站内搜索₍ᐢ •⌄• ᐢ₎

搜索引擎的站内搜索要等他先收录，我是说筛选那一块有点麻烦~~~~
