### ISSUE TITLE
关于附件管理annex数据数量的问题

### ISSUE THREAD

**Issue by Carodia** [magicblack/maccms10#810]
本地测试加入七万数据后，vod_annex表中的数据量达到了1900多万条，大小到了2G多，请问老师这是怎么回事？

**Comment by magicblack** [comment]
看看表中的内容是哪些~ 
我这里测试大部分是采集的时候下载到本地的图片附件索引信息，你这个数量级确实有些大，也和你采集的内容包含的图片数量有关。

**Comment by Carodia** [comment]
我用基础-附件管理-附件初始化之后就是这个样子了

**Comment by magicblack** [comment]
初始化会将你数据库里所有视频、文章、专题、分类、演员等包含的图片添加到附件表，如果原始数据很大，附件表就会大。
