### ISSUE TITLE
两个建议，Player.js中能否增加一个PlayTitle影片名称的参数？

### ISSUE THREAD

**Issue by wowo344** [magicblack/maccms10#811]
1.  Player.js中已有PlayUrl、Sid、Nid等，是否能增加一个PlayTitle影片名称的参数？ 用来调外部播放器时， 用来显示水印或者其它的操作。 
2.  后台视频列表中， 建议增加周人气、日人气这类常用的字段， 方便站长运营和视频内容。

**Comment by maigosama** [comment]
如果可以的话，还想多增加一个演员的参数，同调用外部播放器时想显示出来

**Comment by magicblack** [comment]
麻烦提供一个调用外部播放器的场景，比如引入链接，参数怎么传递等~

**Comment by jackrebel** [comment]
> 麻烦提供一个调用外部播放器的场景，比如引入链接，参数怎么传递等~
 我也有这个需求， 用来显示影片的弹幕。  根据影片名称去检索对应的弹幕， 类似这种：
<iframe border="0" src="//xxx.com/play/xxx.mp4?url='+MacPlayer.PlayUrl+'&next=下一集'+MacPlayer.PlayLinkNext+'**&vodname='+MacPlayer.PlayTitle**+'" width="100%" height="100%" marginWidth="0" frameSpacing="0" marginHeight="0" frameBorder="0" scrolling="no" vspale="0" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" noResize></iframe>

 很多个采集资源， 同一个影片的弹幕都分开了， 这样非常不好。  用影片名称去检索弹幕就可以避免这个问题。

**Comment by aruoop** [comment]
![QQ截图20220216020754](https://user-images.githubusercontent.com/42017510/154122990-60184d83-7c45-4135-a770-d15f6fbf447b.png)
像这样吗？

**Comment by jackrebel** [comment]
> ![QQ截图20220216020754](https://user-images.githubusercontent.com/42017510/154122990-60184d83-7c45-4135-a770-d15f6fbf447b.png) 像这样吗？

对。 你这还没带字幕的， 我要的是字莫按影片名能读取到。

**Comment by magicblack** [comment]
![image](https://user-images.githubusercontent.com/20452515/159121541-bd219339-3caf-4046-b3e5-50a71e5528be.png)
在播放页player_aaaa变量里增加了vod相关参数，为避免影响其他站长正常使用，本次不改js哈，需要的话自行改 /static/player/parse.js 二次开发~

**Comment by maigosama** [comment]
大佬万岁，今天试了一下，播放器能获取到视频信息了
