### ISSUE TITLE
webshell查杀工具 报毒

### ISSUE THREAD

**Issue by ycgz2008** [magicblack/maccms10#814]
![This is an image](https://s4.ax1x.com/2022/02/08/H18ShV.jpg)

**Comment by magicblack** [comment]
这个文件的内容比较多，具体报毒是多少行有没有？

**Comment by ycgz2008** [comment]
> 这个文件的内容比较多，具体报毒是多少行有没有？

没有找到，只是提示，可能是误报

**Comment by magicblack** [comment]
好的感谢反馈，代码均开源在github上，如果有问题可以再次打开~
