### ISSUE TITLE
你好，能否增加一个年份筛选的参数用于APP

### ISSUE THREAD

**Issue by a250059653** [magicblack/maccms10#815]
新年快乐，能否增加一个年份筛选的参数用于APP筛选功能的完善

**Comment by kaihuang666** [comment]
同求，能否为api增加一个year筛选的接口

**Comment by magicblack** [comment]
目前用的是哪个接口，/api.php/provide/vod/ 吗？

**Comment by a250059653** [comment]
/api.php/provide/vod/?ac=detail&t=

**Comment by a250059653** [comment]
> 目前用的是哪个接口，/api.php/provide/vod/ 吗？

/api.php/provide/vod/?ac=detail&t=

**Comment by magicblack** [comment]
近期优化下~

**Comment by feng99** [comment]
> 新年快乐，能否增加一个年份筛选的参数用于APP筛选功能的完善

您好 ,您的app 是自己写的原生?  还是把h5打包成App呀?

**Comment by a250059653** [comment]
> > 新年快乐，能否增加一个年份筛选的参数用于APP筛选功能的完善
> 
> 您好 ,您的app 是自己写的原生? 还是把h5打包成App呀?

原生，这边提供打包服务，有兴趣可以加我qq250059653

**Comment by magicblack** [comment]
1. 增加年份筛选参数year，year可为4位或9位长度字符，如：
    - year=2010（筛选2010年影片）
    - year=2008-2015（筛选2008年至2015年的影片）
2. 增加排序方向参数sort_direct，目前仅支持按vod_time排序：
    - sort_direct=desc，表示倒序（默认）
    - sort_direct=asc，表示正序
3. 增加单页数据量参数pagesize，最大为100，如：
    - pagesize=10，每页取10条
    - pagesize=50，每页取50条

**Comment by ichenc** [comment]
弹窗公告咋整啊
