### ISSUE TITLE
年份筛选可否实现年份范围的筛选？

### ISSUE THREAD

**Issue by iamithunk** [magicblack/maccms10#816]
目前程序好像只能在年份筛选时候具体到每一个年份，电影已经有上百年了，筛选页面会出现100来个年份做筛选？可否实现实现这种方式筛选，比如90年代电影 1990-1999年这个范围的筛选？

**Comment by a250059653** [comment]
> 目前程序好像只能在年份筛选时候具体到每一个年份，电影已经有上百年了，筛选页面会出现100来个年份做筛选？可否实现实现这种方式筛选，比如90年代电影 1990-1999年这个范围的筛选？

话说貌似没有筛选年份的api接口把

**Comment by magicblack** [comment]
这种需要改动结构了，实现比较困难~
