### ISSUE TITLE
评论和留言如果有某些符号不能正确显示

### ISSUE THREAD

**Issue by maigosama** [magicblack/maccms10#817]
**描述您的问题**  
评论和留言出现某些符号，例如省略号 &hellip;  ，后台会保存为 & amp;hellip;  ，前台则显示为 & hellip;

**Comment by magicblack** [comment]
这个是安全起见做了一些转义~

**Comment by maigosama** [comment]
嗯嗯，我是很理解这个初衷的，只是考虑到页面没有正确显示评论留言某些符号这个问题，用户可能会一脸懵逼⊙_⊙，想继续完善其健壮性

**Comment by maigosama** [comment]
弱弱问一声，可以完善吗？用户评论留言很多符号被转义了显示不正确呢，因为颜文字之类的挺常用的

**Comment by magicblack** [comment]
修复了，下个版本生效~

**Comment by maigosama** [comment]
膜拜大佬
