### ISSUE TITLE
/api.php/provide/vod/?ac=detail&ids=接口能否对该影片的播放量+1

### ISSUE THREAD

**Issue by a250059653** [magicblack/maccms10#818]
/api.php/provide/vod/?ac=detail&ids=接口能否对该影片的播放量+1

**Comment by a250059653** [comment]
影片中的vod_hits字段+1

**Comment by magicblack** [comment]
可以考虑，不过开启了可能影响部分采集站性能，下个版本加个开关实现吧~

**Comment by magicblack** [comment]
![image](https://user-images.githubusercontent.com/20452515/159120344-131e0314-8c26-4a05-927b-adc9fb6193cc.png)
支持了

**Comment by kkdysite** [comment]
这效率 嗷嗷的 赞一个，这个 真的是自己二开上的，没想到 今天作者支持了

**Comment by a250059653** [comment]
有需要打包App的可以加我QQ250059653
