### ISSUE TITLE
采集，自定义规则，已经采集好文章，内容发布。没有绑定分类的选项

### ISSUE THREAD

**Issue by sd231902** [magicblack/maccms10#820]
采集，自定义规则，已经采集好文章，内容发布。没有绑定分类的选项
真的，是采集的文章，真没找到绑定分类的选项。

**Comment by magicblack** [comment]
问一下采集源那边，其他人使用是否正常，是否有提供文章的分类信息~

**Comment by magicblack** [comment]
采集完之后，有一个中间页，页面顶部有对应分类的绑定，自己选择绑定下就可以了。
![image](https://user-images.githubusercontent.com/20452515/157047051-4cc80a8e-0d7d-482f-9950-5fc7f71640f7.png)
非技术问题可以在tg群求助，这边先关闭了哈~
