### ISSUE TITLE
老大,前台如何调用后台的多语言切换

### ISSUE THREAD

**Issue by xj811975** [magicblack/maccms10#821]
想弄个中英或者简繁的网站,但是感觉后台自带的多语言切换好厉害,好棒,想问问前台如何引用并由用户切换并不影响后台,虽然我拥i18n弄了一半,但是后台输出的翻译不了,用翻译插件又导致各种问题,~~~

**Comment by magicblack** [comment]
前台的多语言要在模板实现，简繁的前端调用个js就可以，中英的会麻烦些

**Comment by xj811975** [comment]
如何调用?可以给个例子吗?

**Comment by xj811975** [comment]
現在用js插件翻译 但是如果标题为繁体字的话,就搜索不到该视频

**Comment by magicblack** [comment]
简体、繁体搜索不支持相互匹配的。js的是在模板改，具体可自行搜索实现~
