### ISSUE TITLE
修改的播放器顺序，但是默认播放器没有修改

### ISSUE THREAD

**Issue by work53** [magicblack/maccms10#823]
就是想调整默认播放器，在后台调整了排序最大，前台也是排在第一位，但是不是默认选中状态，老王，这个怎么操作，或者哪位大佬告知小弟，我发现可以在某个视频播放组上移第一位就可以了，但是这样一个一个视频操作，太难了,或者有数据库批量修改的方法也可以，具体该怎么写？

				        {maccms:foreach name="obj.vod_play_list" id="vo"}
						<a href="javascript:void(0);" {if condition="$key eq 1"}class="active"{/if} alt="{$vo.player_info.show}"><i class="iconfont">&#xe62f;</i>&nbsp;{$vo.player_info.show}</a>{/maccms:foreach}

**Comment by work53** [comment]
已解决

**Comment by mxystv** [comment]
大佬，这个咋解决的，同样的问题
