### ISSUE TITLE
FAQ 12的Answer有问题

### ISSUE THREAD

**Issue by tian-le** [magicblack/maccms10#827]
**描述您的问题**  
在Nginx下使用maccms10, 伪静态规则配置帮助有问题.

12，nginx下除了首页其他都是404怎么办？修改一下伪静态规则，一般都可以解决了。 如果修改了后台文件入口admin.php，则改为对应的文件名。
if (!-e $request_filename) {
rewrite ^/index.php(.)$ /index.php?s=$1 last;
rewrite ^/admin.php(.)$ /admin.php?s=$1 last;
rewrite ^/api.php(.)$ /api.php?s=$1 last;
rewrite ^(.)$ /index.php?s=$1 last;
break;
}

折腾了半天, 发现上面的(.)都应该改成(.*), 虽说不是什么大问题, 但是还真的需要查一会儿才能发现这个问题.

**Comment by magicblack** [comment]
是```.*```，可能格式被github吃掉了，我优化下~
