### ISSUE TITLE
播放器参数设置里面的缓冲提示是否无效？

### ISSUE THREAD

**Issue by iamithunk** [magicblack/maccms10#829]
播放器参数设置有两个默认设置，一个预加载提示：/static/player/prestrain.html，一个是缓冲提示：/static/player/loading.html，为什么缓冲提示设置无效？确定有/static/player/loading.html这个文件。
请问player.js里面有句话：<iframe id="install" src="" frameBorder="0" scrolling="no" width="100%" height="100%" style="position:absolute;z-index:99998;display:none;"></iframe>
这个iframe是预留加载哪个页面的呢？

**Comment by magicblack** [comment]
自行调试观察执行流程~
