### ISSUE TITLE
部分图片无法显示

### ISSUE THREAD

**Issue by chengzf** [magicblack/maccms10#831]
查看源代码发现部分图片的地址是“/img.php?url=http://img9.doubanio.com/view/photo/s_ratio_poster/public/p2680311060.jpg”
而img.php本身是不存在的，这导致图片不能正常显示？
但img.php?url=后面那段地址才是正确的图片地址，而且是可以正常显示的。

**Comment by magicblack** [comment]
img.php这个是用来做图片代理的（部分图床防盗链）。一般是资源站返回的图片地址，找资源站要一下试试~
