### ISSUE TITLE
cms后台搜索优化开启后会导致影片搜索结果不一致

### ISSUE THREAD

**Issue by a250059653** [magicblack/maccms10#832]
cms后台搜索优化开启后会导致影片搜索结果不一致
![image](https://user-images.githubusercontent.com/52188308/155272835-118e19b4-2b54-4c26-9026-9edcd2e92b42.png)
![image](https://user-images.githubusercontent.com/52188308/155272885-e4773af5-3f60-4335-9753-610f594e359f.png)

**Comment by magicblack** [comment]
搜索优化缓存结果目前会被缓存2周，如果影响大可以关闭~
