### ISSUE TITLE
maccms10安装报错 fileinfo 显示支持（报红）

### ISSUE THREAD

**Issue by 13330863440** [magicblack/maccms10#833]
问题描述：
![image](https://user-images.githubusercontent.com/30033972/155439693-e234add8-a8d7-48da-b2ab-fd7c6d3ec151.png)

- fileinfo 结果显示支持，
但是点击下一步提示环境检测不通过
![image](https://user-images.githubusercontent.com/30033972/155439747-012c6d8c-39a4-428d-85df-c882aa1f18a0.png)

**Comment by magicblack** [comment]
重启php-fpm后重新安装看看~

**Comment by dary123** [comment]
> 重启php-fpm后重新安装看看~

重启了，还是显示如图上那样

**Comment by QiuZiXian** [comment]
解决了，需要安装fileinfo，然后重启php
