### ISSUE TITLE
php 8.1下 网站参数配置无法保存

### ISSUE THREAD

**Issue by iamithunk** [magicblack/maccms10#834]
php 8.1下 网站参数配置无法保存，一直正在保存数据中……，切换回php 7.4 保存正常

**Comment by magicblack** [comment]
本地测试php8保存正常，麻烦F12看下报错~

**Comment by iamithunk** [comment]
查看F12后，发现页面 /admin.php/admin/system/config.html   出现 Failed to load resource: the server responded with a status of 500 () 错误。详细错误信息为： 类型错误: join(): Argument #1 ($pieces) must be of type array, string given

**Comment by iamithunk** [comment]
同时，后台还发现一个错误提示，是否顺便也修正下：Mixed Content: The page at 'https://www.ifengmovie.com/ithunk.php/admin/index/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://update.maccms.la/v10/check/version'. This request has been blocked; the content must be served over HTTPS.

**Comment by magicblack** [comment]
感谢反馈。问题已定位到，将在下个版本修复~

**Comment by iamithunk** [comment]
PHP8.1下的这个错误依然没有修正
