### ISSUE TITLE
建议优化图片二次更新流程

### ISSUE THREAD

**Issue by Freenessfish** [magicblack/maccms10#835]
问题重现：
- 二次更新勾选了图片；
- 当资源站A挂了，这时候点同步图片，会发现本地下载了一个548 B统一大小的损坏图片文件（实际上资源站A的图片地址已经404）。这时候切换资源站B更新的时候，并不会二次更新新站源B的图片;
- 经过测试，如果手动编辑影片信息把图片地址删除后再次采集资源站B才会更新，但是下载图片地址是新的随机名，这会导致服务器上有大量重复的图片文件（经过对比测试后台的附件管理-检测无效文件、数据初始化 等操作均不能自动清除）。可实际情况不可能手动去一个一个检查删除有问题的图片的地址。

特此请求作者优化图片二更的相关流程，图片也算是重点内容，而且现在资源站失联频繁。
目前想到的建议解决方案是：

- 勾选了二次更新图片，每次采集强制更新图片地址，当保存(自动/手动)同步本地时，替换/覆盖原图片名（而不是生成新文件名）、更新annex表；
- 同时建议新增批量优化图片大小功能（如批量缩小大于指定大小的图片，因为官采图片都是几兆的大小）

**Comment by magicblack** [comment]
1. 需要更新图片的，通过数据库批量更新下图片字段的内容；
2. 服务器重复图片目前没有好的办法，生成规则根据时间来的，如果有存放空间问题，建议走图床；
3. 优化图片大小也属于图床功能，常见CDN都能解决，暂不考虑放在cms里实现~
