### ISSUE TITLE
地址二更规则

### ISSUE THREAD

**Issue by meidusha010** [magicblack/maccms10#836]
**描述您的问题**  
在开启地址二更规则合并时，应该判断一下地址是否重合，不是整体判断

**如何重现**  
1. 在多个相同类似资源站采集中，会有不同名称但地址相同的数据出现，如果使用替换，则有会将旧的数据替换掉，使用合并，会将两个相同地址合并出来，事实上如果只判断选集地址不判断当前选集的名称的话，就应该不会出现

**预期结果**  

资源整合会比较新且重复率下降

**版本信息:**  
 -  程序版本: 2022.1000.3029
 - 操作系统: Windows 10
 - 浏览器: chrome

**Comment by magicblack** [comment]
多资源场景不好优化了，考虑拆成多个站，每个站使用不同的资源站吧。
