### ISSUE TITLE
首页的视频 如何按照上映时间排序? 

### ISSUE THREAD

**Issue by feng99** [magicblack/maccms10#839]
**描述您的问题**  
首页的视频 如何按照上映时间排序? 现在默认看起来是按照采集时间排序的,就会导致很多 
几年前的老电影出现在首页

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: cms v10  
 - 操作系统: linux  php7.0
 - 浏览器:  chrome
 - 主题使用的是mojia

**其他备注信息**  
我应该修改哪个文件?
.html文件 还是.php文件?

和主题有关,还是和macms有关?

期待您的回复

**Comment by magicblack** [comment]
参考：说明文档/标签说明.txt 第400行开始，根据文档修改首页获取视频的模板标签（maccms:vod标签的by参数）。需要改.html，主题相关的~
