### ISSUE TITLE
There are multiple reflective XSS vulnerabilities in the website

### ISSUE THREAD

**Issue by kpa1on** [magicblack/maccms10#840]
Vulnerability name：Reflective XSS

Vulnerability level：Medium risk

Affected version：v2021.1000.1081<=v2022.1000.3029

Vulnerability location：Many places，Here are some places I found
1、url：http://127.0.0.1/maccms10/admin.php/admin/art/data.html?select=&input=&type=&status=&level=&lock=&pic=&order=&wd=           Affected parameters：select & input
2、url：http://127.0.0.1maccms10/admin.php/admin/website/data.html?select=&input=&type=&status=&level=&lock=&pic=&order=&wd=         Affected parameters：select & input
3、url：http://127.0.0.1maccms10/admin.php/admin/plog/index.html?type=&wd=         Affected parameters：wd
4、url：http://127.0.0.1maccms10/admin.php/admin/ulog/index.html?mid=&type=&wd=         Affected parameters：wd
5、url：http://127.0.0.1maccms10/admin.php/admin/vod/data.html?repeat=         Affected parameters：repeat

Verification process：
Get administrator cookies through reflective XSS：
First, the user logs in to the background
![image](https://user-images.githubusercontent.com/59214809/156299814-e0f84147-53a1-4ed0-96a9-2b1dfa2fe833.png)
Then we make a payad that can get cookies by using the vulnerable URL，Send it to the victim or make it run by other means.
For example, here I choose this URL：[http://127.0.0.1/maccms10/admin123.php/admin/vod/data.html?repeat=%22%3E%3CScRiPt%3Ealert(document.cookie)%3C/ScRiPt%3E]
After the victim clicks, the cookie pops up successfully. Here, the XSS platform can also be used to accept the cookie.
![image](https://user-images.githubusercontent.com/59214809/156300247-fccf0c41-bec5-4f3b-b981-95922bdcb97f.png)
Other URLs are the same：
![image](https://user-images.githubusercontent.com/59214809/156300313-f204f505-c000-4d34-80d6-08a03135e951.png)
![image](https://user-images.githubusercontent.com/59214809/156300373-05372764-6b7c-4912-a22c-56850ebf49f5.png)

Repair method：
【1】HTML escape the input data so that it is not recognized as an executable script
【2】Filter the data according to the tags and attributes of the whitelist to clear the executable script (such as script tag, oneror attribute of img tag, etc.)

**Comment by magicblack** [comment]
thanks, will check and fix
