### ISSUE TITLE
扩展分类筛选数据，显示的影片不全是什么情况啊？

### ISSUE THREAD

**Issue by paxdiamon** [magicblack/maccms10#841]
通过扩展分类筛选 数据，显示的影片不全是什么情况啊？比如我家了100个纪录片，扩展分类填的纪录，然后vod/show筛选 “纪录” 数据可能只显示了60-70个？ 但是vod/type分类页面显示是全的
![image](https://user-images.githubusercontent.com/100766934/156342733-28e5d270-fd35-4652-a6ed-2dacccfbc9f2.png)
![image](https://user-images.githubusercontent.com/100766934/156342764-7d38c46c-03d2-4f75-96f3-128fd81c4372.png)
![image](https://user-images.githubusercontent.com/100766934/156342817-614325ec-fdf0-462f-9f7b-17bd702125e6.png)
![image](https://user-images.githubusercontent.com/100766934/156342847-f613f901-e6ac-44e9-a348-25aee6a40a0d.png)

**Comment by magicblack** [comment]
如果开启了 系统-网站参数配置-性能优化-视频搜索优化，先关闭「前台」试试~

**Comment by paxdiamon** [comment]
系统-网站参数配置-性能优化-视频搜索优化，关闭「前台」
 关闭后可以显示了，但是  [前台] 和 [采集]  不能同时关闭，如果两个都不勾上，保存后，会自动勾选 [前台]。

现在开 [前台] 会导致扩展分类显示不全， 开 [采集]  会导致  采集资源的时候速度非常慢。 想两个都关闭，又关闭不了。

**Comment by magicblack** [comment]
感谢反馈，是一个保存的小bug，下个版本将修复~
你可以先手动修改此文件： application/extra/maccms.php 
搜索 vod_search_optimise，将其后面的值设置为空，如图：
<img width="364" alt="image" src="https://user-images.githubusercontent.com/20452515/157044625-43d42c20-f700-4a3f-bd4d-2d6e3789d053.png">
