### ISSUE TITLE
关于站群功能没生效，想请教一下

### ISSUE THREAD

**Issue by maigosama** [magicblack/maccms10#844]
**描述您的问题**  
最近有使用站群功能的打算，于是测试了一下，发现并没有生效，觉得说不定是自己的配置问题。然后搜索了一下别人发的历史问题，看到去年9月17号也有人提过相同的问题。

站群功能除了域名、模板和模板目录这三个地方是影响到配置之外，还有其它导致不能生效的因素吗？这三个地方都分别测试过还是没成功，所以只能来请教大佬啦，麻烦啦

自己做的设置：
宝塔：站点绑定两个域名，使用第1个域名的ssl，不过两个域名都能正常访问
后台：开了伪静态，在站群管理配置里面填入了第2个域名的一级域名（二级域名也测试过），网站名称、keyword、描述都随便填了一串字符，模板选择那里选择过几个模板测试，模板目录html，广告目录ads。最后点保存，这个域名虽然能正常访问，但模板还是第1个域名的模板

**Comment by maigosama** [comment]
再次更新，原来不是证书的原因，而是因为我用了cdn转换了端口，在站群配置那里把端口号加上就ok了

**Comment by magicblack** [comment]
感谢反馈~
