### ISSUE TITLE
生成静态页面内容会失败自动退出

### ISSUE THREAD

**Issue by flyingfishstudio** [magicblack/maccms10#845]
生成选项选择生成内容页的静态页面时，执行半小时左右会失败自动退出。测试环境内容数据1万条

**如何重现**  
1.登陆后台
2.点击生成，生成选项
3.点击视频分类，全部内容

**预期结果**  
所有内容页静态页面成功生成

**版本信息:**  
 -  程序版本: [v2022.1000.3029]
 - 操作系统: [centos7]
 - 浏览器: [chrome]

**其他备注信息**

**Comment by magicblack** [comment]
"会失败自动退出" 请提供一下失败错误信息，以及自动退出后是什么样子的？

**Comment by magicblack** [comment]
可以找PC和WAP同一套的自适应模板来解决~

**Comment by flyingfishstudio** [comment]
大神能推荐一套模版么flyingfishstudio@outlook.com
make生成页面夜里出现了协议报错，关闭页面，重新点击未生成续传，一直卡住白屏，抓包就是一直在做checkcache,已经做了1个多小时。
![IMG_7303](https://user-images.githubusercontent.com/6603768/158523738-5d8265c4-fe44-4c90-a62e-ae97a0d991e4.jpg)

**Comment by magicblack** [comment]
模板可以tg群里问问群友。make生成如果量大，白天值守跑一下，或者找台服务器在服务器上运行浏览器跑吧~

**Comment by flyingfishstudio** [comment]
主要是资源有限，量比较大导致的问题，我把超时时间加大问题就解决了。感谢关注，只要能忍暂时还不想花费精力在界面上，所以您如果有能凑合用的模版可以分享一个过渡哈。
