### ISSUE TITLE
mysql 占用CPU 100%  有优化空间吗？

### ISSUE THREAD

**Issue by songguowei** [magicblack/maccms10#849]
最近每天晚上CPU 100% 然后重启一下mysql 过一会儿就会降下来，可以怎么优化一下
如果把数据库放在另一台服务器上   可以解决吗？

**Comment by magicblack** [comment]
可能是定期采集或者爬虫导致。尝试在后台开启 系统-网站参数-性能优化-视频搜索优化 选项来优化~
