### ISSUE TITLE
好多慢查询。 

### ISSUE THREAD

**Issue by wowo344** [magicblack/maccms10#850]
这是mysql慢查询日志，举例：
  SET timestamp=1646833004;
SELECT * FROM `mac_vod` WHERE  `vod_name` LIKE '%我们的婚姻%'  AND `vod_play_from` LIKE '%xxxxxxxxxxxx%'  AND (    vod_status=1 ) ORDER BY `vod_time` DESC LIMIT 0,20;

SET timestamp=1646832995;
SELECT * FROM `mac_vod` WHERE  `vod_name` LIKE '%神探夏洛克%'  AND `vod_play_from` LIKE '%xxxxxxxxxxxx%'  AND (    vod_status=1 ) ORDER BY `vod_time` DESC LIMIT 0,20;

 第一个vod_name的like %%我可以忍受，  为什么vod_play_form 也要like %....%,  这我就忍受不了啊。 
vod_play_form是固定的吧， 直接用=等于不行吗， 也要like全扫描？

8H16G机器， 人一多直接100%。

**Comment by magicblack** [comment]
感谢反馈，vod_play_form是固定的，已修复~ 其他慢查询可以尝试用后台 系统-网站参数-性能优化-视频搜索优化 选项来优化。

**Comment by wowo344** [comment]
> 感谢反馈，vod_play_form是固定的，已修复~ 其他慢查询可以尝试用后台 系统-网站参数-性能优化-视频搜索优化 选项来优化。

# User@Host: vod[vod] @ localhost [127.0.0.1]  Id: 32699718
# Query_time: 3.872432  Lock_time: 0.000146 Rows_sent: 27  Rows_examined: 211685
SET timestamp=1647006972;
SELECT * FROM `mac_vod` WHERE  `vod_status` = 1  AND `vod_year` IN ('2014')  AND `type_id` IN ('1','6','7','8','9','10','11','12','23')  AND (`vod_class` LIKE '%战争%') ORDER BY `vod_time` DESC LIMIT 48,48;

vod_class like '%xxxxxxx%'

vod_class应该也是固定的吧， 不用like。
