### ISSUE TITLE
1029火车头角色图片测试正常，入库图片为空，

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#852]
1029火车头角色图片测试正常，入库图片为空，

**Comment by aruoop** [comment]
![image](https://user-images.githubusercontent.com/42017510/157701471-75988b99-da2f-45ca-945c-db2a5cc913b9.png)
![image](https://user-images.githubusercontent.com/42017510/157701625-808c7055-b584-4711-9db6-3721141a5ca9.png)

**Comment by aruoop** [comment]
入库的时候不选同步图片，
入库完成后 有图片地址，点击手动同步图床显示下载成功，但是地址变为空白

**Comment by aruoop** [comment]
演员，视频图片同步图床正常，
就是角色无法同步

**Comment by magicblack** [comment]
检查一下采集到的数据流是否正常~

**Comment by aruoop** [comment]
> 检查一下采集到的数据流是否正常~

发现是图片403 应该是开了防盗链导致无法下载

**Comment by aruoop** [comment]
发现原因了，因为有视频存在的情况下，截图入库会失败
在没有视频存在的情况下可以正常入库

**Comment by magicblack** [comment]
看到你新提的issue了，目前没有好的办法，只能按新视频同步的方式来。

**Comment by aruoop** [comment]
发现一个问题，就是源站有截图内容 采集的后截图内容为空
