### ISSUE TITLE
防红防封跳转 开启后异常

### ISSUE THREAD

**Issue by Freenessfish** [magicblack/maccms10#853]
防红防封跳转 开启后，时常在vx里打开提示页复制链接或者右上角打开，但是这时即使自行打开浏览器输入网址访问，也是打开的提示页。
另一种情况则完全相反，vx、qq都是直接打开了完全没显示提示页。
以上情况在相同的手机上不同的时段打开随机出现。

测试环境：
开了缓存、Redis、Cloudflare、首页静态
iOS下的Safari、Chrome、Edge

**Comment by maigosama** [comment]
这个我之前测试过，可以开数据缓存，但不能开页面缓存和静态

**Comment by magicblack** [comment]
先按网友提供的思路尝试一下吧~

**Comment by Freenessfish** [comment]
这。。。我都测试过了当然知道不开缓存静态可以，但是需求就是在开的时候能有效，
并且开缓存静态CDN的需求是不可动摇的
