### ISSUE TITLE
升到最新版3029， 仍然有很多mysql慢查询， 人多cpu时不时会爆红。 

### ISSUE THREAD

**Issue by wowo344** [magicblack/maccms10#854]
服务器配置， 8H16G。mysql8.0  已经升到最新版3029。数据20W+， 
1.  后台已经开启"搜索优化==》前台、采集"， 
2.  开启了memcached数据缓存，页面缓存、 缓存时间3600秒。
3.  首页已经静态化。

sql慢日志：

SELECT * FROM `mac_vod` WHERE  `vod_status` = 1  AND `type_id` IN ('1','6','7','8','9','10','11','12','23') ORDER BY `vod_time` DESC LIMIT 66864,48;
# Time: 2022-03-11T06:00:38.889063Z
# User@Host: vod[vod] @ localhost [127.0.0.1]  Id: 32613030
# Query_time: 3.217183  Lock_time: 0.000120 Rows_sent: 48  Rows_examined: 285595
SET timestamp=1646978435;
SELECT * FROM `mac_vod` WHERE  `vod_status` = 1  AND `type_id` IN ('1','6','7','8','9','10','11','12','23') ORDER BY `vod_time` DESC LIMIT 73920,48;
# Time: 2022-03-11T06:00:44.164652Z
# User@Host: vod[vod] @ localhost [127.0.0.1]  Id: 32613042
# Query_time: 3.540619  Lock_time: 0.000113 Rows_sent: 15  Rows_examined: 211627
SET timestamp=1646978440;
SELECT * FROM `mac_vod` WHERE  `vod_status` = 1  AND `type_id` IN ('14')  AND (`vod_class` LIKE '%战争%') ORDER BY `vod_time` DESC LIMIT 0,48;
# Time: 2022-03-11T06:04:48.085584Z
# User@Host: vod[vod] @ localhost [127.0.0.1]  Id: 32613696
# Query_time: 3.316398  Lock_time: 0.000112 Rows_sent: 14  Rows_examined: 211627

SET timestamp=1646981054;
SELECT * FROM `mac_vod` WHERE  `vod_status` = 1  AND `vod_area` IN ('韩国')  AND `type_id` IN ('24','25','26','27','28') ORDER BY `vod_time` DESC LIMIT 0,48;

很多很多很多很多这类慢查询的日志。 

怎么样优化这类慢查询？

**Comment by wowo344** [comment]
// 是否开启请求缓存 true自动缓存 支持设置请求缓存规则
    'request_cache'          => true,
    // 请求缓存有效期
    'request_cache_expire'   => 3600,

已经开启全局请求缓存， 现在正是晚高峰。。。坐等效果。

**Comment by magicblack** [comment]
效果怎么样？欢迎反馈~

**Comment by magicblack** [comment]
vod_class有多个的情况

**Comment by magicblack** [comment]
站的数据量比较大，可考虑拆分，建议每个站不超过5w条数据。这个暂时关闭了，有需要请重新开一个新issue~

**Comment by wowo344** [comment]
> 效果怎么样？欢迎反馈~

开启后， 会让验证码失效。
