### ISSUE TITLE
火车头入库，有视频相同标题的情况下，二次更新入库无法更新截图

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#855]
在数据库有视频名称的情况下截图无法火车头入库

新视频可以正常入库，希望二次更新能增加截图更新选项

和同步截图到附件的选项

**Comment by aruoop** [comment]
希望增加一个同步截图到附件的选项

**Comment by magicblack** [comment]
这个实现起来也有点个性化了，可以把需要同步截图的视频挑出来删掉，重新从火车头同步一遍~

**Comment by aruoop** [comment]
> 这个实现起来也有点个性化了，可以把需要同步截图的视频挑出来删掉，重新从火车头同步一遍~

没办法像其他内容那样直接更新替换掉原来的吗？
