### ISSUE TITLE
请求添加阿里云oss和腾讯云的cos图床接口

### ISSUE THREAD

**Issue by Freenessfish** [magicblack/maccms10#856]
这两个主要的云还是很多人使用的，
请求添加这两个作为默认图床选项：
可选项: 国内版、国际版、CDN配置

**Comment by lonhowe** [comment]
七牛太难用了！

**Comment by magicblack** [comment]
你的这个需求，可以用这个方案实现：
1. 图片下载到本地
2. 配置第三方图床，回源到本地图片的目录（图床没图片时，会自动从源里抓取，回源之后就保存在图床里了）
3. 配置maccms图片访问域名，使图片从步骤2里的图床获取
