### ISSUE TITLE
关于分布式数据库！

### ISSUE THREAD

**Issue by songguowei** [magicblack/maccms10#859]
开了分布式数据库，主从分离，然后从服务器cpu就被mysql占满了
并发直接就1000多了
不开分布式数据库的时候，主服务器并发才300多！
这是为什么

**Comment by magicblack** [comment]
这个问题我没遇到过，理论上开了主从，读就都落在从服务器上了。
你开启调试，看看查询语句方面有没有变化，会不会是流量涌入等其他原因造成~

**Comment by aruoop** [comment]
发现升级新版后cpu经常被数据库占满！流量没几个

**Comment by magicblack** [comment]
没有反馈这边先关闭了，如果还有问题麻烦重新开一个issue~
