### ISSUE TITLE
最新版本 采集 vod_play_url字段 入库空白。  xml模式。同样的资源 采用老版本可以正常入库

### ISSUE THREAD

**Issue by wasonCheung** [magicblack/maccms10#860]
**描述您的问题**  
最新版本 采集 vod_play_url字段 入库空白。  xml模式。同样的资源 采用老版本可以正常入库

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**  

**/app/commom/model/Collect.php:439**

添加打印  mac_echo(json_encode($v));

原始数据正常

<img width="1815" alt="360截图17860603365346" src="https://user-images.githubusercontent.com/89003922/159185037-3343490b-5e95-43cc-9425-4893fc67beb6.png">

**Comment by magicblack** [comment]
和新版本无关。网站上有没有对应的播放器，没有播放器会清空播放链接~

**Comment by wasonCheung** [comment]
> 没有播放器会清空链接~

我说呢，刚升级的最新版本。之前一直用的几年前的版本了。修改哪里才能入库呢，我一直用的都是自己的播放器。感谢答复

**Comment by magicblack** [comment]
在播放器那里添加对应播放器~
