### ISSUE TITLE
采资源库图片同步第三方上传失败的时候,希望不要改数据库并删除本地图片

### ISSUE THREAD

**Issue by kkdysite** [magicblack/maccms10#861]
**描述您的问题**  
在使用第三方 图床的时候,因为资源库的图片有的过大或者其他问题,会上传失败,但是本地会留一个图片并且数据库地址也是本地的.自己清理还需要再去数据库  (实际是无法清理的,因为还要逐条去搜资源库的图片)

希望上传失败的时候 本地图片自己删掉,然后数据库的图片维持和资源库一致就好了.

**其他备注信息**

**Comment by magicblack** [comment]
目前的规则是：如果开启同步图片，就会下载图片到本地。再根据配置的图片存储方式，决定是否上传到远程及是否保留本地。
如果下载图片到本地时，失败了，则数据库直接用资源库的地址（远程）；
如果上传到远程时，失败了，就会使用下载到本地的图片地址（本地）。

你这里的前提是开启了同步图片，只要下载图片到本地成功，就不会用资源库的地址了。这个实现目的是尽可能保证图片可被访问（资源库不稳定等）。

你的这个需求，或许需要自己动手实现一下比较好。有个简单的方案可供参考：
1. 图片下载到本地
2. 配置第三方图床，回源到本地图片的目录（图床没图片时，会自动从源里抓取，回源之后就保存在图床里了）
3. 配置maccms图片访问域名，使图片从步骤2里的图床获取
