### ISSUE TITLE
火车头采集，更新时间被程序系统时间替换，如果解决！

### ISSUE THREAD

**Issue by yvcool** [magicblack/maccms10#862]
火车采集，发布过去的更新时间被程序自动替换为当前时间。而不是采集的更新时间！这个怎么解决！

**如何重现**  

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by magicblack** [comment]
更新时间是固定当前的。新版增加支持了传入字段 vod_time_update，具体参考稍后的提交。

**Comment by nguyenloc879** [comment]
![image](https://user-images.githubusercontent.com/73431662/169019652-6de44993-b36f-496b-a3f3-cdb0f9eb8790.png)
help me
