### ISSUE TITLE
老大！能否优化下，采集时，忽略标题空格，现在同一片名有空格和无空格，会是2部！

### ISSUE THREAD

**Issue by skyccpbx** [magicblack/maccms10#864]
老大！能否优化下，采集时，忽略标题空格，现在同一片名有空格和无空格，会是2部！
例如：行尸走肉第一季 -- 行尸走肉 第一季 -- 行尸走肉  第一季
只要有空格都会重复采集！会早上很多重复资源！

**Comment by magicblack** [comment]
试试名称同义词替换功能~

**Comment by skyccpbx** [comment]
试过了名称同义词替换功能，空格数量不同还是 会造成重复，不是吧，希望老大吧标题片名空格直接个过滤掉吧！！

**Comment by maigosama** [comment]
试试这样？“ =”  （引号去掉）

**Comment by magicblack** [comment]
采集的数据源比较多？如果单一数据源不会有这个问题，多个数据源，需要自定义多种维度的替换规则了。名称中空格都去掉又会影响正常场景中的空格需求，不好界定。你自己定义名称同义词吧，多定些规则（如 走肉 第一季=走肉第一季）~
