### ISSUE TITLE
maccms前台搜索问题

### ISSUE THREAD

**Issue by 1522582813** [magicblack/maccms10#867]
苹果cms后台搜索某一关键词可以全部展现，但是前台搜索同样的关键词，只展现一部分，不清楚是什么原因。如下图所示
![QQ截图20220403135135](https://user-images.githubusercontent.com/63383664/161414517-08587042-25a9-4843-9392-48c7d7375aa1.png)
![QQ截图20220403135142](https://user-images.githubusercontent.com/63383664/161414522-96250506-f076-424e-8229-1786cdf449f5.png)

**Comment by tomlei88** [comment]
这个我也遇到了！

**Comment by maigosama** [comment]
我也有这个问题，前台搜不到视频了

**Comment by maigosama** [comment]
补充：我把前台视频搜索优化关了，搞定啦，哈哈

**Comment by 1522582813** [comment]
> 补充：我把前台视频搜索优化关了，搞定啦，哈哈
怎么优化的，求解

**Comment by maigosama** [comment]
> > 补充：我把前台视频搜索优化关了，搞定啦，哈哈
> > 怎么优化的，求解

在后台网站参数把这个设置关了就可以了

**Comment by 1522582813** [comment]
> 

是吧这两个参数关了吗
![QQ截图20220410193432](https://user-images.githubusercontent.com/63383664/162616091-b798cff5-e139-468a-848a-4e89bd2e449d.png)
？

**Comment by magicblack** [comment]
开了搜索优化会缓存结果14天。可以在这里关掉：系统-网站参数配置-性能优化-视频搜索优化~
