### ISSUE TITLE
更新后出现的两个问题

### ISSUE THREAD

**Issue by SLi-Man** [magicblack/maccms10#868]
## Q1：后台搜索关键词点开第二页就会乱码编程空白
![Q1](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-7089ab17-28be-4047-a800-390e3e4f88d6/96f0c92e-c7a3-40db-82af-06c5dc478433.png)

## Q2：前台搜索一个视频没有搜到，后台添加了这个视频后，清除缓存，再次搜索还是搜不到
比如搜索：肖申克的救赎，数据库里没有所以搜不到，然后我添加了这部电影，再搜索：肖申克的救赎，还是没有，只有换别的关键词搜索才可以搜到

**Comment by tomlei88** [comment]
我也遇到搜索不显示内容的，数据库里明明有，这两个问题我也遇到了。

**Comment by paxdiamon** [comment]
这两个问题我也遇到了。一个站环境是linux + nginx 会出现这两个问题 ,  另外一个站环境是 windows+apache 没有这两个问题

**Comment by paxdiamon** [comment]
Q1：后台搜索关键词点开第二页就会乱码  空白
又试了一下，这个问题，搜索 如果是数字和英文，就可以翻页。如果搜索中文，就会出现上述问题。 可能是哪里的编码问题？

**Comment by magicblack** [comment]
问题1：将在下个版本修复。
问题2：默认开启了搜索缓存，结果会缓存2周。如果不希望用到搜索缓存，要在 系统-网站参数配置-性能优化-视频搜索优化，把前端和采集都取消勾选~
