### ISSUE TITLE
数据库导入问题

### ISSUE THREAD

**Issue by cceessff** [magicblack/maccms10#869]
**描述您的问题**  
数据库导入不应该用 Db::query(),应该用Db::execute(),否则如果使用了读写分离的话会出现问题

**Comment by magicblack** [comment]
我查看了代码，database.php里的内容最后是通过execute执行的。你说的导入是指哪个地方，给一下具体文件和行数。或者你直接改了发起PR~

**Comment by magicblack** [comment]
这个先关闭了，有进一步的讨论可以重新打开。

**Comment by cceessff** [comment]
application/common/util/Database.php 文件第180行
