### ISSUE TITLE
网站参数配置保存提示类不存在

### ISSUE THREAD

**Issue by Jackzyy** [magicblack/maccms10#87]
错误提示：
![image](https://user-images.githubusercontent.com/39424122/67742133-1f411080-fa56-11e9-83af-fe6175bcce61.png)
版本：
![image](https://user-images.githubusercontent.com/39424122/67742292-9c6c8580-fa56-11e9-8a44-7d68321e6faf.png)

**Comment by magicblack** [comment]
包里少了个文件，下载离线包，覆盖 \application\common\validate 目录即可。

**Comment by Jackzyy** [comment]
> 包里少了个文件，下载离线包，覆盖 \application\common\validate 目录即可。
> 或者 修改本地版本号小于1018，重新在线升级。

下载离线包后保存已正常
