### ISSUE TITLE
批量操作视频无法使用一直报参数错误

### ISSUE THREAD

**Issue by scxff1** [magicblack/maccms10#871]
批量操作视频无法使用一直报参数错误

**截图**  
![Screenshot (13)](https://user-images.githubusercontent.com/103019170/161683193-4d49199f-5888-4e06-a515-96b84409fc9a.png)

**Comment by magicblack** [comment]
请提供一下这个页面之前选择的参数~

**Comment by magicblack** [comment]
这个先关闭了，有进一步的讨论可以重新打开。
