### ISSUE TITLE
修改会员分组失败

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#872]
**描述您的问题**  
修改会员分组失败

**如何重现**  
在后台将一个会员从默认会员修改为vip会员失败

**版本信息:**  
 -  程序版本: [2022.1000.3030]
 - 操作系统: [Windows 11]
 - 浏览器: [chrome]

**其他备注信息**

**Comment by magicblack** [comment]
请同时将他的【包时截止】改成一个未来时间，且小于2049年试试~
