### ISSUE TITLE
非常希望优化对视频采集的图片不成功的处理

### ISSUE THREAD

**Issue by maigosama** [magicblack/maccms10#873]
**描述您的问题**  

为了避免视频重复，目前我是把一个资源站作为主资源，其它资源站只更新，我是把图片保存到本地的，但是主资源站有些图片采集不了的话，后台会自动生成一个几百字节的jpg文件，用文本打开后内容如下。由于有这样的一个文件占了个坑，导致没办法由其它资源站更新时自动补上图片，不知大佬有没有办法优化呢。例如增加一个采集判断，如果视频图片文件大小小于4K就覆盖掉，之类的

![image](https://user-images.githubusercontent.com/98445209/162611290-c97edc3f-6165-486d-83ec-c061cb1fcdab.png)

**Comment by Carodia** [comment]
我也一直有这个困扰，一直没好意思跟老大讲，就自己拼凑了一个方法。
代码如下：
if (strpos(',' . $config['uprule'], 'j')!==false && (substr($info["vod_pic"], 0, 5) == "/http" || substr($info["vod_pic"], 0, 4) == "http" || strpos($info["vod_pic"], 'http') !== false || empty($info['vod_pic']) || (exif_imagetype($GLOBALS['config']['upload']['remoteurl'].$info['vod_pic']) === false && exif_imagetype($info['vod_pic']) === false ))) {
                        	    $pa = mac_convert_encoding($info['vod_pic'],"UTF-8","GB2312");
                                if(file_exists($pa)){ @unlink($pa); }
                            $tmp = $this->syncImages($config_sync_pic, $v['vod_pic'],'vod');
                            $update['vod_pic'] = (string)$tmp['pic'];
                            $msg =$tmp['msg'];
                        }
上面的代码是application/common/model/collect.php 里面vod部分的。
/http 是因为我测试的时候，有时候远程没有反应，系统会自动在http远程链接前面加右斜杠，同步图片时无法同步。
$GLOBALS['config']['upload']['remoteurl'].$info['vod_pic'] 因为我测试空间太小，一部分图片剪切转移到了另外一个远程地址。
以上基本只实现了本地图片如果损坏，则在重复采集时，如果本地图片已经损坏或者远程文件夹里仍然有漏网之鱼的话，会将本地的损坏文件删除并通过新地址下载图片进行替换。当然如果远端文件夹里有损坏图片，也会重新将新图片下载到本地，远程的图片删不掉，一般我都是把损坏的图片手动删除以后再上传到远程空间。
使用上面的代码，还需要在后台——系统——采集参数配置——视频采集设置——二次更新规则里选上“图片”这一项。

想要更完美，静等老大的法子了！

**Comment by maigosama** [comment]
> 我也一直有这个困扰，一直没好意思跟老大讲，就自己拼凑了一个方法。 代码如下： if (strpos(',' . $config['uprule'], 'j')!==false && (substr($info["vod_pic"], 0, 5) == "/http" || substr($info["vod_pic"], 0, 4) == "http" || strpos($info["vod_pic"], 'http') !== false || empty($info['vod_pic']) || (exif_imagetype($GLOBALS['config']['upload']['remoteurl'].$info['vod_pic']) === false && exif_imagetype($info['vod_pic']) === false ))) { $pa = mac_convert_encoding($info['vod_pic'],"UTF-8","GB2312"); if(file_exists($pa)){ @Unlink($pa); } $tmp = $this->syncImages($config_sync_pic, $v['vod_pic'],'vod'); $update['vod_pic'] = (string)$tmp['pic']; $msg =$tmp['msg']; } 上面的代码是application/common/model/collect.php 里面vod部分的。 /http 是因为我测试的时候，有时候远程没有反应，系统会自动在http远程链接前面加右斜杠，同步图片时无法同步。 $GLOBALS['config']['upload']['remoteurl'].$info['vod_pic'] 因为我测试空间太小，一部分图片剪切转移到了另外一个远程地址。 以上基本只实现了本地图片如果损坏，则在重复采集时，如果本地图片已经损坏或者远程文件夹里仍然有漏网之鱼的话，会将本地的损坏文件删除并通过新地址下载图片进行替换。当然如果远端文件夹里有损坏图片，也会重新将新图片下载到本地，远程的图片删不掉，一般我都是把损坏的图片手动删除以后再上传到远程空间。 使用上面的代码，还需要在后台——系统——采集参数配置——视频采集设置——二次更新规则里选上“图片”这一项。
> 
> 想要更完美，静等老大的法子了！

感觉你的方法对于我的情况也够用了，我的图片只保存在本地。
最后静等大佬更新！

**Comment by magicblack** [comment]
> 

能否将你的修改做一个Pull-Request，这边可以合并~

**Comment by magicblack** [comment]
换了个方式实现，在保存图片的时候判断是否是真实图片。有兴趣可以看下是否还有优化空间~
