### ISSUE TITLE
路由规则/actor/show/错误

### ISSUE THREAD

**Issue by lonhowe** [magicblack/maccms10#874]
默认的路由规则中actorshow/<id>-<area?>-<blood?>-<by?>-<letter?>-<level?>-<order?>-<page?>-<sex?>-<starsign?>   => actor/show   在访问/actor/show/后，显示框架错误，临时添加了actor/show/ => actor/show解决了，请看看是不是哪里有问题。
苹果CMS10 最新版的3030

**Comment by magicblack** [comment]
你好，目前无法重现，你先用此方法解决，后续有其他人遇到我再看看~
