### ISSUE TITLE
建议把扩展标签的空格分割判断剔除

### ISSUE THREAD

**Issue by zmmx** [magicblack/maccms10#875]
建议把扩展标签的空格分隔判断剔除，只用“,”这个作为唯一分隔判断。不然很多英文词组会被错误分割。

**Comment by Carodia** [comment]
application/common.php
以下是代码：
function mac_url_create($str,$type='actor',$flag='vod',$ac='search',$sp='&nbsp;')
{
    if(!$str){
        return '未知';
    }
    $res = [];
    **//QINGUA 中文关键词使用空格判断，英文不用空格，考虑英文名中间是空格分隔的问题
    if(preg_match("/[\x{2E80}-\x{9FFF}]+/u",$str)){
        $str = str_replace(array(' / ','/','|',',','，',' ',',,'),',',$str);
        $str = trim($str,',');
    } else {
        $str = str_replace(array('/','|',',','，',',,'),',',$str);
        $str = trim($str,','); 
    }**
    $arr = explode(',',$str);
    foreach($arr as $k=>$v){
        $res[$k] = '<a href="'.mac_url($flag.'/'.$ac,[$type=>$v]).'" target="_blank">'.$v.'</a>'.$sp;
    }
    return implode('',$res);
}
上面是我自己现在使用的方法，主要是加了一个中英文判断，分别处理。主要是针对我自己测试时遇到的问题修改的，不过您说的空格问题应该是能解决的。
声明一下，我只是小白，一般都是遇到了问题，根据自己想要达成的想法，然后百度、谷歌一通，找到就啪啪，找不到就视而不见。
您可以尝试一下，完美的方法还是要等老大有时间来处理了！

**Comment by magicblack** [comment]
@Carodia 感谢。这边再优化了一下，支持兼容中英文混合情况下标签分隔包含空格的处理（如演员有： 张三，李四，Jack Ma）。
