### ISSUE TITLE
用户登录和注册页面出现500的错误提示

### ISSUE THREAD

**Issue by bioger** [magicblack/maccms10#877]
宝塔ng服务器，php7.4，苹果最新版，问题如图，上个月出现过，后来不知道怎么回事自动好了，现在又出现这个问题了，不知道怎么解决

**Comment by bioger** [comment]
图片怎么传不上去？
页面：index.php/user/login.html
错误提示：Failed to load resource: the server responded with a status of 500 ()

**Comment by magicblack** [comment]
无法重现，麻烦再上传截图看看。或者看下你网站的日志，对应500错误将日志贴出来~

**Comment by bioger** [comment]
您好，您的邮件已经收到，我会尽快处理，请您耐心等待...

**Comment by bioger** [comment]
具体解决办法是把性能优化里面的缓存全部关闭，就正常了，现在我也无法重现问题

**Comment by bioger** [comment]
现在关于性能优化的设置，发现有一些问题：
1、开启file缓存后，会把服务器的磁盘占满，有没有限制缓存占用空间的办法，或者像监控一样缓存达到一定大小后自动删除旧的缓存
2、后台测试连接成功，开启redis后，可能是redis的内存问题，redis会挂掉
3、后台测试连接成功，开启memched后，视频详情页提示如下：亲爱的：您没有权限访问此数据，请升级会员 页面自动 跳转 ，

**Comment by bioger** [comment]
宝塔Nginx环境

**Comment by bioger** [comment]
> 无法重现，麻烦再上传截图看看。或者看下你网站的日志，对应500错误将日志贴出来~

jquery.min.js:2          POST https://www.hke8.com/user/login.html 500
send @ jquery.min.js:2
ajax @ jquery.min.js:2
（匿名） @ login:190
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

昨天又出现这个问题了，js提示这个问题

**Comment by wowo344** [comment]
> > 无法重现，麻烦再上传截图看看。或者看下你网站的日志，对应500错误将日志贴出来~
> 
> jquery.min.js:2 POST https://www.hke8.com/user/login.html 500 send @ jquery.min.js:2 ajax @ jquery.min.js:2 （匿名） @ login:190 dispatch @ jquery.min.js:2 y.handle @ jquery.min.js:2
> 
> 昨天又出现这个问题了，js提示这个问题

你应该F12， 去点击那个500红的请求地址， 然后看下右侧“预览”出来的消息。  这样才能诊断问题。

**Comment by bioger** [comment]
您好，您的邮件已经收到，我会尽快处理，请您耐心等待...

**Comment by magicblack** [comment]
> 现在关于性能优化的设置，发现有一些问题： 1、开启file缓存后，会把服务器的磁盘占满，有没有限制缓存占用空间的办法，或者像监控一样缓存达到一定大小后自动删除旧的缓存 2、后台测试连接成功，开启redis后，可能是redis的内存问题，redis会挂掉 3、后台测试连接成功，开启memched后，视频详情页提示如下：亲爱的：您没有权限访问此数据，请升级会员 页面自动 跳转 ，

1暂不支持，宝塔有插件可以支持磁盘容量监控~
2和3需要你再排查，环境不同这边无法具体处理~

**Comment by magicblack** [comment]
这个issue先关闭，如果还有问题请重新提一个新issue。
