### ISSUE TITLE
关于连载集数更新的建议

### ISSUE THREAD

**Issue by philipsc** [magicblack/maccms10#878]
**描述您的问题**  
连载集数更新逻辑问题。

**如何重现**  
当同时采集多个资源站的时候，A资源站连载集数为22，B资源站连载集数为18，这时如果B资源站后更新就会把最新连载集数22覆盖掉，连载数变成18。

**预期结果**  
希望可以在更新入库的时候对比当前连载数大小，比如当前连载数为22，采集B资源站的连载集数为18，18<22则不更新连载数，这样连载集数始终显示为最大数。

**Comment by shangxin-lazy** [comment]
暂同，很需要这个功能

**Comment by magicblack** [comment]
采集配置里，地址二更规则配置为【合并】能否解决这个问题？

**Comment by shangxin-lazy** [comment]
> 采集配置里，地址二更规则配置为【合并】能否解决这个问题？

貌似不行

**Comment by magicblack** [comment]
好的，为了不影响其他站长的使用，这边加个【集数多优先】的二更规则，到时候你们选择上~
![image](https://user-images.githubusercontent.com/20452515/168472745-77ec006e-5fa0-4b15-aed0-16377ac64a48.png)

**Comment by philipsc** [comment]
> 好的，为了不影响其他站长的使用，这边加个【集数多优先】的二更规则，到时候你们选择上~ ![image](https://user-images.githubusercontent.com/20452515/168472745-77ec006e-5fa0-4b15-aed0-16377ac64a48.png)

这不对吧，跟我想的不是一回事啊。。。这样就意味着A、B两个资源站只更新集数比较多的那个吗？单实际他们都是分别在A、B两个播放器下的啊，只是可能B资源站更新的慢一点，采集还是要更新B资源站地址的 只是不更新B资源站的连载数。

A播放器对应A资源站
B播放器对应B资源站

A连载数为22
B连载数为18
采集的时候A、B两个地址都要更新的，只是如果先采集A 则系统连载数更新为22，再采集B资源站的时候 B资源站的连载数为18小于系统连载数22，则只更新地址不更新连载数。

**Comment by magicblack** [comment]
【不更新连载数】 具体影响的是哪个地方的值？麻烦截图贴一下~

**Comment by philipsc** [comment]
![QQ截图20220515203334](https://user-images.githubusercontent.com/31801469/168473119-0f5c3dff-4cb2-4ef8-a8d3-fb6f5243a2b9.png)
我所说的连载集数指的是这个地方的数据。

**Comment by magicblack** [comment]
了解，我想复杂了~ 那明白你意思了，我处理下。

**Comment by philipsc** [comment]
> 了解，我想复杂了~ 那明白你意思了，我处理下。

thanks

**Comment by magicblack** [comment]
@philipsc 
1， 是不是可以理解为，这个连载数，取的是A和B2个资源的相对大值？ max(22, 18) = 22
2， 我看了一下这个字段是vod_serial，数据库里它是字符串类型的，有可能资源方填写的是字符吧？

**Comment by philipsc** [comment]
> @philipsc 1， 是不是可以理解为，这个连载数，取的是A和B2个资源的相对大值？ max(22, 18) = 22 2， 我看了一下这个字段是vod_serial，数据库里它是字符串类型的，有可能资源方填写的是字符吧？

不管是A还是B应该都是跟数据库的vod_serial相比取最大值，如果资源站是使用的苹果CMS做的  那这个地方应该是字符串，其他第三方的资源站是字符的话 您看怎么处理一下 跳过比较或转换后比较

**Comment by magicblack** [comment]
了解了，谢谢~

**Comment by shangxin-lazy** [comment]
大佬，是不是搞错了，我看更新的代码注释掉了，我还找了半天集数优先的开关

**Comment by magicblack** [comment]
> 

默认已经按资源站返回的集数多的优先了~
