### ISSUE TITLE
建议增强一下视频搜索功能吗？

### ISSUE THREAD

**Issue by panxinxc** [magicblack/maccms10#879]
目前v10只支持视频名称拼音副标tag演员导演这几个关键词搜索，在部分情况下搜索效果还是欠佳的，例如一个视频数据如下：
名称：《探索发现》 
播放地址：
20190426 蜀舟发现记一$url.mp4
20190427 蜀舟发现记二$url2.mp4

以如上数据为例，目前的搜索规则只能通过名称“探索发现”搜索到，如果用户在只知道或只想搜索“蜀舟发现记二”的话是搜索不到数据的，所以建议增强一下搜索功能，使其能够通过集名中“蜀舟发现记二”搜索并点击直接播放第二集。

**Comment by magicblack** [comment]
抱歉，目前搜索架构无法支持到，否则会占用更多的数据库CPU资源~
