### ISSUE TITLE
3030版本后台留言管理差不到用户的留言，数据库可以查询到

### ISSUE THREAD

**Issue by GitSarp** [magicblack/maccms10#881]
**描述您的问题**  
留言管理差不到用户的留言，数据库可以查询到

**如何重现**  

**预期结果**  
在后台留言管理管理用户留言

**截图**  
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/14067824/164141006-626e3797-27fa-40ff-aa4d-a5cc63c5cfb2.png">

**版本信息:**  
 -  程序版本: [2022.1000.3030]
 - 操作系统: [mac]
 - 浏览器: [chrome]

**Comment by magicblack** [comment]
无法重现。留言管理，管理的是用户在留言板上填写的内容；或许你需要的是“评论管理”，对应用户在视频下面发表的评论。
这边本地留言管理、评论管理均正常。

**Comment by maigosama** [comment]
是不是开了什么缓存啊

**Comment by GitSarp** [comment]
开了redis缓存，但是我记得好像清了缓存也没用。目前重新在新的服务器上部署了，未发现问题。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "magicblack/maccms10"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [magicblack/maccms10] 3030版本后台留言管理差不到用户的留言，数据库可以查询到 (Issue #881)





 
是不是开了什么缓存啊
