### ISSUE TITLE
大佬，二次采集建议优化一下，跪求

### ISSUE THREAD

**Issue by linkala** [magicblack/maccms10#882]
大佬，现在二次采集当不勾选图片时，影片中空图片，即使资源站有图片也无法采集更新；
但如果勾选了原来有地址的图片（非同步图片）也会被同步掉。
建议：能否优化为，当不勾选二次更新图片时，只对原影片中无图片和新增图片有影响，即同步图片，这样可以解决原来图片为空的BUG，也不会影响原来有影片的远程图片。

**Comment by wowo344** [comment]
我也觉得这个很重要，  资源站换了一波又一波， 图床挂了一批又一批的， 重新同步图片真的是个麻烦事情。 

检测图片有效可能会造成采集缓慢， 但是这个很重要。

**Comment by magicblack** [comment]
是否和这个问题类似？
https://github.com/magicblack/maccms10/issues/873

**Comment by linkala** [comment]
> 是否和这个问题类似？ #873
感谢大佬回复，不是一个问题，但是类似吧，我的问题主要针对同步图片时。
面临的问题：
一、当二次更新规则中不勾选图片，选择了同步图片到本地，这时如果一个影片为空图片地址，资源站也无法采集进去替换，图片还是空的。
二、当二次更新勾选图片时，选择了同步图片，可以替换为空地址图片的影片，但是同时也影响了原有速度不错的远程图片。

能否实现：
a、当二次采集时只影响影片为空的图片和新增的影片，不会对原有的影片中远程图片进行替换。
（而如果想全部图片同步时，选中菜单视频数据同步图片即可，不会有所冲突。）
b、采集资源时，筛选某图片地址，如puui.qpic.cn|douban.cn这种前缀的不进行同步，还调用原有的地址，其他的进行同步，也可以解决问题一二。

**Comment by magicblack** [comment]
a、为空的图片，是指图片地址是空白么？

这种情况可以用影子站的形式解决，把所有图片为空和不为空的数据分2个站，为空的全部同步，同步好再把数据导回原站即可。

你所提的issue属于很细节的优化需求，这个看起来反而会增加理解难度（什么时候更新、什么时候不更新，站长容易摸不着头脑），可能暂时不考虑实现~

**Comment by linkala** [comment]
> a、为空的图片，是指图片地址是空白么？
> 
> 这种情况可以用影子站的形式解决，把所有图片为空和不为空的数据分2个站，为空的全部同步，同步好再把数据导回原站即可。
> 
> 你所提的issue属于很细节的优化需求，这个看起来反而会增加理解难度（什么时候更新、什么时候不更新，站长容易摸不着头脑），可能暂时不考虑实现~

不仅仅是处理为空的图片，还有失效的某一些图片，采集的时候如果可以过滤一下，就更加完美了，我问了好多人都比较头痛这个问题。
