### ISSUE TITLE
希望可以更新下前台SID的问题

### ISSUE THREAD

**Issue by jhgjkbh** [magicblack/maccms10#883]
有A,B两个资源站，A是在排第一，B是排第二的，如果按正常来采集，A是优先，这样A的播放组的SID就是vodplay/22832-1-1.html这样，如果B的资源站更新，再更新A，A就变成了vodplay/22832-2-1.html。虽然可以列表里保持排序，但是播放页的SID就不一致了。

如果B站的资源有，而A资源没有，采集了之后，B的SID从1开始，毫无疑问，但是如果更新了A之后，这样A的资源变成SID1，而B的资源变成SID2。

这样可以保持一下资源的一致性，如果可以改一下最好，不管是采集入库的时候增加设置参数还是后期前台展现的时候可以自定义SID，这样可以将一些速度快的资源排前面，而速度较慢的资源做备用。

**Comment by philipsc** [comment]
如果我没理解错的话，同一个视频ID的SID代表的是播放器，如果要保持某个播放器始终排在第一位的话，首先设置播放器的排序（数值越大越靠前），然后在网站参数配置-预留参数-播放器顺序设置为全局即可。

**Comment by jhgjkbh** [comment]
> 如果我没理解错的话，同一个视频ID的SID代表的是播放器，如果要保持某个播放器始终排在第一位的话，首先设置播放器的排序（数值越大越靠前），然后在网站参数配置-预留参数-播放器顺序设置为全局即可。

理解错了，我说的SID，SID数值啊哥哥，后加入的播放地址，即使排在前面，也是2-1，-3-1这样的属性。
我的表达有误吗？

**Comment by magicblack** [comment]
我没有看明白。如果要实现你的需求，有什么好的处理办法吗？

**Comment by magicblack** [comment]
明白你的意思了，其实这个sid是根据写到vod里的链接顺序生成的，表明了一个取播放链接的指引。
这种情况一般是出现在多个资源站混合采集的情况下？可以考虑只保留一个较优质的资源站采集。
此调整影响面比较大，暂不打算实现~
