### ISSUE TITLE
希望在后台增加一个mac_vod_search表查询过期设置自定义选项

### ISSUE THREAD

**Issue by zmmx** [magicblack/maccms10#887]
14天有点太长了，很多数据刷新很不及时，建议增加自定义时长功能。

**Comment by hnityyy** [comment]
是的，，查询数据缓存时间太长，改短点或者后台自定义更好，，，，

**Comment by magicblack** [comment]
如果间隔时间太短，常常清理缓存反而会造成服务器压力增大。你们希望最低多少天？

**Comment by zmmx** [comment]
建议是直接在后台增加一个时间的设置，或者集成进api.php/timming/index 定时任务里 让站长自己按需设定 可以选择在服务器闲时更新缓存

**Comment by magicblack** [comment]
可以做配置项，但要看一下最低间隔需求是多少~

**Comment by magicblack** [comment]
已支持~
