### ISSUE TITLE
关于开放API播放组的一个问题

### ISSUE THREAD

**Issue by SLi-Man** [magicblack/maccms10#888]
开放API的指定播放组的问题：
A站开启了开放API并指定播放组为youku，B站打开A站采集后就只能看到播放数据【只有】youku的资源，如果一个数据有多个播放组就不会被显示在采集中，例如一个数据有两个播放组：youku,qiyi，开放API指定了youku后，这条数据就不会被纳入采集中

希望修复！！另外希望指定播放组能指定多个播放组

**Comment by magicblack** [comment]
已处理~

**Comment by philipsc** [comment]
最新版 2022.1000.3031，虽然可以指定多个播放组，但是如果指定了多个播放组，采集的时候会随机漏掉某个资源组的更新，比如资源站A开启了youku,iqiyi两个播放组，影片最开始只有youku资源，但下次更新添加了iqiyi资源，采集能看到新的iqiyi资源组，但是却更新不上。

**Comment by philipsc** [comment]
虽然不知道甜甜原来写法为什么会出这种BUG，但是我似乎已经解决了。
文件路径
/application/api/controller/Provide.php
注释第202-205行
新增206-209行
$res['list'][$k]['vod_play_from'] = $v['vod_play_from'];
$res['list'][$k]['vod_play_url'] = $v['vod_play_url'];
$res['list'][$k]['vod_play_server'] = $v['vod_play_server'];
$res['list'][$k]['vod_play_note'] = $v['vod_play_note'];

**Comment by magicblack** [comment]
如果只指定返回一个播放组，则只返回此播放组的播放数据。可以改成填写多个播放组，就能支持原样多返回了~
