### ISSUE TITLE
管理后面的会员参数配置里有两个注册开关

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#890]
如图
应该是前面的提示语写错了

![QQ截图20220509141820](https://user-images.githubusercontent.com/55046423/167351462-b3e364be-b8a4-4070-b6df-76c3848cc359.png)

**Comment by philipsc** [comment]
第二个应该是审核开关，哈哈  看开关值就明白了，标题不重要。。。

**Comment by magicblack** [comment]
感谢反馈，翻译问题，已修复~
