### ISSUE TITLE
求教：如何删除同一个播放器下的播放地址？

### ISSUE THREAD

**Issue by Carodia** [magicblack/maccms10#891]
老大好！
比如说在ckplayer播放组中，因为多个网站都是默认ckplayer，所以采集的时候会出现不同网站的m3u文件地址统统归在了一起。现在有的源站已经关闭了，造成很多的可用和不可用的地址共存，在播放页面出现很多的无用按钮。
我想知道如何能根据失效地址的域名关键词将失效地址从播放组中单独清除，并且不会影响到其他地址？
谢谢！

**Comment by magicblack** [comment]
后台没支持这个功能。自己写脚本查数据库，然后找到你想清除的，完成后再update回数据库吧~
