### ISSUE TITLE
版权提示设置为“ifram播放页跳转”时有问题

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#892]
![QQ截图20220510155925](https://user-images.githubusercontent.com/55046423/167579393-25dadf83-8533-4893-812b-2ef3b9178d16.png)

版权提示设置为“ifram播放页跳转”时有问题
如果视频没有设置跳转url，进入播放页时根本不使用copyright模板，而是直接使用了播放页模板进行了播放
视频设置了跳转url的时候不会有这个问题
版权提示设置为“内容页跳转”或“播放页跳转”时也都没有这个问题
这就造成了原本在一个copyright模板就可以处理完的所有情况，现在需要在播放页模板进行这一次额外的处理
建议去掉这个跳转url不能为空的限制

**Comment by magicblack** [comment]
记得处理过类似的issue，你看一下这个是否解决了你的问题？
https://github.com/magicblack/maccms10/issues/660

**Comment by lixuehan1234** [comment]
> 记得处理过类似的issue，你看一下这个是否解决了你的问题？ #660

并没有完全解决（最新版本的程序）
版权提示方式设置为”iframe播放页跳转“且视频跳转url为空时仍然直接调用了播放模板，而不是copyright模板
还是建议取消这个需要跳转url的限制~

**Comment by magicblack** [comment]
我看这里已经去掉了判断？
https://github.com/magicblack/maccms10/commit/2208631df945920c4a5cc5b47b672972e8998710

**Comment by lixuehan1234** [comment]
找到原因了！
![github](https://user-images.githubusercontent.com/55046423/168411695-2e720750-49ae-4bed-a407-5bd2c50b3dba.png)

application/common/controller/all.php 547行
这里还有一次限制，且只针对“iframe播放页跳转”这一种情况
删掉这个限制之后是正常的，应该就是它引起的~

**Comment by magicblack** [comment]
ok，我们加到master里去。
