### ISSUE TITLE
“采集参数配置--地址二更规则”配置对下载地址无效

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#893]
![QQ截图20220510161634](https://user-images.githubusercontent.com/55046423/167582348-547e57fb-889f-415f-8145-017d3b156ba5.png)

“采集参数配置--地址二更规则”配置对下载地址无效
这个设置项只对播放地址有效
无论这里设置成“替换”还是“合并”，下载地址一律都是直接替换
看了下源码
application\common\model\Collect.php文件里
只对采集到的播放地址进行了这个配置的判断处理，下载地址并没有进行处理
建议处理一下，多谢大佬~

**Comment by magicblack** [comment]
目前没有其他站长反馈，可能下载地址用的较少。你能读懂代码的话，可以clone一下，提个Pull request~

**Comment by lixuehan1234** [comment]
我只了解一点点皮毛，会看不会写 TT

我说一下我发现问题的位置吧

![QQ图片20220513123829](https://user-images.githubusercontent.com/55046423/168212233-8e80c772-330e-4c2f-8d90-e1d2bafb8974.png)

application\common\model\Collect.php 791行这里，对播放地址合并方式进行了判断处理

![222](https://user-images.githubusercontent.com/55046423/168212502-a2d8b7be-00ae-4851-aef4-c3d5c865bf5e.png)

但是855行这里，下载地址并没有进行合并方式的判断，直接就替换掉了

**Comment by magicblack** [comment]
好的，感谢反馈。已经修改了，发布后可以测试一下~
