### ISSUE TITLE
能否添加一个留言本昵称输出标签以及就用户隐私问题优化

### ISSUE THREAD

**Issue by shangxin-lazy** [magicblack/maccms10#898]
**描述您的问题**  

想请问下留言本的标签为何没有“用户昵称”，能否后继添加

我看了官方给出的{$vo.gbook_name}这个标签对应的是后台的“账号”，非“昵称”。

因为用户有些是使用手机号和qq号等联系方式作为“账号”，考虑到隐私问题，我是想获取“昵称”输出的。

或者说，官方能否就隐私的问题进行优化，例如*号隐藏?

**预期结果**  
添加留言本用户昵称标签，或者对于留言本和评论显示的名称进行部分*号隐藏

**Comment by shangxin-lazy** [comment]
对了，以及评论模块的{$vo.comment_name}标签也是对应用户的账号，能否也添加一个“昵称“标签呢

**Comment by maigosama** [comment]
这个问题从我刚开始用苹果cms的时候就发现了，没有昵称标签，后来我自己都忘了这件事了，静等大佬答复

**Comment by magicblack** [comment]
有部分站点用户是没有user_nick_name的，可能会导致空白。现在兼容了一下，优先使用用户的昵称，如果没有就使用用户名。
关于*号隐藏，你可以自己写一个函数实现，字符串函数比较简单。

**Comment by shangxin-lazy** [comment]
> 有部分站点用户是没有user_nick_name的，可能会导致空白。现在兼容了一下，优先使用用户的昵称，如果没有就使用用户名。 关于*号隐藏，你可以自己写一个函数实现，字符串函数比较简单。

标签不变是嘛。使用{$vo.gbook_name}以及{$vo.comment_name}标签，是优先使用用户的昵称，如果没有就使用用户名的
