### ISSUE TITLE
再次思考了一下关于视频名称空格的问题

### ISSUE THREAD

**Issue by maigosama** [magicblack/maccms10#899]
假如A资源某视频名称是 “12 3“
而B资源默认把所有视频空格都去掉了，所以视频名称变成“123“，导致B资源不能更新

其实之前也有人提到过类似的问题，虽然当时我觉得同义词替换可以用 “ =”，不过这个方法一刀切死的话，又导致所采集的视频名称完全没有空格变得很奇怪。如果把所有这样的视频都单独做同义词替换的话，数量又太多

我在想能否加个命令，仅在视频更新的过程中，把数据库中的视频名称，以及所采集资源中的视频名称都做去空格处理，然后再对比，这样子来解决呢？由于有同义词替换这个功能，所以去空格处理可以放到替换之后再执行

**Comment by maigosama** [comment]
我不会php，就大概表达一下想法

x=去空格（本地视频名称）
y=去空格（资源视频名称）
if x==y （更新y视频）
else （入库y视频）

大概这样子，嘿嘿

**Comment by jackrebel** [comment]
> 我不会php，就大概表达一下想法
> 
> 同义词替换后 x=去空格（本地视频名称） y=去空格（资源视频名称） if x==y （更新资源） else （资源视频名称 入库）
> 
> 大概这样子，嘿嘿

我也觉得， 大家都去掉空格去对比片名， 来判断是否重复可行。

**Comment by magicblack** [comment]
查询是否有重名使用了数据库筛选，已经有空格的数据已入库，筛选只能包含有空格。
这个功能比较个性化了，建议你多配置规则+数据库sql批量操作实现，我们暂时不做调整~

**Comment by maigosama** [comment]
至少，能否在资源选了“”只更新不新增“”的情况下加上这个 去空格对比 功能呢？

**Comment by maigosama** [comment]
如果手动独立每一条片名设置规则，工作量会异常庞大，因为某些资源站默认了所有视频都没有空格
