### ISSUE TITLE
王哥maccms10运行了半年后数据库造成cpu100%爆满有什么处理方法吗？

### ISSUE THREAD

**Issue by 1709926360** [magicblack/maccms10#90]
王哥maccms10运行了半年后数据库造成cpu100%爆满有什么处理方法吗？

**Comment by magicblack** [comment]
使用redis缓存，并且 静态首页。

**Comment by 1709926360** [comment]
我设置了，也都在使用，现在是数据库太大，我百度了一下需要优化数据库，说可以通过optimize来优化，但是我用了感觉效果步明显
