### ISSUE TITLE
请问大佬，评论和留言模板，输出内容的地方哪里改

### ISSUE THREAD

**Issue by shangxin-lazy** [magicblack/maccms10#900]
**描述您的问题**  
之前问了大佬关于留言昵称的问题，也问了关于*号隐藏手机号的问题。奈何本人是小白，百度了好久找到了一个解决方法，但是并不理想。所以，我想请教下大佬关于留言标签和模板标签的php文件实在哪里呢

**预期结果**  
我一开始的方案是直接在用户评论的时候对获取的用户名和昵称是手机号进行中间*号隐藏的，但是我所用的app不会走这个过程，直接是明文，导致网站会直接显示手机号，所以想请教大佬，了解一下在前端处理[就是模板标签获取用户名和昵称的过程中*号隐藏]

**Comment by shangxin-lazy** [comment]
我一开始的想法本末倒置了，现在的想法是数据库明文，前端密文。

**Comment by magicblack** [comment]
在app获取数据对应的接口里修改，可以本地搭好环境调试一下~

**Comment by shangxin-lazy** [comment]
> 在app获取数据对应的接口里修改，可以本地搭好环境调试一下~

app层面不行，因为app并不是我开发的，想从网站入手改下

**Comment by magicblack** [comment]
我的意思是，看看APP调用的是什么接口，在接口输出前做修改~

**Comment by shangxin-lazy** [comment]
> 我的意思是，看看APP调用的是什么接口，在接口输出前做修改~

开发者给调用接口加密了。。

**Comment by philipsc** [comment]
{$vo.gbook_name|mac_substring='5'}，你要的是这种吗？mac_substring需要显示几位数就写几

**Comment by shangxin-lazy** [comment]
> {$vo.gbook_name|mac_substring='5'}，你要的是这种吗？mac_substring需要显示几位数就写几

大佬，想请教下mac_substring是哪里获取的呢，我不想要鱼想要渔，谢谢

**Comment by magicblack** [comment]
> 

全局搜索就有了，在这里：

application/common.php line: 633
