### ISSUE TITLE
写模板，vod_play_list.urls 按集数倒序排的问题请教

### ISSUE THREAD

**Issue by jackrebel** [magicblack/maccms10#901]
{maccms:foreach name="obj.vod_play_list" id="vo"}
 
        {maccms:foreach name="vo.urls" id="vo2"   **by="nid" order="desc"**  }
        <a href="{:mac_url_vod_play($obj,['sid'=>$vo.sid,'nid'=>$vo2.nid])}" >{$vo2.name}</a>
        {/maccms:foreach}
     
{/maccms:foreach}

为什么 by="nid" order="desc"   按集数倒序排无效， 该怎么写？

**Comment by magicblack** [comment]
好像不支持这样写。你用php标签写原生语句实现试试，用sort、ksort这些排序函数就可以了~
