### ISSUE TITLE
请问下maccms数据库读写过多导致mysql吧cpu占满，想要升级配置应该选多cpu的服务器还是选算力高核心少的机器？

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#902]
请问下maccms数据库读写过多导致mysql吧cpu占满，
想要升级配置
应该选多cpu的服务器还是选算力高核心少的机器？
AMD5950X和双e5-2690
应该选哪个可以改善数据库红的问题

**Comment by magicblack** [comment]
尽量选择cpu算力高+磁盘性能好的~

**Comment by aruoop** [comment]
> 尝试选择cpu算力高+磁盘性能好~

amd5950x算力高，只有16核心32线程
双E5-2690 v4 算力低些，但是他有28核56线程
不知道哪个性能会更强点
