### ISSUE TITLE
希望可以支持emoji表情，目前好像输入emoji表情就无法提交留言了

### ISSUE THREAD

**Issue by yhx1798865406** [magicblack/maccms10#903]
希望可以支持emoji表情，目前好像输入emoji表情就无法提交留言了

**Comment by shangxin-lazy** [comment]
可以百度，对数据库的编码改一下就支持了

**Comment by yhx1798865406** [comment]
> 可以百度，对数据库的编码改一下就支持了

改成了utf8mb4  还是显示问号

**Comment by magicblack** [comment]
对应字段改对了吗？

> > 可以百度，对数据库的编码改一下就支持了
> 
> 改成了utf8mb4 还是显示问号

**Comment by magicblack** [comment]
数据库连接文件 application/database.php 里面的 charset 也要改成 utf8mb4 。
