### ISSUE TITLE
maccms10 后台首页刷新显示Html源代码

### ISSUE THREAD

**Issue by myxxl** [magicblack/maccms10#904]
maccms10 后台首页刷新显示Html源代码
![1212](https://user-images.githubusercontent.com/61246789/168524012-fbfd958a-8f72-4d38-be3d-5df7d32e8d73.png)

**Comment by shangxin-lazy** [comment]
查看下php版本

**Comment by myxxl** [comment]
> 查看下php版本

php 7.3

**Comment by myxxl** [comment]
> 查看下php版本

php 7.4

**Comment by magicblack** [comment]
清除本地缓存，重新输入后台地址~
