### ISSUE TITLE
关于备注更新被覆盖问题

### ISSUE THREAD

**Issue by shangxin-lazy** [magicblack/maccms10#905]
[关于连载集数更新问题](https://github.com/magicblack/maccms10/issues/878) 

这个问题和我想问的有异曲同工之处，我的问题是在备注方面的。A资源的备注是更新至x集;B资源的备注是更新至y集。且x≠y，由于不同资源站更新进度不同，备注也不同(例如官方番剧总比资源站的番剧更新慢)，就会导致定时采集的时候，一会采到更新慢的，一会采到更新快的。使得备注在x和y两者中反复横跳。而且我看大多数的站都会使用备注这个方式告诉访客当前影片的更新进度，如果用户不了解这个机制的话，是不会想点进来看的。所以想问下大佬，这个办法有没有办法处理。备注处理起来还是比较麻烦的。

因为他含文字，而且不同资源站的备注格式也不同。

如果单独从字符串取出数字对比的话，又有一个问题"更新至x集/全集y集"之类格式。所以我想，能否在后台添加一个正则判断，站长自己人工写正则取出数字判断呢？

当然，这只是我这个小白个人的想法，大佬如果有更好的解决办法的话就按照大佬自己的来就好

**Comment by aa068** [comment]
可以利用定時採集時間差來解決
如你有TG~@kickaj

**Comment by maigosama** [comment]
没办法解决，就算是加了判断也是不够全面的，不同资源站的备注不单只有这个差异，例如还有些集数是 x.5

**Comment by philipsc** [comment]
我可以提供一个解决办法，在一个安全的目录中建立SQL用于提取备注，同时比较提取数值与数据表中的数值大小，大于数据库数值则更新写入数据库，在每次采集完成后，延时20秒左右启动定时任务，当然，根据资源站数量，这个SQL的数量可能会有上百条，我母亲就是使用这种方法，4个资源站，且每个资源站都还有好几种备注方式，差不多150条SQL的样子，同时还用于处理，完结状态，上线日期，主演中的特殊符号等其他任务。

**Comment by philipsc** [comment]
`UPDATE `mac_vod` set `vod_serial` = if(CAST(`vod_serial` AS SIGNED)<substring(`vod_remarks`,4,2),substring(`vod_remarks`,4,2),`vod_serial`) WHERE `vod_remarks` LIKE '更新至__集';`

就上面这种写法，你根据实际情况去做修改。

**Comment by shangxin-lazy** [comment]
> 我可以提供一个解决办法，在一个安全的目录中建立SQL用于提取备注，同时比较提取数值与数据表中的数值大小，大于数据库数值则更新写入数据库，在每次采集完成后，延时20秒左右启动定时任务，当然，根据资源站数量，这个SQL的数量可能会有上百条，我目前就是使用这种方法，4个资源站，且每个资源站都还有好几种备注方式，差不多150条SQL的样子，同时还用于处理，完结状态，上线日期，主演中的特殊符号等其他任务。

我水平太低，这样确实是可以，但是就我的半吊子水平实现不了，感谢大佬提供的思路，我最近学习下

**Comment by magicblack** [comment]
感谢各位提供的思路，目前连载场景比较复杂多样，目前数据库结构兼容起来很困难。楼主参考上面大神提供的思路改一下哈~
