### ISSUE TITLE
maccms安装完，进不去后台

### ISSUE THREAD

**Issue by abe520** [magicblack/maccms10#906]
**描述您的问题**  
安装完，进不去后台，排查方向？
换过mac版本，也换phpnginx,mariadb有没推荐的版本号

**预期结果**  

**截图**  
![image](https://user-images.githubusercontent.com/9929511/168870171-db4c21e7-c8e9-43de-9970-e79e7cf14dda.png)

**版本信息:**  
 -  程序版本: [如 v2022.1000.3031]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by magicblack** [comment]
后台路径默认是 /admin.php ~
