### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by nguyenloc879** [magicblack/maccms10#908]
t I set up maccms on my hosting but got "zip" missing error. How do I add it?

**Comment by nguyenloc879** [comment]
![image](https://user-images.githubusercontent.com/73431662/169018901-3c6e8271-9c1c-46e1-ae1f-fd59fcca552f.png)
网络看起来像这样

**Comment by lixuehan1234** [comment]
在php配置里开启即可

**Comment by brevis-ng** [comment]
if you resloved it, please closed issued. thanks
