### ISSUE TITLE
定时任务提示：curl: (18) transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by dd0072** [magicblack/maccms10#91]
用宝塔的计划任务触发的定时任务，查看宝塔计划任务日志提示：curl: (18) transfer closed with outstanding read data remaining，上网查了也找不到比较好的解决办法。只好求助王哥了。

**Comment by magicblack** [comment]
可能是网络或数据量大导致请求超时了。应该是请求成功了，没啥事。

**Comment by dd0072** [comment]
> 可能是网络或数据量大导致请求超时了。应该是请求成功了，没啥事。

除了用宝塔触发外还有其它的办法吗？

**Comment by dd0072** [comment]
> 可能是网络或数据量大导致请求超时了。应该是请求成功了，没啥事。

宝塔的cron是这样写的curl -sS --connect-timeout 10 -m 3600，我将它改成了curl -sS --connect-timeout 900 -m 1800，但似乎没什么用。
