### ISSUE TITLE
播放报错

### ISSUE THREAD

**Issue by GitSarp** [magicblack/maccms10#910]
**描述您的问题**  
使用https播放时正常，使用http播放后报错（好像是调用不到dplayer.js），求解决方案

https://xxx/static/player/.js net::ERR_ABORTED 404 (Not Found)

https时正常，可以正常调用到dplayer.js播放,为什么会这样呢

**如何重现**  

**预期结果**  
希望http播放不报错

**截图**  
<img width="708" alt="image" src="https://user-images.githubusercontent.com/14067824/169783376-e9a66258-de78-44fc-9e09-b3da29e10ed2.png">

**版本信息:**  
 -  程序版本: [2022.1000.3031]
 - 操作系统: [ios & macos]
 - 浏览器: [chrome]

**Comment by magicblack** [comment]
具体要看为什么没有获取到dplayer关键词。建议让http301跳转到https即可，https也是大势所趋了~
