### ISSUE TITLE
关于按年份全局排序的建议

### ISSUE THREAD

**Issue by philipsc** [magicblack/maccms10#915]
**描述您的问题**  
资源站经常补一些年份比较老的资源，采集后这些年份较久远的资源就排在了前面，有时候这种非当年资源较多的时候会占用很多新片的位置。

**如何重现**  
自建一个资源站，在其中增加两个不同年份的电影，更新年份比较老的电影后采集，采集后，主站年份较老的电影会排在第一位。

**预期结果**  
希望可以增加一个按年份排序的全局功能，涵盖所有页面，包括，主页、分类、搜索等所有影片展示页面，不受模板标签影响，此功能默认关闭，由需要的站长自行打开。
![年份信息](https://user-images.githubusercontent.com/31801469/171776724-3b49d5a5-d085-4b18-8ff3-86b4430efd0c.png)
如果影片资料中没有年份信息则统一放在排序末尾处。

**截图**  
![排序问题](https://user-images.githubusercontent.com/31801469/171776053-be0cfeb0-d0db-4828-aa55-4f0282d33d50.png)
截图中的预期结果是希望能按照年份由近及远（2022→2015）的显示。

**版本信息:**  
 -  程序版本: 2022.1000.3031
 - 操作系统: Windows 11
 - 浏览器: Microsoft Edge 102.0.1245.30

**其他备注信息**

**Comment by magicblack** [comment]
数据库设计的年份目前为字符类型，直接排序会非预期。可以通过SQL语句修改vod_time来实现你希望排序的效果：
`UPDATE mac_vod SET vod_time=UNIX_TIMESTAMP(CONCAT(vod_year, '-01-01 00:00:00')) WHERE LENGTH(vod_year)=4;`

如有需要，执行前记得备份数据~
