### ISSUE TITLE
详情页跳转到播放页，如何使用优先级较高的播放器？

### ISSUE THREAD

**Issue by dogevip** [magicblack/maccms10#916]
**描述您的问题**  
播放器的优先级可以自定义但是不知道如何调用。详情页跳转到播放页，如何使用优先级较高的播放器？

**预期结果**  
详情页跳转到播放页，自动使用优先级较高的播放器

**Comment by philipsc** [comment]
系统→网站参数配置→预留参数→播放器顺序（勾选全局），然后在视频→播放器中设置播放器的排序（数值越大排列越靠前）

**Comment by magicblack** [comment]
感谢回复。题主可以看按楼上提供的方法试一下~
