### ISSUE TITLE
筛选页面获取不到isend参数

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#918]
筛选页面获取不到isend参数，无法进行完结和未完结资源的筛选
直接在url写isend参数也不行，因为$param里根本没有这个值
建议作者大大增加对这个参数的支持，不然后台那个isend就形同虚设了~

**Comment by magicblack** [comment]
筛选页路由固定，无法再增加其他参数了。可以二次开发通过cookie来传递筛选【是否完结】。
参考提交示例，目前针对采集可配置是否完结参数~
