### ISSUE TITLE
关于演员（主演）对比入库的问题反馈

### ISSUE THREAD

**Issue by philipsc** [magicblack/maccms10#919]
**描述您的问题**  
现在有一部电视剧和电影名字相同，主演不同，入库重复规则勾选了演员（由于一些原因不能勾选更多条件），但是再演员明显不同的情况下还会将电视剧强制入库到电影，主演信息如下。
剧名（电影、电视剧相同）：第一夫人

电影主演：娜塔丽·波特曼,彼得·萨斯加德,格蕾塔·葛韦格,娜塔莉·波特曼,比利·克鲁德普,约翰·赫特,卡斯珀·菲利普森

电视剧主演：吉莲·安德森,基弗·萨瑟兰,维奥拉·戴维斯,米歇尔·菲佛,达科塔·范宁,艾伦·艾克哈特,O·T·法格本,艾伦·伯斯汀,卡莉·史派妮,伊莱扎·斯坎伦,瑞斯·维克菲尔德,莉莉·拉贝,唐娜·琳·钱普林,萨尼雅·西德尼,莱克西·安德伍德,德里克·塞西尔,阿雅·卡什,赵家玲,凯登·博伊德,迈克尔·阿伦诺夫,Thomas E. Sullivan,伯纳黛特·奎格利,朱迪·格雷尔,查理·普拉默,雷吉娜·泰勒,杰里米·博布,艾比·格洛弗,艾希礼·勒孔特·坎贝尔,阿尔洛·默茨,克里·杜瓦尔,杰基·厄尔·哈利,格洛利亚·鲁本,

**如何重现**  
1.测试资源站中增加相同名称的电影和电视剧，如：第一夫人
2.分别录入上述电影主演、和电视剧主演。
3.入库重复规则仅勾选演员。
4.采集刚刚录入的2部同名视频。

**预期结果**  
主演完全不相同的同名视频要能分开入库。

**截图**  
无

**版本信息:**  
 -  程序版本: 2022.1000.3031
 - 操作系统: Windows 11
 - 浏览器: Microsoft Edge 102.0.1245.30

**其他备注信息**  
测试过程中发现，采集比对主演的过程似乎有一个相似值。比如库中有一部名称与将要采集的名称相同，且有1-2位主演与将要采集的视频相同，系统也会默认2部剧为同一部。但是市面上各个资源站也不能做到同剧主演完全一致，所以这是个很难取舍的问题。但如我本次提交的issue中提到的 完全不相同的主演应该时可以比对且分开入库的吧。

**Comment by magicblack** [comment]
目前是交叉对比演员列表，只要同名且有演员一致，则认为是同一视频。你这里的情况理论上不会，是否开启了搜索优化-采集部分？

**Comment by magicblack** [comment]
这个问题没有进一步的反馈，暂时关闭。如有疑问可重新提交issue。
