### ISSUE TITLE
希望站群功能能让每个模板里面的视频排序不一样

### ISSUE THREAD

**Issue by allcdn** [magicblack/maccms10#920]
现在站群功能除了模板不一样，视频排序啥的都一样，希望加个功能能让顺序不一样

**Comment by jackrebel** [comment]
你自己改下模板中的排序规则不就行了， 后台不是有很多推荐级1，2，3，4，5，6，7，8，9等可以用嘛。。。

**Comment by allcdn** [comment]
[https://s3.bmp.ovh/imgs/2022/06/08/501f4e6107422662.png](https://s3.bmp.ovh/imgs/2022/06/08/501f4e6107422662.png)
你看图片类似这样的功能，可以在站群哪里加这个功能

**Comment by allcdn** [comment]
问题：现在站群插件虽然能每个域名使用不一样的模板，但是每个站的数据排序都是一模一样的，虽然可以改模板中的排序设置为随机，但是这个刷新一下网页就会随机变化。

希望能像船说cms程序那样加一个id转换，来改变数据排序一样的问题

[https://www.free-img.com/imgs/2022/06/10/33548a4857bc8e85.png](https://www.free-img.com/imgs/2022/06/10/33548a4857bc8e85.png)

**Comment by magicblack** [comment]
这个是个性化需求，自行二次开发实现哦~
