### ISSUE TITLE
静态路径设置里面配置成{年}{月}，实际静态生成的是{月}{日}目录

### ISSUE THREAD

**Issue by wwwfcdhnet** [magicblack/maccms10#924]
后台"URL地址配置"  --->  "静态路径设置" 中的“视频详情”和“视频播放”中把路径设置为vodhtml/{year}{month}/{id}和vodhtml/{year}{month}/{id}，但是我静态化后实际上生成的是月日目录，而不是预期的年月目录。（我只测试了这两个，其他没有测试）

**Comment by magicblack** [comment]
感谢反馈，已修复，将于近期发布~
