### ISSUE TITLE
后台视频数据的链接有问题

### ISSUE THREAD

**Issue by 502315278** [magicblack/maccms10#927]
**描述您的问题**  
后台视频数据的链接有问题

**截图**  
![image](https://user-images.githubusercontent.com/9147478/174780609-8f48a3a1-cf7d-4ce3-b31e-de306627d9b0.png)

**Comment by magicblack** [comment]
默认伪静态会输出 /vod/detail/id/{id}.html，检查一下伪静态的配置吧~

**Comment by 502315278** [comment]
> 默认伪静态会输出 /vod/detail/id/{id}.html，检查一下伪静态的配置吧~

使用默认的配置就会这样，请问有没有推荐的配置规则？

**Comment by magicblack** [comment]
在系统设置 - URL地址配置 - 路由伪静态设置，开启路由和伪静态试试~
![image](https://user-images.githubusercontent.com/20452515/182458068-e57880f1-3011-4309-94b6-b8dfa8987b79.png)
