### ISSUE TITLE
关于开放API播放组的一个问题

### ISSUE THREAD

**Issue by philipsc** [magicblack/maccms10#928]
**描述您的问题**  
api中指定了多个播放组，并按提示用英文逗号分隔，但是在?ac=detail 详情页中并未看到多个播放组出现，导致采集的时候多个播放组不能新增和更新。

**如何重现**  
1. 资源站设置多个播放组
2. 资源站API设置中 指定播放组 填入 设置的多个播发组并以英文逗号分隔。
3. 打开api详情页（?ac=detail）检查json数据会发现只有一个播放组

**预期结果**  
在api详情页中输出指定的多个播放组内容

**截图**  
怀疑和 str_contains 函数有关，因为str_contains在php8.0才被支持，但是我的环境是php7.2
因为函数不能执行if判断中$key变量无法被正确赋值。
![str_contains](https://user-images.githubusercontent.com/31801469/176119416-164556f6-4edc-4568-9bc3-ce7f6530da73.jpg)

**版本信息:**  
 -  程序版本: 2022.1000.3031
 - 操作系统: 如 Windows 11
 - 浏览器: edge

**其他备注信息**

**Comment by philipsc** [comment]
我又思考了一下，这里的逻辑是不是应该这样：如果’$GLOBALS['config']['api']['vod']['from']‘有多个值（多个播放组），将这多个播放组的值与系统数据库的’$v['vod_play_from']‘对比，如果系统存在这个播放组，就返回播放组对应的’$v['vod_play_url']‘，如果不存在则不显示，但是作者这里写’$arr_from[$key]‘那么不管$key的值为多少，那么'$arr_from'也只会返回一组数据，这写法是不是存在问题

**Comment by magicblack** [comment]
感谢反馈，逻辑确实有问题。此前固定只允许一个播放组，改成多播放组这里就不用进入处理逻辑了~ 已经修改，等待发新版本。
