### ISSUE TITLE
ftp同步图片路径会出现2遍

### ISSUE THREAD

**Issue by muzidudu** [magicblack/maccms10#930]
**描述您的问题**  

本地保留的图片路径正常

ftp路径设置的是 /

ftp服务器保存的图片路径重复2次 

/upload/vod/20220630-1/upload/vod/20220630-1/091e3e45cb534132dd0e6f07848457c9.jpg

**Comment by magicblack** [comment]
看看服务器的图片地址有无重复路径？以及检查ftp的服务端、本地端图片保存路径情况。
