### ISSUE TITLE
SQL injection vulnerability in maccms10 background

### ISSUE THREAD

**Issue by GxBSXUKing** [magicblack/maccms10#931]
Vulnerability name：SQL injection
Vulnerability level：Medium risk
Affected version：v2021.1000.1081<=v2022.1000.3031
Vulnerability location：
Log in to the background and click the database function module to select the data batch replacement function
![Image](https://user-images.githubusercontent.com/28795365/176849280-f767d15e-cd7c-4b67-8efc-bc84fb83eb20.png)
![Image](https://user-images.githubusercontent.com/28795365/176849369-361d7eb1-f38f-4dac-8695-f530c2ca1856.png)
Intercept selection data table
![Image](https://user-images.githubusercontent.com/28795365/176849431-efde3c3a-a240-4a86-8589-42c5ad30b1ab.png)
Enter payload to attack
![Image](https://user-images.githubusercontent.com/28795365/176849454-72574958-3b5b-4c30-8daf-a530e1b8df1e.png)
Audit the code. There is no restriction on the type and length of the parameter tables, and there is no token verification
![Image](https://user-images.githubusercontent.com/28795365/176849485-060f5b16-05c4-4dda-9b3e-6568441166a4.png)
This vulnerability can obtain a large amount of data
![Image](https://user-images.githubusercontent.com/28795365/176849518-7a04d93b-6b86-478b-ba22-a1ece2bac901.png)

**Comment by magicblack** [comment]
Fixed, thanks for your hard work.
