### ISSUE TITLE
慢排序， 怎么样优化？

### ISSUE THREAD

**Issue by jackrebel** [magicblack/maccms10#933]
正在显示第 0 - 12 行 (共 13 行, 查询花费 2.9721 秒。) 
`EXPLAIN SELECT * FROM `mac_vod` WHERE `vod_status` = 1 AND `vod_letter` IN ('A') AND `type_id` IN ('2','13','14','15','16','22') AND (`vod_class` like '%家庭%') ORDER BY `vod_hits` DESC LIMIT 0,72;`

ORDER BY `vod_hits` DESC, 排了个序后要3秒， 怎么样优化此类？

已经给Vod_hits、type_id等字段加了索引。

**Comment by magicblack** [comment]
这边本地6w条数据测试没啥问题，基本0.00x秒。
如果是排序问题，可以给vod_hits增加DESC排序的索引。

也可以尝试开启一下搜索缓存功能，减缓LIKE搜索造成的压力。
