### ISSUE TITLE
/application/admin/controller/Collect.php  添加一行，方便挂机采集知道进度

### ISSUE THREAD

**Issue by kkdysite** [magicblack/maccms10#934]
**描述您的问题**  
例如 edge浏览器  最左侧几个标签同事 采集多个资源库，此时断点采集功能 无法使用。无法实时知道采集进度
浏览器固定标签格式 类似
https://***/***.php/admin/collect/api.html?ac=cj&cjflag=fceef6250232feb7d277b162be0ddc2c&cjurl=https%3A%2F%2Fapi.***.com%2Fapi.php%2Fprovide%2Fvod%2Ffrom%xxxx%2Fat%2Fxml%2F&h=&t=&ids=&wd=&type=1&mid=1&opt=0&sync_pic_opt=2&filter=0&filter_from=&param=&page=914

**增加一行*  

第280行 增加一行
mac_echo('<title>'.$param['page'].'/'.$res['page']['pagecount'].'</title>');

**预期结果**  
浏览器标签标题 显示   969/1276 这个采集进度

**Comment by magicblack** [comment]
感谢建议，已加上~
