### ISSUE TITLE
数据库存储用户IP出现错误，用户无法登录

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#935]
![QQ截图20220709191100](https://user-images.githubusercontent.com/55046423/178103268-19019b53-0544-4e5e-81a6-5183d7988aae.png)

如图

因为IP的数值较大，而数据库的相关字段又是Int型，导致无法存储，用户无法登录。

把相关字段的位数调大也不行，因为超过了 2^31-1的数值上限。

建议作者大大调整一下存储IP的相关字段的类型~

**Comment by magicblack** [comment]
感谢反馈，新版数据库已经可以容纳42亿（最大IP为255.255.255.254），你这里的改下int unsigned 就可以了~
