### ISSUE TITLE
删除分类无法更新新分类

### ISSUE THREAD

**Issue by maqueaa** [magicblack/maccms10#938]
**描述您的问题**  
我删除了老的演员分类后，添加了新的演员分类，但是读取开放接口依然是老的分类，数据库也没有老分类了。没开缓存

**如何重现**  
1.删除顶级演员分类
2.清空演员数据库
3.添加新的顶级演员分类
4.添加子分类
**预期结果**  
读取最新分类

**截图**  
![image](https://user-images.githubusercontent.com/93441749/180746808-a1e0cf2e-11c0-4bc1-9b7e-3ff2da3ffd5c.png)
![image](https://user-images.githubusercontent.com/93441749/180746930-dbefd620-2ca2-4688-a8a4-b54d3704fc77.png)
这个是我当前的演员分类

![image](https://user-images.githubusercontent.com/93441749/180747052-9dbe3f44-a5f0-4fdb-ae7d-d01f60a2207d.png)

从开放接口读取的分类

**版本信息:**  
 -  程序版本: [2022.1000.3031]
 - 操作系统: [如 Windows 10]
 - 浏览器: [如 chrome]

**其他备注信息**

**Comment by magicblack** [comment]
有些模型数据是强制缓存的，后台清理一下缓存试试~
