### ISSUE TITLE
关于获取注册用户ip地址为0.0.0.0的问题

### ISSUE THREAD

**Issue by juanjuan0610** [magicblack/maccms10#939]
**描述您的问题**  
频繁出现获取到用户的IP地址为0.0.0.0，就想请教一下，这个问题的出现是因为这些用户都属于ipv6的用户还是其他什么原因？

**截图**  
![QQ图片20220729152340](https://user-images.githubusercontent.com/107374796/181707317-bd0821f9-b8bc-4369-a603-9d46aee40a74.png)

**版本信息:**  
 -  程序版本: 2022.1000.3031
 - 操作系统: centos8.0
 - 浏览器: chrome

**Comment by magicblack** [comment]
需要看你的网站是否有cdn、反向代理等，如果有可能会导致程序获取到的IP不是真实用户IP，从而导致上面显示问题。建议找运维看看吧~
