### ISSUE TITLE
作者 怎么把图片域名 把baidu之类的 屏蔽了 显示img.php?url=

### ISSUE THREAD

**Issue by dadage888** [magicblack/maccms10#941]
作者 怎么把图片域名 把baidu之类的 屏蔽了 显示img.php?url=

有的资源站图片域名 就是 包含了 baidu 

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by magicblack** [comment]
系统 - 附件参数配置 - 反盗链标识/反盗链接口 配置下~
