### ISSUE TITLE
建议加个和赞片cms一样的一键绑定分类

### ISSUE THREAD

**Issue by 1340096565** [magicblack/maccms10#943]
建议加个和赞片cms一样的一键绑定分类，点击了这个按钮自动绑定分类。比如分类管理有国产剧，资源站有国产剧这个分类，点击了会自动绑定国产剧

**Comment by chinapzw** [comment]
这种不可能,我一个站同名分类一大堆,不切实际啊,你可以看html代码,里面就有分类id,直接手动去改php文件
