### ISSUE TITLE
关于后台入口文件admin.php

### ISSUE THREAD

**Issue by 9dizhi** [magicblack/maccms10#948]
在站点迁移过程中，发现_**admin.php**_代码被修改，
当前，不清楚是系统自动修改，抑或是被提权木马所修改？

具体更改代码如下
原来代码
`//define('BIND_MODULE','admin');`
`define('ENTRANCE', 'admin');`
被修改后
`define('BIND_MODULE','api');`
`define('ENTRANCE', 'api');`

导致访问后台路径时空白，无法正常访问！
请告知原因！谢谢！

**Comment by 22553456** [comment]
这都被你发现了

**Comment by 9dizhi** [comment]
抱歉，犯了低级错误。
重命名时，把admin.php跟api.php调转了
