### ISSUE TITLE
runtime文件目录不断增大，请问文件缓存过期的会自动删除吗？

### ISSUE THREAD

**Issue by otary** [magicblack/maccms10#949]
**描述您的问题**  
runtime文件目录目前已达到30多G，还在不断增大，请问文件缓存过期的会自动删除吗？我的缓存也只有4小时有效期

**版本信息:**  
 -  程序版本: 目前最新版本

**Comment by 22553456** [comment]
你把清除缓存做个定时任务不就好了

**Comment by otary** [comment]
不好，那全部缓存都被清除了，我只先去除过期的数据

**Comment by 22553456** [comment]
> 不好，那全部缓存都被清除了，我只先去除过期的数据

那不用，过期后访问会重新覆盖原来的缓存

**Comment by magicblack** [comment]
【文件缓存过期的会自动删除吗？】
目前没有这个功能。可以自行搜索自动删除（比如4小时）前的文件脚本，配置个定时任务执行就可以了。
