### ISSUE TITLE
为什么后台开启缓存一直卡这里

### ISSUE THREAD

**Issue by 583455189** [magicblack/maccms10#95]
![IZVV ZVOIJWI4H 7 N)%R1T](https://user-images.githubusercontent.com/20038296/68001631-d7152e80-fc9f-11e9-8554-5904b31fa7a5.png)

**Comment by jesusjsc** [comment]
同样的问题！“网站参数配置”页面不能保存。

**Comment by magicblack** [comment]
包里少了个文件，下载离线包，覆盖 \application\common\validate 目录即可。
或者 修改本地版本号小于1018，重新在线升级。
