### ISSUE TITLE
重名视频数据的处理建议

### ISSUE THREAD

**Issue by qingxuwang** [magicblack/maccms10#950]
在检验重名视频数据中
入库重复规则：使用 名称和分类
但在Collect.php函数vod_data检测 inrule 为b时以小分类type_id作为判断，应该使用type_id_1大分类判断

这样可以避免多个资源站分类不准确大量的重名数据入库
可以增加一项更新时候检测大分类相同，小分类不同时可以更新小分类的ID
eg：电影（3）-动作片（31）更新为电影（3）-喜剧片（32）
而不是重复入库

**Comment by magicblack** [comment]
这个设计之初即使用小分类最细级别，可以先绑定好资源分类id映射~
