### ISSUE TITLE
站群管理里的模板目录要怎么配置，配置了多种方式都报错

### ISSUE THREAD

**Issue by otary** [magicblack/maccms10#951]
**描述您的问题**  

新增了一个域名，想使用另一套模板，模板已经放在template目录下了，配置如下，访问报：`模板文件不存在:index/index.html`

![image](https://user-images.githubusercontent.com/3916327/184501480-fe231f12-b9a3-4e05-a22a-23e886eca25e.png)

![image](https://user-images.githubusercontent.com/3916327/184501555-b5879387-6071-4d7e-8c55-aa32ebe4c053.png)

模板路径改成这样的，也不行，一样的报错，请问该怎么配置才行？

![image](https://user-images.githubusercontent.com/3916327/184501564-4336209c-5489-4ff3-9487-30402c9d7ac7.png)

**版本信息:**  
 -  程序版本: 最新版本

**Comment by magicblack** [comment]
这个自己找资料配置使用哦~

**Comment by jinghuashang** [comment]
老哥解决了吗我也遇到了这个问题
