### ISSUE TITLE
关于后台-视频搜索优化

### ISSUE THREAD

**Issue by 9dizhi** [magicblack/maccms10#952]
**描述您的问题**  
作者老哥说过，目前开启搜索优化，会缓存结果14天，
请问，如何修改为7天或者更短时间？来适应站长自身需求。

还有一点，笔者不太明白，【前台】与【采集】的区别？
是否只要开启其中一个，都能正常驱动搜索优化功能，达到前端用户快速搜索相关关键词的作用

**一点建议**  
建议在入库vod_search表时，判断是否有返回数据，若查询结果为 0，则不写入vod_search表，缩减vod_search表的大小。

**Comment by 22553456** [comment]
VodSearch.php在这里面修改

**Comment by magicblack** [comment]
“如何修改为7天或者更短时间？来适应站长自身需求”：
手动修改方式楼上正解~ 这边也将在这个版本增加配置项支持更短时间。 

【前台】与【采集】的区别：
顾名思义，前台仅是前端用户搜索时的优化，采集是后台采集数据时的优化。根据多位站长实际使用反馈，因采集数据需要实时查询最新的，一般只需要开启【前台】即可，仅开启1个也能实现优化搜索。

"若查询结果为 0，则不写入vod_search表，缩减vod_search表的大小"：
这个不建议，否则将失去搜索优化的效果，每次都会去LIKE模糊查询。而增加的大小有限，此表做了索引优化，千万级别的数据都能顶的住~

**Comment by magicblack** [comment]
新版本已支持后台配置缓存时间~
