### ISSUE TITLE
留言本问题

### ISSUE THREAD

**Issue by 965769136** [magicblack/maccms10#953]
1.希望留言本能搞个加密留言的功能，这样只有留言者和站长看到。
2. 希望留言能同步到邮箱，这样站长就能及时回复留言。

**Comment by magicblack** [comment]
这个需求你接一个免费的在线客服就可以了~

**Comment by 965769136** [comment]
在线客服是一对一聊天，而留言是可以开放给访问看，但有些留言是需要隐藏加密内容，比如说联系方式这些隐私。这也许是我个人的想法吧。谢谢你的回答，辛苦了！
