### ISSUE TITLE
为啥经常出现这个错误

### ISSUE THREAD

**Issue by 1713172499** [magicblack/maccms10#954]
![1660721185013](https://user-images.githubusercontent.com/32571618/185059902-33cfdf0e-0feb-4cb5-b67c-90fe04bb82fd.png)
不知道是哪里造成的，每次都要去修复表，有时候修复不了还得mysqlcheck

**Comment by magicblack** [comment]
一般和你服务器有关系，参考这个解决下：
https://blog.csdn.net/wang1qqqq/article/details/108584572

写个脚本定时执行；或者先备份好，再尝试把表类型改成InnoDB试下。
