### ISSUE TITLE
开放API播放组bug

### ISSUE THREAD

**Issue by grayson85** [magicblack/maccms10#957]
**描述您的问题**  **截图**  
网站内采集了3组播放器 A,B,C. 在开放API设定了播放器A和B. 
然而API回复却还是包含了3组播放器A,B,C的资料.

**如何重现**  
只选定fsm3u8,wjm3u8
![image](https://user-images.githubusercontent.com/37401242/185824344-3edc9eee-f820-46fb-bc4c-15ead7cc523c.png)

没选定leduo播放器，可是API回复却还是包含了leduo
![image](https://user-images.githubusercontent.com/37401242/185824604-e9796c76-86d4-45ca-baaa-f154c8602df2.png)

**预期结果**  
只选了2组播放器，API应该只回复2组播放器的资料。

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Linux]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by magicblack** [comment]
感谢反馈，已重现、修复~
