### ISSUE TITLE
自定义采集中有些无用信息不想要，在哪里可以设置规则

### ISSUE THREAD

**Issue by duansix** [magicblack/maccms10#959]
**描述您的问题**  
自定义采集中有些无用信息不想要，在哪里可以设置规则
比如JSON采集来的信息中的播放地址里面有些不必要的信息
可以在哪里替换或者删除掉呢

**如何重现**  
目前采用的是 数据库直接SQL命令替换 但是采集每日都会更新 更新完还要重新手动执行SQL命令

**预期结果**  
希望能回复一下 在哪里设置 自定义采集来的数据 在入库之前 改变数据的部分信息

**Comment by magicblack** [comment]
目前只有后台配置 - 采集参数配置 - 采集词库设置 这里有部分字段可以替换。其他的还是需要自行通过脚本更新~
可以写一个定时任务，检查vod表最新更新或添加了视频，就执行sql命令。
