### ISSUE TITLE
你好 我的只要提交跟代码相关的东西都一直显示数据提交中

### ISSUE THREAD

**Issue by chenhao2006814** [magicblack/maccms10#96]
1.那个统计代码留空正常,不是代码也没事,但是一粘贴js代码就显示数据提交中
2. 那个播放器参数页面也是如此
3. 是某个模块没有打开吗?还是什么问题呢?
4. 那个你说的那个模块我也重新上传了版本号不知道怎么改
5. 我的提问结束.
# 谢谢,第一次 有点紧张又有点激动

**Comment by magicblack** [comment]
1018只有网站配置会这样，其他页面没关系。 按你说的都有问题很可能是配置文件目录没有写入权限。

**Comment by chenhao2006814** [comment]
> 1018只有网站配置会这样，其他页面没关系。按您说的都有问题很可能是配置文件目录没有写入权限。

1. 不是所有的页面都不能正常提交
2. 是跟代码有关系的页面 统计代码是js代码播放器配置那个是里面含有.html后缀的地址,只有这俩个不能正常保存
3. 其他的页面保存都没问题
4. 那个统计代码如果留空的话或者写跟代码无关的都可以正常保存,比如:111111或者汉字都可以保存,唯独贴了js代码不能保存
5. 我总觉得是有哪个模块阻止了我不能提交跟代码相关的东西

**Comment by magicblack** [comment]
那你得检查一下自己服务器里的安全软件了，可能是被拦截了。F12调差 返回信息
