### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#960]
1、现在有mac_url_vod_plot函数方便地生成视频对应的剧情列表链接，但是没有mac_url_vod_role用来生成角色函数，建议增加这个函数，非常感谢
2、vod/plot页面没有正常的aid，和视频首页的aid一样是10
3、role/detail页面获取不到$GLOBALS.type_id参数
4、plot/index页面无法通过$param['page']获取当前的页码

**Comment by magicblack** [comment]
1、角色采用的结构不同，暂无法实现。
2、已增加vod/plot的aid，值为18。
3、role/detail已增加$GLOBALS.type_id。
4、plot/index已增加$param['page']。

**Comment by magicblack** [comment]
https://github.com/magicblack/maccms10/commit/e7cfbffc020e6695687e40891917765080d62341

新版本发布后更新生效~
