### ISSUE TITLE
Reflective XSS vulnerability in website

### ISSUE THREAD

**Issue by Scholar-City** [magicblack/maccms10#961]
Vulnerability name：Reflective XSS

Vulnerability level：Medium risk

Affected version：v2022.1000.3032<=

Vulnerability location：This is one of the places I found
```
http://127.0.0.1/api.php/wechat?signature=606fd96dcdac6cae332c334c0f50aaf8cb974203&timestamp=qwe&nonce=qwe&echostr=<img src=x onerror=alert(document.cookie)>
```

Verification process：
Get administrator cookies through reflective XSS：
First, the user logs in to the background

![image](https://user-images.githubusercontent.com/45580466/187027496-543cbdf5-7df6-4a57-a6e6-461f84789729.png)

Watch here.
![image-20220827185231106](https://user-images.githubusercontent.com/45580466/187027514-e59ae423-f04d-4d6f-a095-02fe9ef19661.png)

When the echostr parameter is not empty, the valid() method of the $wechatObj object is called.
The class of the $wechatObj object is WechatPublic.
Look here to WechatPublic.php.
![image-20220827185348619](https://user-images.githubusercontent.com/45580466/187027585-328fd73c-3293-4ea8-b7b2-bb8a494c02e2.png)

Accept the parameter assignment to $echoStr and then call the checkSignature() method to check the Signature, here continue to follow the checkSignature() function analysis
![image-20220827185509974](https://user-images.githubusercontent.com/45580466/187027649-776c74f9-ff20-4ae2-b9a7-2ab035f49904.png)

Accept $timestamp, $nonce and the $token value of the configuration file (token is a fixed string qweqwe in the configuration file), and assign the three strings to the $tmpArr array, and finally get the sha1 value, which already knows that the token value is fixed
![image-20220827190605981](https://user-images.githubusercontent.com/45580466/187027686-90eb0a01-dff3-458f-a327-1c5881b6d644.png)

Directly constructing $timestamp and $nonce values are also fixed values.
get sha1: 606fd96dcdac6cae332c334c0f50aaf8cb974203

Construct the passed $signature as the resulting sha1, and make the judgment result true.
Then construct echostr as xss payload to inject.
```
http://127.0.0.1/api.php/wechat?signature=606fd96dcdac6cae332c334c0f50aaf8cb974203&timestamp=qwe&nonce=qwe&echostr=<img src=x onerror=alert(document.cookie)>
```
![image-20220827190130214](https://user-images.githubusercontent.com/45580466/187027761-ed4c5a8d-3d25-40f6-a8c5-a01797a3dfec.png)

Repair method：
【1】HTML escape the input data so that it is not recognized as an executable script
【2】Filter the data according to the tags and attributes of the whitelist to clear the executable script (such as script tag, oneror attribute of img tag, etc.)

**Comment by magicblack** [comment]
Confirmed & fixed, thanks for your feedback.
