### ISSUE TITLE
苹果cms v10什么时候支持图片webp格式上传

### ISSUE THREAD

**Issue by Fewdays** [magicblack/maccms10#962]
苹果cms v10什么时候支持图片webp格式上传

**Comment by 22553456** [comment]
自己添加一下格式就好了

**Comment by Fewdays** [comment]
在哪里添加

**Comment by Fewdays** [comment]
> 自己添加一下格式就好了

在哪里添加呢

**Comment by 22553456** [comment]
不是支持webp格式麼

**Comment by 22553456** [comment]
image.php里面

**Comment by Fewdays** [comment]
为什么我上传webp格式的图片提示
![image](https://user-images.githubusercontent.com/20038296/187139585-12b41d5d-78a7-4a0a-9219-401bd215becf.png)

**Comment by 22553456** [comment]
不知道啊，你是不是没更新

**Comment by Fewdays** [comment]
是最新版，image.php里面我看了有webp，可是上传就是不支持

**Comment by 22553456** [comment]
后台上传设置里面看看

**Comment by Fewdays** [comment]
只有一个附件，
![image](https://user-images.githubusercontent.com/20038296/187326383-cfd9e12f-feac-474e-8dfb-e2c01f463693.png)

**Comment by Fewdays** [comment]
> 后台上传设置里面看看

没有

**Comment by wwwwc** [comment]
文件改了也不支持的，我试过！
好像没办法解决问题，只能等作者更新

**Comment by wwwwc** [comment]
> 我测试没问题啊

奇怪了，我的下载webp就提示失败

**Comment by magicblack** [comment]
前端的需要改这个文件，这边修改了，近期发版本生效~
