### ISSUE TITLE
发现大量/index.php/ajax/suggest请求如何禁止

### ISSUE THREAD

**Issue by tomlei88** [magicblack/maccms10#964]
![image](https://user-images.githubusercontent.com/103014450/188139275-f5bfa7aa-6fea-4f4b-9384-e7b133bcc187.png)
查看网站日志发现大量 /index.php/ajax/suggest?mid=1&wd=%E9%81%87%E8%A7%81%E7%92%80%E7%92%A8%E7%9A%84%E4%BD%A0&limit=500 访问这种url的请求，请问如何关闭。

**Comment by lixuehan1234** [comment]
把搜索框的 class   中的  mac_wd  改成别的或者去掉即可

**Comment by magicblack** [comment]
@tomlei88 参考2楼提供的方法试试。这个是前端模板发起的请求，没有关闭选项~
