### ISSUE TITLE
后台打开页面缓存时，视频报错功能只能点一次，点第二次的时候会提示数据错误

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#965]
如题
打开页面缓存，视频报错的页面也会被缓存。
第二次点报错的时候就提示数据格式有误
即使加上时间戳也一样
不知能否优化一下这方面的问题
非常感谢~

**Comment by magicblack** [comment]
麻烦提供一下具体报错的请求和返回截图，F12开发者模式看一下网络请求~

**Comment by lixuehan1234** [comment]
> 麻烦提供一下具体报错的请求和返回截图，F12开发者模式看一下网络请求~

这个还真没法提供……我就说一下具体的问题吧。

就是使用视频报错功能时MAC.Gbook.Report()，如果打开了后台“页面缓存”的功能，那么请求的这个页面/index.php/gbook/report.html，也被缓存起来，第二次再使用这个功能的时候就直接使用缓存的页面了，就不再是json格式而是html格式了，但就造成了格式的错误。
我觉得这种异步请求的页面如果不放在缓存的范畴里可能可以解决这个问题

**Comment by magicblack** [comment]
已解决，将在新版本发布~
