### ISSUE TITLE
搬完家对接的苹果后台图床上传不了图片了

### ISSUE THREAD

**Issue by wwwwc** [magicblack/maccms10#966]
搬完家对接的苹果后台图床上传不了图片了
之前搬过N次也没生问题
唯一的区别就是宝塔版本，搬家前是破解版本，后是正版版本
请大神帮忙解决
付费解雇 
Q：526666071

**Comment by magicblack** [comment]
一般是检查权限相关问题、服务器到图床的连接是否顺畅~
