### ISSUE TITLE
关于随机排序rnd的性能问题

### ISSUE THREAD

**Issue by 1713172499** [magicblack/maccms10#967]
**描述您的问题**  
这个随机排序的实现是获取最大页数，然后随机一页去取数据，当数据量很大时，这里使用limit实现的话，会直接锁表几十秒，会直接影响整个网站，关于这个随机的实现方式希望能再优化一下。
影响效率的代码如下：application/common/model/Vod.php 420行左右
```php
if($by=='rnd'){

      $data_count = $this->countData($where);
      $page_total = floor($data_count / $lp['num']) + 1;
      if($data_count < $lp['num']){
          $lp['num'] = $data_count;
      }
      $randi = @mt_rand(1, $page_total);
      $page = $randi;
      $by = 'hits_week';
      $order = 'desc';
  }
```

**截图**  
![image](https://user-images.githubusercontent.com/32571618/188262370-3ce5eba5-3732-4707-8a0c-9925da5a8dc8.png)

**Comment by magicblack** [comment]
感谢反馈，这边研究下~

**Comment by nykk520** [comment]
大哥，指定type_id的时候，可能会出现随机的vod_id，不是对应的type_id，结果就是一个视频都随机不出来
