### ISSUE TITLE
部分分类无法开启

### ISSUE THREAD

**Issue by xunskynet** [magicblack/maccms10#969]
**描述您的问题**  
程序再打一次安装，后台分类是使用正常。也不知道开启了什么，就这样的错误了
MACCMS 最新版

**如何重现**  
![image](https://user-images.githubusercontent.com/113071628/189001172-9a809861-264d-482b-8296-6fb836a01b8e.png)

**预期结果**  

**截图**  

**版本信息:**  
 -  程序版本: [如 2022.1000.3026]
 - 操作系统: [如 Windows 11]
 - 浏览器: [如 chrome, safari]

**其他备注信息**

**Comment by xunskynet** [comment]
都没人遇见过吗

**Comment by magicblack** [comment]
无法重现。请给出具体无法开启的表现。

**Comment by magicblack** [comment]
再次验证没有这个问题，由于没有进一步反馈这边先关闭了。
