### ISSUE TITLE
老王，文章不能加视频，麻烦看下

### ISSUE THREAD

**Issue by 791813752** [magicblack/maccms10#97]
文章不能加视频，放外链mp4,flv等之类的类型都不行呀，提示视频类型错误
![Screenshot_20191102_010616](https://user-images.githubusercontent.com/52873469/68042867-f1d2bc00-fd0e-11e9-9c7b-4ac2d2b115c4.jpg)
好无奈呀，网站前端也是提示：无法加载插件
还有，希望老哥更新下：文章页添加的视频可以是这种类型http://xxx.com/?url=http://xxx.com/1.m3u8，这种的，可以更方便，希望王哥速速解决😂

**Comment by magicblack** [comment]
你说的那种 直接插入iframe即可~~~

**Comment by 791813752** [comment]
插入iframe也不行呀，前台不显示，也无法播放
看图，王哥
![-1a9af402411e5ab4](https://user-images.githubusercontent.com/52873469/68065813-69cdd000-fd69-11e9-8fe7-dc0f02a9fa9a.jpg)

**Comment by 791813752** [comment]
这俩个iframe
一个是直链形式，就是http://xxx.com/1.mp4这种形式。
另一个是加了框架的，也就是解析http://xxx.com/?url=http://xxx.com/1.mp4这种形式。
高宽都是200，底下俩个选项都打了勾，但是前台俩个都显示不出来。。。，王哥麻烦看下，谢谢王哥

**Comment by 791813752** [comment]
王哥，咋不回消息呀

**Comment by magicblack** [comment]
修改一下模板调用标签，使用  mac_url_content_img函数处理下就可以了。
