### ISSUE TITLE
采集资源，不定时出现登录

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#970]
采集资源，不定时出现登录
 有时候采集几页 有时候采集十几页的时候又会出现提示登录，

**Comment by xunskynet** [comment]
鼠标放到采集选项 右键 复制链接 另外网页打开 若出现错误·请退一步

**Comment by magicblack** [comment]
未遇到这个问题~ 一般是服务器配置问题，可以把php的session保存时间设置长一点试试。参考：
https://www.jianshu.com/p/86801b3a8660
