### ISSUE TITLE
iis10 伪静态web.config可以提供一下吗

### ISSUE THREAD

**Issue by 916422** [magicblack/maccms10#971]
iis10 伪静态web.config可以提供一下吗

**Comment by danceking** [comment]
实在看不下去了。
工具：
https://www.toolnb.com//tools/rewriteTools.html

**Comment by jackrebel** [comment]
https://s.8kmm.com/?wd=iis 这个可以各个转换

**Comment by danceking** [comment]
> 

你这是搜索，结果不还到我说的那个站点去了吗？

> https://s.8kmm.com/?wd=iis 这个可以各个转换
