### ISSUE TITLE
采集时重名很多,入库重复规则问题

### ISSUE THREAD

**Issue by masaike999** [magicblack/maccms10#974]
采集时重名很多,入库重复规则可不可以添加一个一级分类的选项,现有分类选项是按二级分类但是选择后会有很多重复影片,只选择标题又有些电视剧或者电影是重名的,能不能增加一个顶级分类的选项,选择后按照顶级分类来判断入库重复,这样即减免了重复入库,又能区分重名影片,是个比较折中的办法

**Comment by magicblack** [comment]
这个暂不考虑支持~ 请结合其他策略实现去重。
