### ISSUE TITLE
有关redis缓存删除(会删除同一个redis库中的其它缓存)

### ISSUE THREAD

**Issue by danceking** [magicblack/maccms10#975]
后台已经设置“$GLOBALS['config']['app']['cache_flag']”缓存前缀为“www_123_com”，但在后台中点击“操作->清理缓存”会删除缓存redis库中 前缀为“www_123_com”以及其他的所有缓存，实测几十次确定此bug才提交！

**Comment by danceking** [comment]
怎么没关注这个错误呢。要是一个redis库里有其它站前缀的缓存也会被清除。明显的bug！！！

**Comment by magicblack** [comment]
此为think框架底层实现，且如果清理指定前缀的缓存时，如果数据量较大，将会非常耗时。
建议独立运行一个redis（比如端口6380）来承载缓存~
