### ISSUE TITLE
重复入库问题，求解！

### ISSUE THREAD

**Issue by wangsclub** [magicblack/maccms10#976]
**描述您的问题**  
系统 - 采集参数设置  - 视频采集设置 - 地址二更规则。
当二次更新选择“合并”时，播放地址相同，而$前缀不同的话，会作为新资源重复入库。
例如：
高清$http://www.xxx.com/200902/index.m3u8
标清$http://www.xxx.com/200902/index.m3u8

**Comment by magicblack** [comment]
这个作为整体的一部分判断的，前缀不同就认为资源不同~
