### ISSUE TITLE
注册时，手机号不判断格式及位数，均可注册成功问题！

### ISSUE THREAD

**Issue by iermei** [magicblack/maccms10#978]
**描述您的问题**  
1、注册时输入手机号，不判断格式，比如12345674999、1111111111111也可以通过，并且可发送验证码，而不断消耗短信。
注册开启了验证手机号，有部分会员的手机号为类似1111112222222333333等，注册成功，不知如何收到的验证码的。
这个问题让用户无限用此类方式注册账号。

2、IP识别很多为0.0.0.0的，所以IP注册限制只能设置多一些，限制一个IP注册一个的话，很多用户无法注册，包括我自己的IP登录、注册经常会显示0.0.0.0.

**问题**
1、我已经在User.php加入了手机号登录，并且判断手机号格式及数量。
`("/^1[345789]\d{9}$/", $data['user_name'])`

请问如何在注册时判断手机号格式及数量？
User.php内修改哪一段？

2、IP问题不知出现在哪里，希望能完善。

**Comment by magicblack** [comment]
1、注册发短信的正则已优化，不满足正则的手机号将发不出短信。
2、IP问题需要看你网站的网络结构，是否有CDN等，如果有CDN可能需要对齐调整获取ip的方法，具体在这里：
https://github.com/magicblack/maccms10/blob/master/application/common.php#L957-L995
