### ISSUE TITLE
使用.htaccess开启伪静态跟自定义错误页重复冲突问题

### ISSUE THREAD

**Issue by iermei** [magicblack/maccms10#979]
使用.htaccess开启伪静态后，自定义错误页重复，导致自定义错误页失效。
因为是虚拟主机，所以要用.htaccess自定义。
`#伪静态
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php?/$1 [QSA,PT,L]`

`#自定义错误页
ErrorDocument 403 /403.shtml
ErrorDocument 504 /504.shtml
ErrorDocument 500 /500.shtml`

由于经常占用CPU到100%，而返回504错误，用户以为网站失效了，所以要自定义一个504页面告诉用户。
这里要怎么写才能让504错误生效？

**Comment by magicblack** [comment]
需要自行搜索研究下网站服务器的配置~

**Comment by iermei** [comment]
有知道怎么写的大神吗？
伪静态规则跟自定义错误重复。
如果CPU占用不到100%，就不会出现504错误了，我也就不会去自定义错误页了。
