### ISSUE TITLE
定时生成地图，生成后提示控制器不存在

### ISSUE THREAD

**Issue by 791813752** [magicblack/maccms10#98]
老王看下，伪静态也设置了，定时生成地图，生成后就提示控制器不存在
![Screenshot_20191102_012722](https://user-images.githubusercontent.com/52873469/68043380-1c714480-fd10-11e9-8497-ae7cc515c3e0.jpg)
重装了好几次都是这样的，麻烦看下，谢谢王哥

**Comment by magicblack** [comment]
没有关系，那说跳转了。已经生成完毕。
