### ISSUE TITLE
/index.php/vod/search/时$param无参数,只有$param.page有值,其它都是空白

### ISSUE THREAD

**Issue by chinapzw** [magicblack/maccms10#980]
/index.php/vod/search/时$param无参数,只有$param.page有值,其它都是空白
已升级到最新版,看了代码,本来以后是我模板的问题,但放在模板最上方也一样不显示{php}print_r($param);{/php}

**Comment by magicblack** [comment]
这边测试没有问题~
<img width="648" alt="image" src="https://user-images.githubusercontent.com/20452515/210173743-694b4d6c-94d9-4485-8bc9-3f60b8fe4ec2.png">

对应模板文件：
./template/default_pc/html/vod/search.html

相关代码：
```
<?php
    echo '打印 $param: <pre>';
print_r($param);
?>
</pre>
<!--搜索结果-->
```
