### ISSUE TITLE
条件已经成熟了,是时候开发分表了

### ISSUE THREAD

**Issue by chinapzw** [magicblack/maccms10#981]
mysql数据量的限制,单表vod一百万时很慢,虽然有缓存,但还是需要15秒打开,碰到搜索直接就完了,我也在摸索这块,本来做出了个站群,可以引用文章,把能采的资源都按分类采回来后,发现搜索都要20秒,缓存后秒开,但站群就行了,哎,看了好多分表文章,都没有好的方案,本来想着改动下model/vod.php的listdata就好了,发现入库也要折腾,所以就有了以下的想法:
不改动原有数据库,按分类id新建表为vod_1   ......vod_n
入库时或更改时,修改mac_vod数据主表,然后按相关id修改子表数据
查找视频列表时从分表查找.
呃....搜索的最佳方案,要自己的折腾了

**Comment by hkcalm** [comment]
牛批

**Comment by magicblack** [comment]
目前架构难大改，不建议单站vod超过10w数据。考虑拆分站点，或者达到此量级自行二次开发~

**Comment by overMiracle** [comment]
@chinapzw  可以把全站用ES重构，如有需要可以联系我
