### ISSUE TITLE
二次更新勾选了分集剧情。但是火车头采集发布上去变成新增了。名称一样

### ISSUE THREAD

**Issue by hkcalm** [magicblack/maccms10#982]
**描述您的问题**  
二次更新勾选了分集剧情。但是火车头采集发布上去变成新增了。名称一样
![image](https://user-images.githubusercontent.com/11788305/195752124-a5f07e85-d09e-425d-9314-f2af6396e7f0.png)
![image](https://user-images.githubusercontent.com/11788305/195752163-c12a1517-7bd1-43cd-8697-4cfbe6907331.png)

**Comment by magicblack** [comment]
看看演员、导演是否一致~ 新增了说明入库未判断为重复~
