### ISSUE TITLE
An xss problem

### ISSUE THREAD

**Issue by WenstAlanni** [magicblack/maccms10#983]
version 10 have xss  Vulnerability

**Comment by WenstAlanni** [comment]
hi, I found an xss vulnerability in the api interface
For details, go to https://github.com/WenstAlanni/maccms-xss/blob/main/README.md

**Comment by hkcalm** [comment]
这个资源站利用上。就是割韭菜了

**Comment by magicblack** [comment]
感谢反馈，将在下个版本修复。
