### ISSUE TITLE
网站被挂马了，想咨询一下大家

### ISSUE THREAD

**Issue by maigosama** [magicblack/maccms10#985]
被挂了个很隐蔽的跳转木马，想测试的时候不跳，但是又偶尔来一下
首先会跳转到 “正在进入旗下新产品，为你定制，请稍后...” 的页面，然后再次跳转到涩情网站
好苦恼啊，找不到哪里的原因，想咨询一下大家有没有碰到过一样的情况，是怎么处理的呢

**Comment by wasonCheung** [comment]
那个版本

**Comment by maigosama** [comment]
> 那个版本

2022.1000.3031

**Comment by wasonCheung** [comment]
是官方原版吗

**Comment by maigosama** [comment]
> 是官方原版吗

在这里下载的

**Comment by wasonCheung** [comment]
查找下 那些源文件被修改了，看下它的挂马位置

**Comment by maigosama** [comment]
> 查找下 那些源文件被修改了，看下它的挂马位置
文件好多，不知道怎么找

**Comment by maigosama** [comment]
> 查找下 那些源文件被修改了，看下它的挂马位置

文件好多，不知道怎么找

**Comment by maigosama** [comment]
终于找到了，模板有个js被改了，跳转的url用了16位编码加密，解码后是 https://zz.bdustatic.com/linksubmit/push.js

**Comment by maigosama** [comment]
不过不知道是哪里的漏洞被黑进来的了

**Comment by gqq1356** [comment]
我遇到这种情况一般会对比变更前后的网站日志 总有些奇怪的参数存在于日志中，希望你能查看下

**Comment by gqq1356** [comment]
关于这个连接 一般人很容易看成是百度推送的链接 @https://zz.bdustatic.com/linksubmit/push.js

**Comment by maigosama** [comment]
> 我遇到这种情况一般会对比变更前后的网站日志 总有些奇怪的参数存在于日志中，希望你能查看下

有时候一些跳转频率很低的马，不容易马上发现，有时候隔了好久才知道，这次是访客留言告诉我才知道的，唉

**Comment by maigosama** [comment]
> 关于这个连接 一般人很容易看成是百度推送的链接 @https://zz.bdustatic.com/linksubmit/push.js

确实

**Comment by gqq1356** [comment]
> 

我了解过这种挂马，他们的代码思路是检测是不是手机端 若是进入第二层 然后来源地址是不是搜索引擎 若是进入第三层 当前时间（建立了一个长度为24的数组代表24小时）若是指定时间 则跳转概率增加，若没有进入跳转逻辑则标记浏览次数 若次数大于指定次数并且满足第一层条件 才进行跳转 ,希望对你寻找目标代码有用

**Comment by maigosama** [comment]
> > 
> 
> 我了解过这种挂马，他们的代码思路是检测是不是手机端 若是进入第二层 然后来源地址是不是搜索引擎 若是进入第三层 当前时间（建立了一个长度为24的数组代表24小时）若是指定时间 则跳转概率增加，若没有进入跳转逻辑则标记浏览次数 若次数大于指定次数并且满足第一层条件 才进行跳转 ,希望对你寻找目标代码有用

嗯，貌似是差不多这样，网站被挂过好几次了，主要是不知哪里的漏洞，可以请教一下你是怎么防护的吗，我装的是宝塔收费版nginx防火墙

**Comment by gqq1356** [comment]
> 

找到原因才谈得上防护，若您没找到问题出在哪段代码，很大概率是模板上出了问题，最好的解决办法是花钱买正版模板（寻找原因的方法例如：网站日志文件中搜索这几种可疑字段 eval ，fputs，base64，phpinfo），若您找到了原因，那就对症下药即可

**Comment by magicblack** [comment]
先按这个文档清理一下：
https://github.com/magicblack/maccms10/wiki/%E5%B0%8F%E7%99%BD%E9%80%9A%E7%94%A8%E6%B8%85%E7%90%86php%E5%90%8E%E9%97%A8%E5%8A%9E%E6%B3%95%E7%AE%80%E5%8D%95%E6%98%93%E6%87%82

最好换个服务器重新安装一次纯净包，迁移数据，以免还有残留。其他就是日常防护，定期检查文件改动情况~
