### ISSUE TITLE
关于多语言

### ISSUE THREAD

**Issue by maigosama** [magicblack/maccms10#987]
貌似很早前就看到有这样的计划了，当然要实现这个的话又太难为大佬了，现在打算做一个外国站，在翻译中，模板已经翻译完了。
cms那里是否只有语言包有一部分需要翻译？不知道能不能请大佬帮忙把语言包里面 会在前台出现的 和 不会在前台出现的 分成两部分呢，我自己虽然已经在整理了，只是可能会有漏。分开之后大家只需要自行翻译会在前台出现的那部分就可以啦！

**Comment by magicblack** [comment]
看这个文件：
./application/lang/zh-cn.php

后台出现的一般是这些情况：
1. 不带前缀的，如 vod art 等
2. 以 menu/ 、admin/ 开头 
3. 前后台公共的 model/

其他情况可以拿关键词自己全局搜索一下代码~
