### ISSUE TITLE
如何设置隐藏下载链接的部分字段并提示仅限VIP查看

### ISSUE THREAD

**Issue by jaycekao** [magicblack/maccms10#988]
![image](https://user-images.githubusercontent.com/46006171/199702282-b7c5bc98-4bca-415f-b195-7c508931b412.png)

请问怎么让整个下载链接区块让所有用户可见，同时下载链接的后半部分又隐藏起来并提示仅限VIP用户可查看？具体样式见附图！

**系统默认的会员组里设置不出上面的效果，难道是第三方插件实现的？

**Comment by wasonCheung** [comment]
加个判断就行了，非vip用户显示***

**Comment by cnstephen** [comment]
来个代码

**Comment by cnstephen** [comment]
> 加个判断就行了，非vip用户显示***

不知道用啥参数,来个代码

**Comment by magicblack** [comment]
官方没有这个功能，需要自行在模板里开发~
