### ISSUE TITLE
关于视频编辑保存时自动生成数据的问题

### ISSUE THREAD

**Issue by Nothingtodoforma** [magicblack/maccms10#989]
在编辑视频信息保存时，系统自动生成的拼音以及首字母对于多音字的识别存在问题。比如这个《乐队男孩》，识别成了leduinanhai，首字母也成了L。
![image](https://user-images.githubusercontent.com/49300630/200483172-9d3a7e8c-a3fd-46ee-b45f-ef4a44e529fe.png)

**Comment by maigosama** [comment]
我估计这个不好解决

**Comment by magicblack** [comment]
确实不好解决，这个用的是初级匹配库，对于多音字的处理还是需要自行编辑一下。
