### ISSUE TITLE
sitemap生成里面的条数和什么有关

### ISSUE THREAD

**Issue by 791813752** [magicblack/maccms10#99]
就是我第一个站，是很久以前建的，自动生成的sitemap里面基本上有100条，但是我最近建的新站，sitemap里面只有30条，而且<priority>0.8</priority>还是0.8，我老站是1.0，想问下王哥，这个是跟什么有关，是不是可以改，改哪里，王哥简单说下就行了

**Comment by 791813752** [comment]
priority是0.8，刚刚用的代码形式，github应该是屏蔽了

**Comment by magicblack** [comment]
去修改模板页面
