### ISSUE TITLE
同步图片的功能不全

### ISSUE THREAD

**Issue by lixuehan1234** [magicblack/maccms10#990]
后台数据列表里，同步图片的功能不全
只能同步主图和详情图片
但是海报图、截图还有网址模块里的logo都不能同步
希望可以增加相关的功能~

**Comment by magicblack** [comment]
麻烦截图提供一下操作重现步骤~

**Comment by lixuehan1234** [comment]
![QQ截图20230102114800](https://user-images.githubusercontent.com/55046423/210193773-c230c309-3cd9-4e02-aa42-61353e5a110a.png)

就是这里，同步图片的范围只能选主图和详情图片，海报图、截图列表、还有网址模块里的logo都无法选择，也不能同步

**Comment by magicblack** [comment]
这个暂时不考虑实现，可以尝试通过采集更新试试~
