### ISSUE TITLE
二级目录安装 伪静态 404

### ISSUE THREAD

**Issue by cnstephen** [magicblack/maccms10#992]
location /二级目录/ {
 if (!-e $request_filename) {
        rewrite ^/index.php(.*)$ /index.php?s=$1 last;
        rewrite ^/admin.php(.*)$ /admin.php?s=$1 last;
        rewrite ^/api.php(.*)$ /api.php?s=$1 last;
        rewrite ^(.*)$ /index.php?s=$1 last;
        break;
   }
}
伪静态规则,啥情况

**Comment by magicblack** [comment]
nginx规则，自行搜索调试~
