### ISSUE TITLE
发现日志多了超多这种连接，请问下是做啥的，怎么去掉呀？

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms10#996]
发现日志多了超多这种连接，请问下是做啥的，怎么去掉呀？
/index.php/ajax/hits?mid=1&id=106654&type=update

**Comment by aa068** [comment]
這只是幫你計算點擊次數的

**Comment by magicblack** [comment]
楼上正解。这个是网站正常功能，不需要动。
