### ISSUE TITLE
挂马检测  app\admin\controller\Database->inspect()

### ISSUE THREAD

**Issue by bitihou2022** [magicblack/maccms10#997]
挂马检测   
 方法不存在: app\admin\controller\Database->inspect() 
这个如何解决？
谢谢了。。

**Comment by magicblack** [comment]
这个是缺少了方法，先升级一下到最新版本，或者手动从这里复制这个文件内容覆盖一下你站对应文件：
https://github.com/magicblack/maccms10/blob/master/application/admin/controller/Database.php

**Comment by bitihou2022** [comment]
=========我是分割线==========
