### ISSUE TITLE
控制器不存在:app\admin\controller\Update

### ISSUE THREAD

**Issue by l769829723** [magicblack/maccms10#998]
**描述您的问题**  
点击升级数据库脚本的时候会报错: 控制器不存在:app\admin\controller\Update

**如何重现**  

1. 登陆到后台首页
2. 点升级数据库脚本

**预期结果**  
正常执行升级

**截图**  
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/4329643/206906328-bdb38cec-a02a-450f-89f9-4e12de0a1df7.png">

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/4329643/206906366-83a084c2-cd74-4572-b144-c46d2dde7d87.png">

**版本信息:**  
运行环境 | Linux (LiteSpeed)
-- | --
数据库版本 | 10.5.12-MariaDB-cll-lve
PHP版本 | 7.2.34
ThinkPHP版本 | 5.0.24
程序版本 | 2022.1000.3031

**其他备注信息**  
点在线升级之类的也会报控制器不存在的错误,请问知不知道是哪里的问题?

**Comment by magicblack** [comment]
在后台 应用 - 文件安全检测，勾选 差异文件，然后提交看看是不是有控制器文件被改了~
建议备份好数据，重新在github下载最新版的安装包，迁移一下。
